Here we will perform all the feature engineering required for this project. We will test all. See the vbest approach for automation.

In [2]:
import pandas as pd

In [3]:
aiico_data=pd.read_csv('stock_data/AIICO.csv')

In [4]:
aiico_data

,id,symbol,trade_date,open_price,high_price,low_price,close_price,volume,created_at
0,42813,AIICO,2017-01-03,0.60,NaN,NaN,0.60,356956,2026-04-08T02:41:25.765521+00:00
1,43373,AIICO,2017-01-04,0.61,NaN,NaN,0.61,180900,2026-04-08T02:42:20.164398+00:00
2,43483,AIICO,2017-01-05,0.62,NaN,NaN,0.62,838300,2026-04-08T02:42:22.380516+00:00
3,43593,AIICO,2017-01-06,0.62,NaN,NaN,0.62,81591,2026-04-08T02:42:23.84796+00:00
4,43683,AIICO,2017-01-09,0.60,NaN,NaN,0.60,7669839,2026-04-08T02:42:26.938159+00:00
...,...,...,...,...,...,...,...,...,...
2258,298023,AIICO,2026-07-13,3.96,NaN,NaN,3.96,6133839,2026-07-13T15:10:02.995074+00:00
2259,298461,AIICO,2026-07-14,3.96,NaN,NaN,3.96,3349343,2026-07-14T15:10:03.094441+00:00
2260,298899,AIICO,2026-07-15,3.96,NaN,NaN,3.96,3986502,2026-07-15T15:10:03.078609+00:00
2261,299337,AIICO,2026-07-16,4.04,NaN,NaN,4.04,6691535,2026-07-16T15:10:03.113936+00:00
2262,299775,AIICO,2026-07-17,4.13,NaN,NaN,4.13,3108626,2026-07-17T15:10:03.053983+00:00

In [5]:
aiico_data_2=aiico_data.drop(['high_price','low_price'], axis=1)

In [6]:
aiico_data_2

,id,symbol,trade_date,open_price,close_price,volume,created_at
0,42813,AIICO,2017-01-03,0.60,0.60,356956,2026-04-08T02:41:25.765521+00:00
1,43373,AIICO,2017-01-04,0.61,0.61,180900,2026-04-08T02:42:20.164398+00:00
2,43483,AIICO,2017-01-05,0.62,0.62,838300,2026-04-08T02:42:22.380516+00:00
3,43593,AIICO,2017-01-06,0.62,0.62,81591,2026-04-08T02:42:23.84796+00:00
4,43683,AIICO,2017-01-09,0.60,0.60,7669839,2026-04-08T02:42:26.938159+00:00
...,...,...,...,...,...,...,...
2258,298023,AIICO,2026-07-13,3.96,3.96,6133839,2026-07-13T15:10:02.995074+00:00
2259,298461,AIICO,2026-07-14,3.96,3.96,3349343,2026-07-14T15:10:03.094441+00:00
2260,298899,AIICO,2026-07-15,3.96,3.96,3986502,2026-07-15T15:10:03.078609+00:00
2261,299337,AIICO,2026-07-16,4.04,4.04,6691535,2026-07-16T15:10:03.113936+00:00
2262,299775,AIICO,2026-07-17,4.13,4.13,3108626,2026-07-17T15:10:03.053983+00:00

## Stock data feature engineering
### 1. Derive the returns in Percentage
This is the percentage difference between the current closing price and previous price

In [7]:
aiico_data_2['returns_pct']=aiico_data_2['close_price'].pct_change()*100
aiico_data_2

,id,symbol,trade_date,open_price,close_price,volume,created_at,returns_pct
0,42813,AIICO,2017-01-03,0.60,0.60,356956,2026-04-08T02:41:25.765521+00:00,NaN
1,43373,AIICO,2017-01-04,0.61,0.61,180900,2026-04-08T02:42:20.164398+00:00,1.666667
2,43483,AIICO,2017-01-05,0.62,0.62,838300,2026-04-08T02:42:22.380516+00:00,1.639344
3,43593,AIICO,2017-01-06,0.62,0.62,81591,2026-04-08T02:42:23.84796+00:00,0.000000
4,43683,AIICO,2017-01-09,0.60,0.60,7669839,2026-04-08T02:42:26.938159+00:00,-3.225806
...,...,...,...,...,...,...,...,...
2258,298023,AIICO,2026-07-13,3.96,3.96,6133839,2026-07-13T15:10:02.995074+00:00,0.253165
2259,298461,AIICO,2026-07-14,3.96,3.96,3349343,2026-07-14T15:10:03.094441+00:00,0.000000
2260,298899,AIICO,2026-07-15,3.96,3.96,3986502,2026-07-15T15:10:03.078609+00:00,0.000000
2261,299337,AIICO,2026-07-16,4.04,4.04,6691535,2026-07-16T15:10:03.113936+00:00,2.020202
2262,299775,AIICO,2026-07-17,4.13,4.13,3108626,2026-07-17T15:10:03.053983+00:00,2.227723

In [9]:
aiico_data_2

,id,symbol,trade_date,open_price,close_price,volume,created_at,returns_pct
0,42813,AIICO,2017-01-03,0.60,0.60,356956,2026-04-08T02:41:25.765521+00:00,NaN
1,43373,AIICO,2017-01-04,0.61,0.61,180900,2026-04-08T02:42:20.164398+00:00,1.666667
2,43483,AIICO,2017-01-05,0.62,0.62,838300,2026-04-08T02:42:22.380516+00:00,1.639344
3,43593,AIICO,2017-01-06,0.62,0.62,81591,2026-04-08T02:42:23.84796+00:00,0.000000
4,43683,AIICO,2017-01-09,0.60,0.60,7669839,2026-04-08T02:42:26.938159+00:00,-3.225806
...,...,...,...,...,...,...,...,...
2258,298023,AIICO,2026-07-13,3.96,3.96,6133839,2026-07-13T15:10:02.995074+00:00,0.253165
2259,298461,AIICO,2026-07-14,3.96,3.96,3349343,2026-07-14T15:10:03.094441+00:00,0.000000
2260,298899,AIICO,2026-07-15,3.96,3.96,3986502,2026-07-15T15:10:03.078609+00:00,0.000000
2261,299337,AIICO,2026-07-16,4.04,4.04,6691535,2026-07-16T15:10:03.113936+00:00,2.020202
2262,299775,AIICO,2026-07-17,4.13,4.13,3108626,2026-07-17T15:10:03.053983+00:00,2.227723

### 2. Introduce Lag returns
Lagging is when you include previous information into current data point to give a better information about the past and how it affects the present and future

We will apply Lagging on the returns of previous return(lag1), previous 5 return(lag5), previous 10 return(lag10)

In [10]:
aiico_data_2["lag_return1"] = aiico_data_2["returns_pct"].shift(1)
aiico_data_2["lag_return2"] = aiico_data_2["returns_pct"].shift(2)
aiico_data_2["lag_return5"] = aiico_data_2["returns_pct"].shift(5)
aiico_data_2["lag_return10"] = aiico_data_2["returns_pct"].shift(10)

In [11]:
aiico_data_2.head(15)

,id,symbol,trade_date,open_price,close_price,volume,created_at,returns_pct,lag_return1,lag_return2,lag_return5,lag_return10
0,42813,AIICO,2017-01-03,0.60,0.60,356956,2026-04-08T02:41:25.765521+00:00,NaN,NaN,NaN,NaN,NaN
1,43373,AIICO,2017-01-04,0.61,0.61,180900,2026-04-08T02:42:20.164398+00:00,1.666667,NaN,NaN,NaN,NaN
2,43483,AIICO,2017-01-05,0.62,0.62,838300,2026-04-08T02:42:22.380516+00:00,1.639344,1.666667,NaN,NaN,NaN
3,43593,AIICO,2017-01-06,0.62,0.62,81591,2026-04-08T02:42:23.84796+00:00,0.000000,1.639344,1.666667,NaN,NaN
4,43683,AIICO,2017-01-09,0.60,0.60,7669839,2026-04-08T02:42:26.938159+00:00,-3.225806,0.000000,1.639344,NaN,NaN
5,43793,AIICO,2017-01-10,0.59,0.59,3421173,2026-04-08T02:42:29.227202+00:00,-1.666667,-3.225806,0.000000,NaN,NaN
6,43903,AIICO,2017-01-11,0.60,0.60,1313195,2026-04-08T02:42:30.799441+00:00,1.694915,-1.666667,-3.225806,1.666667,NaN
7,43993,AIICO,2017-01-12,0.60,0.60,277127,2026-04-08T02:42:32.390658+00:00,0.000000,1.694915,-1.666667,1.639344,NaN
8,44123,AIICO,2017-01-13,0.60,0.60,206000,2026-04-08T02:42:34.853543+00:00,0.000000,0.000000,1.694915,0.000000,NaN
9,44213,AIICO,2017-01-16,0.60,0.60,587419,2026-04-08T02:42:38.72803+00:00,0.000000,0.000000,0.000000,-3.225806,NaN
10,44323,AIICO,2017-01-17,0.60,0.60,815155,2026-04-08T02:42:41.056228+00:00,0.000000,0.000000,0.000000,-1.666667,NaN
11,44433,AIICO,2017-01-18,0.60,0.60,5019030,2026-04-08T02:42:42.795307+00:00,0.000000,0.000000,0.000000,1.694915,1.666667
12,44523,AIICO,2017-01-19,0.60,0.60,682173,2026-04-08T02:42:44.39781+00:00,0.000000,0.000000,0.000000,0.000000,1.639344
13,44633,AIICO,2017-01-20,0.60,0.60,1160557,2026-04-08T02:42:46.643743+00:00,0.000000,0.000000,0.000000,0.000000,0.000000
14,44743,AIICO,2017-01-23,0.60,0.60,1278928,2026-04-08T02:42:49.827664+00:00,0.000000,0.000000,0.000000,0.000000,-3.225806

### 3. Applying Moving Averages

Instead of looking at one day's price, we calculate the average of recent prices. This will smoothen the plot to give a sense of the trend. The more the averaging gap, the better the smoothening.

* 5-day	    Very short-term movement
* 10-day	Short-term trend
* 20-day	About one trading month
* 50-day	Medium-term trend

We will use 5(MA_5), 20(MA_20) and 50(MA_50) for this exercise.

In [12]:
aiico_data_2.shape

(2263, 12)

In [13]:
aiico_data_2["stock_MA_5"] = aiico_data_2["close_price"].rolling(window=5).mean()
aiico_data_2["stock_MA_20"] = aiico_data_2["close_price"].rolling(window=20).mean()
aiico_data_2["stock_MA_50"] = aiico_data_2["close_price"].rolling(window=50).mean()

In [14]:
aiico_data_2.head(20)

,id,symbol,trade_date,open_price,close_price,volume,created_at,returns_pct,lag_return1,lag_return2,lag_return5,lag_return10,stock_MA_5,stock_MA_20,stock_MA_50
0,42813,AIICO,2017-01-03,0.60,0.60,356956,2026-04-08T02:41:25.765521+00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,43373,AIICO,2017-01-04,0.61,0.61,180900,2026-04-08T02:42:20.164398+00:00,1.666667,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,43483,AIICO,2017-01-05,0.62,0.62,838300,2026-04-08T02:42:22.380516+00:00,1.639344,1.666667,NaN,NaN,NaN,NaN,NaN,NaN
3,43593,AIICO,2017-01-06,0.62,0.62,81591,2026-04-08T02:42:23.84796+00:00,0.000000,1.639344,1.666667,NaN,NaN,NaN,NaN,NaN
4,43683,AIICO,2017-01-09,0.60,0.60,7669839,2026-04-08T02:42:26.938159+00:00,-3.225806,0.000000,1.639344,NaN,NaN,0.610,NaN,NaN
5,43793,AIICO,2017-01-10,0.59,0.59,3421173,2026-04-08T02:42:29.227202+00:00,-1.666667,-3.225806,0.000000,NaN,NaN,0.608,NaN,NaN
6,43903,AIICO,2017-01-11,0.60,0.60,1313195,2026-04-08T02:42:30.799441+00:00,1.694915,-1.666667,-3.225806,1.666667,NaN,0.606,NaN,NaN
7,43993,AIICO,2017-01-12,0.60,0.60,277127,2026-04-08T02:42:32.390658+00:00,0.000000,1.694915,-1.666667,1.639344,NaN,0.602,NaN,NaN
8,44123,AIICO,2017-01-13,0.60,0.60,206000,2026-04-08T02:42:34.853543+00:00,0.000000,0.000000,1.694915,0.000000,NaN,0.598,NaN,NaN
9,44213,AIICO,2017-01-16,0.60,0.60,587419,2026-04-08T02:42:38.72803+00:00,0.000000,0.000000,0.000000,-3.225806,NaN,0.598,NaN,NaN
10,44323,AIICO,2017-01-17,0.60,0.60,815155,2026-04-08T02:42:41.056228+00:00,0.000000,0.000000,0.000000,-1.666667,NaN,0.600,NaN,NaN
11,44433,AIICO,2017-01-18,0.60,0.60,5019030,2026-04-08T02:42:42.795307+00:00,0.000000,0.000000,0.000000,1.694915,1.666667,0.600,NaN,NaN
12,44523,AIICO,2017-01-19,0.60,0.60,682173,2026-04-08T02:42:44.39781+00:00,0.000000,0.000000,0.000000,0.000000,1.639344,0.600,NaN,NaN
13,44633,AIICO,2017-01-20,0.60,0.60,1160557,2026-04-08T02:42:46.643743+00:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.600,NaN,NaN
14,44743,AIICO,2017-01-23,0.60,0.60,1278928,2026-04-08T02:42:49.827664+00:00,0.000000,0.000000,0.000000,0.000000,-3.225806,0.600,NaN,NaN
15,44853,AIICO,2017-01-24,0.58,0.58,514640,2026-04-08T02:42:51.574002+00:00,-3.333333,0.000000,0.000000,0.000000,-1.666667,0.596,NaN,NaN
16,44943,AIICO,2017-01-25,0.58,0.58,1595529,2026-04-08T02:42:54.05787+00:00,0.000000,-3.333333,0.000000,0.000000,1.694915,0.592,NaN,NaN
17,45053,AIICO,2017-01-26,0.60,0.60,30146271,2026-04-08T02:42:55.759+00:00,3.448276,0.000000,-3.333333,0.000000,0.000000,0.592,NaN,NaN
18,45163,AIICO,2017-01-27,0.60,0.60,1432258,2026-04-08T02:42:57.462271+00:00,0.000000,3.448276,0.000000,0.000000,0.000000,0.592,NaN,NaN
19,45273,AIICO,2017-01-30,0.60,0.60,56806215,2026-04-08T02:43:00.905282+00:00,0.000000,0.000000,3.448276,0.000000,0.000000,0.592,0.6,NaN

### 4. Apply Rolling Volatility
Volatility measures how much returns fluctuate over a period. If i pick a returns period of 20 days , I use this to find out how stable the returns is over 20 days. This is basically the standard deviation during the period.

We will be using Rolling volatility of 20 days

In [15]:
aiico_data_2["returns_volatility_20"] = (
    aiico_data_2["returns_pct"]
      .rolling(window=20)
      .std()
)

aiico_data_2["returns_volatility_50"] = (
    aiico_data_2["returns_pct"]
      .rolling(window=50)
      .std()
)

In [16]:
aiico_data_2.head(25)

,id,symbol,trade_date,open_price,close_price,volume,created_at,returns_pct,lag_return1,lag_return2,lag_return5,lag_return10,stock_MA_5,stock_MA_20,stock_MA_50,returns_volatility_20,returns_volatility_50
0,42813,AIICO,2017-01-03,0.60,0.60,356956,2026-04-08T02:41:25.765521+00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,43373,AIICO,2017-01-04,0.61,0.61,180900,2026-04-08T02:42:20.164398+00:00,1.666667,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,43483,AIICO,2017-01-05,0.62,0.62,838300,2026-04-08T02:42:22.380516+00:00,1.639344,1.666667,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,43593,AIICO,2017-01-06,0.62,0.62,81591,2026-04-08T02:42:23.84796+00:00,0.000000,1.639344,1.666667,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,43683,AIICO,2017-01-09,0.60,0.60,7669839,2026-04-08T02:42:26.938159+00:00,-3.225806,0.000000,1.639344,NaN,NaN,0.610,NaN,NaN,NaN,NaN
5,43793,AIICO,2017-01-10,0.59,0.59,3421173,2026-04-08T02:42:29.227202+00:00,-1.666667,-3.225806,0.000000,NaN,NaN,0.608,NaN,NaN,NaN,NaN
6,43903,AIICO,2017-01-11,0.60,0.60,1313195,2026-04-08T02:42:30.799441+00:00,1.694915,-1.666667,-3.225806,1.666667,NaN,0.606,NaN,NaN,NaN,NaN
7,43993,AIICO,2017-01-12,0.60,0.60,277127,2026-04-08T02:42:32.390658+00:00,0.000000,1.694915,-1.666667,1.639344,NaN,0.602,NaN,NaN,NaN,NaN
8,44123,AIICO,2017-01-13,0.60,0.60,206000,2026-04-08T02:42:34.853543+00:00,0.000000,0.000000,1.694915,0.000000,NaN,0.598,NaN,NaN,NaN,NaN
9,44213,AIICO,2017-01-16,0.60,0.60,587419,2026-04-08T02:42:38.72803+00:00,0.000000,0.000000,0.000000,-3.225806,NaN,0.598,NaN,NaN,NaN,NaN
10,44323,AIICO,2017-01-17,0.60,0.60,815155,2026-04-08T02:42:41.056228+00:00,0.000000,0.000000,0.000000,-1.666667,NaN,0.600,NaN,NaN,NaN,NaN
11,44433,AIICO,2017-01-18,0.60,0.60,5019030,2026-04-08T02:42:42.795307+00:00,0.000000,0.000000,0.000000,1.694915,1.666667,0.600,NaN,NaN,NaN,NaN
12,44523,AIICO,2017-01-19,0.60,0.60,682173,2026-04-08T02:42:44.39781+00:00,0.000000,0.000000,0.000000,0.000000,1.639344,0.600,NaN,NaN,NaN,NaN
13,44633,AIICO,2017-01-20,0.60,0.60,1160557,2026-04-08T02:42:46.643743+00:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.600,NaN,NaN,NaN,NaN
14,44743,AIICO,2017-01-23,0.60,0.60,1278928,2026-04-08T02:42:49.827664+00:00,0.000000,0.000000,0.000000,0.000000,-3.225806,0.600,NaN,NaN,NaN,NaN
15,44853,AIICO,2017-01-24,0.58,0.58,514640,2026-04-08T02:42:51.574002+00:00,-3.333333,0.000000,0.000000,0.000000,-1.666667,0.596,NaN,NaN,NaN,NaN
16,44943,AIICO,2017-01-25,0.58,0.58,1595529,2026-04-08T02:42:54.05787+00:00,0.000000,-3.333333,0.000000,0.000000,1.694915,0.592,NaN,NaN,NaN,NaN
17,45053,AIICO,2017-01-26,0.60,0.60,30146271,2026-04-08T02:42:55.759+00:00,3.448276,0.000000,-3.333333,0.000000,0.000000,0.592,NaN,NaN,NaN,NaN
18,45163,AIICO,2017-01-27,0.60,0.60,1432258,2026-04-08T02:42:57.462271+00:00,0.000000,3.448276,0.000000,0.000000,0.000000,0.592,NaN,NaN,NaN,NaN
19,45273,AIICO,2017-01-30,0.60,0.60,56806215,2026-04-08T02:43:00.905282+00:00,0.000000,0.000000,3.448276,0.000000,0.000000,0.592,0.6000,NaN,NaN,NaN
20,45383,AIICO,2017-01-31,0.59,0.59,12810930,2026-04-08T02:43:03.07753+00:00,-1.666667,0.000000,0.000000,-3.333333,0.000000,0.594,0.5995,NaN,1.576086,NaN
21,45493,AIICO,2017-02-01,0.59,0.59,169982,2026-04-08T02:43:04.619173+00:00,0.000000,-1.666667,0.000000,0.000000,0.000000,0.596,0.5985,NaN,1.522458,NaN
22,45583,AIICO,2017-02-02,0.60,0.60,254049,2026-04-08T02:43:06.209007+00:00,1.694915,0.000000,-1.666667,3.448276,0.000000,0.596,0.5975,NaN,1.525953,NaN
23,45693,AIICO,2017-02-03,0.58,0.58,1228500,2026-04-08T02:43:08.490666+00:00,-3.333333,1.694915,0.000000,0.000000,0.000000,0.592,0.5955,NaN,1.682410,NaN
24,45803,AIICO,2017-02-06,0.59,0.59,229700,2026-04-08T02:43:11.037852+00:00,1.724138,-3.333333,1.694915,0.000000,0.000000,0.590,0.5950,NaN,1.594120,NaN

### 5. Relative Strength Index (RSI)
The Relative Strength Index (RSI) is one of the most popular momentum indicators in technical analysis. It measures the speed and magnitude of recent price changes to indicate whether a stock has been gaining or losing momentum.

RSI ranges from 0 to 100.

* RSI > 70: Often considered overbought.
* RSI < 30: Often considered oversold.

For now we will use `14 days` RSI. We can make adjustments to see which RSI will improve the model.

In [17]:
import pandas_ta as ta

aiico_data_2["stock_RSI"] = ta.rsi(aiico_data_2["close_price"], length=14)

In [19]:
## pandas_ta requires a lower numpy, 2.2 and below
## we are only checking the version
import numpy as np
import sys

print(np.__version__)
print(sys.executable)

2.2.6
c:\Users\pc\Downloads\Python_NGX_Project\venv\python.exe

In [20]:
aiico_data_2.head(20)

,id,symbol,trade_date,open_price,close_price,volume,created_at,returns_pct,lag_return1,lag_return2,lag_return5,lag_return10,stock_MA_5,stock_MA_20,stock_MA_50,returns_volatility_20,returns_volatility_50,stock_RSI
0,42813,AIICO,2017-01-03,0.60,0.60,356956,2026-04-08T02:41:25.765521+00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,43373,AIICO,2017-01-04,0.61,0.61,180900,2026-04-08T02:42:20.164398+00:00,1.666667,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.000000
2,43483,AIICO,2017-01-05,0.62,0.62,838300,2026-04-08T02:42:22.380516+00:00,1.639344,1.666667,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.000000
3,43593,AIICO,2017-01-06,0.62,0.62,81591,2026-04-08T02:42:23.84796+00:00,0.000000,1.639344,1.666667,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.000000
4,43683,AIICO,2017-01-09,0.60,0.60,7669839,2026-04-08T02:42:26.938159+00:00,-3.225806,0.000000,1.639344,NaN,NaN,0.610,NaN,NaN,NaN,NaN,85.786802
5,43793,AIICO,2017-01-10,0.59,0.59,3421173,2026-04-08T02:42:29.227202+00:00,-1.666667,-3.225806,0.000000,NaN,NaN,0.608,NaN,NaN,NaN,NaN,79.688067
6,43903,AIICO,2017-01-11,0.60,0.60,1313195,2026-04-08T02:42:30.799441+00:00,1.694915,-1.666667,-3.225806,1.666667,NaN,0.606,NaN,NaN,NaN,NaN,81.132564
7,43993,AIICO,2017-01-12,0.60,0.60,277127,2026-04-08T02:42:32.390658+00:00,0.000000,1.694915,-1.666667,1.639344,NaN,0.602,NaN,NaN,NaN,NaN,81.132564
8,44123,AIICO,2017-01-13,0.60,0.60,206000,2026-04-08T02:42:34.853543+00:00,0.000000,0.000000,1.694915,0.000000,NaN,0.598,NaN,NaN,NaN,NaN,81.132564
9,44213,AIICO,2017-01-16,0.60,0.60,587419,2026-04-08T02:42:38.72803+00:00,0.000000,0.000000,0.000000,-3.225806,NaN,0.598,NaN,NaN,NaN,NaN,81.132564
10,44323,AIICO,2017-01-17,0.60,0.60,815155,2026-04-08T02:42:41.056228+00:00,0.000000,0.000000,0.000000,-1.666667,NaN,0.600,NaN,NaN,NaN,NaN,81.132564
11,44433,AIICO,2017-01-18,0.60,0.60,5019030,2026-04-08T02:42:42.795307+00:00,0.000000,0.000000,0.000000,1.694915,1.666667,0.600,NaN,NaN,NaN,NaN,81.132564
12,44523,AIICO,2017-01-19,0.60,0.60,682173,2026-04-08T02:42:44.39781+00:00,0.000000,0.000000,0.000000,0.000000,1.639344,0.600,NaN,NaN,NaN,NaN,81.132564
13,44633,AIICO,2017-01-20,0.60,0.60,1160557,2026-04-08T02:42:46.643743+00:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.600,NaN,NaN,NaN,NaN,81.132564
14,44743,AIICO,2017-01-23,0.60,0.60,1278928,2026-04-08T02:42:49.827664+00:00,0.000000,0.000000,0.000000,0.000000,-3.225806,0.600,NaN,NaN,NaN,NaN,81.132564
15,44853,AIICO,2017-01-24,0.58,0.58,514640,2026-04-08T02:42:51.574002+00:00,-3.333333,0.000000,0.000000,0.000000,-1.666667,0.596,NaN,NaN,NaN,NaN,63.528075
16,44943,AIICO,2017-01-25,0.58,0.58,1595529,2026-04-08T02:42:54.05787+00:00,0.000000,-3.333333,0.000000,0.000000,1.694915,0.592,NaN,NaN,NaN,NaN,63.528075
17,45053,AIICO,2017-01-26,0.60,0.60,30146271,2026-04-08T02:42:55.759+00:00,3.448276,0.000000,-3.333333,0.000000,0.000000,0.592,NaN,NaN,NaN,NaN,70.860932
18,45163,AIICO,2017-01-27,0.60,0.60,1432258,2026-04-08T02:42:57.462271+00:00,0.000000,3.448276,0.000000,0.000000,0.000000,0.592,NaN,NaN,NaN,NaN,70.860932
19,45273,AIICO,2017-01-30,0.60,0.60,56806215,2026-04-08T02:43:00.905282+00:00,0.000000,0.000000,3.448276,0.000000,0.000000,0.592,0.6,NaN,NaN,NaN,70.860932

### 6. MACD

MACD stands for Moving Average Convergence Divergence.

It is a trend-following momentum indicator.

It answers the question: `"Is the stock's short-term trend becoming stronger or weaker compared to its longer-term trend?"`

Unlike RSI, which measures the strength of buying and selling, MACD measures changes in momentum.


MACD uses `Exponential Moving Averages (EMA)` instead of simple moving averages.

An EMA gives more weight to recent prices, making it more responsive to new information.

The standard settings are:

- 12-day EMA (short-term)
- 26-day EMA (long-term)

`MACD=EMA12​−EMA26​`

Positive MACD means

`The short-term average is above the long-term average.`

This usually indicates upward momentum.


Negative MACD means

`The short-term trend is weaker than the long-term trend.`

Often interpreted as bearish momentum.



The Signal Line is simply
`A 9-day EMA of the MACD line`

So now we have two lines:

- MACD Line
- Signal Line


If The MACD crosses above the Signal Line.
Many traders interpret this as increasing upward momentum.

Now If the MACD crosses below the Signal Line.
This may indicate weakening momentum.


* **The histogram** is simply
`Histogram=MACD−Signal`


Positive bars suggest bullish momentum is stronger than the signal line.
If the histogram becomes negative, momentum has weakened relative to the signal.


We will use pandas_ta inbuilt formula for these calculations. It will automaticallty create the following columns

* MACD_12_26_9: MACD
* MACDs_12_26_9: SIGNAL line
* MACDh_12_26_9: HISTOGRAM

In [28]:
import pandas_ta as ta
aiico_data_2.ta.macd(close="close_price", append=True)

      MACD_12_26_9  MACDh_12_26_9  MACDs_12_26_9
0              NaN            NaN            NaN
1              NaN            NaN            NaN
2              NaN            NaN            NaN
3              NaN            NaN            NaN
4              NaN            NaN            NaN
...            ...            ...            ...
2258     -0.113428      -0.001212      -0.112216
2259     -0.112567      -0.000281      -0.112286
2260     -0.110610       0.001341      -0.111951
2261     -0.101434       0.008413      -0.109848
2262     -0.085910       0.019150      -0.105060

[2263 rows x 3 columns]

In [35]:
aiico_data_2.rename(columns={'MACD_12_26_9':'MACD','MACDh_12_26_9':'MACD_hist','MACDs_12_26_9':'MACD_signal'},inplace=True)

In [38]:
aiico_data_2.head(50)

,id,symbol,trade_date,open_price,close_price,volume,created_at,returns_pct,lag_return1,lag_return2,...,lag_return10,stock_MA_5,stock_MA_20,stock_MA_50,returns_volatility_20,returns_volatility_50,stock_RSI,MACD,MACD_hist,MACD_signal
0,42813,AIICO,2017-01-03,0.60,0.60,356956,2026-04-08T02:41:25.765521+00:00,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,43373,AIICO,2017-01-04,0.61,0.61,180900,2026-04-08T02:42:20.164398+00:00,1.666667,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,100.000000,NaN,NaN,NaN
2,43483,AIICO,2017-01-05,0.62,0.62,838300,2026-04-08T02:42:22.380516+00:00,1.639344,1.666667,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,100.000000,NaN,NaN,NaN
3,43593,AIICO,2017-01-06,0.62,0.62,81591,2026-04-08T02:42:23.84796+00:00,0.000000,1.639344,1.666667,...,NaN,NaN,NaN,NaN,NaN,NaN,100.000000,NaN,NaN,NaN
4,43683,AIICO,2017-01-09,0.60,0.60,7669839,2026-04-08T02:42:26.938159+00:00,-3.225806,0.000000,1.639344,...,NaN,0.610,NaN,NaN,NaN,NaN,85.786802,NaN,NaN,NaN
5,43793,AIICO,2017-01-10,0.59,0.59,3421173,2026-04-08T02:42:29.227202+00:00,-1.666667,-3.225806,0.000000,...,NaN,0.608,NaN,NaN,NaN,NaN,79.688067,NaN,NaN,NaN
6,43903,AIICO,2017-01-11,0.60,0.60,1313195,2026-04-08T02:42:30.799441+00:00,1.694915,-1.666667,-3.225806,...,NaN,0.606,NaN,NaN,NaN,NaN,81.132564,NaN,NaN,NaN
7,43993,AIICO,2017-01-12,0.60,0.60,277127,2026-04-08T02:42:32.390658+00:00,0.000000,1.694915,-1.666667,...,NaN,0.602,NaN,NaN,NaN,NaN,81.132564,NaN,NaN,NaN
8,44123,AIICO,2017-01-13,0.60,0.60,206000,2026-04-08T02:42:34.853543+00:00,0.000000,0.000000,1.694915,...,NaN,0.598,NaN,NaN,NaN,NaN,81.132564,NaN,NaN,NaN
9,44213,AIICO,2017-01-16,0.60,0.60,587419,2026-04-08T02:42:38.72803+00:00,0.000000,0.000000,0.000000,...,NaN,0.598,NaN,NaN,NaN,NaN,81.132564,NaN,NaN,NaN
10,44323,AIICO,2017-01-17,0.60,0.60,815155,2026-04-08T02:42:41.056228+00:00,0.000000,0.000000,0.000000,...,NaN,0.600,NaN,NaN,NaN,NaN,81.132564,NaN,NaN,NaN
11,44433,AIICO,2017-01-18,0.60,0.60,5019030,2026-04-08T02:42:42.795307+00:00,0.000000,0.000000,0.000000,...,1.666667,0.600,NaN,NaN,NaN,NaN,81.132564,NaN,NaN,NaN
12,44523,AIICO,2017-01-19,0.60,0.60,682173,2026-04-08T02:42:44.39781+00:00,0.000000,0.000000,0.000000,...,1.639344,0.600,NaN,NaN,NaN,NaN,81.132564,NaN,NaN,NaN
13,44633,AIICO,2017-01-20,0.60,0.60,1160557,2026-04-08T02:42:46.643743+00:00,0.000000,0.000000,0.000000,...,0.000000,0.600,NaN,NaN,NaN,NaN,81.132564,NaN,NaN,NaN
14,44743,AIICO,2017-01-23,0.60,0.60,1278928,2026-04-08T02:42:49.827664+00:00,0.000000,0.000000,0.000000,...,-3.225806,0.600,NaN,NaN,NaN,NaN,81.132564,NaN,NaN,NaN
15,44853,AIICO,2017-01-24,0.58,0.58,514640,2026-04-08T02:42:51.574002+00:00,-3.333333,0.000000,0.000000,...,-1.666667,0.596,NaN,NaN,NaN,NaN,63.528075,NaN,NaN,NaN
16,44943,AIICO,2017-01-25,0.58,0.58,1595529,2026-04-08T02:42:54.05787+00:00,0.000000,-3.333333,0.000000,...,1.694915,0.592,NaN,NaN,NaN,NaN,63.528075,NaN,NaN,NaN
17,45053,AIICO,2017-01-26,0.60,0.60,30146271,2026-04-08T02:42:55.759+00:00,3.448276,0.000000,-3.333333,...,0.000000,0.592,NaN,NaN,NaN,NaN,70.860932,NaN,NaN,NaN
18,45163,AIICO,2017-01-27,0.60,0.60,1432258,2026-04-08T02:42:57.462271+00:00,0.000000,3.448276,0.000000,...,0.000000,0.592,NaN,NaN,NaN,NaN,70.860932,NaN,NaN,NaN
19,45273,AIICO,2017-01-30,0.60,0.60,56806215,2026-04-08T02:43:00.905282+00:00,0.000000,0.000000,3.448276,...,0.000000,0.592,0.6000,NaN,NaN,NaN,70.860932,NaN,NaN,NaN
20,45383,AIICO,2017-01-31,0.59,0.59,12810930,2026-04-08T02:43:03.07753+00:00,-1.666667,0.000000,0.000000,...,0.000000,0.594,0.5995,NaN,1.576086,NaN,62.956362,NaN,NaN,NaN
21,45493,AIICO,2017-02-01,0.59,0.59,169982,2026-04-08T02:43:04.619173+00:00,0.000000,-1.666667,0.000000,...,0.000000,0.596,0.5985,NaN,1.522458,NaN,62.956362,NaN,NaN,NaN
22,45583,AIICO,2017-02-02,0.60,0.60,254049,2026-04-08T02:43:06.209007+00:00,1.694915,0.000000,-1.666667,...,0.000000,0.596,0.5975,NaN,1.525953,NaN,67.199795,NaN,NaN,NaN
23,45693,AIICO,2017-02-03,0.58,0.58,1228500,2026-04-08T02:43:08.490666+00:00,-3.333333,1.694915,0.000000,...,0.000000,0.592,0.5955,NaN,1.682410,NaN,53.900929,NaN,NaN,NaN
24,45803,AIICO,2017-02-06,0.59,0.59,229700,2026-04-08T02:43:11.037852+00:00,1.724138,-3.333333,1.694915,...,0.000000,0.590,0.5950,NaN,1.594120,NaN,58.340263,NaN,NaN,NaN
25,45913,AIICO,2017-02-07,0.58,0.58,1152969,2026-04-08T02:43:12.662822+00:00,-1.694915,1.724138,-3.333333,...,-3.333333,0.588,0.5945,NaN,1.595619,NaN,52.858444,-0.006287,NaN,NaN
26,46003,AIICO,2017-02-08,0.60,0.60,143417888,2026-04-08T02:43:14.224877+00:00,3.448276,-1.694915,1.724138,...,0.000000,0.590,0.5945,NaN,1.739558,NaN,60.793183,-0.005105,NaN,NaN
27,46114,AIICO,2017-02-09,0.58,0.58,8615439,2026-04-08T02:43:16.408746+00:00,-3.333333,3.448276,-1.694915,...,3.448276,0.586,0.5935,NaN,1.893848,NaN,51.464485,-0.005716,NaN,NaN
28,46225,AIICO,2017-02-10,0.60,0.60,139049,2026-04-08T02:43:18.597686+00:00,3.448276,-3.333333,3.448276,...,0.000000,0.590,0.5935,NaN,2.058269,NaN,58.347679,-0.004534,NaN,NaN
29,46317,AIICO,2017-02-13,0.60,0.60,180489,2026-04-08T02:43:22.775561+00:00,0.000000,3.448276,-3.333333,...,0.000000,0.592,0.5935,NaN,2.058269,NaN,58.347679,-0.003557,NaN,NaN
30,46429,AIICO,2017-02-14,0.58,0.58,3778339,2026-04-08T02:43:24.286485+00:00,-3.333333,0.000000,3.448276,...,-1.666667,0.592,0.5925,NaN,2.190681,NaN,50.106427,-0.004346,NaN,NaN
31,46541,AIICO,2017-02-15,0.59,0.59,214682,2026-04-08T02:43:26.422065+00:00,1.724138,-3.333333,0.000000,...,0.000000,0.590,0.5920,NaN,2.230317,NaN,53.632852,-0.004117,NaN,NaN
32,46653,AIICO,2017-02-16,0.59,0.59,438877,2026-04-08T02:43:28.597754+00:00,0.000000,1.724138,-3.333333,...,1.694915,0.592,0.5915,NaN,2.230317,NaN,53.632852,-0.003891,NaN,NaN
33,46745,AIICO,2017-02-17,0.60,0.60,440244,2026-04-08T02:43:31.044717+00:00,1.694915,0.000000,1.724138,...,-3.333333,0.592,0.5915,NaN,2.264667,NaN,57.145659,-0.002871,0.001620,-0.004492
34,49413,AIICO,2017-02-20,0.60,0.60,105733,2026-04-08T02:51:00.639833+00:00,0.000000,1.694915,0.000000,...,1.724138,0.592,0.5915,NaN,2.264667,NaN,57.145659,-0.002040,0.001961,-0.004001
35,49505,AIICO,2017-02-21,0.60,0.60,96005,2026-04-08T02:51:03.098475+00:00,0.000000,0.000000,1.694915,...,-1.694915,0.596,0.5925,NaN,2.122763,NaN,57.145659,-0.001365,0.002109,-0.003474
36,46837,AIICO,2017-02-22,0.60,0.60,188700,2026-04-08T02:44:33.152084+00:00,0.000000,0.000000,0.000000,...,3.448276,0.598,0.5935,NaN,2.122763,NaN,57.145659,-0.000821,0.002122,-0.002943
37,46929,AIICO,2017-02-23,0.60,0.60,16500,2026-04-08T02:44:35.448225+00:00,0.000000,0.000000,0.000000,...,-3.333333,0.600,0.5935,NaN,1.979485,NaN,57.145659,-0.000385,0.002046,-0.002432
38,47021,AIICO,2017-02-24,0.55,0.55,97543676,2026-04-08T02:44:37.781529+00:00,-8.333333,0.000000,0.000000,...,3.448276,0.590,0.5910,NaN,2.721571,NaN,36.899044,-0.004028,-0.001277,-0.002751
39,47113,AIICO,2017-02-27,0.55,0.55,41904,2026-04-08T02:44:42.101817+00:00,0.000000,-8.333333,0.000000,...,0.000000,0.580,0.5885,NaN,2.721571,NaN,36.899044,-0.006836,-0.003268,-0.003568
40,47205,AIICO,2017-02-28,0.57,0.57,95700,2026-04-08T02:44:45.006295+00:00,3.636364,0.000000,-8.333333,...,-3.333333,0.574,0.5875,NaN,2.846906,NaN,45.806360,-0.007363,-0.003036,-0.004327
41,47297,AIICO,2017-03-01,0.57,0.57,96983,2026-04-08T02:44:47.332471+00:00,0.000000,3.636364,0.000000,...,1.724138,0.568,0.5865,NaN,2.846906,NaN,45.806360,-0.007692,-0.002692,-0.005000
42,47389,AIICO,2017-03-02,0.59,0.59,307916,2026-04-08T02:44:49.657807+00:00,3.508772,0.000000,3.636364,...,0.000000,0.566,0.5860,NaN,2.935704,NaN,53.430364,-0.006267,-0.001013,-0.005253
43,47481,AIICO,2017-03-03,0.60,0.60,235191,2026-04-08T02:44:51.301699+00:00,1.694915,3.508772,0.000000,...,1.694915,0.576,0.5870,NaN,2.853164,NaN,56.709659,-0.004281,0.000778,-0.005059
44,47573,AIICO,2017-03-06,0.63,0.63,665248,2026-04-08T02:44:56.024588+00:00,5.000000,1.694915,3.508772,...,0.000000,0.592,0.5890,NaN,3.033065,NaN,64.732953,-0.000283,0.003821,-0.004104
45,47665,AIICO,2017-03-07,0.60,0.60,1009642,2026-04-08T02:44:58.263872+00:00,-4.761905,5.000000,1.694915,...,0.000000,0.598,0.5900,NaN,3.215187,NaN,53.962408,0.000460,0.003651,-0.003191
46,47757,AIICO,2017-03-08,0.60,0.60,2171398,2026-04-08T02:44:59.957789+00:00,0.000000,-4.761905,5.000000,...,0.000000,0.604,0.5900,NaN,3.124109,NaN,53.962408,0.001036,0.003382,-0.002346
47,47849,AIICO,2017-03-09,0.60,0.60,1013353,2026-04-08T02:45:01.661944+00:00,0.000000,0.000000,-4.761905,...,0.000000,0.606,0.5910,NaN,3.021495,NaN,53.962408,0.001476,0.003057,-0.001581
48,47941,AIICO,2017-03-10,0.59,0.59,575956,2026-04-08T02:45:03.96312+00:00,-1.666667,0.000000,0.000000,...,-8.333333,0.604,0.5905,NaN,2.948924,NaN,50.466588,0.001006,0.002070,-0.001064
49,48033,AIICO,2017-03-13,0.57,0.57,949072,2026-04-08T02:45:08.663664+00:00,-3.389831,-1.666667,0.000000,...,0.000000,0.592,0.5890,0.5938,3.042331,NaN,44.287136,-0.000969,0.000076,-0.001045

### 7. Stock Volume Moving Average

Daily trading volume measures how many shares changed hands.

In [39]:
aiico_data_2['stock_volume_MA']=aiico_data_2['volume'].rolling(window=20).mean()

In [40]:
aiico_data_2.head(30)

,id,symbol,trade_date,open_price,close_price,volume,created_at,returns_pct,lag_return1,lag_return2,...,stock_MA_5,stock_MA_20,stock_MA_50,returns_volatility_20,returns_volatility_50,stock_RSI,MACD,MACD_hist,MACD_signal,stock_volume_MA
0,42813,AIICO,2017-01-03,0.60,0.60,356956,2026-04-08T02:41:25.765521+00:00,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,43373,AIICO,2017-01-04,0.61,0.61,180900,2026-04-08T02:42:20.164398+00:00,1.666667,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,100.000000,NaN,NaN,NaN,NaN
2,43483,AIICO,2017-01-05,0.62,0.62,838300,2026-04-08T02:42:22.380516+00:00,1.639344,1.666667,NaN,...,NaN,NaN,NaN,NaN,NaN,100.000000,NaN,NaN,NaN,NaN
3,43593,AIICO,2017-01-06,0.62,0.62,81591,2026-04-08T02:42:23.84796+00:00,0.000000,1.639344,1.666667,...,NaN,NaN,NaN,NaN,NaN,100.000000,NaN,NaN,NaN,NaN
4,43683,AIICO,2017-01-09,0.60,0.60,7669839,2026-04-08T02:42:26.938159+00:00,-3.225806,0.000000,1.639344,...,0.610,NaN,NaN,NaN,NaN,85.786802,NaN,NaN,NaN,NaN
5,43793,AIICO,2017-01-10,0.59,0.59,3421173,2026-04-08T02:42:29.227202+00:00,-1.666667,-3.225806,0.000000,...,0.608,NaN,NaN,NaN,NaN,79.688067,NaN,NaN,NaN,NaN
6,43903,AIICO,2017-01-11,0.60,0.60,1313195,2026-04-08T02:42:30.799441+00:00,1.694915,-1.666667,-3.225806,...,0.606,NaN,NaN,NaN,NaN,81.132564,NaN,NaN,NaN,NaN
7,43993,AIICO,2017-01-12,0.60,0.60,277127,2026-04-08T02:42:32.390658+00:00,0.000000,1.694915,-1.666667,...,0.602,NaN,NaN,NaN,NaN,81.132564,NaN,NaN,NaN,NaN
8,44123,AIICO,2017-01-13,0.60,0.60,206000,2026-04-08T02:42:34.853543+00:00,0.000000,0.000000,1.694915,...,0.598,NaN,NaN,NaN,NaN,81.132564,NaN,NaN,NaN,NaN
9,44213,AIICO,2017-01-16,0.60,0.60,587419,2026-04-08T02:42:38.72803+00:00,0.000000,0.000000,0.000000,...,0.598,NaN,NaN,NaN,NaN,81.132564,NaN,NaN,NaN,NaN
10,44323,AIICO,2017-01-17,0.60,0.60,815155,2026-04-08T02:42:41.056228+00:00,0.000000,0.000000,0.000000,...,0.600,NaN,NaN,NaN,NaN,81.132564,NaN,NaN,NaN,NaN
11,44433,AIICO,2017-01-18,0.60,0.60,5019030,2026-04-08T02:42:42.795307+00:00,0.000000,0.000000,0.000000,...,0.600,NaN,NaN,NaN,NaN,81.132564,NaN,NaN,NaN,NaN
12,44523,AIICO,2017-01-19,0.60,0.60,682173,2026-04-08T02:42:44.39781+00:00,0.000000,0.000000,0.000000,...,0.600,NaN,NaN,NaN,NaN,81.132564,NaN,NaN,NaN,NaN
13,44633,AIICO,2017-01-20,0.60,0.60,1160557,2026-04-08T02:42:46.643743+00:00,0.000000,0.000000,0.000000,...,0.600,NaN,NaN,NaN,NaN,81.132564,NaN,NaN,NaN,NaN
14,44743,AIICO,2017-01-23,0.60,0.60,1278928,2026-04-08T02:42:49.827664+00:00,0.000000,0.000000,0.000000,...,0.600,NaN,NaN,NaN,NaN,81.132564,NaN,NaN,NaN,NaN
15,44853,AIICO,2017-01-24,0.58,0.58,514640,2026-04-08T02:42:51.574002+00:00,-3.333333,0.000000,0.000000,...,0.596,NaN,NaN,NaN,NaN,63.528075,NaN,NaN,NaN,NaN
16,44943,AIICO,2017-01-25,0.58,0.58,1595529,2026-04-08T02:42:54.05787+00:00,0.000000,-3.333333,0.000000,...,0.592,NaN,NaN,NaN,NaN,63.528075,NaN,NaN,NaN,NaN
17,45053,AIICO,2017-01-26,0.60,0.60,30146271,2026-04-08T02:42:55.759+00:00,3.448276,0.000000,-3.333333,...,0.592,NaN,NaN,NaN,NaN,70.860932,NaN,NaN,NaN,NaN
18,45163,AIICO,2017-01-27,0.60,0.60,1432258,2026-04-08T02:42:57.462271+00:00,0.000000,3.448276,0.000000,...,0.592,NaN,NaN,NaN,NaN,70.860932,NaN,NaN,NaN,NaN
19,45273,AIICO,2017-01-30,0.60,0.60,56806215,2026-04-08T02:43:00.905282+00:00,0.000000,0.000000,3.448276,...,0.592,0.6000,NaN,NaN,NaN,70.860932,NaN,NaN,NaN,5719162.80
20,45383,AIICO,2017-01-31,0.59,0.59,12810930,2026-04-08T02:43:03.07753+00:00,-1.666667,0.000000,0.000000,...,0.594,0.5995,NaN,1.576086,NaN,62.956362,NaN,NaN,NaN,6341861.50
21,45493,AIICO,2017-02-01,0.59,0.59,169982,2026-04-08T02:43:04.619173+00:00,0.000000,-1.666667,0.000000,...,0.596,0.5985,NaN,1.522458,NaN,62.956362,NaN,NaN,NaN,6341315.60
22,45583,AIICO,2017-02-02,0.60,0.60,254049,2026-04-08T02:43:06.209007+00:00,1.694915,0.000000,-1.666667,...,0.596,0.5975,NaN,1.525953,NaN,67.199795,NaN,NaN,NaN,6312103.05
23,45693,AIICO,2017-02-03,0.58,0.58,1228500,2026-04-08T02:43:08.490666+00:00,-3.333333,1.694915,0.000000,...,0.592,0.5955,NaN,1.682410,NaN,53.900929,NaN,NaN,NaN,6369448.50
24,45803,AIICO,2017-02-06,0.59,0.59,229700,2026-04-08T02:43:11.037852+00:00,1.724138,-3.333333,1.694915,...,0.590,0.5950,NaN,1.594120,NaN,58.340263,NaN,NaN,NaN,5997441.55
25,45913,AIICO,2017-02-07,0.58,0.58,1152969,2026-04-08T02:43:12.662822+00:00,-1.694915,1.724138,-3.333333,...,0.588,0.5945,NaN,1.595619,NaN,52.858444,-0.006287,NaN,NaN,5884031.35
26,46003,AIICO,2017-02-08,0.60,0.60,143417888,2026-04-08T02:43:14.224877+00:00,3.448276,-1.694915,1.724138,...,0.590,0.5945,NaN,1.739558,NaN,60.793183,-0.005105,NaN,NaN,12989266.00
27,46114,AIICO,2017-02-09,0.58,0.58,8615439,2026-04-08T02:43:16.408746+00:00,-3.333333,3.448276,-1.694915,...,0.586,0.5935,NaN,1.893848,NaN,51.464485,-0.005716,NaN,NaN,13406181.60
28,46225,AIICO,2017-02-10,0.60,0.60,139049,2026-04-08T02:43:18.597686+00:00,3.448276,-3.333333,3.448276,...,0.590,0.5935,NaN,2.058269,NaN,58.347679,-0.004534,NaN,NaN,13402834.05
29,46317,AIICO,2017-02-13,0.60,0.60,180489,2026-04-08T02:43:22.775561+00:00,0.000000,3.448276,-3.333333,...,0.592,0.5935,NaN,2.058269,NaN,58.347679,-0.003557,NaN,NaN,13382487.55

In [41]:
aiico_data_2.info()

<class 'pandas.DataFrame'>
RangeIndex: 2263 entries, 0 to 2262
Data columns (total 22 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id                     2263 non-null   int64
 1   symbol                 2263 non-null   str
 2   trade_date             2263 non-null   str
 3   open_price             2262 non-null   float64
 4   close_price            2263 non-null   float64
 5   volume                 2263 non-null   int64
 6   created_at             2263 non-null   str
 7   returns_pct            2262 non-null   float64
 8   lag_return1            2261 non-null   float64
 9   lag_return2            2260 non-null   float64
 10  lag_return5            2257 non-null   float64
 11  lag_return10           2252 non-null   float64
 12  stock_MA_5             2259 non-null   float64
 13  stock_MA_20            2244 non-null   float64
 14  stock_MA_50            2214 non-null   float64
 15  returns_volatility_20  2243 non-null   float64
 16  returns_volatility_50  2213 non-null   float64
 17  stock_RSI              2262 non-null   float64
 18  MACD                   2238 non-null   float64
 19  MACD_hist              2230 non-null   float64
 20  MACD_signal            2230 non-null   float64
 21  stock_volume_MA        2244 non-null   float64
dtypes: float64(17), int64(2), str(3)
memory usage: 389.1 KB

In [42]:
aiico_data_2.isna().sum()

id                        0
symbol                    0
trade_date                0
open_price                1
close_price               0
volume                    0
created_at                0
returns_pct               1
lag_return1               2
lag_return2               3
lag_return5               6
lag_return10             11
stock_MA_5                4
stock_MA_20              19
stock_MA_50              49
returns_volatility_20    20
returns_volatility_50    50
stock_RSI                 1
MACD                     25
MACD_hist                33
MACD_signal              33
stock_volume_MA          19
dtype: int64

In [43]:
aiico_cleaned=aiico_data_2.dropna()

In [44]:
aiico_cleaned

,id,symbol,trade_date,open_price,close_price,volume,created_at,returns_pct,lag_return1,lag_return2,...,stock_MA_5,stock_MA_20,stock_MA_50,returns_volatility_20,returns_volatility_50,stock_RSI,MACD,MACD_hist,MACD_signal,stock_volume_MA
50,48125,AIICO,2017-03-14,0.57,0.57,3559140,2026-04-08T02:45:11.088473+00:00,0.000000,-3.389831,-1.666667,...,0.586,0.5885,0.5932,2.952268,2.384043,44.287136,-0.002506,-0.001169,-0.001337,5488296.00
51,48217,AIICO,2017-03-15,0.57,0.57,3765251,2026-04-08T02:45:12.861206+00:00,0.000000,0.000000,-3.389831,...,0.580,0.5875,0.5924,2.922928,2.370819,44.287136,-0.003681,-0.001875,-0.001806,5665824.45
52,48309,AIICO,2017-03-16,0.57,0.57,2271616,2026-04-08T02:45:15.084197+00:00,0.000000,0.000000,0.000000,...,0.574,0.5865,0.5914,2.922928,2.357464,44.287136,-0.004560,-0.002203,-0.002357,5757461.40
53,48401,AIICO,2017-03-17,0.59,0.59,1989491,2026-04-08T02:45:17.543831+00:00,3.508772,0.000000,0.000000,...,0.574,0.5860,0.5908,3.009420,2.413292,52.165344,-0.003601,-0.000995,-0.002606,5834923.75
54,48493,AIICO,2017-03-20,0.59,0.59,1313841,2026-04-08T02:45:21.873889+00:00,0.000000,3.508772,0.000000,...,0.578,0.5855,0.5906,3.009420,2.369940,52.165344,-0.002809,-0.000162,-0.002646,5895329.15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2258,298023,AIICO,2026-07-13,3.96,3.96,6133839,2026-07-13T15:10:02.995074+00:00,0.253165,-3.422983,1.741294,...,4.022,4.1110,4.3864,2.987390,2.815631,37.906530,-0.113428,-0.001212,-0.112216,6903072.35
2259,298461,AIICO,2026-07-14,3.96,3.96,3349343,2026-07-14T15:10:03.094441+00:00,0.000000,0.253165,-3.422983,...,3.996,4.0805,4.3818,2.956692,2.815557,37.906530,-0.112567,-0.000281,-0.112286,6456163.80
2260,298899,AIICO,2026-07-15,3.96,3.96,3986502,2026-07-15T15:10:03.078609+00:00,0.000000,0.000000,0.253165,...,3.984,4.0585,4.3748,2.870553,2.783520,37.906530,-0.110610,0.001341,-0.111951,6209837.50
2261,299337,AIICO,2026-07-16,4.04,4.04,6691535,2026-07-16T15:10:03.113936+00:00,2.020202,0.000000,0.000000,...,3.974,4.0405,4.3616,2.923575,2.470319,43.797942,-0.101434,0.008413,-0.109848,6254280.50
2262,299775,AIICO,2026-07-17,4.13,4.13,3108626,2026-07-17T15:10:03.053983+00:00,2.227723,2.020202,0.000000,...,4.010,4.0470,4.3492,2.139909,2.488577,49.592326,-0.085910,0.019150,-0.105060,6010622.10

In [45]:
aiico_cleaned.to_csv('feature_engineering/stocks_FE/AIICO_ENGINEERED')

### Automate the Process

Based on the steps taken we have to find a way to smartly automate this process for all stock data.

In [61]:
import pandas as pd
import pandas_ta as ta
import numpy as np
import os

import pandas as pd

def prepare_data(data: pd.DataFrame,drop_items: list[str] | None = None) -> pd.DataFrame:
    if drop_items is None:
        drop_items = ["high_price", "low_price"]
    return data.drop(columns=drop_items)

def stock_returns_percent(data: pd.DataFrame) -> pd.DataFrame:
    data['returns_pct']=data['close_price'].pct_change()*100
    return data

def lag_returns(data: pd.DataFrame,lag_items: list[int] | None = None) -> pd.DataFrame:
    if lag_items is None:
        lag_items=[1]
    for lag in lag_items:
        data[f'lag_return{lag}']=data['returns_pct'].shift(lag)
    return data
    
def moving_averages(data: pd.DataFrame,averaging_items: list[int] | None = None) -> pd.DataFrame:
    if averaging_items is None:
        averaging_items=[5]
    for avg in averaging_items:
        data[f'stock_MA_{avg}']=data['close_price'].rolling(avg).mean()
    return data

def rolling_volatility(data: pd.DataFrame,volatility_items: list[int] | None = None) -> pd.DataFrame:
    if volatility_items is None:
        volatility_items=[20]
    for vol in volatility_items:
        data[f'returns_volatility_{vol}']=data['returns_pct'].rolling(vol).std()
    return data

def relative_strength_index(data:pd.DataFrame, rsi_length:int | None=None) -> pd.DataFrame:
     if rsi_length is None:
        rsi_length=14

     data['stock_RSI']=ta.rsi(data['close_price'], length=rsi_length)
     return data

def ma_convergence_divergence(data:pd.DataFrame) -> pd.DataFrame:
     data.ta.macd(close='close_price', append=True)
     data.rename(columns={'MACD_12_26_9':'MACD','MACDh_12_26_9':'MACD_hist','MACDs_12_26_9':'MACD_signal'},inplace=True)
     return data

def volume_moving_average(data: pd.DataFrame,volume_items: list[int] | None = None) -> pd.DataFrame:
    if volume_items is None:
        volume_items=[20]
    for vol in volume_items:
        data[f'stock_volume_MA_{vol}']=data['volume'].rolling(vol).mean()
    return data

def clean_and_save(data:pd.DataFrame,stock_name:str):
     cleaned_data=data.dropna()
     cleaned_data.to_csv(f'feature_engineering/stocks_FE/{stock_name.upper()}_ENGINEERED',index=False)


def stock_data_engineering(folder_path):
    for csv_data in os.listdir(folder_path):
        try:
            if csv_data.endswith(".csv"):
                data = pd.read_csv(os.path.join(folder_path, csv_data))

            if len(data) > 400:
                ticker = os.path.splitext(csv_data)[0] ## Captures the name of the stock
                print()
                print(f'{csv_data} engineering begins')

                ## Prepare the data
                print("preparing data")
                prepared_data=prepare_data(data,drop_items=["high_price", "low_price"])

                ## Implement stock returns (%)
                print("stock returns")
                data_with_stock_returns=stock_returns_percent(prepared_data)

                ## Implement lagging
                print("lag returns")
                data_lag_returns=lag_returns(data_with_stock_returns,lag_items=[1,5,10])

                ## Applying Moving Averege
                print("moving_averages")
                data_moving_average=moving_averages(data_lag_returns,averaging_items=[5,20,50])

                ## Applying Rolling Volatility
                print("rolling_volatility")
                data_rolling_volatility = rolling_volatility(data_moving_average,volatility_items=[20,50])

                ## Intrducing RSI
                print("relative_strength_index")
                data_rsi=relative_strength_index(data_rolling_volatility,rsi_length=14)

                ## Calculating the MACD
                print("ma_convergence_divergence")
                data_macd=ma_convergence_divergence(data_rsi)

                ## Get stock volume moving average
                print("volume_moving_average")
                data_volume_ma = volume_moving_average(data_macd,volume_items=[20])

                ## Clean and save data
                print("clean_and_save")
                clean_and_save(data_volume_ma,stock_name=ticker)

                print(f"{ticker} engineering completed")
            else:
                continue
            
        except Exception as e:
            print(f"Error! {ticker}", e)

In [67]:
stock_data_engineering("stock_data")

ACADEMY.csv engineering begins
preparing data
stock returns
lag returns
moving_averages
rolling_volatility
relative_strength_index
ma_convergence_divergence
volume_moving_average
clean_and_save
ACADEMY engineering completed

ACCESSCORP.csv engineering begins
preparing data
stock returns
lag returns
moving_averages
rolling_volatility
relative_strength_index
ma_convergence_divergence
volume_moving_average
clean_and_save
ACCESSCORP engineering completed

AFRINSURE.csv engineering begins
preparing data
stock returns
lag returns
moving_averages
rolling_volatility
relative_strength_index
ma_convergence_divergence
volume_moving_average
clean_and_save
AFRINSURE engineering completed

AFRIPRUD.csv engineering begins
preparing data
stock returns
lag returns
moving_averages
rolling_volatility
relative_strength_index
ma_convergence_divergence
volume_moving_average
clean_and_save
AFRIPRUD engineering completed

AFROMEDIA.csv engineering begins
preparing data
stock returns
lag returns
moving_averages
rolling_volatility
relative_strength_index
ma_convergence_divergence
volume_moving_average
clean_and_save
AFROMEDIA engineering completed

AIICO.csv engineering begins
preparing data
stock returns
lag returns
moving_averages
rolling_volatility
relative_strength_index
ma_convergence_divergence
volume_moving_average
clean_and_save
AIICO engineering completed

AIRTELAFRI.csv engineering begins
preparing data
stock returns
lag returns
moving_averages
rolling_volatility
relative_strength_index
ma_convergence_divergence
volume_moving_average
clean_and_save
AIRTELAFRI engineering completed

ARADEL.csv engineering begins
preparing data
stock returns
lag returns
moving_averages
rolling_volatility
relative_strength_index
ma_convergence_divergence
volume_moving_average
clean_and_save
ARADEL engineering completed

AUSTINLAZ.csv engineering begins
preparing data
stock returns
lag returns
moving_averages
rolling_volatility
relative_strength_index
ma_convergence_divergence
volume_moving_average
clean_and_save
AUSTINLAZ engineering completed

BERGER.csv engineering begins
preparing data
stock returns
lag returns
moving_averages
rolling_volatility
relative_strength_index
ma_convergence_divergence
volume_moving_average
clean_and_save
BERGER engineering completed

BETAGLAS.csv engineering begins
preparing data
stock returns
lag returns
moving_averages
rolling_volatility
relative_strength_index
ma_convergence_divergence
volume_moving_average
clean_and_save
BETAGLAS engineering completed

BUACEMENT.csv engineering begins
preparing data
stock returns
lag returns
moving_averages
rolling_volatility
relative_strength_index
ma_convergence_divergence
volume_moving_average
clean_and_save
BUACEMENT engineering completed

BUAFOODS.csv engineering begins
preparing data
stock returns
lag returns
moving_averages
rolling_volatility
relative_strength_index
ma_convergence_divergence
volume_moving_average
clean_and_save
BUAFOODS engineering completed

CADBURY.csv engineering begins
preparing data
stock returns
lag returns
moving_averages
rolling_volatility
relative_strength_index
ma_convergence_divergence
volume_moving_average
clean_and_save
CADBURY engineering completed

CAP.csv engineering begins
preparing data
stock returns
lag returns
moving_averages
rolling_volatility
relative_strength_index
ma_convergence_divergence
volume_moving_average
clean_and_save
CAP engineering completed

CHAMS.csv engineering begins
preparing data
stock returns
lag returns
moving_averages
rolling_volatility
relative_strength_index
ma_convergence_divergence
volume_moving_average
clean_and_save
CHAMS engineering completed

CONHALLPLC.csv engineering begins
preparing data
stock returns
lag returns
moving_averages
rolling_volatility
relative_strength_index
ma_convergence_divergence
volume_moving_average
clean_and_save
CONHALLPLC engineering completed

CONOIL.csv engineering begins
preparing data
stock returns
lag returns
moving_averages
rolling_volatility
relative_strength_index
ma_convergence_divergence
volume_moving_average
clean_and_save
CONOIL engineering completed

CORNERST.csv engineering begins
preparing data
stock returns
lag returns
moving_averages
rolling_volatility
relative_strength_index
ma_convergence_divergence
volume_moving_average
clean_and_save
CORNERST engineering completed

CUSTODIAN.csv engineering begins
preparing data
stock returns
lag returns
moving_averages
rolling_volatility
relative_strength_index
ma_convergence_divergence
volume_moving_average
clean_and_save
CUSTODIAN engineering completed

CUTIX.csv engineering begins
preparing data
stock returns
lag returns
moving_averages
rolling_volatility
relative_strength_index
ma_convergence_divergence
volume_moving_average
clean_and_save
CUTIX engineering completed

CWG.csv engineering begins
preparing data
stock returns
lag returns
moving_averages
rolling_volatility
relative_strength_index
ma_convergence_divergence
volume_moving_average
clean_and_save
CWG engineering completed

DAARCOMM.csv engineering begins
preparing data
stock returns
lag returns
moving_averages
rolling_volatility
relative_strength_index
ma_convergence_divergence
volume_moving_average
clean_and_save
DAARCOMM engineering completed

DANGCEM.csv engineering begins
preparing data
stock returns
lag returns
moving_averages
rolling_volatility
relative_strength_index
ma_convergence_divergence
volume_moving_average
clean_and_save
DANGCEM engineering completed

DANGSUGAR.csv engineering begins
preparing data
stock returns
lag returns
moving_averages
rolling_volatility
relative_strength_index
ma_convergence_divergence
volume_moving_average
clean_and_save
DANGSUGAR engineering completed

EKOCORP.csv engineering begins
preparing data
stock returns
lag returns
moving_averages
rolling_volatility
relative_strength_index
ma_convergence_divergence
volume_moving_average
clean_and_save
EKOCORP engineering completed

ELLAHLAKES.csv engineering begins
preparing data
stock returns
lag returns
moving_averages
rolling_volatility
relative_strength_index
ma_convergence_divergence
volume_moving_average
clean_and_save
ELLAHLAKES engineering completed

ETERNA.csv engineering begins
preparing data
stock returns
lag returns
moving_averages
rolling_volatility
relative_strength_index
ma_convergence_divergence
volume_moving_average
clean_and_save
ETERNA engineering completed

ETI.csv engineering begins
preparing data
stock returns
lag returns
moving_averages
rolling_volatility
relative_strength_index
ma_convergence_divergence
volume_moving_average
clean_and_save
ETI engineering completed

EUNISELL.csv engineering begins
preparing data
stock returns
lag returns
moving_averages
rolling_volatility
relative_strength_index
ma_convergence_divergence
volume_moving_average
clean_and_save
EUNISELL engineering completed

FCMB.csv engineering begins
preparing data
stock returns
lag returns
moving_averages
rolling_volatility
relative_strength_index
ma_convergence_divergence
volume_moving_average
clean_and_save
FCMB engineering completed

FIDELITYBK.csv engineering begins
preparing data
stock returns
lag returns
moving_averages
rolling_volatility
relative_strength_index
ma_convergence_divergence
volume_moving_average
clean_and_save
FIDELITYBK engineering completed

FIDSON.csv engineering begins
preparing data
stock returns
lag returns
moving_averages
rolling_volatility
relative_strength_index
ma_convergence_divergence
volume_moving_average
clean_and_save
FIDSON engineering completed

FTNCOCOA.csv engineering begins
preparing data
stock returns
lag returns
moving_averages
rolling_volatility
relative_strength_index
ma_convergence_divergence
volume_moving_average
clean_and_save
FTNCOCOA engineering completed

GEREGU.csv engineering begins
preparing data
stock returns
lag returns
moving_averages
rolling_volatility
relative_strength_index
ma_convergence_divergence
volume_moving_average
clean_and_save
GEREGU engineering completed

GTCO.csv engineering begins
preparing data
stock returns
lag returns
moving_averages
rolling_volatility
relative_strength_index
ma_convergence_divergence
volume_moving_average
clean_and_save
GTCO engineering completed

GUINEAINS.csv engineering begins
preparing data
stock returns
lag returns
moving_averages
rolling_volatility
relative_strength_index
ma_convergence_divergence
volume_moving_average
clean_and_save
GUINEAINS engineering completed

GUINNESS.csv engineering begins
preparing data
stock returns
lag returns
moving_averages
rolling_volatility
relative_strength_index
ma_convergence_divergence
volume_moving_average
clean_and_save
GUINNESS engineering completed

IKEJAHOTEL.csv engineering begins
preparing data
stock returns
lag returns
moving_averages
rolling_volatility
relative_strength_index
ma_convergence_divergence
volume_moving_average
clean_and_save
IKEJAHOTEL engineering completed

IMG.csv engineering begins
preparing data
stock returns
lag returns
moving_averages
rolling_volatility
relative_strength_index
ma_convergence_divergence
volume_moving_average
clean_and_save
IMG engineering completed

INFINITY.csv engineering begins
preparing data
stock returns
lag returns
moving_averages
rolling_volatility
relative_strength_index
ma_convergence_divergence
volume_moving_average
clean_and_save
INFINITY engineering completed

INTBREW.csv engineering begins
preparing data
stock returns
lag returns
moving_averages
rolling_volatility
relative_strength_index
ma_convergence_divergence
volume_moving_average
clean_and_save
INTBREW engineering completed

INTENEGINS.csv engineering begins
preparing data
stock returns
lag returns
moving_averages
rolling_volatility
relative_strength_index
ma_convergence_divergence
volume_moving_average
clean_and_save
INTENEGINS engineering completed

JAIZBANK.csv engineering begins
preparing data
stock returns
lag returns
moving_averages
rolling_volatility
relative_strength_index
ma_convergence_divergence
volume_moving_average
clean_and_save
JAIZBANK engineering completed

JAPAULGOLD.csv engineering begins
preparing data
stock returns
lag returns
moving_averages
rolling_volatility
relative_strength_index
ma_convergence_divergence
volume_moving_average
clean_and_save
JAPAULGOLD engineering completed

JBERGER.csv engineering begins
preparing data
stock returns
lag returns
moving_averages
rolling_volatility
relative_strength_index
ma_convergence_divergence
volume_moving_average
clean_and_save
JBERGER engineering completed

JOHNHOLT.csv engineering begins
preparing data
stock returns
lag returns
moving_averages
rolling_volatility
relative_strength_index
ma_convergence_divergence
volume_moving_average
clean_and_save
JOHNHOLT engineering completed

JULI.csv engineering begins
preparing data
stock returns
lag returns
moving_averages
rolling_volatility
relative_strength_index
ma_convergence_divergence
volume_moving_average
clean_and_save
JULI engineering completed

LASACO.csv engineering begins
preparing data
stock returns
lag returns
moving_averages
rolling_volatility
relative_strength_index
ma_convergence_divergence
volume_moving_average
clean_and_save
LASACO engineering completed

LEARNAFRCA.csv engineering begins
preparing data
stock returns
lag returns
moving_averages
rolling_volatility
relative_strength_index
ma_convergence_divergence
volume_moving_average
clean_and_save
LEARNAFRCA engineering completed

LINKASSURE.csv engineering begins
preparing data
stock returns
lag returns
moving_averages
rolling_volatility
relative_strength_index
ma_convergence_divergence
volume_moving_average
clean_and_save
LINKASSURE engineering completed

LIVESTOCK.csv engineering begins
preparing data
stock returns
lag returns
moving_averages
rolling_volatility
relative_strength_index
ma_convergence_divergence
volume_moving_average
clean_and_save
LIVESTOCK engineering completed

LIVINGTRUST.csv engineering begins
preparing data
stock returns
lag returns
moving_averages
rolling_volatility
relative_strength_index
ma_convergence_divergence
volume_moving_average
clean_and_save
LIVINGTRUST engineering completed

MAYBAKER.csv engineering begins
preparing data
stock returns
lag returns
moving_averages
rolling_volatility
relative_strength_index
ma_convergence_divergence
volume_moving_average
clean_and_save
MAYBAKER engineering completed

MBENEFIT.csv engineering begins
preparing data
stock returns
lag returns
moving_averages
rolling_volatility
relative_strength_index
ma_convergence_divergence
volume_moving_average
clean_and_save
MBENEFIT engineering completed

MCNICHOLS.csv engineering begins
preparing data
stock returns
lag returns
moving_averages
rolling_volatility
relative_strength_index
ma_convergence_divergence
volume_moving_average
clean_and_save
MCNICHOLS engineering completed

MECURE.csv engineering begins
preparing data
stock returns
lag returns
moving_averages
rolling_volatility
relative_strength_index
ma_convergence_divergence
volume_moving_average
clean_and_save
MECURE engineering completed

MEYER.csv engineering begins
preparing data
stock returns
lag returns
moving_averages
rolling_volatility
relative_strength_index
ma_convergence_divergence
volume_moving_average
clean_and_save
MEYER engineering completed

MORISON.csv engineering begins
preparing data
stock returns
lag returns
moving_averages
rolling_volatility
relative_strength_index
ma_convergence_divergence
volume_moving_average
clean_and_save
MORISON engineering completed

MTNN.csv engineering begins
preparing data
stock returns
lag returns
moving_averages
rolling_volatility
relative_strength_index
ma_convergence_divergence
volume_moving_average
clean_and_save
MTNN engineering completed

MULTITREX.csv engineering begins
preparing data
stock returns
lag returns
moving_averages
rolling_volatility
relative_strength_index
ma_convergence_divergence
volume_moving_average
clean_and_save
MULTITREX engineering completed

MULTIVERSE.csv engineering begins
preparing data
stock returns
lag returns
moving_averages
rolling_volatility
relative_strength_index
ma_convergence_divergence
volume_moving_average
clean_and_save
MULTIVERSE engineering completed

NAHCO.csv engineering begins
preparing data
stock returns
lag returns
moving_averages
rolling_volatility
relative_strength_index
ma_convergence_divergence
volume_moving_average
clean_and_save
NAHCO engineering completed

NASCON.csv engineering begins
preparing data
stock returns
lag returns
moving_averages
rolling_volatility
relative_strength_index
ma_convergence_divergence
volume_moving_average
clean_and_save
NASCON engineering completed

NB.csv engineering begins
preparing data
stock returns
lag returns
moving_averages
rolling_volatility
relative_strength_index
ma_convergence_divergence
volume_moving_average
clean_and_save
NB engineering completed

NCR.csv engineering begins
preparing data
stock returns
lag returns
moving_averages
rolling_volatility
relative_strength_index
ma_convergence_divergence
volume_moving_average
clean_and_save
NCR engineering completed

NEIMETH.csv engineering begins
preparing data
stock returns
lag returns
moving_averages
rolling_volatility
relative_strength_index
ma_convergence_divergence
volume_moving_average
clean_and_save
NEIMETH engineering completed

NEM.csv engineering begins
preparing data
stock returns
lag returns
moving_averages
rolling_volatility
relative_strength_index
ma_convergence_divergence
volume_moving_average
clean_and_save
NEM engineering completed

NESTLE.csv engineering begins
preparing data
stock returns
lag returns
moving_averages
rolling_volatility
relative_strength_index
ma_convergence_divergence
volume_moving_average
clean_and_save
NESTLE engineering completed

NGXGROUP.csv engineering begins
preparing data
stock returns
lag returns
moving_averages
rolling_volatility
relative_strength_index
ma_convergence_divergence
volume_moving_average
clean_and_save
NGXGROUP engineering completed

NNFM.csv engineering begins
preparing data
stock returns
lag returns
moving_averages
rolling_volatility
relative_strength_index
ma_convergence_divergence
volume_moving_average
clean_and_save
NNFM engineering completed

NPFMCRFBK.csv engineering begins
preparing data
stock returns
lag returns
moving_averages
rolling_volatility
relative_strength_index
ma_convergence_divergence
volume_moving_average
clean_and_save
NPFMCRFBK engineering completed

OANDO.csv engineering begins
preparing data
stock returns
lag returns
moving_averages
rolling_volatility
relative_strength_index
ma_convergence_divergence
volume_moving_average
clean_and_save
OANDO engineering completed

OKOMUOIL.csv engineering begins
preparing data
stock returns
lag returns
moving_averages
rolling_volatility
relative_strength_index
ma_convergence_divergence
volume_moving_average
clean_and_save
OKOMUOIL engineering completed

OMATEK.csv engineering begins
preparing data
stock returns
lag returns
moving_averages
rolling_volatility
relative_strength_index
ma_convergence_divergence
volume_moving_average
clean_and_save
OMATEK engineering completed

PHARMDEKO.csv engineering begins
preparing data
stock returns
lag returns
moving_averages
rolling_volatility
relative_strength_index
ma_convergence_divergence
volume_moving_average
clean_and_save
PHARMDEKO engineering completed

PREMPAINTS.csv engineering begins
preparing data
stock returns
lag returns
moving_averages
rolling_volatility
relative_strength_index
ma_convergence_divergence
volume_moving_average
clean_and_save
PREMPAINTS engineering completed

PRESTIGE.csv engineering begins
preparing data
stock returns
lag returns
moving_averages
rolling_volatility
relative_strength_index
ma_convergence_divergence
volume_moving_average
clean_and_save
PRESTIGE engineering completed

PZ.csv engineering begins
preparing data
stock returns
lag returns
moving_averages
rolling_volatility
relative_strength_index
ma_convergence_divergence
volume_moving_average
clean_and_save
PZ engineering completed

REDSTAREX.csv engineering begins
preparing data
stock returns
lag returns
moving_averages
rolling_volatility
relative_strength_index
ma_convergence_divergence
volume_moving_average
clean_and_save
REDSTAREX engineering completed

RONCHESS.csv engineering begins
preparing data
stock returns
lag returns
moving_averages
rolling_volatility
relative_strength_index
ma_convergence_divergence
volume_moving_average
clean_and_save
RONCHESS engineering completed

ROYALEX.csv engineering begins
preparing data
stock returns
lag returns
moving_averages
rolling_volatility
relative_strength_index
ma_convergence_divergence
volume_moving_average
clean_and_save
ROYALEX engineering completed

RTBRISCOE.csv engineering begins
preparing data
stock returns
lag returns
moving_averages
rolling_volatility
relative_strength_index
ma_convergence_divergence
volume_moving_average
clean_and_save
RTBRISCOE engineering completed

SCOA.csv engineering begins
preparing data
stock returns
lag returns
moving_averages
rolling_volatility
relative_strength_index
ma_convergence_divergence
volume_moving_average
clean_and_save
SCOA engineering completed

SEPLAT.csv engineering begins
preparing data
stock returns
lag returns
moving_averages
rolling_volatility
relative_strength_index
ma_convergence_divergence
volume_moving_average
clean_and_save
SEPLAT engineering completed

SKYAVN.csv engineering begins
preparing data
stock returns
lag returns
moving_averages
rolling_volatility
relative_strength_index
ma_convergence_divergence
volume_moving_average
clean_and_save
SKYAVN engineering completed

SOVRENINS.csv engineering begins
preparing data
stock returns
lag returns
moving_averages
rolling_volatility
relative_strength_index
ma_convergence_divergence
volume_moving_average
clean_and_save
SOVRENINS engineering completed

STACO.csv engineering begins
preparing data
stock returns
lag returns
moving_averages
rolling_volatility
relative_strength_index
ma_convergence_divergence
volume_moving_average
clean_and_save
STACO engineering completed

STANBIC.csv engineering begins
preparing data
stock returns
lag returns
moving_averages
rolling_volatility
relative_strength_index
ma_convergence_divergence
volume_moving_average

In [68]:
data=pd.read_csv('feature_engineering/stocks_FE/DANGCEM_ENGINEERED')

In [69]:
data.head()

,id,symbol,trade_date,open_price,close_price,volume,created_at,returns_pct,lag_return1,lag_return5,...,stock_MA_5,stock_MA_20,stock_MA_50,returns_volatility_20,returns_volatility_50,stock_RSI,MACD,MACD_hist,MACD_signal,stock_volume_MA_20
0,48089,DANGCEM,2017-03-14,160.5,160.5,110348,2026-04-08T02:45:11.088473+00:00,0.312500,-0.621118,4.924293,...,158.68,163.965,166.1138,2.639646,1.786330,44.852485,-2.556640,-0.324587,-2.232052,131046.40
1,48181,DANGCEM,2017-03-15,160.5,160.5,14242,2026-04-08T02:45:12.861206+00:00,0.000000,0.312500,-2.847839,...,160.35,163.540,165.8440,2.633715,1.786330,44.852485,-2.383181,-0.120903,-2.262278,129470.20
2,48273,DANGCEM,2017-03-16,160.0,160.0,40822,2026-04-08T02:45:15.084197+00:00,-0.311526,0.000000,4.995071,...,160.40,163.090,165.7036,2.633239,1.697588,44.023477,-2.260008,0.001816,-2.261824,127882.15
3,48365,DANGCEM,2017-03-17,166.0,166.0,363998,2026-04-08T02:45:17.543831+00:00,3.750000,-0.311526,0.782473,...,161.40,162.940,165.6836,2.780608,1.781573,54.815997,-1.659117,0.482166,-2.141283,120953.45
4,48457,DANGCEM,2017-03-20,165.0,165.0,381772,2026-04-08T02:45:21.873889+00:00,-0.602410,3.750000,-0.621118,...,162.40,162.740,165.6036,2.783272,1.775130,52.982490,-1.249198,0.713668,-1.962866,111636.80

In [70]:
data2=pd.read_csv('feature_engineering/stocks_FE/DAARCOMM_ENGINEERED')

In [71]:
data2

,id,symbol,trade_date,open_price,close_price,volume,created_at,returns_pct,lag_return1,lag_return5,...,stock_MA_5,stock_MA_20,stock_MA_50,returns_volatility_20,returns_volatility_50,stock_RSI,MACD,MACD_hist,MACD_signal,stock_volume_MA_20
0,69761,DAARCOMM,2018-03-01,0.48,0.48,271000,2026-04-08T03:01:36.321302+00:00,-4.000000,0.000000,0.000000,...,0.496,0.4990,0.4996,0.894427,0.565685,0.000000,-0.001595,-0.001276,-0.000319,19177.00
1,69853,DAARCOMM,2018-03-02,0.48,0.48,0,2026-04-08T03:01:38.625174+00:00,0.000000,-4.000000,0.000000,...,0.492,0.4980,0.4992,0.894427,0.565685,0.000000,-0.002827,-0.002007,-0.000821,18677.00
2,69945,DAARCOMM,2018-03-05,0.48,0.48,0,2026-04-08T03:01:43.47208+00:00,0.000000,0.000000,0.000000,...,0.488,0.4970,0.4988,0.894427,0.565685,0.000000,-0.003760,-0.002352,-0.001409,18677.00
3,70037,DAARCOMM,2018-03-06,0.48,0.48,0,2026-04-08T03:01:45.677681+00:00,0.000000,0.000000,0.000000,...,0.484,0.4960,0.4984,0.894427,0.565685,0.000000,-0.004448,-0.002432,-0.002017,18222.00
4,70129,DAARCOMM,2018-03-08,0.48,0.48,42000,2026-04-08T03:01:48.923554+00:00,0.000000,0.000000,0.000000,...,0.480,0.4950,0.4980,0.894427,0.565685,0.000000,-0.004937,-0.002336,-0.002601,20322.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1974,298049,DAARCOMM,2026-07-13,1.76,1.76,3004280,2026-07-13T15:10:02.995074+00:00,6.666667,-8.839779,9.696970,...,1.830,1.6790,1.7776,7.390873,6.573655,50.972657,-0.008581,0.026895,-0.035476,2742459.10
1975,298487,DAARCOMM,2026-07-14,1.76,1.76,760868,2026-07-14T15:10:03.094441+00:00,0.000000,6.666667,9.944751,...,1.784,1.6775,1.7796,7.248642,6.562835,50.972657,-0.005003,0.024378,-0.029381,2640741.15
1976,298925,DAARCOMM,2026-07-15,1.66,1.66,839004,2026-07-15T15:10:03.078609+00:00,-5.681818,0.000000,-2.512563,...,1.728,1.6755,1.7814,7.274721,6.567586,47.279622,-0.010121,0.015409,-0.025529,2565796.55
1977,299363,DAARCOMM,2026-07-16,1.70,1.70,1205491,2026-07-16T15:10:03.113936+00:00,2.409639,-5.681818,-6.701031,...,1.706,1.6710,1.7854,7.195140,6.537316,48.875216,-0.010824,0.011764,-0.022588,2569147.85
1978,299801,DAARCOMM,2026-07-17,1.65,1.65,2397115,2026-07-17T15:10:03.053983+00:00,-2.941176,2.409639,-8.839779,...,1.706,1.6630,1.7872,7.218782,6.534291,46.961910,-0.015240,0.005879,-0.021118,2615354.85

## Macroeconomic Data Engineering

We will create a function that will make us choose the number of lagging required for any variable. We will keep maximum lag column for each feature at 3 ie. oil_price can only have lag oil_price_lag(n) three times. We might not need this at all. We will just create this function for future use (reusability)

In [1]:
import pandas as pd
macro_data=pd.read_csv('macroeconomic_data/populated_cleaned_macro_data')

In [2]:
macro_data.head(10)

,Quarter,Month,Date,consumer_price_index(CPI)_monthly,Crude Oil Price_monthly,Domestic Production_monthly,Crude Oil Export_monthly,Inflation_allItemsAverage_monthly,Money Supply(M2)_monthly,currency in circulation_monthly,...,gdp_svc_Other Services_quarterly,GDP at Current Basic Prices_quarterly,Net Taxes on Products_quarterly,GDP at Current Market Prices_quarterly,foreign_reserve_Gross(USD)_monthly,foreign_reserve_Liquid(USD)_monthly,Year,Month_idx,foreign_reserve_gross(USD)_daily,foreign_reserve_liquid(USD)_daily
0,Q2,April,2017-04-03,204.45661,52.13,1.6,1.15,17.32,22304267.84,1983633.07,...,1237.68,26028.36,200.5,26228.85,3.029795e+10,2.962647e+10,2017,4,3.030715e+10,2.963927e+10
1,Q2,April,2017-04-04,204.45661,52.13,1.6,1.15,17.32,22304267.84,1983633.07,...,1237.68,26028.36,200.5,26228.85,3.029795e+10,2.962647e+10,2017,4,3.031831e+10,2.965163e+10
2,Q2,April,2017-04-05,204.45661,52.13,1.6,1.15,17.32,22304267.84,1983633.07,...,1237.68,26028.36,200.5,26228.85,3.029795e+10,2.962647e+10,2017,4,3.032576e+10,2.966022e+10
3,Q2,April,2017-04-06,204.45661,52.13,1.6,1.15,17.32,22304267.84,1983633.07,...,1237.68,26028.36,200.5,26228.85,3.029795e+10,2.962647e+10,2017,4,3.034555e+10,2.968121e+10
4,Q2,April,2017-04-07,204.45661,52.13,1.6,1.15,17.32,22304267.84,1983633.07,...,1237.68,26028.36,200.5,26228.85,3.029795e+10,2.962647e+10,2017,4,3.036654e+10,2.970295e+10
5,Q2,April,2017-04-10,204.45661,52.13,1.6,1.15,17.32,22304267.84,1983633.07,...,1237.68,26028.36,200.5,26228.85,3.029795e+10,2.962647e+10,2017,4,3.039389e+10,2.973158e+10
6,Q2,April,2017-04-11,204.45661,52.13,1.6,1.15,17.32,22304267.84,1983633.07,...,1237.68,26028.36,200.5,26228.85,3.029795e+10,2.962647e+10,2017,4,3.039392e+10,2.973163e+10
7,Q2,April,2017-04-12,204.45661,52.13,1.6,1.15,17.32,22304267.84,1983633.07,...,1237.68,26028.36,200.5,26228.85,3.029795e+10,2.962647e+10,2017,4,3.041681e+10,2.975423e+10
8,Q2,April,2017-04-13,204.45661,52.13,1.6,1.15,17.32,22304267.84,1983633.07,...,1237.68,26028.36,200.5,26228.85,3.029795e+10,2.962647e+10,2017,4,3.044376e+10,2.977964e+10
9,Q2,April,2017-04-18,204.45661,52.13,1.6,1.15,17.32,22304267.84,1983633.07,...,1237.68,26028.36,200.5,26228.85,3.029795e+10,2.962647e+10,2017,4,3.056378e+10,2.989211e+10

In [3]:
macro_data.shape

(2257, 84)

In [12]:
import pandas as pd

def daily_lag(data: pd.DataFrame,feature: str,lag_list: list[int] | None = None) -> pd.DataFrame:
    """
    Create lagged versions of a daily feature.
    Maximum of three lag features is advisable.
    NOTE: Drop NaN after lagging.
    """
    if lag_list is None:
        lag_list = [1]

    for lag in lag_list:
        if lag > 0:
            data[f"{feature}_lag{lag}"] = data[feature].shift(lag)

    return data


def monthly_lag(data: pd.DataFrame,feature: str,lag_list: list[int] | None = None) -> pd.DataFrame:
    '''Monthly Lag function. It is advisable to keep at maximum lag instance of 3'''
    
    if lag_list is None:
        lag_list = [1]

    monthly_data = (
        data.groupby(['Year', 'Month_idx'])[feature]
        .first()
        .reset_index()
        .sort_values(['Year', 'Month_idx'])
    )

    for lag in lag_list:
        monthly_data[f'{feature}_lag{lag}'] = monthly_data[feature].shift(lag)

    data = data.merge(
        monthly_data.drop(columns=[feature]),
        on=['Year', 'Month_idx'],
        how='left'
    )

    return data


def quarterly_lag(data: pd.DataFrame,feature: str,lag_list: list[int] | None = None) -> pd.DataFrame:
    '''Quarterly Lag function. It is advisable to keep at maximum lag instance of 3'''
    
    if lag_list is None:
        lag_list = [1]

    quarterly_data = (
        data.groupby(['Year', 'Quarter'])[feature]
        .first()
        .reset_index()
        .sort_values(['Year', 'Quarter'])
    )

    for lag in lag_list:
        quarterly_data[f'{feature}_lag{lag}'] = quarterly_data[feature].shift(lag)

    print(data.columns.tolist())
    print(quarterly_data.columns.tolist())

    data = data.merge(
        quarterly_data.drop(columns=[feature]),
        on=['Year', 'Quarter'],
        how='left'
    )

    return data

In [13]:
def lag_features(data: pd.DataFrame,features_lag: dict[str, list[int]] | None = None) -> pd.DataFrame:
    '''Creates lag features based on the frequency suffix.'''

    if features_lag is None:
        return data

    for feature, lag_list in features_lag.items():

        if feature.endswith('_daily'):
            data = daily_lag(
                data=data,
                feature=feature,
                lag_list=lag_list
            )

        elif feature.endswith('_monthly'):
            data = monthly_lag(
                data=data,
                feature=feature,
                lag_list=lag_list
            )

        elif feature.endswith('_quarterly'):
            data = quarterly_lag(
                data=data,
                feature=feature,
                lag_list=lag_list
            )

    return data

Test below

In [14]:
lag_dict = {
    "foreign_reserve_liquid(USD)_daily": [1, 5, 10],
    "consumer_price_index(CPI)_monthly": [1, 2],
    "GDP at Current Market Prices_quarterly": [1]
}

In [15]:
data = lag_features(macro_data, lag_dict)

['Quarter', 'Month', 'Date', 'consumer_price_index(CPI)_monthly', 'Crude Oil Price_monthly', 'Domestic Production_monthly', 'Crude Oil Export_monthly', 'Inflation_allItemsAverage_monthly', 'Money Supply(M2)_monthly', 'currency in circulation_monthly', 'bank reserves_monthly', 'netForeignAssets_monthly', 'netDomesticAssets_monthly', 'netDomesticCredit_monthly', 'creditToGovernment_monthly', 'creditToPrivateSector_monthly', 'MonetaryPolicyRate_monthly', 'TreasuryBillRate_monthly', 'Lending_Rate_monthly', 'Exchange_Rate(USD-EOP)_monthly', 'Premium_Motor_Spirit(PMS)_monthly', 'A. GDP_AGRICULTURE(agric)_quarterly', 'gdp_agric_Crop Production_quarterly', 'gdp_agric_Livestock_quarterly', 'gdp_agric_Forestry_quarterly', ' gdp_Fishing_quarterly', 'GDP_INDUSTRY(ind)_quarterly', 'gdp_ind_Mining and Quarrying(MQ)_quarterly', 'gdp_ind_MQ_Crude Petroleum and Natural Gas_quarterly', 'gdp_ind_MQ_Coal Mining_quarterly', 'gdp_ind_MQ_Metal Ores_quarterly', 'gdp_ind_MQ_Quarrying and Other Minerals_quarterly', 'gdp_ind_Manufacturing(mfg)_quarterly', ' gdp_ind_mfg_Oil Refining_quarterly', 'gdp_ind_mfg_Cement_quarterly', 'gdp_ind_mfg_Food, Beverage and Tobacco_quarterly', 'gdp_ind_mfg_Textile, Apparel and Footwear_quarterly', 'gdp_ind_mfg_Wood and Wood Products_quarterly', 'gdp_ind_mfg_Pulp, Paper and Paper Products_quarterly', 'gdp_ind_mfg_Chemical and Pharmaceutical Products_quarterly', 'gdp_ind_mfg_Non-Metallic Products_quarterly', 'gdp_ind_mfg_Plastic and Rubber Products_quarterly', 'gdp_ind_mfg_Electrical and Electronics_quarterly', 'gdp_ind_mfg_Basic Metal, Iron and Steel_quarterly', 'gdp_ind_mfg_Motor Vehicles and Assembly_quarterly', 'gdp_ind_mfg_Other Manufacturing_quarterly', 'gdp_ind_Electricity, Gas, Steam & Air conditioner_quarterly', 'gdp_ind_Water supply, Sewage, Waste Management_quarterly', 'gdp_ind_Construction_quarterly', 'GDP_SERVICES(svc)_quarterly', 'gdp_svc_Trade_quarterly', 'gdp_svc_Accommodation and Food Services_quarterly', 'gdp_svc_Transportation and Storage(TS)_quarterly', 'gdp_svc_TS_RoadTransport_quarterly', 'gdp_svc_TS_Rail Transport & Pipelines_quarterly', 'gdp_svc_TS_Water Transport_quarterly', 'gdp_svc_TS_Air Transport_quarterly', 'gdp_svc_TS_Transport Services_quarterly', 'gdp_svc_TS_Post and Courier Services_quarterly', 'gdp_svc_Information and Communication(IC)_quarterly', 'gdp_svc_IC_Telecommunications and Information Services_quarterly', 'gdp_svc_IC_Publishing_quarterly', 'gdp_svc_IC_Motion Pictures, Sound Recording and Music Production_quarterly', 'gdp_svc_IC_Broadcasting_quarterly', 'gdp_svc_Arts, Entertainment & Recreation_quarterly', 'gdp_svc_Financial and Insurance(FI)_quarterly', 'gdp_svc_FI_Financial Institutions_quarterly', 'gdp_svc_FI_Insurance_quarterly', 'gdp_svc_Real Estate_quarterly', 'gdp_svc_Professional, Scientific & Technical Services_quarterly', 'gdp_svc_Administrative and Support Services_quarterly', 'gdp_svc_Public Administration_quarterly', 'gdp_svc_Education_quarterly', 'gdp_svc_Human Health & Social Services_quarterly', 'gdp_svc_Other Services_quarterly', 'GDP at Current Basic Prices_quarterly', 'Net Taxes on Products_quarterly', 'GDP at Current Market Prices_quarterly', 'foreign_reserve_Gross(USD)_monthly', 'foreign_reserve_Liquid(USD)_monthly', 'Year', 'Month_idx', 'foreign_reserve_gross(USD)_daily', 'foreign_reserve_liquid(USD)_daily', 'foreign_reserve_liquid(USD)_daily_lag1', 'foreign_reserve_liquid(USD)_daily_lag5', 'foreign_reserve_liquid(USD)_daily_lag10', 'consumer_price_index(CPI)_monthly_lag1', 'consumer_price_index(CPI)_monthly_lag2']
['Year', 'Quarter', 'GDP at Current Market Prices_quarterly', 'GDP at Current Market Prices_quarterly_lag1']

In [16]:
data.head(50)

,Quarter,Month,Date,consumer_price_index(CPI)_monthly,Crude Oil Price_monthly,Domestic Production_monthly,Crude Oil Export_monthly,Inflation_allItemsAverage_monthly,Money Supply(M2)_monthly,currency in circulation_monthly,...,Year,Month_idx,foreign_reserve_gross(USD)_daily,foreign_reserve_liquid(USD)_daily,foreign_reserve_liquid(USD)_daily_lag1,foreign_reserve_liquid(USD)_daily_lag5,foreign_reserve_liquid(USD)_daily_lag10,consumer_price_index(CPI)_monthly_lag1,consumer_price_index(CPI)_monthly_lag2,GDP at Current Market Prices_quarterly_lag1
0,Q2,April,2017-04-03,204.456610,52.13,1.60,1.15,17.32,22304267.84,1983633.07,...,2017,4,3.030715e+10,2.963927e+10,NaN,NaN,NaN,NaN,NaN,NaN
1,Q2,April,2017-04-04,204.456610,52.13,1.60,1.15,17.32,22304267.84,1983633.07,...,2017,4,3.031831e+10,2.965163e+10,2.963927e+10,NaN,NaN,NaN,NaN,NaN
2,Q2,April,2017-04-05,204.456610,52.13,1.60,1.15,17.32,22304267.84,1983633.07,...,2017,4,3.032576e+10,2.966022e+10,2.965163e+10,NaN,NaN,NaN,NaN,NaN
3,Q2,April,2017-04-06,204.456610,52.13,1.60,1.15,17.32,22304267.84,1983633.07,...,2017,4,3.034555e+10,2.968121e+10,2.966022e+10,NaN,NaN,NaN,NaN,NaN
4,Q2,April,2017-04-07,204.456610,52.13,1.60,1.15,17.32,22304267.84,1983633.07,...,2017,4,3.036654e+10,2.970295e+10,2.968121e+10,NaN,NaN,NaN,NaN,NaN
5,Q2,April,2017-04-10,204.456610,52.13,1.60,1.15,17.32,22304267.84,1983633.07,...,2017,4,3.039389e+10,2.973158e+10,2.970295e+10,2.963927e+10,NaN,NaN,NaN,NaN
6,Q2,April,2017-04-11,204.456610,52.13,1.60,1.15,17.32,22304267.84,1983633.07,...,2017,4,3.039392e+10,2.973163e+10,2.973158e+10,2.965163e+10,NaN,NaN,NaN,NaN
7,Q2,April,2017-04-12,204.456610,52.13,1.60,1.15,17.32,22304267.84,1983633.07,...,2017,4,3.041681e+10,2.975423e+10,2.973163e+10,2.966022e+10,NaN,NaN,NaN,NaN
8,Q2,April,2017-04-13,204.456610,52.13,1.60,1.15,17.32,22304267.84,1983633.07,...,2017,4,3.044376e+10,2.977964e+10,2.975423e+10,2.968121e+10,NaN,NaN,NaN,NaN
9,Q2,April,2017-04-18,204.456610,52.13,1.60,1.15,17.32,22304267.84,1983633.07,...,2017,4,3.056378e+10,2.989211e+10,2.977964e+10,2.970295e+10,NaN,NaN,NaN,NaN
10,Q2,April,2017-04-19,204.456610,52.13,1.60,1.15,17.32,22304267.84,1983633.07,...,2017,4,3.058580e+10,2.991221e+10,2.989211e+10,2.973158e+10,2.963927e+10,NaN,NaN,NaN
11,Q2,April,2017-04-20,204.456610,52.13,1.60,1.15,17.32,22304267.84,1983633.07,...,2017,4,3.060621e+10,2.993048e+10,2.991221e+10,2.973163e+10,2.965163e+10,NaN,NaN,NaN
12,Q2,April,2017-04-21,204.456610,52.13,1.60,1.15,17.32,22304267.84,1983633.07,...,2017,4,3.062753e+10,2.994964e+10,2.993048e+10,2.975423e+10,2.966022e+10,NaN,NaN,NaN
13,Q2,April,2017-04-24,204.456610,52.13,1.60,1.15,17.32,22304267.84,1983633.07,...,2017,4,3.073113e+10,3.004628e+10,2.994964e+10,2.977964e+10,2.968121e+10,NaN,NaN,NaN
14,Q2,April,2017-04-25,204.456610,52.13,1.60,1.15,17.32,22304267.84,1983633.07,...,2017,4,3.076270e+10,3.007552e+10,3.004628e+10,2.989211e+10,2.970295e+10,NaN,NaN,NaN
15,Q2,April,2017-04-26,204.456610,52.13,1.60,1.15,17.32,22304267.84,1983633.07,...,2017,4,3.080186e+10,3.011239e+10,3.007552e+10,2.991221e+10,2.973158e+10,NaN,NaN,NaN
16,Q2,April,2017-04-27,204.456610,52.13,1.60,1.15,17.32,22304267.84,1983633.07,...,2017,4,3.084111e+10,3.014940e+10,3.011239e+10,2.993048e+10,2.973163e+10,NaN,NaN,NaN
17,Q2,April,2017-04-28,204.456610,52.13,1.60,1.15,17.32,22304267.84,1983633.07,...,2017,4,3.086463e+10,3.017061e+10,3.014940e+10,2.994964e+10,2.975423e+10,NaN,NaN,NaN
18,Q2,May,2017-05-02,207.729678,52.94,1.79,1.34,17.59,21768241.12,1975812.32,...,2017,5,3.097483e+10,3.027177e+10,3.017061e+10,3.004628e+10,2.977964e+10,204.456610,NaN,NaN
19,Q2,May,2017-05-03,207.729678,52.94,1.79,1.34,17.59,21768241.12,1975812.32,...,2017,5,3.098454e+10,3.027938e+10,3.027177e+10,3.007552e+10,2.989211e+10,204.456610,NaN,NaN
20,Q2,May,2017-05-04,207.729678,52.94,1.79,1.34,17.59,21768241.12,1975812.32,...,2017,5,3.098840e+10,3.028118e+10,3.027938e+10,3.011239e+10,2.991221e+10,204.456610,NaN,NaN
21,Q2,May,2017-05-05,207.729678,52.94,1.79,1.34,17.59,21768241.12,1975812.32,...,2017,5,3.098370e+10,3.027455e+10,3.028118e+10,3.014940e+10,2.993048e+10,204.456610,NaN,NaN
22,Q2,May,2017-05-08,207.729678,52.94,1.79,1.34,17.59,21768241.12,1975812.32,...,2017,5,3.093376e+10,3.021892e+10,3.027455e+10,3.017061e+10,2.994964e+10,204.456610,NaN,NaN
23,Q2,May,2017-05-09,207.729678,52.94,1.79,1.34,17.59,21768241.12,1975812.32,...,2017,5,3.092849e+10,3.021197e+10,3.021892e+10,3.027177e+10,3.004628e+10,204.456610,NaN,NaN
24,Q2,May,2017-05-10,207.729678,52.94,1.79,1.34,17.59,21768241.12,1975812.32,...,2017,5,3.092247e+10,3.020474e+10,3.021197e+10,3.027938e+10,3.007552e+10,204.456610,NaN,NaN
25,Q2,May,2017-05-11,207.729678,52.94,1.79,1.34,17.59,21768241.12,1975812.32,...,2017,5,3.091112e+10,3.019196e+10,3.020474e+10,3.028118e+10,3.011239e+10,204.456610,NaN,NaN
26,Q2,May,2017-05-12,207.729678,52.94,1.79,1.34,17.59,21768241.12,1975812.32,...,2017,5,3.087860e+10,3.015821e+10,3.019196e+10,3.027455e+10,3.014940e+10,204.456610,NaN,NaN
27,Q2,May,2017-05-15,207.729678,52.94,1.79,1.34,17.59,21768241.12,1975812.32,...,2017,5,3.078138e+10,3.006099e+10,3.015821e+10,3.021892e+10,3.017061e+10,204.456610,NaN,NaN
28,Q2,May,2017-05-16,207.729678,52.94,1.79,1.34,17.59,21768241.12,1975812.32,...,2017,5,3.075260e+10,3.003206e+10,3.006099e+10,3.021197e+10,3.027177e+10,204.456610,NaN,NaN
29,Q2,May,2017-05-17,207.729678,52.94,1.79,1.34,17.59,21768241.12,1975812.32,...,2017,5,3.072388e+10,3.000299e+10,3.003206e+10,3.020474e+10,3.027938e+10,204.456610,NaN,NaN
30,Q2,May,2017-05-18,207.729678,52.94,1.79,1.34,17.59,21768241.12,1975812.32,...,2017,5,3.069595e+10,2.997508e+10,3.000299e+10,3.019196e+10,3.028118e+10,204.456610,NaN,NaN
31,Q2,May,2017-05-19,207.729678,52.94,1.79,1.34,17.59,21768241.12,1975812.32,...,2017,5,3.066526e+10,2.994470e+10,2.997508e+10,3.015821e+10,3.027455e+10,204.456610,NaN,NaN
32,Q2,May,2017-05-22,207.729678,52.94,1.79,1.34,17.59,21768241.12,1975812.32,...,2017,5,3.057786e+10,2.985882e+10,2.994470e+10,3.006099e+10,3.021892e+10,204.456610,NaN,NaN
33,Q2,May,2017-05-23,207.729678,52.94,1.79,1.34,17.59,21768241.12,1975812.32,...,2017,5,3.054763e+10,2.982889e+10,2.985882e+10,3.003206e+10,3.021197e+10,204.456610,NaN,NaN
34,Q2,May,2017-05-24,207.729678,52.94,1.79,1.34,17.59,21768241.12,1975812.32,...,2017,5,3.051953e+10,2.980115e+10,2.982889e+10,3.000299e+10,3.020474e+10,204.456610,NaN,NaN
35,Q2,May,2017-05-25,207.729678,52.94,1.79,1.34,17.59,21768241.12,1975812.32,...,2017,5,3.049468e+10,2.977672e+10,2.980115e+10,2.997508e+10,3.019196e+10,204.456610,NaN,NaN
36,Q2,May,2017-05-26,207.729678,52.94,1.79,1.34,17.59,21768241.12,1975812.32,...,2017,5,3.046156e+10,2.974400e+10,2.977672e+10,2.994470e+10,3.015821e+10,204.456610,NaN,NaN
37,Q2,May,2017-05-30,207.729678,52.94,1.79,1.34,17.59,21768241.12,1975812.32,...,2017,5,3.036080e+10,2.964445e+10,2.974400e+10,2.985882e+10,3.006099e+10,204.456610,NaN,NaN
38,Q2,May,2017-05-31,207.729678,52.94,1.79,1.34,17.59,21768241.12,1975812.32,...,2017,5,3.032964e+10,2.961376e+10,2.964445e+10,2.982889e+10,3.003206e+10,204.456610,NaN,NaN
39,Q2,June,2017-06-01,211.637809,50.57,1.87,1.42,17.63,22047770.68,1897917.15,...,2017,6,3.030020e+10,2.958485e+10,2.961376e+10,2.980115e+10,3.000299e+10,207.729678,204.45661,NaN
40,Q2,June,2017-06-02,211.637809,50.57,1.87,1.42,17.63,22047770.68,1897917.15,...,2017,6,3.028322e+10,2.956838e+10,2.958485e+10,2.977672e+10,2.997508e+10,207.729678,204.45661,NaN
41,Q2,June,2017-06-05,211.637809,50.57,1.87,1.42,17.63,22047770.68,1897917.15,...,2017,6,3.027895e+10,2.956524e+10,2.956838e+10,2.974400e+10,2.994470e+10,207.729678,204.45661,NaN
42,Q2,June,2017-06-06,211.637809,50.57,1.87,1.42,17.63,22047770.68,1897917.15,...,2017,6,3.028970e+10,2.957630e+10,2.956524e+10,2.964445e+10,2.985882e+10,207.729678,204.45661,NaN
43,Q2,June,2017-06-07,211.637809,50.57,1.87,1.42,17.63,22047770.68,1897917.15,...,2017,6,3.029192e+10,2.957838e+10,2.957630e+10,2.961376e+10,2.982889e+10,207.729678,204.45661,NaN
44,Q2,June,2017-06-08,211.637809,50.57,1.87,1.42,17.63,22047770.68,1897917.15,...,2017,6,3.028371e+10,2.957006e+10,2.957838e+10,2.958485e+10,2.980115e+10,207.729678,204.45661,NaN
45,Q2,June,2017-06-09,211.637809,50.57,1.87,1.42,17.63,22047770.68,1897917.15,...,2017,6,3.026680e+10,2.955287e+10,2.957006e+10,2.956838e+10,2.977672e+10,207.729678,204.45661,NaN
46,Q2,June,2017-06-12,211.637809,50.57,1.87,1.42,17.63,22047770.68,1897917.15,...,2017,6,3.023515e+10,2.952113e+10,2.955287e+10,2.956524e+10,2.974400e+10,207.729678,204.45661,NaN
47,Q2,June,2017-06-13,211.637809,50.57,1.87,1.42,17.63,22047770.68,1897917.15,...,2017,6,3.022218e+10,2.950831e+10,2.952113e+10,2.957630e+10,2.964445e+10,207.729678,204.45661,NaN
48,Q2,June,2017-06-14,211.637809,50.57,1.87,1.42,17.63,22047770.68,1897917.15,...,2017,6,3.021401e+10,2.950031e+10,2.950831e+10,2.957838e+10,2.961376e+10,207.729678,204.45661,NaN
49,Q2,June,2017-06-15,211.637809,50.57,1.87,1.42,17.63,22047770.68,1897917.15,...,2017,6,3.021141e+10,2.949801e+10,2.950031e+10,2.957006e+10,2.958485e+10,207.729678,204.45661,NaN

### SUCCESS! 

Its complete. We can use these functions to apply any amount of economic lagging on the features we like