Here we will perform all the feature engineering required for this project. We will test all. See the vbest approach for automation.

In [1]:
import pandas as pd

In [2]:
aiico_data=pd.read_csv('stock_data/AIICO.csv')

In [3]:
aiico_data

,id,symbol,trade_date,open_price,high_price,low_price,close_price,volume,created_at
0,42813,AIICO,2017-01-03,0.60,NaN,NaN,0.60,356956,2026-04-08T02:41:25.765521+00:00
1,43373,AIICO,2017-01-04,0.61,NaN,NaN,0.61,180900,2026-04-08T02:42:20.164398+00:00
2,43483,AIICO,2017-01-05,0.62,NaN,NaN,0.62,838300,2026-04-08T02:42:22.380516+00:00
3,43593,AIICO,2017-01-06,0.62,NaN,NaN,0.62,81591,2026-04-08T02:42:23.84796+00:00
4,43683,AIICO,2017-01-09,0.60,NaN,NaN,0.60,7669839,2026-04-08T02:42:26.938159+00:00
...,...,...,...,...,...,...,...,...,...
2258,298023,AIICO,2026-07-13,3.96,NaN,NaN,3.96,6133839,2026-07-13T15:10:02.995074+00:00
2259,298461,AIICO,2026-07-14,3.96,NaN,NaN,3.96,3349343,2026-07-14T15:10:03.094441+00:00
2260,298899,AIICO,2026-07-15,3.96,NaN,NaN,3.96,3986502,2026-07-15T15:10:03.078609+00:00
2261,299337,AIICO,2026-07-16,4.04,NaN,NaN,4.04,6691535,2026-07-16T15:10:03.113936+00:00
2262,299775,AIICO,2026-07-17,4.13,NaN,NaN,4.13,3108626,2026-07-17T15:10:03.053983+00:00

In [ ]:
aiico_data_2=aiico_data.drop(['high_price','low_price'], axis=1)

,id,symbol,trade_date,open_price,high_price,low_price,close_price,volume,created_at
0,42813,AIICO,2017-01-03,0.60,NaN,NaN,0.60,356956,2026-04-08T02:41:25.765521+00:00
1,43373,AIICO,2017-01-04,0.61,NaN,NaN,0.61,180900,2026-04-08T02:42:20.164398+00:00
2,43483,AIICO,2017-01-05,0.62,NaN,NaN,0.62,838300,2026-04-08T02:42:22.380516+00:00
3,43593,AIICO,2017-01-06,0.62,NaN,NaN,0.62,81591,2026-04-08T02:42:23.84796+00:00
4,43683,AIICO,2017-01-09,0.60,NaN,NaN,0.60,7669839,2026-04-08T02:42:26.938159+00:00
...,...,...,...,...,...,...,...,...,...
2258,298023,AIICO,2026-07-13,3.96,NaN,NaN,3.96,6133839,2026-07-13T15:10:02.995074+00:00
2259,298461,AIICO,2026-07-14,3.96,NaN,NaN,3.96,3349343,2026-07-14T15:10:03.094441+00:00
2260,298899,AIICO,2026-07-15,3.96,NaN,NaN,3.96,3986502,2026-07-15T15:10:03.078609+00:00
2261,299337,AIICO,2026-07-16,4.04,NaN,NaN,4.04,6691535,2026-07-16T15:10:03.113936+00:00
2262,299775,AIICO,2026-07-17,4.13,NaN,NaN,4.13,3108626,2026-07-17T15:10:03.053983+00:00

In [5]:
aiico_data_2

,id,symbol,trade_date,open_price,close_price,volume,created_at
0,42813,AIICO,2017-01-03,0.60,0.60,356956,2026-04-08T02:41:25.765521+00:00
1,43373,AIICO,2017-01-04,0.61,0.61,180900,2026-04-08T02:42:20.164398+00:00
2,43483,AIICO,2017-01-05,0.62,0.62,838300,2026-04-08T02:42:22.380516+00:00
3,43593,AIICO,2017-01-06,0.62,0.62,81591,2026-04-08T02:42:23.84796+00:00
4,43683,AIICO,2017-01-09,0.60,0.60,7669839,2026-04-08T02:42:26.938159+00:00
...,...,...,...,...,...,...,...
2258,298023,AIICO,2026-07-13,3.96,3.96,6133839,2026-07-13T15:10:02.995074+00:00
2259,298461,AIICO,2026-07-14,3.96,3.96,3349343,2026-07-14T15:10:03.094441+00:00
2260,298899,AIICO,2026-07-15,3.96,3.96,3986502,2026-07-15T15:10:03.078609+00:00
2261,299337,AIICO,2026-07-16,4.04,4.04,6691535,2026-07-16T15:10:03.113936+00:00
2262,299775,AIICO,2026-07-17,4.13,4.13,3108626,2026-07-17T15:10:03.053983+00:00

## Stock data feature engineering
### 1. Derive the returns in Percentage
This is the percentage difference between the current closing price and previous price

In [8]:
aiico_data_2['returns_pct']=aiico_data_2['close_price'].pct_change()*100
aiico_data_2

,id,symbol,trade_date,open_price,close_price,volume,created_at,returns,returns_pct
0,42813,AIICO,2017-01-03,0.60,0.60,356956,2026-04-08T02:41:25.765521+00:00,NaN,NaN
1,43373,AIICO,2017-01-04,0.61,0.61,180900,2026-04-08T02:42:20.164398+00:00,1.666667,1.666667
2,43483,AIICO,2017-01-05,0.62,0.62,838300,2026-04-08T02:42:22.380516+00:00,1.639344,1.639344
3,43593,AIICO,2017-01-06,0.62,0.62,81591,2026-04-08T02:42:23.84796+00:00,0.000000,0.000000
4,43683,AIICO,2017-01-09,0.60,0.60,7669839,2026-04-08T02:42:26.938159+00:00,-3.225806,-3.225806
...,...,...,...,...,...,...,...,...,...
2258,298023,AIICO,2026-07-13,3.96,3.96,6133839,2026-07-13T15:10:02.995074+00:00,0.253165,0.253165
2259,298461,AIICO,2026-07-14,3.96,3.96,3349343,2026-07-14T15:10:03.094441+00:00,0.000000,0.000000
2260,298899,AIICO,2026-07-15,3.96,3.96,3986502,2026-07-15T15:10:03.078609+00:00,0.000000,0.000000
2261,299337,AIICO,2026-07-16,4.04,4.04,6691535,2026-07-16T15:10:03.113936+00:00,2.020202,2.020202
2262,299775,AIICO,2026-07-17,4.13,4.13,3108626,2026-07-17T15:10:03.053983+00:00,2.227723,2.227723

In [9]:
aiico_data_2.drop(['returns'],axis=1,inplace=True)

In [10]:
aiico_data_2

,id,symbol,trade_date,open_price,close_price,volume,created_at,returns_pct
0,42813,AIICO,2017-01-03,0.60,0.60,356956,2026-04-08T02:41:25.765521+00:00,NaN
1,43373,AIICO,2017-01-04,0.61,0.61,180900,2026-04-08T02:42:20.164398+00:00,1.666667
2,43483,AIICO,2017-01-05,0.62,0.62,838300,2026-04-08T02:42:22.380516+00:00,1.639344
3,43593,AIICO,2017-01-06,0.62,0.62,81591,2026-04-08T02:42:23.84796+00:00,0.000000
4,43683,AIICO,2017-01-09,0.60,0.60,7669839,2026-04-08T02:42:26.938159+00:00,-3.225806
...,...,...,...,...,...,...,...,...
2258,298023,AIICO,2026-07-13,3.96,3.96,6133839,2026-07-13T15:10:02.995074+00:00,0.253165
2259,298461,AIICO,2026-07-14,3.96,3.96,3349343,2026-07-14T15:10:03.094441+00:00,0.000000
2260,298899,AIICO,2026-07-15,3.96,3.96,3986502,2026-07-15T15:10:03.078609+00:00,0.000000
2261,299337,AIICO,2026-07-16,4.04,4.04,6691535,2026-07-16T15:10:03.113936+00:00,2.020202
2262,299775,AIICO,2026-07-17,4.13,4.13,3108626,2026-07-17T15:10:03.053983+00:00,2.227723

### 2. Introduce Lag returns
Lagging is when you include previous information into current data point to give a better information about the past and how it affects the present and future

We will apply Lagging on the returns of previous return(lag1), previous 5 return(lag5), previous 10 return(lag10)

In [12]:
aiico_data_2["lag_return1"] = aiico_data_2["returns_pct"].shift(1)
aiico_data_2["lag_return2"] = aiico_data_2["returns_pct"].shift(2)
aiico_data_2["lag_return5"] = aiico_data_2["returns_pct"].shift(5)
aiico_data_2["lag_return10"] = aiico_data_2["returns_pct"].shift(10)

In [14]:
aiico_data_2.head(15)

,id,symbol,trade_date,open_price,close_price,volume,created_at,returns_pct,lag_return1,lag_return2,lag_return5,lag_return10
0,42813,AIICO,2017-01-03,0.60,0.60,356956,2026-04-08T02:41:25.765521+00:00,NaN,NaN,NaN,NaN,NaN
1,43373,AIICO,2017-01-04,0.61,0.61,180900,2026-04-08T02:42:20.164398+00:00,1.666667,NaN,NaN,NaN,NaN
2,43483,AIICO,2017-01-05,0.62,0.62,838300,2026-04-08T02:42:22.380516+00:00,1.639344,1.666667,NaN,NaN,NaN
3,43593,AIICO,2017-01-06,0.62,0.62,81591,2026-04-08T02:42:23.84796+00:00,0.000000,1.639344,1.666667,NaN,NaN
4,43683,AIICO,2017-01-09,0.60,0.60,7669839,2026-04-08T02:42:26.938159+00:00,-3.225806,0.000000,1.639344,NaN,NaN
5,43793,AIICO,2017-01-10,0.59,0.59,3421173,2026-04-08T02:42:29.227202+00:00,-1.666667,-3.225806,0.000000,NaN,NaN
6,43903,AIICO,2017-01-11,0.60,0.60,1313195,2026-04-08T02:42:30.799441+00:00,1.694915,-1.666667,-3.225806,1.666667,NaN
7,43993,AIICO,2017-01-12,0.60,0.60,277127,2026-04-08T02:42:32.390658+00:00,0.000000,1.694915,-1.666667,1.639344,NaN
8,44123,AIICO,2017-01-13,0.60,0.60,206000,2026-04-08T02:42:34.853543+00:00,0.000000,0.000000,1.694915,0.000000,NaN
9,44213,AIICO,2017-01-16,0.60,0.60,587419,2026-04-08T02:42:38.72803+00:00,0.000000,0.000000,0.000000,-3.225806,NaN
10,44323,AIICO,2017-01-17,0.60,0.60,815155,2026-04-08T02:42:41.056228+00:00,0.000000,0.000000,0.000000,-1.666667,NaN
11,44433,AIICO,2017-01-18,0.60,0.60,5019030,2026-04-08T02:42:42.795307+00:00,0.000000,0.000000,0.000000,1.694915,1.666667
12,44523,AIICO,2017-01-19,0.60,0.60,682173,2026-04-08T02:42:44.39781+00:00,0.000000,0.000000,0.000000,0.000000,1.639344
13,44633,AIICO,2017-01-20,0.60,0.60,1160557,2026-04-08T02:42:46.643743+00:00,0.000000,0.000000,0.000000,0.000000,0.000000
14,44743,AIICO,2017-01-23,0.60,0.60,1278928,2026-04-08T02:42:49.827664+00:00,0.000000,0.000000,0.000000,0.000000,-3.225806

### 3. Applying Moving Averages

Instead of looking at one day's price, we calculate the average of recent prices. This will smoothen the plot to give a sense of the trend. The more the averaging gap, the better the smoothening.

* 5-day	    Very short-term movement
* 10-day	Short-term trend
* 20-day	About one trading month
* 50-day	Medium-term trend

We will use 5(MA_5), 20(MA_20) and 50(MA_50) for this exercise.

In [15]:
aiico_data_2.shape

(2263, 12)

In [17]:
aiico_data_2["stock_MA_5"] = aiico_data_2["close_price"].rolling(window=5).mean()
aiico_data_2["stock_MA_20"] = aiico_data_2["close_price"].rolling(window=20).mean()
aiico_data_2["stock_MA_50"] = aiico_data_2["close_price"].rolling(window=50).mean()

In [18]:
aiico_data_2.head(20)

,id,symbol,trade_date,open_price,close_price,volume,created_at,returns_pct,lag_return1,lag_return2,lag_return5,lag_return10,stock_MA_5,stock_MA_20,stock_MA_50
0,42813,AIICO,2017-01-03,0.60,0.60,356956,2026-04-08T02:41:25.765521+00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,43373,AIICO,2017-01-04,0.61,0.61,180900,2026-04-08T02:42:20.164398+00:00,1.666667,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,43483,AIICO,2017-01-05,0.62,0.62,838300,2026-04-08T02:42:22.380516+00:00,1.639344,1.666667,NaN,NaN,NaN,NaN,NaN,NaN
3,43593,AIICO,2017-01-06,0.62,0.62,81591,2026-04-08T02:42:23.84796+00:00,0.000000,1.639344,1.666667,NaN,NaN,NaN,NaN,NaN
4,43683,AIICO,2017-01-09,0.60,0.60,7669839,2026-04-08T02:42:26.938159+00:00,-3.225806,0.000000,1.639344,NaN,NaN,0.610,NaN,NaN
5,43793,AIICO,2017-01-10,0.59,0.59,3421173,2026-04-08T02:42:29.227202+00:00,-1.666667,-3.225806,0.000000,NaN,NaN,0.608,NaN,NaN
6,43903,AIICO,2017-01-11,0.60,0.60,1313195,2026-04-08T02:42:30.799441+00:00,1.694915,-1.666667,-3.225806,1.666667,NaN,0.606,NaN,NaN
7,43993,AIICO,2017-01-12,0.60,0.60,277127,2026-04-08T02:42:32.390658+00:00,0.000000,1.694915,-1.666667,1.639344,NaN,0.602,NaN,NaN
8,44123,AIICO,2017-01-13,0.60,0.60,206000,2026-04-08T02:42:34.853543+00:00,0.000000,0.000000,1.694915,0.000000,NaN,0.598,NaN,NaN
9,44213,AIICO,2017-01-16,0.60,0.60,587419,2026-04-08T02:42:38.72803+00:00,0.000000,0.000000,0.000000,-3.225806,NaN,0.598,NaN,NaN
10,44323,AIICO,2017-01-17,0.60,0.60,815155,2026-04-08T02:42:41.056228+00:00,0.000000,0.000000,0.000000,-1.666667,NaN,0.600,NaN,NaN
11,44433,AIICO,2017-01-18,0.60,0.60,5019030,2026-04-08T02:42:42.795307+00:00,0.000000,0.000000,0.000000,1.694915,1.666667,0.600,NaN,NaN
12,44523,AIICO,2017-01-19,0.60,0.60,682173,2026-04-08T02:42:44.39781+00:00,0.000000,0.000000,0.000000,0.000000,1.639344,0.600,NaN,NaN
13,44633,AIICO,2017-01-20,0.60,0.60,1160557,2026-04-08T02:42:46.643743+00:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.600,NaN,NaN
14,44743,AIICO,2017-01-23,0.60,0.60,1278928,2026-04-08T02:42:49.827664+00:00,0.000000,0.000000,0.000000,0.000000,-3.225806,0.600,NaN,NaN
15,44853,AIICO,2017-01-24,0.58,0.58,514640,2026-04-08T02:42:51.574002+00:00,-3.333333,0.000000,0.000000,0.000000,-1.666667,0.596,NaN,NaN
16,44943,AIICO,2017-01-25,0.58,0.58,1595529,2026-04-08T02:42:54.05787+00:00,0.000000,-3.333333,0.000000,0.000000,1.694915,0.592,NaN,NaN
17,45053,AIICO,2017-01-26,0.60,0.60,30146271,2026-04-08T02:42:55.759+00:00,3.448276,0.000000,-3.333333,0.000000,0.000000,0.592,NaN,NaN
18,45163,AIICO,2017-01-27,0.60,0.60,1432258,2026-04-08T02:42:57.462271+00:00,0.000000,3.448276,0.000000,0.000000,0.000000,0.592,NaN,NaN
19,45273,AIICO,2017-01-30,0.60,0.60,56806215,2026-04-08T02:43:00.905282+00:00,0.000000,0.000000,3.448276,0.000000,0.000000,0.592,0.6,NaN

### Apply Rolling Volatility
Volatility measures how much returns fluctuate over a period. If i pick a returns period of 20 days , I use this to find out how stable the returns is over 20 days. This is basically the standard deviation during the period.

We will be using Rolling volatility of 20 days

In [20]:
aiico_data_2["returns_volatility_20"] = (
    aiico_data_2["returns_pct"]
      .rolling(window=20)
      .std()
)

In [21]:
aiico_data_2.head(25)

,id,symbol,trade_date,open_price,close_price,volume,created_at,returns_pct,lag_return1,lag_return2,lag_return5,lag_return10,stock_MA_5,stock_MA_20,stock_MA_50,returns_volatility_20
0,42813,AIICO,2017-01-03,0.60,0.60,356956,2026-04-08T02:41:25.765521+00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,43373,AIICO,2017-01-04,0.61,0.61,180900,2026-04-08T02:42:20.164398+00:00,1.666667,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,43483,AIICO,2017-01-05,0.62,0.62,838300,2026-04-08T02:42:22.380516+00:00,1.639344,1.666667,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,43593,AIICO,2017-01-06,0.62,0.62,81591,2026-04-08T02:42:23.84796+00:00,0.000000,1.639344,1.666667,NaN,NaN,NaN,NaN,NaN,NaN
4,43683,AIICO,2017-01-09,0.60,0.60,7669839,2026-04-08T02:42:26.938159+00:00,-3.225806,0.000000,1.639344,NaN,NaN,0.610,NaN,NaN,NaN
5,43793,AIICO,2017-01-10,0.59,0.59,3421173,2026-04-08T02:42:29.227202+00:00,-1.666667,-3.225806,0.000000,NaN,NaN,0.608,NaN,NaN,NaN
6,43903,AIICO,2017-01-11,0.60,0.60,1313195,2026-04-08T02:42:30.799441+00:00,1.694915,-1.666667,-3.225806,1.666667,NaN,0.606,NaN,NaN,NaN
7,43993,AIICO,2017-01-12,0.60,0.60,277127,2026-04-08T02:42:32.390658+00:00,0.000000,1.694915,-1.666667,1.639344,NaN,0.602,NaN,NaN,NaN
8,44123,AIICO,2017-01-13,0.60,0.60,206000,2026-04-08T02:42:34.853543+00:00,0.000000,0.000000,1.694915,0.000000,NaN,0.598,NaN,NaN,NaN
9,44213,AIICO,2017-01-16,0.60,0.60,587419,2026-04-08T02:42:38.72803+00:00,0.000000,0.000000,0.000000,-3.225806,NaN,0.598,NaN,NaN,NaN
10,44323,AIICO,2017-01-17,0.60,0.60,815155,2026-04-08T02:42:41.056228+00:00,0.000000,0.000000,0.000000,-1.666667,NaN,0.600,NaN,NaN,NaN
11,44433,AIICO,2017-01-18,0.60,0.60,5019030,2026-04-08T02:42:42.795307+00:00,0.000000,0.000000,0.000000,1.694915,1.666667,0.600,NaN,NaN,NaN
12,44523,AIICO,2017-01-19,0.60,0.60,682173,2026-04-08T02:42:44.39781+00:00,0.000000,0.000000,0.000000,0.000000,1.639344,0.600,NaN,NaN,NaN
13,44633,AIICO,2017-01-20,0.60,0.60,1160557,2026-04-08T02:42:46.643743+00:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.600,NaN,NaN,NaN
14,44743,AIICO,2017-01-23,0.60,0.60,1278928,2026-04-08T02:42:49.827664+00:00,0.000000,0.000000,0.000000,0.000000,-3.225806,0.600,NaN,NaN,NaN
15,44853,AIICO,2017-01-24,0.58,0.58,514640,2026-04-08T02:42:51.574002+00:00,-3.333333,0.000000,0.000000,0.000000,-1.666667,0.596,NaN,NaN,NaN
16,44943,AIICO,2017-01-25,0.58,0.58,1595529,2026-04-08T02:42:54.05787+00:00,0.000000,-3.333333,0.000000,0.000000,1.694915,0.592,NaN,NaN,NaN
17,45053,AIICO,2017-01-26,0.60,0.60,30146271,2026-04-08T02:42:55.759+00:00,3.448276,0.000000,-3.333333,0.000000,0.000000,0.592,NaN,NaN,NaN
18,45163,AIICO,2017-01-27,0.60,0.60,1432258,2026-04-08T02:42:57.462271+00:00,0.000000,3.448276,0.000000,0.000000,0.000000,0.592,NaN,NaN,NaN
19,45273,AIICO,2017-01-30,0.60,0.60,56806215,2026-04-08T02:43:00.905282+00:00,0.000000,0.000000,3.448276,0.000000,0.000000,0.592,0.6000,NaN,NaN
20,45383,AIICO,2017-01-31,0.59,0.59,12810930,2026-04-08T02:43:03.07753+00:00,-1.666667,0.000000,0.000000,-3.333333,0.000000,0.594,0.5995,NaN,1.576086
21,45493,AIICO,2017-02-01,0.59,0.59,169982,2026-04-08T02:43:04.619173+00:00,0.000000,-1.666667,0.000000,0.000000,0.000000,0.596,0.5985,NaN,1.522458
22,45583,AIICO,2017-02-02,0.60,0.60,254049,2026-04-08T02:43:06.209007+00:00,1.694915,0.000000,-1.666667,3.448276,0.000000,0.596,0.5975,NaN,1.525953
23,45693,AIICO,2017-02-03,0.58,0.58,1228500,2026-04-08T02:43:08.490666+00:00,-3.333333,1.694915,0.000000,0.000000,0.000000,0.592,0.5955,NaN,1.682410
24,45803,AIICO,2017-02-06,0.59,0.59,229700,2026-04-08T02:43:11.037852+00:00,1.724138,-3.333333,1.694915,0.000000,0.000000,0.590,0.5950,NaN,1.594120