# NGX PRACTICE

In [1]:
import requests
import os
from dotenv import load_dotenv

load_dotenv()

True

In [2]:
ngx_api_key=os.getenv("NGX_API_KEY")

ngx_market_url = "https://www.ngxpulse.ng/api/ngxdata/market"
ngx_stocks_url = "https://www.ngxpulse.ng/api/ngxdata/stocks"

headers = {
    "X-API-Key": f"{ngx_api_key}",
    "Content-Type": "application/json"
}

In [3]:
response = requests.get(ngx_stocks_url, headers=headers)

print(response.status_code)

if response.status_code == 200:
    data = response.json()
    print(data)
else:
    print(response.text)

200

In [5]:
len(data['stocks'])

146

In [6]:
ngx_asi_url='https://www.ngxpulse.ng/api/ngxdata/indices/asi/history?from=2020-01-01'

response = requests.get(ngx_asi_url, headers=headers)

print(response.status_code)

if response.status_code == 200:
    data = response.json()
    print(data)
else:
    print(response.text)

200

In [7]:
len(data['history'])

1618

In [10]:

ngx_asi_url='https://www.ngxpulse.ng/api/ngxdata/indices/asi/history?from=2020-01-01'

response = requests.get(ngx_asi_url, headers=headers)

print(response.status_code)

if response.status_code == 200:
    data = response.json()
    print(data)
else:
    print(response.text)

200

In [3]:
import requests
import pandas as pd
from dotenv import load_dotenv
import os

ngx_api_key=os.getenv("NGX_API_KEY")

# url = "https://www.ngxpulse.ng/api/ngxdata/stocks/DANGCEM/history"

# headers = {
#     "X-API-Key": ngx_api_key,
#     "Content-Type": "application/json"
# }

# response = requests.get(url, headers=headers)

# response.raise_for_status()

# data = response.json()

# df = pd.DataFrame(data)

# df.head()

# # df.to_csv("DANGCEM_history.csv", index=False)

In [4]:
import requests
import pandas as pd


url = "https://www.ngxpulse.ng/api/ngxdata/prices/DANGCEM"

headers = {
    "X-API-Key": ngx_api_key
}

params = {
    "from": "2017-01-01",
    "to": "2026-07-18"
}

response = requests.get(
    url,
    headers=headers,
    params=params
)

print(response.status_code)
print(response.text)

200

In [ ]:
data=response.text
data

## Note the data returned is a text data. We have to convert to json object

'{"success":true,"symbol":"DANGCEM","prices":[{"id":42778,"symbol":"DANGCEM","trade_date":"2017-01-03","open_price":173.99,"high_price":null,"low_price":null,"close_price":173.99,"volume":19200,"created_at":"2026-04-08T02:41:25.765521+00:00"},{"id":43338,"symbol":"DANGCEM","trade_date":"2017-01-04","open_price":173.99,"high_price":null,"low_price":null,"close_price":173.99,"volume":29100,"created_at":"2026-04-08T02:42:20.164398+00:00"},{"id":43448,"symbol":"DANGCEM","trade_date":"2017-01-05","open_price":167.02,"high_price":null,"low_price":null,"close_price":167.02,"volume":191164,"created_at":"2026-04-08T02:42:22.380516+00:00"},{"id":43558,"symbol":"DANGCEM","trade_date":"2017-01-06","open_price":167,"high_price":null,"low_price":null,"close_price":167,"volume":64437,"created_at":"2026-04-08T02:42:23.84796+00:00"},{"id":43648,"symbol":"DANGCEM","trade_date":"2017-01-09","open_price":169,"high_price":null,"low_price":null,"close_price":169,"volume":401559,"created_at":"2026-04-08T02:42:26.938159+00:00"},{"id":43758,"symbol":"DANGCEM","trade_date":"2017-01-10","open_price":168,"high_price":null,"low_price":null,"close_price":168,"volume":90263,"created_at":"2026-04-08T02:42:29.227202+00:00"},{"id":43868,"symbol":"DANGCEM","trade_date":"2017-01-11","open_price":168,"high_price":null,"low_price":null,"close_price":168,"volume":8283,"created_at":"2026-04-08T02:42:30.799441+00:00"},{"id":43958,"symbol":"DANGCEM","trade_date":"2017-01-12","open_price":168,"high_price":null,"low_price":null,"close_price":168,"volume":230640,"created_at":"2026-04-08T02:42:32.390658+00:00"},{"id":44068,"symbol":"DANGCEM","trade_date":"2017-01-13","open_price":168,"high_price":null,"low_price":null,"close_price":168,"volume":39673,"created_at":"2026-04-08T02:42:34.853543+00:00"},{"id":44178,"symbol":"DANGCEM","trade_date":"2017-01-16","open_price":168,"high_price":null,"low_price":null,"close_price":168,"volume":66471,"created_at":"2026-04-08T02:42:38.72803+00:00"},{"id":44288,"symbol":"DANGCEM","trade_date":"2017-01-17","open_price":168,"high_price":null,"low_price":null,"close_price":168,"volume":823837,"created_at":"2026-04-08T02:42:41.056228+00:00"},{"id":44398,"symbol":"DANGCEM","trade_date":"2017-01-18","open_price":168,"high_price":null,"low_price":null,"close_price":168,"volume":504897,"created_at":"2026-04-08T02:42:42.795307+00:00"},{"id":44488,"symbol":"DANGCEM","trade_date":"2017-01-19","open_price":167,"high_price":null,"low_price":null,"close_price":167,"volume":188632,"created_at":"2026-04-08T02:42:44.39781+00:00"},{"id":44598,"symbol":"DANGCEM","trade_date":"2017-01-20","open_price":167,"high_price":null,"low_price":null,"close_price":167,"volume":163006,"created_at":"2026-04-08T02:42:46.643743+00:00"},{"id":44708,"symbol":"DANGCEM","trade_date":"2017-01-23","open_price":167,"high_price":null,"low_price":null,"close_price":167,"volume":211476,"created_at":"2026-04-08T02:42:49.827664+00:00"},{"id":44818,"symbol":"DANGCEM","trade_date":"2017-01-24","open_price":167,"high_price":null,"low_price":null,"close_price":167,"volume":804424,"created_at":"2026-04-08T02:42:51.574002+00:00"},{"id":44908,"symbol":"DANGCEM","trade_date":"2017-01-25","open_price":167,"high_price":null,"low_price":null,"close_price":167,"volume":20179,"created_at":"2026-04-08T02:42:54.05787+00:00"},{"id":45018,"symbol":"DANGCEM","trade_date":"2017-01-26","open_price":167.01,"high_price":null,"low_price":null,"close_price":167.01,"volume":149466,"created_at":"2026-04-08T02:42:55.759+00:00"},{"id":45128,"symbol":"DANGCEM","trade_date":"2017-01-27","open_price":167.01,"high_price":null,"low_price":null,"close_price":167.01,"volume":52738,"created_at":"2026-04-08T02:42:57.462271+00:00"},{"id":45238,"symbol":"DANGCEM","trade_date":"2017-01-30","open_price":166,"high_price":null,"low_price":null,"close_price":166,"volume":63274,"created_at":"2026-04-08T02:43:00.905282+00:00"},{"id":45348,"symbol":"DANGCEM","trade_date":"2017-01-31","open_price":166,"high_price":null,"low_price":null,"close_price":166,"volume":62010,"created_at":"2026-04-08T02:43:03.07753+00:00"},{"id":45458,"symbol":"DANGCEM","trade_date":"2017-02-01","open_price":168,"high_price":null,"low_price":null,"close_price":168,"volume":81482,"created_at":"2026-04-08T02:43:04.619173+00:00"},{"id":45548,"symbol":"DANGCEM","trade_date":"2017-02-02","open_price":168,"high_price":null,"low_price":null,"close_price":168,"volume":212689,"created_at":"2026-04-08T02:43:06.209007+00:00"},{"id":45658,"symbol":"DANGCEM","trade_date":"2017-02-03","open_price":168,"high_price":null,"low_price":null,"close_price":168,"volume":14116,"created_at":"2026-04-08T02:43:08.490666+00:00"},{"id":45768,"symbol":"DANGCEM","trade_date":"2017-02-06","open_price":165.01,"high_price":null,"low_price":null,"close_price":165.01,"volume":371429,"created_at":"2026-04-08T02:43:11.037852+00:00"},{"id":45878,"symbol":"DANGCEM","trade_date":"2017-02-07","open_price":166,"high_price":null,"low_price":null,"close_price":166,"volume":119663,"created_at":"2026-04-08T02:43:12.662822+00:00"},{"id":45968,"symbol":"DANGCEM","trade_date":"2017-02-08","open_price":167.11,"high_price":null,"low_price":null,"close_price":167.11,"volume":347802,"created_at":"2026-04-08T02:43:14.224877+00:00"},{"id":46078,"symbol":"DANGCEM","trade_date":"2017-02-09","open_price":167.11,"high_price":null,"low_price":null,"close_price":167.11,"volume":232216,"created_at":"2026-04-08T02:43:16.408746+00:00"},{"id":46189,"symbol":"DANGCEM","trade_date":"2017-02-10","open_price":167.11,"high_price":null,"low_price":null,"close_price":167.11,"volume":13627,"created_at":"2026-04-08T02:43:18.597686+00:00"},{"id":46281,"symbol":"DANGCEM","trade_date":"2017-02-13","open_price":168.01,"high_price":null,"low_price":null,"close_price":168.01,"volume":91300,"created_at":"2026-04-08T02:43:22.775561+00:00"},{"id":46393,"symbol":"DANGCEM","trade_date":"2017-02-14","open_price":168.01,"high_price":null,"low_price":null,"close_price":168.01,"volume":12855,"created_at":"2026-04-08T02:43:24.286485+00:00"},{"id":46505,"symbol":"DANGCEM","trade_date":"2017-02-15","open_price":169,"high_price":null,"low_price":null,"close_price":169,"volume":45766,"created_at":"2026-04-08T02:43:26.422065+00:00"},{"id":46617,"symbol":"DANGCEM","trade_date":"2017-02-16","open_price":169,"high_price":null,"low_price":null,"close_price":169,"volume":72583,"created_at":"2026-04-08T02:43:28.597754+00:00"},{"id":46709,"symbol":"DANGCEM","trade_date":"2017-02-17","open_price":169,"high_price":null,"low_price":null,"close_price":169,"volume":502572,"created_at":"2026-04-08T02:43:31.044717+00:00"},{"id":49377,"symbol":"DANGCEM","trade_date":"2017-02-20","open_price":169,"high_price":null,"low_price":null,"close_price":169,"volume":568105,"created_at":"2026-04-08T02:51:00.639833+00:00"},{"id":49469,"symbol":"DANGCEM","trade_date":"2017-02-21","open_price":168.99,"high_price":null,"low_price":null,"close_price":168.99,"volume":69772,"created_at":"2026-04-08T02:51:03.098475+00:00"},{"id":46801,"symbol":"DANGCEM","trade_date":"2017-02-22","open_price":168.99,"high_price":null,"low_price":null,"close_price":168.99,"volume":119499,"created_at":"2026-04-08T02:44:33.152084+00:00"},{"id":46893,"symbol":"DANGCEM","trade_date":"2017-02-23","open_price":168.99,"high_price":null,"low_price":null,"close_price":168.99,"volume":31882,"created_at":"2026-04-08T02:44:35.448225+00:00"},{"id":46985,"symbol":"DANGCEM","trade_date":"2017-02-24","open_price":168.99,"high_price":null,"low_price":null,"close_price":168.99,"volume":27899,"created_at":"2026-04-08T02:44:37.781529+00:00"},{"id":47077,"symbol":"DANGCEM","trade_date":"2017-02-27","open_price":168.99,"high_price":null,"low_price":null,"close_price":168.99,"volume":12298,"created_at":"2026-04-08T02:44:42.101817+00:00"},{"id":47169,"symbol":"DANGCEM","trade_date":"2017-02-28","open_price":168.99,"high_price":null,"low_price":null,"close_price":168.99,"volume":13849,"created_at":"2026-04-08T02:44:45.006295+00:00"},{"id":47261,"symbol":"DANGCEM","trade_date":"2017-03-01","open_price":168.99,"high_price":null,"low_price":null,"close_price":168.99,"volume":10997,"created_at":"2026-04-08T02:44:47.332471+00:00"},{"id":47353,"symbol":"DANGCEM","trade_date":"2017-03-02","open_price":160.55,"high_price":null,"low_price":null,"close_price":160.55,"volume":123541,"created_at":"2026-04-08T02:44:49.657807+00:00"},{"id":47445,"symbol":"DANGCEM","trade_date":"2017-03-03","open_price":160.55,"high_price":null,"low_price":null,"close_price":160.55,"volume":200433,"created_at":"2026-04-08T02:44:51.301699+00:00"},{"id":47537,"symbol":"DANGCEM","trade_date":"2017-03-06","open_price":149.26,"high_price":null,"low_price":null,"close_price":149.26,"volume":111322,"created_at":"2026-04-08T02:44:56.024588+00:00"},{"id":47629,"symbol":"DANGCEM","trade_date":"2017-03-07","open_price":156.61,"high_price":null,"low_price":null,"close_price":156.61,"volume":54827,"created_at":"2026-04-08T02:44:58.263872+00:00"},{"id":47721,"symbol":"DANGCEM","trade_date":"2017-03-08","open_price":152.15,"high_price":null,"low_price":null,"close_price":152.15,"volume":62774,"created_at":"2026-04-08T02:44:59.957789+00:00"},{"id":47813,"symbol":"DANGCEM","trade_date":"2017-03-09","open_price":159.75,"high_price":null,"low_price":null,"close_price":159.75,"volume":32303,"created_at":"2026-04-08T02:45:01.661944+00:00"},{"id":47905,"symbol":"DANGCEM","trade_date":"2017-03-10","open_price":161,"high_price":null,"low_price":null,"close_price":161,"volume":408771,"created_at":"2026-04-08T02:45:03.96312+00:00"},{"id":47997,"symbol":"DANGCEM","trade_date":"2017-03-13","open_price":160,"high_price":null,"low_price":null,"close_price":160,"volume":41387,"created_at":"2026-04-08T02:45:08.663664+00:00"},{"id":48089,"symbol":"DANGCEM","trade_date":"2017-03-14","open_price":160.5,"high_price":null,"low_price":null,"close_price":160.5,"volume":110348,"created_at":"2026-04-08T02:45:11.088473+00:00"},{"id":48181,"symbol":"DANGCEM","trade_date":"2017-03-15","open_price":160.5,"high_price":null,"low_price":null,"close_price":160.5,"volume":14242,"created_at":"2026-04-08T02:45:12.861206+00:00"},{"id":48273,"symbol":"DANGCEM","trade_date":"2017-03-16","open_price":160,"high_price":null,"low_price":null,"close_price":160,"volume":40822,"created_at":"2026-04-08T02:45:15.084197+00:00"},{"id":48365,"symbol":"DANGCEM","trade_date":"2017-03-17","open_price":166,"high_price":null,"low_price":null,"close_price":166,"volume":363998,"created_at":"2026-04-08T02:45:17.543831+00:00"},{"id":48457,"symbol":"DANGCEM","trade_date":"2017-03-20","open_price":165,"high_price":null,"low_price":null,"close_price":165,"volume":381772,"created_at":"2026-04-08T02:45:21.873889+00:00"},{"id":48549,"symbol":"DANGCEM","trade_date":"2017-03-21","open_price":165,"high_price":null,"low_price":null,"close_price":165,"volume":1213496,"created_at":"2026-04-08T02:45:25.078347+00:00"},{"id":48641,"symbol":"DANGCEM","trade_date":"2017-03-22","open_price":165,"high_price":null,"low_price":null,"close_price":165,"volume":26649,"created_at":"2026-04-08T02:45:26.626215+00:00"},{"id":48733,"symbol":"DANGCEM","trade_date":"2017-03-23","open_price":165,"high_price":null,"low_price":null,"close_price":165,"volume":37097,"created_at":"2026-04-08T02:45:28.377346+00:00"},{"id":48825,"symbol":"DANGCEM","trade_date":"2017-03-24","open_price":165,"high_price":null,"low_price":null,"close_price":165,"volume":29742,"created_at":"2026-04-08T02:45:30.775015+00:00"},{"id":48917,"symbol":"DANGCEM","trade_date":"2017-03-27","open_price":165,"high_price":null,"low_price":null,"close_price":165,"volume":27122,"created_at":"2026-04-08T02:45:34.704999+00:00"},{"id":49009,"symbol":"DANGCEM","trade_date":"2017-03-28","open_price":162,"high_price":null,"low_price":null,"close_price":162,"volume":42493,"created_at":"2026-04-08T02:45:36.347457+00:00"},{"id":49101,"symbol":"DANGCEM","trade_date":"2017-03-29","open_price":162,"high_price":null,"low_price":null,"close_price":162,"volume":707382,"created_at":"2026-04-08T02:45:38.731306+00:00"},{"id":49193,"symbol":"DANGCEM","trade_date":"2017-03-30","open_price":165,"high_price":null,"low_price":null,"close_price":165,"volume":5317188,"created_at":"2026-04-08T02:45:40.513553+00:00"},{"id":49285,"symbol":"DANGCEM","trade_date":"2017-03-31","open_price":165,"high_price":null,"low_price":null,"close_price":165,"volume":22641,"created_at":"2026-04-08T02:45:42.281198+00:00"},{"id":49561,"symbol":"DANGCEM","trade_date":"2017-04-03","open_price":161.1,"high_price":null,"low_price":null,"close_price":161.1,"volume":56854,"created_at":"2026-04-08T02:51:07.481095+00:00"},{"id":49653,"symbol":"DANGCEM","trade_date":"2017-04-04","open_price":161.1,"high_price":null,"low_price":null,"close_price":161.1,"volume":31188,"created_at":"2026-04-08T02:51:09.86923+00:00"},{"id":49745,"symbol":"DANGCEM","trade_date":"2017-04-05","open_price":161.1,"high_price":null,"low_price":null,"close_price":161.1,"volume":55315,"created_at":"2026-04-08T02:51:12.308135+00:00"},{"id":49837,"symbol":"DANGCEM","trade_date":"2017-04-06","open_price":164.6,"high_price":null,"low_price":null,"close_price":164.6,"volume":39678,"created_at":"2026-04-08T02:51:14.846493+00:00"},{"id":49929,"symbol":"DANGCEM","trade_date":"2017-04-07","open_price":164.6,"high_price":null,"low_price":null,"close_price":164.6,"volume":14237,"created_at":"2026-04-08T02:51:17.320635+00:00"},{"id":50021,"symbol":"DANGCEM","trade_date":"2017-04-10","open_price":164.6,"high_price":null,"low_price":null,"close_price":164.6,"volume":7421,"created_at":"2026-04-08T02:51:21.583607+00:00"},{"id":50112,"symbol":"DANGCEM","trade_date":"2017-04-11","open_price":164,"high_price":null,"low_price":null,"close_price":164,"volume":2041788,"created_at":"2026-04-08T02:51:23.796131+00:00"},{"id":50203,"symbol":"DANGCEM","trade_date":"2017-04-12","open_price":164,"high_price":null,"low_price":null,"close_price":164,"volume":2809,"created_at":"2026-04-08T02:51:26.28287+00:00"},{"id":50294,"symbol":"DANGCEM","trade_date":"2017-04-13","open_price":164,"high_price":null,"low_price":null,"close_price":164,"volume":36177,"created_at":"2026-04-08T02:51:28.606475+00:00"},{"id":50385,"symbol":"DANGCEM","trade_date":"2017-04-18","open_price":160,"high_price":null,"low_price":null,"close_price":160,"volume":524537,"created_at":"2026-04-08T02:51:35.070654+00:00"},{"id":50476,"symbol":"DANGCEM","trade_date":"2017-04-19","open_price":160,"high_price":null,"low_price":null,"close_price":160,"volume":120754,"created_at":"2026-04-08T02:51:37.390681+00:00"},{"id":50567,"symbol":"DANGCEM","trade_date":"2017-04-20","open_price":159,"high_price":null,"low_price":null,"close_price":159,"volume":130208,"created_at":"2026-04-08T02:51:39.751187+00:00"},{"id":50658,"symbol":"DANGCEM","trade_date":"2017-04-21","open_price":159,"high_price":null,"low_price":null,"close_price":159,"volume":1507,"created_at":"2026-04-08T02:51:42.059234+00:00"},{"id":50749,"symbol":"DANGCEM","trade_date":"2017-04-24","open_price":165,"high_price":null,"low_price":null,"close_price":165,"volume":303345,"created_at":"2026-04-08T02:51:46.271638+00:00"},{"id":50840,"symbol":"DANGCEM","trade_date":"2017-04-25","open_price":165,"high_price":null,"low_price":null,"close_price":165,"volume":15392,"created_at":"2026-04-08T02:51:48.506234+00:00"},{"id":50931,"symbol":"DANGCEM","trade_date":"2017-04-26","open_price":159,"high_price":null,"low_price":null,"close_price":159,"volume":372709,"created_at":"2026-04-08T02:51:50.787758+00:00"},{"id":51022,"symbol":"DANGCEM","trade_date":"2017-04-27","open_price":160,"high_price":null,"low_price":null,"close_price":160,"volume":783402,"created_at":"2026-04-08T02:51:53.168104+00:00"},{"id":51113,"symbol":"DANGCEM","trade_date":"2017-04-28","open_price":159,"high_price":null,"low_price":null,"close_price":159,"volume":972037,"created_at":"2026-04-08T02:51:55.619599+00:00"},{"id":51204,"symbol":"DANGCEM","trade_date":"2017-05-02","open_price":159,"high_price":null,"low_price":null,"close_price":159,"volume":103970,"created_at":"2026-04-08T02:52:01.291461+00:00"},{"id":51295,"symbol":"DANGCEM","trade_date":"2017-05-03","open_price":158.99,"high_price":null,"low_price":null,"close_price":158.99,"volume":1412964,"created_at":"2026-04-08T02:52:03.619408+00:00"},{"id":51386,"symbol":"DANGCEM","trade_date":"2017-05-04","open_price":159,"high_price":null,"low_price":null,"close_price":159,"volume":1065280,"created_at":"2026-04-08T02:52:06.041901+00:00"},{"id":51477,"symbol":"DANGCEM","trade_date":"2017-05-05","open_price":159.5,"high_price":null,"low_price":null,"close_price":159.5,"volume":985691,"created_at":"2026-04-08T02:52:08.320033+00:00"},{"id":51568,"symbol":"DANGCEM","trade_date":"2017-05-08","open_price":159.5,"high_price":null,"low_price":null,"close_price":159.5,"volume":745297,"created_at":"2026-04-08T02:52:12.828428+00:00"},{"id":51659,"symbol":"DANGCEM","trade_date":"2017-05-09","open_price":162,"high_price":null,"low_price":null,"close_price":162,"volume":665655,"created_at":"2026-04-08T02:52:15.102333+00:00"},{"id":51750,"symbol":"DANGCEM","trade_date":"2017-05-10","open_price":166.01,"high_price":null,"low_price":null,"close_price":166.01,"volume":1608844,"created_at":"2026-04-08T02:52:17.709352+00:00"},{"id":51841,"symbol":"DANGCEM","trade_date":"2017-05-11","open_price":173.3,"high_price":null,"low_price":null,"close_price":173.3,"volume":8767205,"created_at":"2026-04-08T02:52:19.900179+00:00"},{"id":51932,"symbol":"DANGCEM","trade_date":"2017-05-12","open_price":165,"high_price":null,"low_price":null,"close_price":165,"volume":2094040,"created_at":"2026-04-08T02:52:22.170941+00:00"},{"id":52023,"symbol":"DANGCEM","trade_date":"2017-05-15","open_price":163.01,"high_price":null,"low_price":null,"close_price":163.01,"volume":1810329,"created_at":"2026-04-08T02:52:26.563035+00:00"},{"id":52115,"symbol":"DANGCEM","trade_date":"2017-05-16","open_price":163,"high_price":null,"low_price":null,"close_price":163,"volume":10027582,"created_at":"2026-04-08T02:52:28.807233+00:00"},{"id":52207,"symbol":"DANGCEM","trade_date":"2017-05-17","open_price":163,"high_price":null,"low_price":null,"close_price":163,"volume":70071,"created_at":"2026-04-08T02:52:31.099411+00:00"},{"id":52299,"symbol":"DANGCEM","trade_date":"2017-05-18","open_price":163,"high_price":null,"low_price":null,"close_price":163,"volume":3991541,"created_at":"2026-04-08T02:52:33.303088+00:00"},{"id":52391,"symbol":"DANGCEM","trade_date":"2017-05-19","open_price":162.99,"high_price":null,"low_price":null,"close_price":162.99,"volume":6020780,"created_at":"2026-04-08T02:52:35.640534+00:00"},{"id":52483,"symbol":"DANGCEM","trade_date":"2017-05-22","open_price":163,"high_price":null,"low_price":null,"close_price":163,"volume":532568,"created_at":"2026-04-08T02:52:39.854932+00:00"},{"id":52575,"symbol":"DANGCEM","trade_date":"2017-05-23","open_price":162.01,"high_price":null,"low_price":null,"close_price":162.01,"volume":100109,"created_at":"2026-04-08T02:52:42.264162+00:00"},{"id":52667,"symbol":"DANGCEM","trade_date":"2017-05-24","open_price":163,"high_price":null,"low_price":null,"close_price":163,"volume":1363777,"created_at":"2026-04-08T02:52:44.613941+00:00"},{"id":52759,"symbol":"DANGCEM","trade_date":"2017-05-25","open_price":163,"high_price":null,"low_price":null,"close_price":163,"volume":43674,"created_at":"2026-04-08T02:52:46.963191+00:00"},{"id":52851,"symbol":"DANGCEM","trade_date":"2017-05-26","open_price":166.8,"high_price":null,"low_price":null,"close_price":166.8,"volume":601445,"created_at":"2026-04-08T02:52:49.347152+00:00"},{"id":52943,"symbol":"DANGCEM","trade_date":"2017-05-30","open_price":167.1,"high_price":null,"low_price":null,"close_price":167.1,"volume":4438423,"created_at":"2026-04-08T02:52:54.942696+00:00"},{"id":53035,"symbol":"DANGCEM","trade_date":"2017-05-31","open_price":175,"high_price":null,"low_price":null,"close_price":175,"volume":1125522,"created_at":"2026-04-08T02:52:57.421655+00:00"}

In [11]:
import json

DATA=json.loads(data)
DATA

{'success': True,
 'symbol': 'DANGCEM',
 'prices': [{'id': 42778,
   'symbol': 'DANGCEM',
   'trade_date': '2017-01-03',
   'open_price': 173.99,
   'high_price': None,
   'low_price': None,
   'close_price': 173.99,
   'volume': 19200,
   'created_at': '2026-04-08T02:41:25.765521+00:00'},
  {'id': 43338,
   'symbol': 'DANGCEM',
   'trade_date': '2017-01-04',
   'open_price': 173.99,
   'high_price': None,
   'low_price': None,
   'close_price': 173.99,
   'volume': 29100,
   'created_at': '2026-04-08T02:42:20.164398+00:00'},
  {'id': 43448,
   'symbol': 'DANGCEM',
   'trade_date': '2017-01-05',
   'open_price': 167.02,
   'high_price': None,
   'low_price': None,
   'close_price': 167.02,
   'volume': 191164,
   'created_at': '2026-04-08T02:42:22.380516+00:00'},
  {'id': 43558,
   'symbol': 'DANGCEM',
   'trade_date': '2017-01-06',
   'open_price': 167,
   'high_price': None,
   'low_price': None,
   'close_price': 167,
   'volume': 64437,
   'created_at': '2026-04-08T02:42:23.84796+00:00'},
  {'id': 43648,
   'symbol': 'DANGCEM',
   'trade_date': '2017-01-09',
   'open_price': 169,
   'high_price': None,
   'low_price': None,
   'close_price': 169,
   'volume': 401559,
   'created_at': '2026-04-08T02:42:26.938159+00:00'},
  {'id': 43758,
   'symbol': 'DANGCEM',
   'trade_date': '2017-01-10',
   'open_price': 168,
   'high_price': None,
   'low_price': None,
   'close_price': 168,
   'volume': 90263,
   'created_at': '2026-04-08T02:42:29.227202+00:00'},
  {'id': 43868,
   'symbol': 'DANGCEM',
   'trade_date': '2017-01-11',
   'open_price': 168,
   'high_price': None,
   'low_price': None,
   'close_price': 168,
   'volume': 8283,
   'created_at': '2026-04-08T02:42:30.799441+00:00'},
  {'id': 43958,
   'symbol': 'DANGCEM',
   'trade_date': '2017-01-12',
   'open_price': 168,
   'high_price': None,
   'low_price': None,
   'close_price': 168,
   'volume': 230640,
   'created_at': '2026-04-08T02:42:32.390658+00:00'},
  {'id': 44068,
   'symbol': 'DANGCEM',
   'trade_date': '2017-01-13',
   'open_price': 168,
   'high_price': None,
   'low_price': None,
   'close_price': 168,
   'volume': 39673,
   'created_at': '2026-04-08T02:42:34.853543+00:00'},
  {'id': 44178,
   'symbol': 'DANGCEM',
   'trade_date': '2017-01-16',
   'open_price': 168,
   'high_price': None,
   'low_price': None,
   'close_price': 168,
   'volume': 66471,
   'created_at': '2026-04-08T02:42:38.72803+00:00'},
  {'id': 44288,
   'symbol': 'DANGCEM',
   'trade_date': '2017-01-17',
   'open_price': 168,
   'high_price': None,
   'low_price': None,
   'close_price': 168,
   'volume': 823837,
   'created_at': '2026-04-08T02:42:41.056228+00:00'},
  {'id': 44398,
   'symbol': 'DANGCEM',
   'trade_date': '2017-01-18',
   'open_price': 168,
   'high_price': None,
   'low_price': None,
   'close_price': 168,
   'volume': 504897,
   'created_at': '2026-04-08T02:42:42.795307+00:00'},
  {'id': 44488,
   'symbol': 'DANGCEM',
   'trade_date': '2017-01-19',
   'open_price': 167,
   'high_price': None,
   'low_price': None,
   'close_price': 167,
   'volume': 188632,
   'created_at': '2026-04-08T02:42:44.39781+00:00'},
  {'id': 44598,
   'symbol': 'DANGCEM',
   'trade_date': '2017-01-20',
   'open_price': 167,
   'high_price': None,
   'low_price': None,
   'close_price': 167,
   'volume': 163006,
   'created_at': '2026-04-08T02:42:46.643743+00:00'},
  {'id': 44708,
   'symbol': 'DANGCEM',
   'trade_date': '2017-01-23',
   'open_price': 167,
   'high_price': None,
   'low_price': None,
   'close_price': 167,
   'volume': 211476,
   'created_at': '2026-04-08T02:42:49.827664+00:00'},
  {'id': 44818,
   'symbol': 'DANGCEM',
   'trade_date': '2017-01-24',
   'open_price': 167,
   'high_price': None,
   'low_price': None,
   'close_price': 167,
   'volume': 804424,
   'created_at': '2026-04-08T02:42:51.574002+00:00'},
  {'id': 44908,
   'symbol': 'DANGCEM',
   'trade_date': '2017-01-25',
   'open_price': 167,
   'high_price': None,
   'low_price': None,
   'close_price': 167,
   'volume': 20179,
   'created_at': '2026-04-08T02:42:54.05787+00:00'},
  {'id': 45018,
   'symbol': 'DANGCEM',
   'trade_date': '2017-01-26',
   'open_price': 167.01,
   'high_price': None,
   'low_price': None,
   'close_price': 167.01,
   'volume': 149466,
   'created_at': '2026-04-08T02:42:55.759+00:00'},
  {'id': 45128,
   'symbol': 'DANGCEM',
   'trade_date': '2017-01-27',
   'open_price': 167.01,
   'high_price': None,
   'low_price': None,
   'close_price': 167.01,
   'volume': 52738,
   'created_at': '2026-04-08T02:42:57.462271+00:00'},
  {'id': 45238,
   'symbol': 'DANGCEM',
   'trade_date': '2017-01-30',
   'open_price': 166,
   'high_price': None,
   'low_price': None,
   'close_price': 166,
   'volume': 63274,
   'created_at': '2026-04-08T02:43:00.905282+00:00'},
  {'id': 45348,
   'symbol': 'DANGCEM',
   'trade_date': '2017-01-31',
   'open_price': 166,
   'high_price': None,
   'low_price': None,
   'close_price': 166,
   'volume': 62010,
   'created_at': '2026-04-08T02:43:03.07753+00:00'},
  {'id': 45458,
   'symbol': 'DANGCEM',
   'trade_date': '2017-02-01',
   'open_price': 168,
   'high_price': None,
   'low_price': None,
   'close_price': 168,
   'volume': 81482,
   'created_at': '2026-04-08T02:43:04.619173+00:00'},
  {'id': 45548,
   'symbol': 'DANGCEM',
   'trade_date': '2017-02-02',
   'open_price': 168,
   'high_price': None,
   'low_price': None,
   'close_price': 168,
   'volume': 212689,
   'created_at': '2026-04-08T02:43:06.209007+00:00'},
  {'id': 45658,
   'symbol': 'DANGCEM',
   'trade_date': '2017-02-03',
   'open_price': 168,
   'high_price': None,
   'low_price': None,
   'close_price': 168,
   'volume': 14116,
   'created_at': '2026-04-08T02:43:08.490666+00:00'},
  {'id': 45768,
   'symbol': 'DANGCEM',
   'trade_date': '2017-02-06',
   'open_price': 165.01,
   'high_price': None,
   'low_price': None,
   'close_price': 165.01,
   'volume': 371429,
   'created_at': '2026-04-08T02:43:11.037852+00:00'},
  {'id': 45878,
   'symbol': 'DANGCEM',
   'trade_date': '2017-02-07',
   'open_price': 166,
   'high_price': None,
   'low_price': None,
   'close_price': 166,
   'volume': 119663,
   'created_at': '2026-04-08T02:43:12.662822+00:00'},
  {'id': 45968,
   'symbol': 'DANGCEM',
   'trade_date': '2017-02-08',
   'open_price': 167.11,
   'high_price': None,
   'low_price': None,
   'close_price': 167.11,
   'volume': 347802,
   'created_at': '2026-04-08T02:43:14.224877+00:00'},
  {'id': 46078,
   'symbol': 'DANGCEM',
   'trade_date': '2017-02-09',
   'open_price': 167.11,
   'high_price': None,
   'low_price': None,
   'close_price': 167.11,
   'volume': 232216,
   'created_at': '2026-04-08T02:43:16.408746+00:00'},
  {'id': 46189,
   'symbol': 'DANGCEM',
   'trade_date': '2017-02-10',
   'open_price': 167.11,
   'high_price': None,
   'low_price': None,
   'close_price': 167.11,
   'volume': 13627,
   'created_at': '2026-04-08T02:43:18.597686+00:00'},
  {'id': 46281,
   'symbol': 'DANGCEM',
   'trade_date': '2017-02-13',
   'open_price': 168.01,
   'high_price': None,
   'low_price': None,
   'close_price': 168.01,
   'volume': 91300,
   'created_at': '2026-04-08T02:43:22.775561+00:00'},
  {'id': 46393,
   'symbol': 'DANGCEM',
   'trade_date': '2017-02-14',
   'open_price': 168.01,
   'high_price': None,
   'low_price': None,
   'close_price': 168.01,
   'volume': 12855,
   'created_at': '2026-04-08T02:43:24.286485+00:00'},
  {'id': 46505,
   'symbol': 'DANGCEM',
   'trade_date': '2017-02-15',
   'open_price': 169,
   'high_price': None,
   'low_price': None,
   'close_price': 169,
   'volume': 45766,
   'created_at': '2026-04-08T02:43:26.422065+00:00'},
  {'id': 46617,
   'symbol': 'DANGCEM',
   'trade_date': '2017-02-16',
   'open_price': 169,
   'high_price': None,
   'low_price': None,
   'close_price': 169,
   'volume': 72583,
   'created_at': '2026-04-08T02:43:28.597754+00:00'},
  {'id': 46709,
   'symbol': 'DANGCEM',
   'trade_date': '2017-02-17',
   'open_price': 169,
   'high_price': None,
   'low_price': None,
   'close_price': 169,
   'volume': 502572,
   'created_at': '2026-04-08T02:43:31.044717+00:00'},
  {'id': 49377,
   'symbol': 'DANGCEM',
   'trade_date': '2017-02-20',
   'open_price': 169,
   'high_price': None,
   'low_price': None,
   'close_price': 169,
   'volume': 568105,
   'created_at': '2026-04-08T02:51:00.639833+00:00'},
  {'id': 49469,
   'symbol': 'DANGCEM',
   'trade_date': '2017-02-21',
   'open_price': 168.99,
   'high_price': None,
   'low_price': None,
   'close_price': 168.99,
   'volume': 69772,
   'created_at': '2026-04-08T02:51:03.098475+00:00'},
  {'id': 46801,
   'symbol': 'DANGCEM',
   'trade_date': '2017-02-22',
   'open_price': 168.99,
   'high_price': None,
   'low_price': None,
   'close_price': 168.99,
   'volume': 119499,
   'created_at': '2026-04-08T02:44:33.152084+00:00'},
  {'id': 46893,
   'symbol': 'DANGCEM',
   'trade_date': '2017-02-23',
   'open_price': 168.99,
   'high_price': None,
   'low_price': None,
   'close_price': 168.99,
   'volume': 31882,
   'created_at': '2026-04-08T02:44:35.448225+00:00'},
  {'id': 46985,
   'symbol': 'DANGCEM',
   'trade_date': '2017-02-24',
   'open_price': 168.99,
   'high_price': None,
   'low_price': None,
   'close_price': 168.99,
   'volume': 27899,
   'created_at': '2026-04-08T02:44:37.781529+00:00'},
  {'id': 47077,
   'symbol': 'DANGCEM',
   'trade_date': '2017-02-27',
   'open_price': 168.99,
   'high_price': None,
   'low_price': None,
   'close_price': 168.99,
   'volume': 12298,
   'created_at': '2026-04-08T02:44:42.101817+00:00'},
  {'id': 47169,
   'symbol': 'DANGCEM',
   'trade_date': '2017-02-28',
   'open_price': 168.99,
   'high_price': None,
   'low_price': None,
   'close_price': 168.99,
   'volume': 13849,
   'created_at': '2026-04-08T02:44:45.006295+00:00'},
  {'id': 47261,
   'symbol': 'DANGCEM',
   'trade_date': '2017-03-01',
   'open_price': 168.99,
   'high_price': None,
   'low_price': None,
   'close_price': 168.99,
   'volume': 10997,
   'created_at': '2026-04-08T02:44:47.332471+00:00'},
  {'id': 47353,
   'symbol': 'DANGCEM',
   'trade_date': '2017-03-02',
   'open_price': 160.55,
   'high_price': None,
   'low_price': None,
   'close_price': 160.55,
   'volume': 123541,
   'created_at': '2026-04-08T02:44:49.657807+00:00'},
  {'id': 47445,
   'symbol': 'DANGCEM',
   'trade_date': '2017-03-03',
   'open_price': 160.55,
   'high_price': None,
   'low_price': None,
   'close_price': 160.55,
   'volume': 200433,
   'created_at': '2026-04-08T02:44:51.301699+00:00'},
  {'id': 47537,
   'symbol': 'DANGCEM',
   'trade_date': '2017-03-06',
   'open_price': 149.26,
   'high_price': None,
   'low_price': None,
   'close_price': 149.26,
   'volume': 111322,
   'created_at': '2026-04-08T02:44:56.024588+00:00'},
  {'id': 47629,
   'symbol': 'DANGCEM',
   'trade_date': '2017-03-07',
   'open_price': 156.61,
   'high_price': None,
   'low_price': None,
   'close_price': 156.61,
   'volume': 54827,
   'created_at': '2026-04-08T02:44:58.263872+00:00'},
  {'id': 47721,
   'symbol': 'DANGCEM',
   'trade_date': '2017-03-08',
   'open_price': 152.15,
   'high_price': None,
   'low_price': None,
   'close_price': 152.15,
   'volume': 62774,
   'created_at': '2026-04-08T02:44:59.957789+00:00'},
  {'id': 47813,
   'symbol': 'DANGCEM',
   'trade_date': '2017-03-09',
   'open_price': 159.75,
   'high_price': None,
   'low_price': None,
   'close_price': 159.75,
   'volume': 32303,
   'created_at': '2026-04-08T02:45:01.661944+00:00'},
  {'id': 47905,
   'symbol': 'DANGCEM',
   'trade_date': '2017-03-10',
   'open_price': 161,
   'high_price': None,
   'low_price': None,
   'close_price': 161,
   'volume': 408771,
   'created_at': '2026-04-08T02:45:03.96312+00:00'},
  {'id': 47997,
   'symbol': 'DANGCEM',
   'trade_date': '2017-03-13',
   'open_price': 160,
   'high_price': None,
   'low_price': None,
   'close_price': 160,
   'volume': 41387,
   'created_at': '2026-04-08T02:45:08.663664+00:00'},
  {'id': 48089,
   'symbol': 'DANGCEM',
   'trade_date': '2017-03-14',
   'open_price': 160.5,
   'high_price': None,
   'low_price': None,
   'close_price': 160.5,
   'volume': 110348,
   'created_at': '2026-04-08T02:45:11.088473+00:00'},
  {'id': 48181,
   'symbol': 'DANGCEM',
   'trade_date': '2017-03-15',
   'open_price': 160.5,
   'high_price': None,
   'low_price': None,
   'close_price': 160.5,
   'volume': 14242,
   'created_at': '2026-04-08T02:45:12.861206+00:00'},
  {'id': 48273,
   'symbol': 'DANGCEM',
   'trade_date': '2017-03-16',
   'open_price': 160,
   'high_price': None,
   'low_price': None,
   'close_price': 160,
   'volume': 40822,
   'created_at': '2026-04-08T02:45:15.084197+00:00'},
  {'id': 48365,
   'symbol': 'DANGCEM',
   'trade_date': '2017-03-17',
   'open_price': 166,
   'high_price': None,
   'low_price': None,
   'close_price': 166,
   'volume': 363998,
   'created_at': '2026-04-08T02:45:17.543831+00:00'},
  {'id': 48457,
   'symbol': 'DANGCEM',
   'trade_date': '2017-03-20',
   'open_price': 165,
   'high_price': None,
   'low_price': None,
   'close_price': 165,
   'volume': 381772,
   'created_at': '2026-04-08T02:45:21.873889+00:00'},
  {'id': 48549,
   'symbol': 'DANGCEM',
   'trade_date': '2017-03-21',
   'open_price': 165,
   'high_price': None,
   'low_price': None,
   'close_price': 165,
   'volume': 1213496,
   'created_at': '2026-04-08T02:45:25.078347+00:00'},
  {'id': 48641,
   'symbol': 'DANGCEM',
   'trade_date': '2017-03-22',
   'open_price': 165,
   'high_price': None,
   'low_price': None,
   'close_price': 165,
   'volume': 26649,
   'created_at': '2026-04-08T02:45:26.626215+00:00'},
  {'id': 48733,
   'symbol': 'DANGCEM',
   'trade_date': '2017-03-23',
   'open_price': 165,
   'high_price': None,
   'low_price': None,
   'close_price': 165,
   'volume': 37097,
   'created_at': '2026-04-08T02:45:28.377346+00:00'},
  {'id': 48825,
   'symbol': 'DANGCEM',
   'trade_date': '2017-03-24',
   'open_price': 165,
   'high_price': None,
   'low_price': None,
   'close_price': 165,
   'volume': 29742,
   'created_at': '2026-04-08T02:45:30.775015+00:00'},
  {'id': 48917,
   'symbol': 'DANGCEM',
   'trade_date': '2017-03-27',
   'open_price': 165,
   'high_price': None,
   'low_price': None,
   'close_price': 165,
   'volume': 27122,
   'created_at': '2026-04-08T02:45:34.704999+00:00'},
  {'id': 49009,
   'symbol': 'DANGCEM',
   'trade_date': '2017-03-28',
   'open_price': 162,
   'high_price': None,
   'low_price': None,
   'close_price': 162,
   'volume': 42493,
   'created_at': '2026-04-08T02:45:36.347457+00:00'},
  {'id': 49101,
   'symbol': 'DANGCEM',
   'trade_date': '2017-03-29',
   'open_price': 162,
   'high_price': None,
   'low_price': None,
   'close_price': 162,
   'volume': 707382,
   'created_at': '2026-04-08T02:45:38.731306+00:00'},
  {'id': 49193,
   'symbol': 'DANGCEM',
   'trade_date': '2017-03-30',
   'open_price': 165,
   'high_price': None,
   'low_price': None,
   'close_price': 165,
   'volume': 5317188,
   'created_at': '2026-04-08T02:45:40.513553+00:00'},
  {'id': 49285,
   'symbol': 'DANGCEM',
   'trade_date': '2017-03-31',
   'open_price': 165,
   'high_price': None,
   'low_price': None,
   'close_price': 165,
   'volume': 22641,
   'created_at': '2026-04-08T02:45:42.281198+00:00'},
  {'id': 49561,
   'symbol': 'DANGCEM',
   'trade_date': '2017-04-03',
   'open_price': 161.1,
   'high_price': None,
   'low_price': None,
   'close_price': 161.1,
   'volume': 56854,
   'created_at': '2026-04-08T02:51:07.481095+00:00'},
  {'id': 49653,
   'symbol': 'DANGCEM',
   'trade_date': '2017-04-04',
   'open_price': 161.1,
   'high_price': None,
   'low_price': None,
   'close_price': 161.1,
   'volume': 31188,
   'created_at': '2026-04-08T02:51:09.86923+00:00'},
  {'id': 49745,
   'symbol': 'DANGCEM',
   'trade_date': '2017-04-05',
   'open_price': 161.1,
   'high_price': None,
   'low_price': None,
   'close_price': 161.1,
   'volume': 55315,
   'created_at': '2026-04-08T02:51:12.308135+00:00'},
  {'id': 49837,
   'symbol': 'DANGCEM',
   'trade_date': '2017-04-06',
   'open_price': 164.6,
   'high_price': None,
   'low_price': None,
   'close_price': 164.6,
   'volume': 39678,
   'created_at': '2026-04-08T02:51:14.846493+00:00'},
  {'id': 49929,
   'symbol': 'DANGCEM',
   'trade_date': '2017-04-07',
   'open_price': 164.6,
   'high_price': None,
   'low_price': None,
   'close_price': 164.6,
   'volume': 14237,
   'created_at': '2026-04-08T02:51:17.320635+00:00'},
  {'id': 50021,
   'symbol': 'DANGCEM',
   'trade_date': '2017-04-10',
   'open_price': 164.6,
   'high_price': None,
   'low_price': None,
   'close_price': 164.6,
   'volume': 7421,
   'created_at': '2026-04-08T02:51:21.583607+00:00'},
  {'id': 50112,
   'symbol': 'DANGCEM',
   'trade_date': '2017-04-11',
   'open_price': 164,
   'high_price': None,
   'low_price': None,
   'close_price': 164,
   'volume': 2041788,
   'created_at': '2026-04-08T02:51:23.796131+00:00'},
  {'id': 50203,
   'symbol': 'DANGCEM',
   'trade_date': '2017-04-12',
   'open_price': 164,
   'high_price': None,
   'low_price': None,
   'close_price': 164,
   'volume': 2809,
   'created_at': '2026-04-08T02:51:26.28287+00:00'},
  {'id': 50294,
   'symbol': 'DANGCEM',
   'trade_date': '2017-04-13',
   'open_price': 164,
   'high_price': None,
   'low_price': None,
   'close_price': 164,
   'volume': 36177,
   'created_at': '2026-04-08T02:51:28.606475+00:00'},
  {'id': 50385,
   'symbol': 'DANGCEM',
   'trade_date': '2017-04-18',
   'open_price': 160,
   'high_price': None,
   'low_price': None,
   'close_price': 160,
   'volume': 524537,
   'created_at': '2026-04-08T02:51:35.070654+00:00'},
  {'id': 50476,
   'symbol': 'DANGCEM',
   'trade_date': '2017-04-19',
   'open_price': 160,
   'high_price': None,
   'low_price': None,
   'close_price': 160,
   'volume': 120754,
   'created_at': '2026-04-08T02:51:37.390681+00:00'},
  {'id': 50567,
   'symbol': 'DANGCEM',
   'trade_date': '2017-04-20',
   'open_price': 159,
   'high_price': None,
   'low_price': None,
   'close_price': 159,
   'volume': 130208,
   'created_at': '2026-04-08T02:51:39.751187+00:00'},
  {'id': 50658,
   'symbol': 'DANGCEM',
   'trade_date': '2017-04-21',
   'open_price': 159,
   'high_price': None,
   'low_price': None,
   'close_price': 159,
   'volume': 1507,
   'created_at': '2026-04-08T02:51:42.059234+00:00'},
  {'id': 50749,
   'symbol': 'DANGCEM',
   'trade_date': '2017-04-24',
   'open_price': 165,
   'high_price': None,
   'low_price': None,
   'close_price': 165,
   'volume': 303345,
   'created_at': '2026-04-08T02:51:46.271638+00:00'},
  {'id': 50840,
   'symbol': 'DANGCEM',
   'trade_date': '2017-04-25',
   'open_price': 165,
   'high_price': None,
   'low_price': None,
   'close_price': 165,
   'volume': 15392,
   'created_at': '2026-04-08T02:51:48.506234+00:00'},
  {'id': 50931,
   'symbol': 'DANGCEM',
   'trade_date': '2017-04-26',
   'open_price': 159,
   'high_price': None,
   'low_price': None,
   'close_price': 159,
   'volume': 372709,
   'created_at': '2026-04-08T02:51:50.787758+00:00'},
  {'id': 51022,
   'symbol': 'DANGCEM',
   'trade_date': '2017-04-27',
   'open_price': 160,
   'high_price': None,
   'low_price': None,
   'close_price': 160,
   'volume': 783402,
   'created_at': '2026-04-08T02:51:53.168104+00:00'},
  {'id': 51113,
   'symbol': 'DANGCEM',
   'trade_date': '2017-04-28',
   'open_price': 159,
   'high_price': None,
   'low_price': None,
   'close_price': 159,
   'volume': 972037,
   'created_at': '2026-04-08T02:51:55.619599+00:00'},
  {'id': 51204,
   'symbol': 'DANGCEM',
   'trade_date': '2017-05-02',
   'open_price': 159,
   'high_price': None,
   'low_price': None,
   'close_price': 159,
   'volume': 103970,
   'created_at': '2026-04-08T02:52:01.291461+00:00'},
  {'id': 51295,
   'symbol': 'DANGCEM',
   'trade_date': '2017-05-03',
   'open_price': 158.99,
   'high_price': None,
   'low_price': None,
   'close_price': 158.99,
   'volume': 1412964,
   'created_at': '2026-04-08T02:52:03.619408+00:00'},

In [12]:
df=pd.DataFrame(DATA['prices'])
df

,id,symbol,trade_date,open_price,high_price,low_price,close_price,volume,created_at
0,42778,DANGCEM,2017-01-03,173.99,None,None,173.99,19200,2026-04-08T02:41:25.765521+00:00
1,43338,DANGCEM,2017-01-04,173.99,None,None,173.99,29100,2026-04-08T02:42:20.164398+00:00
2,43448,DANGCEM,2017-01-05,167.02,None,None,167.02,191164,2026-04-08T02:42:22.380516+00:00
3,43558,DANGCEM,2017-01-06,167.00,None,None,167.00,64437,2026-04-08T02:42:23.84796+00:00
4,43648,DANGCEM,2017-01-09,169.00,None,None,169.00,401559,2026-04-08T02:42:26.938159+00:00
...,...,...,...,...,...,...,...,...,...
2258,298050,DANGCEM,2026-07-13,1047.00,None,None,1047.00,364352,2026-07-13T15:10:02.995074+00:00
2259,298488,DANGCEM,2026-07-14,1047.00,None,None,1047.00,919411,2026-07-14T15:10:03.094441+00:00
2260,298926,DANGCEM,2026-07-15,1047.00,None,None,1047.00,2505955,2026-07-15T15:10:03.078609+00:00
2261,299364,DANGCEM,2026-07-16,1047.00,None,None,1047.00,269517,2026-07-16T15:10:03.113936+00:00
2262,299802,DANGCEM,2026-07-17,1047.00,None,None,1047.00,388188,2026-07-17T15:10:03.053983+00:00

In [13]:
url = "https://www.ngxpulse.ng/api/ngxdata/prices/CHAMS"

headers = {
    "X-API-Key": ngx_api_key
}

params = {
    "from": "2017-01-01",
    "to": "2026-07-18"
}

response = requests.get(
    url,
    headers=headers,
    params=params
)

print(response.status_code)
print(response.text)

data=response.text
DATA=json.loads(data)
df=pd.DataFrame(DATA['prices'])
df

200

,id,symbol,trade_date,open_price,high_price,low_price,close_price,volume,created_at
0,42839,CHAMS,2017-01-03,0.50,NaN,NaN,0.50,100000,2026-04-08T02:41:25.765521+00:00
1,43399,CHAMS,2017-01-04,0.50,NaN,NaN,0.50,133079,2026-04-08T02:42:20.164398+00:00
2,43509,CHAMS,2017-01-05,0.50,NaN,NaN,0.50,100000,2026-04-08T02:42:22.380516+00:00
3,43619,CHAMS,2017-01-06,0.50,NaN,NaN,0.50,100000,2026-04-08T02:42:23.84796+00:00
4,43709,CHAMS,2017-01-09,0.50,NaN,NaN,0.50,0,2026-04-08T02:42:26.938159+00:00
...,...,...,...,...,...,...,...,...,...
2258,298038,CHAMS,2026-07-13,4.44,NaN,NaN,4.44,10937479,2026-07-13T15:10:02.995074+00:00
2259,298476,CHAMS,2026-07-14,4.41,NaN,NaN,4.41,6746817,2026-07-14T15:10:03.094441+00:00
2260,298914,CHAMS,2026-07-15,4.37,NaN,NaN,4.37,9421036,2026-07-15T15:10:03.078609+00:00
2261,299352,CHAMS,2026-07-16,4.32,NaN,NaN,4.32,4101349,2026-07-16T15:10:03.113936+00:00
2262,299790,CHAMS,2026-07-17,4.20,NaN,NaN,4.20,17233810,2026-07-17T15:10:03.053983+00:00

In [14]:
df.to_csv("stock_data/CHAMS")

In [15]:
url = "https://www.ngxpulse.ng/api/ngxdata/prices/TOTAL"

headers = {
    "X-API-Key": ngx_api_key
}

params = {
    "from": "2017-01-01",
    "to": "2026-07-18"
}

response = requests.get(
    url,
    headers=headers,
    params=params
)

print(response.status_code)
print(response.text)

data=response.text
DATA=json.loads(data)
df=pd.DataFrame(DATA['prices'])
df

200

,id,symbol,trade_date,open_price,high_price,low_price,close_price,volume,created_at
0,42853,TOTAL,2017-01-03,299.0,None,None,299.0,8617,2026-04-08T02:41:25.765521+00:00
1,43413,TOTAL,2017-01-04,299.0,None,None,299.0,7647,2026-04-08T02:42:20.164398+00:00
2,43523,TOTAL,2017-01-05,299.0,None,None,299.0,4834,2026-04-08T02:42:22.380516+00:00
3,43633,TOTAL,2017-01-06,299.0,None,None,299.0,11103,2026-04-08T02:42:23.84796+00:00
4,43723,TOTAL,2017-01-09,300.0,None,None,300.0,128985,2026-04-08T02:42:26.938159+00:00
...,...,...,...,...,...,...,...,...,...
2258,298138,TOTAL,2026-07-13,640.0,None,None,640.0,5309,2026-07-13T15:10:02.995074+00:00
2259,298576,TOTAL,2026-07-14,640.0,None,None,640.0,1815,2026-07-14T15:10:03.094441+00:00
2260,299014,TOTAL,2026-07-15,640.0,None,None,640.0,2045,2026-07-15T15:10:03.078609+00:00
2261,299452,TOTAL,2026-07-16,640.0,None,None,640.0,2106,2026-07-16T15:10:03.113936+00:00
2262,299890,TOTAL,2026-07-17,640.0,None,None,640.0,4038,2026-07-17T15:10:03.053983+00:00

In [16]:
df.to_csv("stock_data/TOTAL")

In [26]:
import requests
import pandas as pd

url = "https://www.ngxpulse.ng/api/ngxdata/stocks"

headers = {
    "X-API-Key": ngx_api_key
}

stocks = requests.get(url, headers=headers).json()

In [27]:
df = pd.DataFrame(stocks['stocks'])

df

,symbol,name,current_price,previous_close,change_percent,official_change_percent,pct_change_7d,volume,market_cap,shares_outstanding,sector,market,trade_date
0,AIRTELAFRI,Airtel Africa Plc,5801.40,5801.40,0.00,NaN,0.00,7865.0,2.180254e+13,3.758152e+09,ICT,Main Board,2026-07-17T00:00:00
1,DANGCEM,Dangote Cement Plc,1047.00,1047.00,0.00,NaN,0.00,388188.0,1.766662e+13,1.687356e+10,INDUSTRIAL GOODS,Premium Board,2026-07-17T00:00:00
2,MTNN,MTN Nigeria Communications Plc,826.50,823.50,0.36,0.36,2.04,1405579.0,1.735283e+13,2.099556e+10,ICT,Premium Board,2026-07-17T00:00:00
3,BUAFOODS,BUA Foods Plc,939.00,939.00,0.00,NaN,0.00,67968.0,1.690200e+13,1.800000e+10,CONSUMER GOODS,Main Board,2026-07-17T00:00:00
4,BUACEMENT,BUA Cement Plc,275.60,275.60,-0.58,-0.58,-18.99,17411684.0,9.333016e+12,3.386435e+10,INDUSTRIAL GOODS,Main Board,2026-07-17T00:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
141,PHARMDEKO,Pharma-Deko Plc,1.83,1.83,0.00,NaN,0.00,NaN,3.967814e+08,2.168204e+08,HEALTHCARE,Main Board,2026-07-17T00:00:00
142,BAPLC,Bon Appetit Plc,6.25,6.25,0.00,NaN,0.00,NaN,6.250000e+07,1.000000e+07,ICT,Growth Board,2026-07-17T00:00:00
143,ABBEYBANK,ABBEYBANK,10.00,10.00,6.00,6.00,9.29,2394758.0,NaN,NaN,FINANCIAL SERVICES,Main Board,2026-07-17T00:00:00
144,CMFC,CMFC [DWL],3.30,3.37,-2.08,-2.08,3.12,3159318.0,NaN,NaN,FINANCIAL SERVICES,Main Board,2026-07-17T00:00:00
145,HBMNG,HBMNG,335.00,335.00,0.00,NaN,0.00,2035024.0,NaN,NaN,INDUSTRIAL GOODS,Premium Board,2026-07-17T00:00:00

In [29]:
os.makedirs("stock_data", exist_ok=True)
df.to_csv("stock_data/All_Stocks_Info",index=False)

In [23]:
list_of_tickers=df['symbol'].tolist()

In [24]:
list_of_tickers

['AIRTELAFRI',
 'DANGCEM',
 'MTNN',
 'BUAFOODS',
 'BUACEMENT',
 'SEPLAT',
 'ARADEL',
 'GTCO',
 'ZENITHBANK',
 'FIRSTHOLDCO',
 'PRESCO',
 'STANBIC',
 'TRANSCOHOT',
 'NESTLE',
 'NB',
 'INTBREW',
 'GEREGU',
 'ETI',
 'UBA',
 'TRANSPOWER',
 'OKOMUOIL',
 'ACCESSCORP',
 'WEMABANK',
 'FIDELITYBK',
 'DANGSUGAR',
 'GUINNESS',
 'UNILEVER',
 'UACN',
 'JBERGER',
 'NASCON',
 'OANDO',
 'FCMB',
 'TRANSCORP',
 'STERLINGNG',
 'CUSTODIAN',
 'JAIZBANK',
 'MECURE',
 'BETAGLAS',
 'NAHCO',
 'PZ',
 'UCAP',
 'NGXGROUP',
 'VITAFOAM',
 'FIDSON',
 'SKYAVN',
 'TOTAL',
 'NIDF',
 'NREIT',
 'AIICO',
 'CONOIL',
 'NEM',
 'HONYFLOUR',
 'ETRANZACT',
 'CADBURY',
 'CAP',
 'CHAMPION',
 'CORNERST',
 'MANSARD',
 'MOFIREIF',
 'IKEJAHOTEL',
 'VFDGROUP',
 'MBENEFIT',
 'CONHALLPLC',
 'UPDC',
 'MAYBAKER',
 'WAPIC',
 'AFRIPRUD',
 'CWG',
 'INFINITY',
 'EUNISELL',
 'BERGER',
 'JAPAULGOLD',
 'NEIMETH',
 'CHAMS',
 'ETERNA',
 'FTGINSURE',
 'ELLAHLAKES',
 'FTNCOCOA',
 'NPFMCRFBK',
 'SOVRENINS',
 'UPDCREIT',
 'LINKASSURE',
 'TIP',
 'LIVESTOCK',
 'IMG',
 'SUNUASSUR',
 'TANTALIZER',
 'LASACO',
 'VERITASKAP',
 'SCOA',
 'CUTIX',
 'DAARCOMM',
 'REDSTAREX',
 'PRESTIGE',
 'ABCTRANS',
 'LIVINGTRUST',
 'UNITYBNK',
 'UHOMREIT',
 'NCR',
 'CAVERTON',
 'CILEASING',
 'REGALINS',
 'UNIVINSURE',
 'RTBRISCOE',
 'ZICHIS',
 'NNFM',
 'MORISON',
 'ROYALEX',
 'HMCALL',
 'MULTIVERSE',
 'CNIF',
 'MEYER',
 'CHELLARAM',
 'LEGENDINT',
 'LEARNAFRCA',
 'SFSREIT',
 'RONCHESS',
 'GOLDBREW',
 'GUINEAINS',
 'UNIONDICON',
 'INTENEGINS',
 'MCNICHOLS',
 'ACADEMY',
 'OMATEK',
 'NSLTECH',
 'STACO',
 'JOHNHOLT',
 'AFRINSURE',
 'AVAIF',
 'AUSTINLAZ',
 'TRIPPLEG',
 'PREMPAINTS',
 'ENAMELWA',
 'EKOCORP',
 'UPL',
 'MULTITREX',
 'ALEX',
 'TRANSEXPR',
 'JULI',
 'THOMASWY',
 'AFROMEDIA',
 'PHARMDEKO',
 'BAPLC',
 'ABBEYBANK',
 'CMFC',
 'HBMNG']

In [33]:
import os
import requests
import pandas as pd

os.makedirs("stock_data", exist_ok=True)

def get_stock_data_from_ngx_pulse(ticker, api_key):

    url = f"https://www.ngxpulse.ng/api/ngxdata/prices/{ticker}"

    headers = {
        "X-API-Key": api_key
    }

    params = {
        "from": "2017-01-01",
        "to": "2026-07-18"
    }

    try:
        response = requests.get(
            url,
            headers=headers,
            params=params,
            timeout=30
        )

        print(f"{ticker}: {response.status_code}")

        if response.status_code != 200:
            print(response.text)
            return

        data = response.json()

        if "prices" not in data:
            print(f"{ticker}: No prices returned")
            return

        df = pd.DataFrame(data["prices"])
        df.to_csv(f"stock_data/{ticker}.csv", index=False)

        print(f"{ticker}: Saved {len(df)} rows")

    except Exception as e:
        print(f"{ticker}: {e}")

In [34]:
for ticker in list_of_tickers[:10]:
    get_stock_data_from_ngx_pulse(ticker,ngx_api_key)

AIRTELAFRI: 200
AIRTELAFRI: Saved 1663 rows
DANGCEM: 200
DANGCEM: Saved 2263 rows
MTNN: 200
MTNN: Saved 1694 rows
BUAFOODS: 200
BUAFOODS: Saved 1063 rows
BUACEMENT: 200
BUACEMENT: Saved 1541 rows
SEPLAT: 200
SEPLAT: Saved 1195 rows
ARADEL: 200
ARADEL: Saved 427 rows
GTCO: 200
GTCO: Saved 1190 rows
ZENITHBANK: 200
ZENITHBANK: Saved 2263 rows
FIRSTHOLDCO: 200
FIRSTHOLDCO: Saved 334 rows