## TRAINING AND TESTING

We will do all training and testing here.

In [1]:
import pandas as pd
import pandas_ta as ta
import numpy as np
import os
import datetime as dt

In [2]:
import pandas as pd

finance_sector_df=pd.read_csv('feature_engineering/stocks_sectors/financial_services/financial_services_sector')

In [3]:
finance_sector_df.head()

,date,sector,weighted_sector_returns,n_stocks_contributing,sector_index,sector_volume
0,2017-01-03,financial_services,0.000000,20.0,100.000000,48125518.0
1,2017-01-04,financial_services,0.353432,20.0,100.353432,26705191.0
2,2017-01-05,financial_services,-0.182223,20.0,100.170565,66991076.0
3,2017-01-06,financial_services,1.397196,20.0,101.570144,97521276.0
4,2017-01-09,financial_services,3.645896,20.0,105.273286,99013315.0

In [4]:
finance_sector_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2263 entries, 0 to 2262
Data columns (total 6 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   date                     2263 non-null   str
 1   sector                   2263 non-null   str
 2   weighted_sector_returns  2263 non-null   float64
 3   n_stocks_contributing    2263 non-null   float64
 4   sector_index             2263 non-null   float64
 5   sector_volume            2263 non-null   float64
dtypes: float64(4), str(2)
memory usage: 106.2 KB

In [5]:
finance_sector_df['date']=pd.to_datetime(finance_sector_df['date'], format='%Y-%m-%d', errors='coerce')

In [6]:
finance_sector_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2263 entries, 0 to 2262
Data columns (total 6 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   date                     2263 non-null   datetime64[us]
 1   sector                   2263 non-null   str
 2   weighted_sector_returns  2263 non-null   float64
 3   n_stocks_contributing    2263 non-null   float64
 4   sector_index             2263 non-null   float64
 5   sector_volume            2263 non-null   float64
dtypes: datetime64[us](1), float64(4), str(1)
memory usage: 106.2 KB

In [7]:
macro_eco_data=pd.read_csv('macroeconomic_data/populated_cleaned_macro_data')

In [8]:
macro_eco_data.head()

,Quarter,Month,Date,consumer_price_index(CPI)_monthly,Crude Oil Price_monthly,Domestic Production_monthly,Crude Oil Export_monthly,Inflation_allItemsAverage_monthly,Money Supply(M2)_monthly,currency in circulation_monthly,...,gdp_svc_Other Services_quarterly,GDP at Current Basic Prices_quarterly,Net Taxes on Products_quarterly,GDP at Current Market Prices_quarterly,foreign_reserve_Gross(USD)_monthly,foreign_reserve_Liquid(USD)_monthly,Year,Month_idx,foreign_reserve_gross(USD)_daily,foreign_reserve_liquid(USD)_daily
0,Q2,April,2017-04-03,204.45661,52.13,1.6,1.15,17.32,22304267.84,1983633.07,...,1237.68,26028.36,200.5,26228.85,3.029795e+10,2.962647e+10,2017,4,3.030715e+10,2.963927e+10
1,Q2,April,2017-04-04,204.45661,52.13,1.6,1.15,17.32,22304267.84,1983633.07,...,1237.68,26028.36,200.5,26228.85,3.029795e+10,2.962647e+10,2017,4,3.031831e+10,2.965163e+10
2,Q2,April,2017-04-05,204.45661,52.13,1.6,1.15,17.32,22304267.84,1983633.07,...,1237.68,26028.36,200.5,26228.85,3.029795e+10,2.962647e+10,2017,4,3.032576e+10,2.966022e+10
3,Q2,April,2017-04-06,204.45661,52.13,1.6,1.15,17.32,22304267.84,1983633.07,...,1237.68,26028.36,200.5,26228.85,3.029795e+10,2.962647e+10,2017,4,3.034555e+10,2.968121e+10
4,Q2,April,2017-04-07,204.45661,52.13,1.6,1.15,17.32,22304267.84,1983633.07,...,1237.68,26028.36,200.5,26228.85,3.029795e+10,2.962647e+10,2017,4,3.036654e+10,2.970295e+10

In [9]:
macro_eco_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 2257 entries, 0 to 2256
Data columns (total 84 columns):
 #   Column                                                                      Non-Null Count  Dtype
---  ------                                                                      --------------  -----
 0   Quarter                                                                     2257 non-null   str
 1   Month                                                                       2257 non-null   str
 2   Date                                                                        2257 non-null   str
 3   consumer_price_index(CPI)_monthly                                           2257 non-null   float64
 4   Crude Oil Price_monthly                                                     2257 non-null   float64
 5   Domestic Production_monthly                                                 2257 non-null   float64
 6   Crude Oil Export_monthly                                                    2257 non-null   float64
 7   Inflation_allItemsAverage_monthly                                           2257 non-null   float64
 8   Money Supply(M2)_monthly                                                    2257 non-null   float64
 9   currency in circulation_monthly                                             2257 non-null   float64
 10  bank reserves_monthly                                                       2257 non-null   float64
 11  netForeignAssets_monthly                                                    2257 non-null   float64
 12  netDomesticAssets_monthly                                                   2257 non-null   float64
 13  netDomesticCredit_monthly                                                   2257 non-null   float64
 14  creditToGovernment_monthly                                                  2257 non-null   float64
 15  creditToPrivateSector_monthly                                               2257 non-null   float64
 16  MonetaryPolicyRate_monthly                                                  2257 non-null   float64
 17  TreasuryBillRate_monthly                                                    2257 non-null   float64
 18  Lending_Rate_monthly                                                        2257 non-null   float64
 19  Exchange_Rate(USD-EOP)_monthly                                              2257 non-null   float64
 20  Premium_Motor_Spirit(PMS)_monthly                                           2257 non-null   float64
 21  A. GDP_AGRICULTURE(agric)_quarterly                                         2257 non-null   float64
 22  gdp_agric_Crop Production_quarterly                                         2257 non-null   float64
 23  gdp_agric_Livestock_quarterly                                               2257 non-null   float64
 24  gdp_agric_Forestry_quarterly                                                2257 non-null   float64
 25   gdp_Fishing_quarterly                                                      2257 non-null   float64
 26  GDP_INDUSTRY(ind)_quarterly                                                 2257 non-null   float64
 27  gdp_ind_Mining and Quarrying(MQ)_quarterly                                  2257 non-null   float64
 28  gdp_ind_MQ_Crude Petroleum and Natural Gas_quarterly                        2257 non-null   float64
 29  gdp_ind_MQ_Coal Mining_quarterly                                            2257 non-null   float64
 30  gdp_ind_MQ_Metal Ores_quarterly                                             2257 non-null   float64
 31  gdp_ind_MQ_Quarrying and Other Minerals_quarterly                           2257 non-null   float64
 32  gdp_ind_Manufacturing(mfg)_quarterly                                        2257 non-null   float64
 33   gdp_ind_mfg_Oil Refining_quarterly                                         2257 non-null   float64
 34  gdp_ind_mfg_Cement_quarterly                                                2257 non-null   float64
 35  gdp_ind_mfg_Food, Beverage and Tobacco_quarterly                            2257 non-null   float64
 36  gdp_ind_mfg_Textile, Apparel and Footwear_quarterly                         2257 non-null   float64
 37  gdp_ind_mfg_Wood and Wood Products_quarterly                                2257 non-null   float64
 38  gdp_ind_mfg_Pulp, Paper and Paper Products_quarterly                        2257 non-null   float64
 39  gdp_ind_mfg_Chemical and Pharmaceutical Products_quarterly                  2257 non-null   float64
 40  gdp_ind_mfg_Non-Metallic Products_quarterly                                 2257 non-null   float64
 41  gdp_ind_mfg_Plastic and Rubber Products_quarterly                           2257 non-null   float64
 42  gdp_ind_mfg_Electrical and Electronics_quarterly                            2257 non-null   float64
 43  gdp_ind_mfg_Basic Metal, Iron and Steel_quarterly                           2257 non-null   float64
 44  gdp_ind_mfg_Motor Vehicles and Assembly_quarterly                           2257 non-null   float64
 45  gdp_ind_mfg_Other Manufacturing_quarterly                                   2257 non-null   float64
 46  gdp_ind_Electricity, Gas, Steam & Air conditioner_quarterly                 2257 non-null   float64
 47  gdp_ind_Water supply, Sewage, Waste Management_quarterly                    2257 non-null   float64
 48  gdp_ind_Construction_quarterly                                              2257 non-null   float64
 49  GDP_SERVICES(svc)_quarterly                                                 2257 non-null   float64
 50  gdp_svc_Trade_quarterly                                                     2257 non-null   float64
 51  gdp_svc_Accommodation and Food Services_quarterly                           2257 non-null   float64
 52  gdp_svc_Transportation and Storage(TS)_quarterly                            2257 non-null   float64
 53  gdp_svc_TS_RoadTransport_quarterly                                          2257 non-null   float64
 54  gdp_svc_TS_Rail Transport & Pipelines_quarterly                             2257 non-null   float64
 55  gdp_svc_TS_Water Transport_quarterly                                        2257 non-null   float64
 56  gdp_svc_TS_Air Transport_quarterly                                          2257 non-null   float64
 57  gdp_svc_TS_Transport Services_quarterly                                     2257 non-null   float64
 58  gdp_svc_TS_Post and Courier Services_quarterly                              2257 non-null   float64
 59  gdp_svc_Information and Communication(IC)_quarterly                         2257 non-null   float64
 60  gdp_svc_IC_Telecommunications and Information Services_quarterly            2257 non-null   float64
 61  gdp_svc_IC_Publishing_quarterly                                             2257 non-null   float64
 62  gdp_svc_IC_Motion Pictures, Sound Recording and Music Production_quarterly  2257 non-null   float64
 63  gdp_svc_IC_Broadcasting_quarterly                                           2257 non-null   float64
 64  gdp_svc_Arts, Entertainment & Recreation_quarterly                          2257 non-null   float64
 65  gdp_svc_Financial and Insurance(FI)_quarterly                               2257 non-null   float64
 66  gdp_svc_FI_Financial Institutions_quarterly                                 2257 non-null   float64
 67  gdp_svc_FI_Insurance_quarterly                                              2257 non-null   float64
 68  gdp_svc_Real Estate_quarterly                                               2257 non-null   float64
 69  gdp_svc_Professional, Scientific & Technical Services_quarterly             2257 non-null   float64
 70  gdp_svc_Administrative and Support Services_quarterly                       2257 non-null   float64
 71  gdp_svc_Public Administration_quarterly                                     2257 non-null   float64
 72  gdp_svc_Education_quarterly                                                 2257 non-null   float64
 73  gdp_svc_Human Health & Social Services_quarterly                            2257 non-null   float64
 74  gdp_svc_Other Services_quarterly                                            2257 non-null   float64
 75  GDP at Current Basic Prices_quarterly                                       2257 non-null   float64
 76  Net Taxes on Products_quarterly                                             2257 non-null   float64
 77  GDP at Current Market Prices_quarterly                                      2257 non-null   float64
 78  foreign_reserve_Gross(USD)_monthly                                          2257 non-null   float64
 79  foreign_reserve_Liquid(USD)_monthly                                         2257 non-null   float64
 80  Year                                                                        2257 non-null   int64
 81  Month_idx                                                                   2257 non-null   int64
 82  foreign_reserve_gross(USD)_daily                                            2257 non-null   float64
 83  foreign_reserve_liquid(USD)_daily                                           2257 non-null   float64
dtypes: float64(79), int64(2), str(3)
memory usage: 1.4 MB

In [10]:
macro_eco_data['Date']=pd.to_datetime(macro_eco_data['Date'], format='%Y-%m-%d', errors="coerce")

In [11]:
macro_eco_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 2257 entries, 0 to 2256
Data columns (total 84 columns):
 #   Column                                                                      Non-Null Count  Dtype
---  ------                                                                      --------------  -----
 0   Quarter                                                                     2257 non-null   str
 1   Month                                                                       2257 non-null   str
 2   Date                                                                        2257 non-null   datetime64[us]
 3   consumer_price_index(CPI)_monthly                                           2257 non-null   float64
 4   Crude Oil Price_monthly                                                     2257 non-null   float64
 5   Domestic Production_monthly                                                 2257 non-null   float64
 6   Crude Oil Export_monthly                                                    2257 non-null   float64
 7   Inflation_allItemsAverage_monthly                                           2257 non-null   float64
 8   Money Supply(M2)_monthly                                                    2257 non-null   float64
 9   currency in circulation_monthly                                             2257 non-null   float64
 10  bank reserves_monthly                                                       2257 non-null   float64
 11  netForeignAssets_monthly                                                    2257 non-null   float64
 12  netDomesticAssets_monthly                                                   2257 non-null   float64
 13  netDomesticCredit_monthly                                                   2257 non-null   float64
 14  creditToGovernment_monthly                                                  2257 non-null   float64
 15  creditToPrivateSector_monthly                                               2257 non-null   float64
 16  MonetaryPolicyRate_monthly                                                  2257 non-null   float64
 17  TreasuryBillRate_monthly                                                    2257 non-null   float64
 18  Lending_Rate_monthly                                                        2257 non-null   float64
 19  Exchange_Rate(USD-EOP)_monthly                                              2257 non-null   float64
 20  Premium_Motor_Spirit(PMS)_monthly                                           2257 non-null   float64
 21  A. GDP_AGRICULTURE(agric)_quarterly                                         2257 non-null   float64
 22  gdp_agric_Crop Production_quarterly                                         2257 non-null   float64
 23  gdp_agric_Livestock_quarterly                                               2257 non-null   float64
 24  gdp_agric_Forestry_quarterly                                                2257 non-null   float64
 25   gdp_Fishing_quarterly                                                      2257 non-null   float64
 26  GDP_INDUSTRY(ind)_quarterly                                                 2257 non-null   float64
 27  gdp_ind_Mining and Quarrying(MQ)_quarterly                                  2257 non-null   float64
 28  gdp_ind_MQ_Crude Petroleum and Natural Gas_quarterly                        2257 non-null   float64
 29  gdp_ind_MQ_Coal Mining_quarterly                                            2257 non-null   float64
 30  gdp_ind_MQ_Metal Ores_quarterly                                             2257 non-null   float64
 31  gdp_ind_MQ_Quarrying and Other Minerals_quarterly                           2257 non-null   float64
 32  gdp_ind_Manufacturing(mfg)_quarterly                                        2257 non-null   float64
 33   gdp_ind_mfg_Oil Refining_quarterly                                         2257 non-null   float64
 34  gdp_ind_mfg_Cement_quarterly                                                2257 non-null   float64
 35  gdp_ind_mfg_Food, Beverage and Tobacco_quarterly                            2257 non-null   float64
 36  gdp_ind_mfg_Textile, Apparel and Footwear_quarterly                         2257 non-null   float64
 37  gdp_ind_mfg_Wood and Wood Products_quarterly                                2257 non-null   float64
 38  gdp_ind_mfg_Pulp, Paper and Paper Products_quarterly                        2257 non-null   float64
 39  gdp_ind_mfg_Chemical and Pharmaceutical Products_quarterly                  2257 non-null   float64
 40  gdp_ind_mfg_Non-Metallic Products_quarterly                                 2257 non-null   float64
 41  gdp_ind_mfg_Plastic and Rubber Products_quarterly                           2257 non-null   float64
 42  gdp_ind_mfg_Electrical and Electronics_quarterly                            2257 non-null   float64
 43  gdp_ind_mfg_Basic Metal, Iron and Steel_quarterly                           2257 non-null   float64
 44  gdp_ind_mfg_Motor Vehicles and Assembly_quarterly                           2257 non-null   float64
 45  gdp_ind_mfg_Other Manufacturing_quarterly                                   2257 non-null   float64
 46  gdp_ind_Electricity, Gas, Steam & Air conditioner_quarterly                 2257 non-null   float64
 47  gdp_ind_Water supply, Sewage, Waste Management_quarterly                    2257 non-null   float64
 48  gdp_ind_Construction_quarterly                                              2257 non-null   float64
 49  GDP_SERVICES(svc)_quarterly                                                 2257 non-null   float64
 50  gdp_svc_Trade_quarterly                                                     2257 non-null   float64
 51  gdp_svc_Accommodation and Food Services_quarterly                           2257 non-null   float64
 52  gdp_svc_Transportation and Storage(TS)_quarterly                            2257 non-null   float64
 53  gdp_svc_TS_RoadTransport_quarterly                                          2257 non-null   float64
 54  gdp_svc_TS_Rail Transport & Pipelines_quarterly                             2257 non-null   float64
 55  gdp_svc_TS_Water Transport_quarterly                                        2257 non-null   float64
 56  gdp_svc_TS_Air Transport_quarterly                                          2257 non-null   float64
 57  gdp_svc_TS_Transport Services_quarterly                                     2257 non-null   float64
 58  gdp_svc_TS_Post and Courier Services_quarterly                              2257 non-null   float64
 59  gdp_svc_Information and Communication(IC)_quarterly                         2257 non-null   float64
 60  gdp_svc_IC_Telecommunications and Information Services_quarterly            2257 non-null   float64
 61  gdp_svc_IC_Publishing_quarterly                                             2257 non-null   float64
 62  gdp_svc_IC_Motion Pictures, Sound Recording and Music Production_quarterly  2257 non-null   float64
 63  gdp_svc_IC_Broadcasting_quarterly                                           2257 non-null   float64
 64  gdp_svc_Arts, Entertainment & Recreation_quarterly                          2257 non-null   float64
 65  gdp_svc_Financial and Insurance(FI)_quarterly                               2257 non-null   float64
 66  gdp_svc_FI_Financial Institutions_quarterly                                 2257 non-null   float64
 67  gdp_svc_FI_Insurance_quarterly                                              2257 non-null   float64
 68  gdp_svc_Real Estate_quarterly                                               2257 non-null   float64
 69  gdp_svc_Professional, Scientific & Technical Services_quarterly             2257 non-null   float64
 70  gdp_svc_Administrative and Support Services_quarterly                       2257 non-null   float64
 71  gdp_svc_Public Administration_quarterly                                     2257 non-null   float64
 72  gdp_svc_Education_quarterly                                                 2257 non-null   float64
 73  gdp_svc_Human Health & Social Services_quarterly                            2257 non-null   float64
 74  gdp_svc_Other Services_quarterly                                            2257 non-null   float64
 75  GDP at Current Basic Prices_quarterly                                       2257 non-null   float64
 76  Net Taxes on Products_quarterly                                             2257 non-null   float64
 77  GDP at Current Market Prices_quarterly                                      2257 non-null   float64
 78  foreign_reserve_Gross(USD)_monthly                                          2257 non-null   float64
 79  foreign_reserve_Liquid(USD)_monthly                                         2257 non-null   float64
 80  Year                                                                        2257 non-null   int64
 81  Month_idx                                                                   2257 non-null   int64
 82  foreign_reserve_gross(USD)_daily                                            2257 non-null   float64
 83  foreign_reserve_liquid(USD)_daily                                           2257 non-null   float64
dtypes: datetime64[us](1), float64(79), int64(2), str(2)
memory usage: 1.4 MB

In [12]:
macro_eco_data = macro_eco_data.rename(columns={"Date": "date"})

In [13]:
macro_eco_data.head()

,Quarter,Month,date,consumer_price_index(CPI)_monthly,Crude Oil Price_monthly,Domestic Production_monthly,Crude Oil Export_monthly,Inflation_allItemsAverage_monthly,Money Supply(M2)_monthly,currency in circulation_monthly,...,gdp_svc_Other Services_quarterly,GDP at Current Basic Prices_quarterly,Net Taxes on Products_quarterly,GDP at Current Market Prices_quarterly,foreign_reserve_Gross(USD)_monthly,foreign_reserve_Liquid(USD)_monthly,Year,Month_idx,foreign_reserve_gross(USD)_daily,foreign_reserve_liquid(USD)_daily
0,Q2,April,2017-04-03,204.45661,52.13,1.6,1.15,17.32,22304267.84,1983633.07,...,1237.68,26028.36,200.5,26228.85,3.029795e+10,2.962647e+10,2017,4,3.030715e+10,2.963927e+10
1,Q2,April,2017-04-04,204.45661,52.13,1.6,1.15,17.32,22304267.84,1983633.07,...,1237.68,26028.36,200.5,26228.85,3.029795e+10,2.962647e+10,2017,4,3.031831e+10,2.965163e+10
2,Q2,April,2017-04-05,204.45661,52.13,1.6,1.15,17.32,22304267.84,1983633.07,...,1237.68,26028.36,200.5,26228.85,3.029795e+10,2.962647e+10,2017,4,3.032576e+10,2.966022e+10
3,Q2,April,2017-04-06,204.45661,52.13,1.6,1.15,17.32,22304267.84,1983633.07,...,1237.68,26028.36,200.5,26228.85,3.029795e+10,2.962647e+10,2017,4,3.034555e+10,2.968121e+10
4,Q2,April,2017-04-07,204.45661,52.13,1.6,1.15,17.32,22304267.84,1983633.07,...,1237.68,26028.36,200.5,26228.85,3.029795e+10,2.962647e+10,2017,4,3.036654e+10,2.970295e+10

LET US WORK WITHOUT ANY LAGGING AT FIRST

In [14]:
## Lets merge the data 

sector_ME_df = finance_sector_df.merge(
    macro_eco_data,
    on="date",
    how="left"
)

In [15]:
sector_ME_df

,date,sector,weighted_sector_returns,n_stocks_contributing,sector_index,sector_volume,Quarter,Month,consumer_price_index(CPI)_monthly,Crude Oil Price_monthly,...,gdp_svc_Other Services_quarterly,GDP at Current Basic Prices_quarterly,Net Taxes on Products_quarterly,GDP at Current Market Prices_quarterly,foreign_reserve_Gross(USD)_monthly,foreign_reserve_Liquid(USD)_monthly,Year,Month_idx,foreign_reserve_gross(USD)_daily,foreign_reserve_liquid(USD)_daily
0,2017-01-03,financial_services,0.000000,20.0,100.000000,48125518.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2017-01-04,financial_services,0.353432,20.0,100.353432,26705191.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2017-01-05,financial_services,-0.182223,20.0,100.170565,66991076.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2017-01-06,financial_services,1.397196,20.0,101.570144,97521276.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2017-01-09,financial_services,3.645896,20.0,105.273286,99013315.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2286,2026-07-13,financial_services,-0.746327,35.0,2695.019313,290562049.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2287,2026-07-14,financial_services,0.906947,35.0,2719.461701,163509442.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2288,2026-07-15,financial_services,0.779799,35.0,2740.668037,258362267.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2289,2026-07-16,financial_services,1.505893,35.0,2781.939574,261040578.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2290,2026-07-17,financial_services,1.536021,35.0,2824.670764,295044834.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [20]:
sector_ME_df.dropna(inplace=True)

In [21]:
sector_ME_df.head()

,date,sector,weighted_sector_returns,n_stocks_contributing,sector_index,sector_volume,Quarter,Month,consumer_price_index(CPI)_monthly,Crude Oil Price_monthly,...,gdp_svc_Other Services_quarterly,GDP at Current Basic Prices_quarterly,Net Taxes on Products_quarterly,GDP at Current Market Prices_quarterly,foreign_reserve_Gross(USD)_monthly,foreign_reserve_Liquid(USD)_monthly,Year,Month_idx,foreign_reserve_gross(USD)_daily,foreign_reserve_liquid(USD)_daily
64,2017-04-03,financial_services,-0.403579,21.0,105.031248,51906903.0,Q2,April,204.45661,52.13,...,1237.68,26028.36,200.5,26228.85,3.029795e+10,2.962647e+10,2017.0,4.0,3.030715e+10,2.963927e+10
65,2017-04-04,financial_services,-0.295235,21.0,104.721159,45091739.0,Q2,April,204.45661,52.13,...,1237.68,26028.36,200.5,26228.85,3.029795e+10,2.962647e+10,2017.0,4.0,3.031831e+10,2.965163e+10
66,2017-04-05,financial_services,0.584640,21.0,105.333401,96410309.0,Q2,April,204.45661,52.13,...,1237.68,26028.36,200.5,26228.85,3.029795e+10,2.962647e+10,2017.0,4.0,3.032576e+10,2.966022e+10
67,2017-04-06,financial_services,-0.282732,21.0,105.035590,101585127.0,Q2,April,204.45661,52.13,...,1237.68,26028.36,200.5,26228.85,3.029795e+10,2.962647e+10,2017.0,4.0,3.034555e+10,2.968121e+10
68,2017-04-07,financial_services,0.624710,21.0,105.691757,51494340.0,Q2,April,204.45661,52.13,...,1237.68,26028.36,200.5,26228.85,3.029795e+10,2.962647e+10,2017.0,4.0,3.036654e+10,2.970295e+10