## Monthly Data Training

We will sort the daily data to fit monthly

In [1]:
import pandas as pd
from datetime import datetime as dt

# 1. Generate the date range from January 1, 2017, up to today
date_series = pd.date_range(start='2017-01-01', end=dt.now(), freq='ME')

# 2. Create the DataFrame and format the dates as %Y-%m-%d
df = pd.DataFrame()
df['date'] = date_series.strftime('%Y-%m-%d')

In [2]:
df

           date
0    2017-01-31
1    2017-02-28
2    2017-03-31
3    2017-04-30
4    2017-05-31
..          ...
110  2026-03-31
111  2026-04-30
112  2026-05-31
113  2026-06-30
114  2026-07-31

[115 rows x 1 columns]

In [3]:
md=pd.read_csv('macroeconomic_data/macro_data(csv)')
md

,year,month,month_idx,consumer_price_index(CPI)_monthly,Crude Oil Price_monthly,Domestic Production_monthly,Crude Oil Export_monthly,Inflation_allItemsAverage_monthly,Money Supply(M2)_monthly,currency in circulation_monthly,...,gdp_svc_Public Administration_quarterly,gdp_svc_Education_quarterly,gdp_svc_Human Health & Social Services_quarterly,gdp_svc_Other Services_quarterly,GDP at Current Basic Prices_quarterly,Net Taxes on Products_quarterly,GDP at Current Market Prices_quarterly,FR_Date,foreign_reserve_Gross(USD)_monthly,foreign_reserve_Liquid(USD)_monthly
0,2017.0,january,1,198.041241,55.01,1.84,1.39,16.44,23096526.55,1994577.62,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01/31/2017,2.817423e+10,2.745703e+10
1,NaN,february,2,201.001141,46.39,1.82,1.37,16.96,22210954.84,1978886.94,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,02/28/2017,2.964668e+10,2.894094e+10
2,NaN,march,3,204.456610,52.13,1.60,1.15,17.32,22304267.84,1983633.07,...,680.04,587.79,186.24,1237.68,26028.36,200.5,26228.85,03/31/2017,3.029795e+10,2.962647e+10
3,NaN,april,4,207.729678,52.94,1.79,1.34,17.59,21768241.12,1975812.32,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,04/28/2017,3.086463e+10,3.017061e+10
4,NaN,may,5,211.637809,50.57,1.87,1.42,17.63,22047770.68,1897917.15,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,05/31/2017,3.032964e+10,2.961376e+10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,NaN,august,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,07/16/2026,5.191564e+10,5.129593e+10
116,NaN,september,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
117,NaN,october,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
118,NaN,november,11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
119,NaN,december,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
mde=pd.read_excel('macroeconomic_data/NGX_Macro_project_data(complete).xlsx')
mde

,year,month,month_idx,consumer_price_index(CPI)_monthly,Crude Oil Price_monthly,Domestic Production_monthly,Crude Oil Export_monthly,Inflation_allItemsAverage_monthly,Money Supply(M2)_monthly,currency in circulation_monthly,...,gdp_svc_Public Administration_quarterly,gdp_svc_Education_quarterly,gdp_svc_Human Health & Social Services_quarterly,gdp_svc_Other Services_quarterly,GDP at Current Basic Prices_quarterly,Net Taxes on Products_quarterly,GDP at Current Market Prices_quarterly,FR_Date,foreign_reserve_Gross(USD)_monthly,foreign_reserve_Liquid(USD)_monthly
0,2017.0,january,1,198.041241,55.01,1.84,1.39,16.44,23096526.55,1994577.62,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01/31/2017,2.817423e+10,2.745703e+10
1,NaN,february,2,201.001141,46.39,1.82,1.37,16.96,22210954.84,1978886.94,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,02/28/2017,2.964668e+10,2.894094e+10
2,NaN,march,3,204.456610,52.13,1.60,1.15,17.32,22304267.84,1983633.07,...,680.04,587.79,186.24,1237.68,26028.36,200.5,26228.85,03/31/2017,3.029795e+10,2.962647e+10
3,NaN,april,4,207.729678,52.94,1.79,1.34,17.59,21768241.12,1975812.32,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,04/28/2017,3.086463e+10,3.017061e+10
4,NaN,may,5,211.637809,50.57,1.87,1.42,17.63,22047770.68,1897917.15,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,05/31/2017,3.032964e+10,2.961376e+10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,NaN,august,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,07/16/2026,5.191564e+10,5.129593e+10
116,NaN,september,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
117,NaN,october,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
118,NaN,november,11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
119,NaN,december,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
mde2=pd.read_excel('macroeconomic_data/NGX_Macro_project_data(complete22).xlsx')
mde2

,year,month,month_idx,consumer_price_index(CPI)_monthly,Crude Oil Price_monthly,Domestic Production_monthly,Crude Oil Export_monthly,Inflation_allItemsAverage_monthly,Money Supply(M2)_monthly,currency in circulation_monthly,...,gdp_svc_Public Administration_quarterly,gdp_svc_Education_quarterly,gdp_svc_Human Health & Social Services_quarterly,gdp_svc_Other Services_quarterly,GDP at Current Basic Prices_quarterly,Net Taxes on Products_quarterly,GDP at Current Market Prices_quarterly,FR_Date,foreign_reserve_Gross(USD)_monthly,foreign_reserve_Liquid(USD)_monthly
0,2017.0,january,1,198.041241,55.01,1.84,1.39,16.44,23096526.55,1994577.62,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01/31/2017,2.817423e+10,2.745703e+10
1,NaN,february,2,201.001141,46.39,1.82,1.37,16.96,22210954.84,1978886.94,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,02/28/2017,2.964668e+10,2.894094e+10
2,NaN,march,3,204.456610,52.13,1.60,1.15,17.32,22304267.84,1983633.07,...,680.04,587.79,186.24,1237.68,26028.36,200.5,26228.85,03/31/2017,3.029795e+10,2.962647e+10
3,NaN,april,4,207.729678,52.94,1.79,1.34,17.59,21768241.12,1975812.32,...,680.04,587.79,186.24,1237.68,26028.36,200.5,26228.85,04/28/2017,3.086463e+10,3.017061e+10
4,NaN,may,5,211.637809,50.57,1.87,1.42,17.63,22047770.68,1897917.15,...,680.04,587.79,186.24,1237.68,26028.36,200.5,26228.85,05/31/2017,3.032964e+10,2.961376e+10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,NaN,august,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,07/16/2026,5.191564e+10,5.129593e+10
116,NaN,september,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
117,NaN,october,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
118,NaN,november,11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
119,NaN,december,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
mde2['FR_Date'] = pd.to_datetime(mde2['FR_Date']).dt.strftime('%Y-%m-%d')

In [8]:
mde2["date"] = pd.date_range(
    start="2017-01-31",
    periods=len(mde2),
    freq="ME"
)

In [9]:
mde2

,year,month,month_idx,consumer_price_index(CPI)_monthly,Crude Oil Price_monthly,Domestic Production_monthly,Crude Oil Export_monthly,Inflation_allItemsAverage_monthly,Money Supply(M2)_monthly,currency in circulation_monthly,...,gdp_svc_Education_quarterly,gdp_svc_Human Health & Social Services_quarterly,gdp_svc_Other Services_quarterly,GDP at Current Basic Prices_quarterly,Net Taxes on Products_quarterly,GDP at Current Market Prices_quarterly,FR_Date,foreign_reserve_Gross(USD)_monthly,foreign_reserve_Liquid(USD)_monthly,date
0,2017.0,january,1,198.041241,55.01,1.84,1.39,16.44,23096526.55,1994577.62,...,NaN,NaN,NaN,NaN,NaN,NaN,2017-01-31,2.817423e+10,2.745703e+10,2017-01-31
1,NaN,february,2,201.001141,46.39,1.82,1.37,16.96,22210954.84,1978886.94,...,NaN,NaN,NaN,NaN,NaN,NaN,2017-02-28,2.964668e+10,2.894094e+10,2017-02-28
2,NaN,march,3,204.456610,52.13,1.60,1.15,17.32,22304267.84,1983633.07,...,587.79,186.24,1237.68,26028.36,200.5,26228.85,2017-03-31,3.029795e+10,2.962647e+10,2017-03-31
3,NaN,april,4,207.729678,52.94,1.79,1.34,17.59,21768241.12,1975812.32,...,587.79,186.24,1237.68,26028.36,200.5,26228.85,2017-04-28,3.086463e+10,3.017061e+10,2017-04-30
4,NaN,may,5,211.637809,50.57,1.87,1.42,17.63,22047770.68,1897917.15,...,587.79,186.24,1237.68,26028.36,200.5,26228.85,2017-05-31,3.032964e+10,2.961376e+10,2017-05-31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,NaN,august,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2026-07-16,5.191564e+10,5.129593e+10,2026-08-31
116,NaN,september,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-09-30
117,NaN,october,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-10-31
118,NaN,november,11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-11-30
119,NaN,december,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-12-31

shift the foreign reserve data to avoid look ahead bias we will shift the monthly data by 1 month. So the information is used to predict the next months returns.

In [12]:
mde2[['foreign_reserve_Gross(USD)_monthly','foreign_reserve_Liquid(USD)_monthly']]=mde2[['foreign_reserve_Gross(USD)_monthly','foreign_reserve_Liquid(USD)_monthly']].shift(1)

In [13]:
mde2

,year,month,month_idx,consumer_price_index(CPI)_monthly,Crude Oil Price_monthly,Domestic Production_monthly,Crude Oil Export_monthly,Inflation_allItemsAverage_monthly,Money Supply(M2)_monthly,currency in circulation_monthly,...,gdp_svc_Education_quarterly,gdp_svc_Human Health & Social Services_quarterly,gdp_svc_Other Services_quarterly,GDP at Current Basic Prices_quarterly,Net Taxes on Products_quarterly,GDP at Current Market Prices_quarterly,FR_Date,foreign_reserve_Gross(USD)_monthly,foreign_reserve_Liquid(USD)_monthly,date
0,2017.0,january,1,198.041241,55.01,1.84,1.39,16.44,23096526.55,1994577.62,...,NaN,NaN,NaN,NaN,NaN,NaN,2017-01-31,NaN,NaN,2017-01-31
1,NaN,february,2,201.001141,46.39,1.82,1.37,16.96,22210954.84,1978886.94,...,NaN,NaN,NaN,NaN,NaN,NaN,2017-02-28,2.817423e+10,2.745703e+10,2017-02-28
2,NaN,march,3,204.456610,52.13,1.60,1.15,17.32,22304267.84,1983633.07,...,587.79,186.24,1237.68,26028.36,200.5,26228.85,2017-03-31,2.964668e+10,2.894094e+10,2017-03-31
3,NaN,april,4,207.729678,52.94,1.79,1.34,17.59,21768241.12,1975812.32,...,587.79,186.24,1237.68,26028.36,200.5,26228.85,2017-04-28,3.029795e+10,2.962647e+10,2017-04-30
4,NaN,may,5,211.637809,50.57,1.87,1.42,17.63,22047770.68,1897917.15,...,587.79,186.24,1237.68,26028.36,200.5,26228.85,2017-05-31,3.086463e+10,3.017061e+10,2017-05-31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,NaN,august,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2026-07-16,5.145923e+10,5.081045e+10,2026-08-31
116,NaN,september,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.191564e+10,5.129593e+10,2026-09-30
117,NaN,october,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-10-31
118,NaN,november,11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-11-30
119,NaN,december,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-12-31

In [14]:
mde3=mde2.drop(columns=['year','month','month_idx'])

In [15]:
mde3

,consumer_price_index(CPI)_monthly,Crude Oil Price_monthly,Domestic Production_monthly,Crude Oil Export_monthly,Inflation_allItemsAverage_monthly,Money Supply(M2)_monthly,currency in circulation_monthly,bank reserves_monthly,netForeignAssets_monthly,netDomesticAssets_monthly,...,gdp_svc_Education_quarterly,gdp_svc_Human Health & Social Services_quarterly,gdp_svc_Other Services_quarterly,GDP at Current Basic Prices_quarterly,Net Taxes on Products_quarterly,GDP at Current Market Prices_quarterly,FR_Date,foreign_reserve_Gross(USD)_monthly,foreign_reserve_Liquid(USD)_monthly,date
0,198.041241,55.01,1.84,1.39,16.44,23096526.55,1994577.62,3311609.44,9473002.48,19005647.02,...,NaN,NaN,NaN,NaN,NaN,NaN,2017-01-31,NaN,NaN,2017-01-31
1,201.001141,46.39,1.82,1.37,16.96,22210954.84,1978886.94,3234760.81,7977399.24,19746640.86,...,NaN,NaN,NaN,NaN,NaN,NaN,2017-02-28,2.817423e+10,2.745703e+10,2017-02-28
2,204.456610,52.13,1.60,1.15,17.32,22304267.84,1983633.07,3309947.53,7628543.46,20342546.55,...,587.79,186.24,1237.68,26028.36,200.5,26228.85,2017-03-31,2.964668e+10,2.894094e+10,2017-03-31
3,207.729678,52.94,1.79,1.34,17.59,21768241.12,1975812.32,3536407.29,7269852.64,20347360.25,...,587.79,186.24,1237.68,26028.36,200.5,26228.85,2017-04-28,3.029795e+10,2.962647e+10,2017-04-30
4,211.637809,50.57,1.87,1.42,17.63,22047770.68,1897917.15,3254006.25,8540084.49,19499233.11,...,587.79,186.24,1237.68,26028.36,200.5,26228.85,2017-05-31,3.086463e+10,3.017061e+10,2017-05-31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2026-07-16,5.145923e+10,5.081045e+10,2026-08-31
116,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.191564e+10,5.129593e+10,2026-09-30
117,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-10-31
118,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-11-30
119,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-12-31

In [18]:
for column in mde3.columns:
    if column.endswith('_monthly'):
        mde3[column]=mde3[column].shift(1)

In [19]:
## We performed the shift in mde2
mde3

,consumer_price_index(CPI)_monthly,Crude Oil Price_monthly,Domestic Production_monthly,Crude Oil Export_monthly,Inflation_allItemsAverage_monthly,Money Supply(M2)_monthly,currency in circulation_monthly,bank reserves_monthly,netForeignAssets_monthly,netDomesticAssets_monthly,...,gdp_svc_Education_quarterly,gdp_svc_Human Health & Social Services_quarterly,gdp_svc_Other Services_quarterly,GDP at Current Basic Prices_quarterly,Net Taxes on Products_quarterly,GDP at Current Market Prices_quarterly,FR_Date,foreign_reserve_Gross(USD)_monthly,foreign_reserve_Liquid(USD)_monthly,date
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2017-01-31,NaN,NaN,2017-01-31
1,198.041241,55.01,1.84,1.39,16.44,23096526.55,1994577.62,3311609.44,9473002.48,19005647.02,...,NaN,NaN,NaN,NaN,NaN,NaN,2017-02-28,NaN,NaN,2017-02-28
2,201.001141,46.39,1.82,1.37,16.96,22210954.84,1978886.94,3234760.81,7977399.24,19746640.86,...,587.79,186.24,1237.68,26028.36,200.5,26228.85,2017-03-31,2.817423e+10,2.745703e+10,2017-03-31
3,204.456610,52.13,1.60,1.15,17.32,22304267.84,1983633.07,3309947.53,7628543.46,20342546.55,...,587.79,186.24,1237.68,26028.36,200.5,26228.85,2017-04-28,2.964668e+10,2.894094e+10,2017-04-30
4,207.729678,52.94,1.79,1.34,17.59,21768241.12,1975812.32,3536407.29,7269852.64,20347360.25,...,587.79,186.24,1237.68,26028.36,200.5,26228.85,2017-05-31,3.029795e+10,2.962647e+10,2017-05-31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2026-07-16,4.958097e+10,4.889970e+10,2026-08-31
116,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.145923e+10,5.081045e+10,2026-09-30
117,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.191564e+10,5.129593e+10,2026-10-31
118,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-11-30
119,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-12-31

In [20]:
mde3[['foreign_reserve_Gross(USD)_monthly','foreign_reserve_Liquid(USD)_monthly']]=mde3[['foreign_reserve_Gross(USD)_monthly','foreign_reserve_Liquid(USD)_monthly']].shift(-1)

In [21]:
mde3

,consumer_price_index(CPI)_monthly,Crude Oil Price_monthly,Domestic Production_monthly,Crude Oil Export_monthly,Inflation_allItemsAverage_monthly,Money Supply(M2)_monthly,currency in circulation_monthly,bank reserves_monthly,netForeignAssets_monthly,netDomesticAssets_monthly,...,gdp_svc_Education_quarterly,gdp_svc_Human Health & Social Services_quarterly,gdp_svc_Other Services_quarterly,GDP at Current Basic Prices_quarterly,Net Taxes on Products_quarterly,GDP at Current Market Prices_quarterly,FR_Date,foreign_reserve_Gross(USD)_monthly,foreign_reserve_Liquid(USD)_monthly,date
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2017-01-31,NaN,NaN,2017-01-31
1,198.041241,55.01,1.84,1.39,16.44,23096526.55,1994577.62,3311609.44,9473002.48,19005647.02,...,NaN,NaN,NaN,NaN,NaN,NaN,2017-02-28,2.817423e+10,2.745703e+10,2017-02-28
2,201.001141,46.39,1.82,1.37,16.96,22210954.84,1978886.94,3234760.81,7977399.24,19746640.86,...,587.79,186.24,1237.68,26028.36,200.5,26228.85,2017-03-31,2.964668e+10,2.894094e+10,2017-03-31
3,204.456610,52.13,1.60,1.15,17.32,22304267.84,1983633.07,3309947.53,7628543.46,20342546.55,...,587.79,186.24,1237.68,26028.36,200.5,26228.85,2017-04-28,3.029795e+10,2.962647e+10,2017-04-30
4,207.729678,52.94,1.79,1.34,17.59,21768241.12,1975812.32,3536407.29,7269852.64,20347360.25,...,587.79,186.24,1237.68,26028.36,200.5,26228.85,2017-05-31,3.086463e+10,3.017061e+10,2017-05-31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2026-07-16,5.145923e+10,5.081045e+10,2026-08-31
116,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.191564e+10,5.129593e+10,2026-09-30
117,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-10-31
118,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-11-30
119,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-12-31

We are now done with the macroeconomic variables. We will head over to the stock_data. We will start with the finance sector stock data.

In [22]:
fin_sec_data=pd.read_csv('feature_engineering/stocks_sectors/financial_services/financial_services_sector')

In [23]:
fin_sec_data

,date,sector,weighted_sector_returns,n_stocks_contributing,sector_index,sector_volume
0,2017-01-03,financial_services,0.000000,20.0,100.000000,48125518.0
1,2017-01-04,financial_services,0.353432,20.0,100.353432,26705191.0
2,2017-01-05,financial_services,-0.182223,20.0,100.170565,66991076.0
3,2017-01-06,financial_services,1.397196,20.0,101.570144,97521276.0
4,2017-01-09,financial_services,3.645896,20.0,105.273286,99013315.0
...,...,...,...,...,...,...
2258,2026-07-13,financial_services,-0.746327,35.0,2695.019313,290562049.0
2259,2026-07-14,financial_services,0.906947,35.0,2719.461701,163509442.0
2260,2026-07-15,financial_services,0.779799,35.0,2740.668037,258362267.0
2261,2026-07-16,financial_services,1.505893,35.0,2781.939574,261040578.0
2262,2026-07-17,financial_services,1.536021,35.0,2824.670764,295044834.0

In [24]:
fin_sec_data_clean=fin_sec_data.copy()

In [25]:
fin_sec_data_clean['sector_volume']=fin_sec_data_clean['sector_volume'].shift(1)

In [27]:
fin_sec_data_clean=fin_sec_data_clean.drop('sector',axis=1)

In [28]:
fin_sec_data_clean

,date,weighted_sector_returns,n_stocks_contributing,sector_index,sector_volume
0,2017-01-03,0.000000,20.0,100.000000,NaN
1,2017-01-04,0.353432,20.0,100.353432,48125518.0
2,2017-01-05,-0.182223,20.0,100.170565,26705191.0
3,2017-01-06,1.397196,20.0,101.570144,66991076.0
4,2017-01-09,3.645896,20.0,105.273286,97521276.0
...,...,...,...,...,...
2258,2026-07-13,-0.746327,35.0,2695.019313,242350071.0
2259,2026-07-14,0.906947,35.0,2719.461701,290562049.0
2260,2026-07-15,0.779799,35.0,2740.668037,163509442.0
2261,2026-07-16,1.505893,35.0,2781.939574,258362267.0
2262,2026-07-17,1.536021,35.0,2824.670764,261040578.0

In [29]:
fin_sec_data_clean=fin_sec_data_clean.dropna()

In [31]:
fin_sec_data_clean['date']=pd.to_datetime(fin_sec_data_clean['date'])

In [33]:
print(fin_sec_data_clean['date'].dtypes)

datetime64[us]

In [43]:
mde3["month"] = mde3["date"].dt.to_period("M")
fin_sec_data_clean["month"] = fin_sec_data_clean["date"].dt.to_period("M")

In [44]:
mde3

,consumer_price_index(CPI)_monthly,Crude Oil Price_monthly,Domestic Production_monthly,Crude Oil Export_monthly,Inflation_allItemsAverage_monthly,Money Supply(M2)_monthly,currency in circulation_monthly,bank reserves_monthly,netForeignAssets_monthly,netDomesticAssets_monthly,...,gdp_svc_Human Health & Social Services_quarterly,gdp_svc_Other Services_quarterly,GDP at Current Basic Prices_quarterly,Net Taxes on Products_quarterly,GDP at Current Market Prices_quarterly,FR_Date,foreign_reserve_Gross(USD)_monthly,foreign_reserve_Liquid(USD)_monthly,date,month
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,2017-01-31,NaN,NaN,2017-01-31,2017-01
1,198.041241,55.01,1.84,1.39,16.44,23096526.55,1994577.62,3311609.44,9473002.48,19005647.02,...,NaN,NaN,NaN,NaN,NaN,2017-02-28,2.817423e+10,2.745703e+10,2017-02-28,2017-02
2,201.001141,46.39,1.82,1.37,16.96,22210954.84,1978886.94,3234760.81,7977399.24,19746640.86,...,186.24,1237.68,26028.36,200.5,26228.85,2017-03-31,2.964668e+10,2.894094e+10,2017-03-31,2017-03
3,204.456610,52.13,1.60,1.15,17.32,22304267.84,1983633.07,3309947.53,7628543.46,20342546.55,...,186.24,1237.68,26028.36,200.5,26228.85,2017-04-28,3.029795e+10,2.962647e+10,2017-04-30,2017-04
4,207.729678,52.94,1.79,1.34,17.59,21768241.12,1975812.32,3536407.29,7269852.64,20347360.25,...,186.24,1237.68,26028.36,200.5,26228.85,2017-05-31,3.086463e+10,3.017061e+10,2017-05-31,2017-05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,2026-07-16,5.145923e+10,5.081045e+10,2026-08-31,2026-08
116,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,5.191564e+10,5.129593e+10,2026-09-30,2026-09
117,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-10-31,2026-10
118,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-11-30,2026-11
119,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-12-31,2026-12

In [45]:
fin_sec_data_clean

,date,weighted_sector_returns,n_stocks_contributing,sector_index,sector_volume,month
1,2017-01-04,0.353432,20.0,100.353432,48125518.0,2017-01
2,2017-01-05,-0.182223,20.0,100.170565,26705191.0,2017-01
3,2017-01-06,1.397196,20.0,101.570144,66991076.0,2017-01
4,2017-01-09,3.645896,20.0,105.273286,97521276.0,2017-01
5,2017-01-10,-1.454119,20.0,103.742486,99013315.0,2017-01
...,...,...,...,...,...,...
2258,2026-07-13,-0.746327,35.0,2695.019313,242350071.0,2026-07
2259,2026-07-14,0.906947,35.0,2719.461701,290562049.0,2026-07
2260,2026-07-15,0.779799,35.0,2740.668037,163509442.0,2026-07
2261,2026-07-16,1.505893,35.0,2781.939574,258362267.0,2026-07
2262,2026-07-17,1.536021,35.0,2824.670764,261040578.0,2026-07

In [46]:
## Get last day of the month
fin_sec_monthly = (
    fin_sec_data_clean
    .sort_values("date")
    .groupby("month")
    .last()
    .reset_index()
)

In [47]:
fin_sec_monthly

,month,date,weighted_sector_returns,n_stocks_contributing,sector_index,sector_volume
0,2017-01,2017-01-31,-0.996463,20.0,109.001843,87259637.0
1,2017-02,2017-02-28,0.649545,21.0,107.626307,169938472.0
2,2017-03,2017-03-31,-0.017945,21.0,105.456849,141367620.0
3,2017-04,2017-04-28,1.815887,20.0,115.418966,120760980.0
4,2017-05,2017-05-31,-2.338342,21.0,138.127184,261656035.0
...,...,...,...,...,...,...
110,2026-03,2026-03-31,-1.878773,35.0,2347.696835,294022203.0
111,2026-04,2026-04-30,1.404651,35.0,2856.819058,809264585.0
112,2026-05,2026-05-29,-0.883768,35.0,2959.843133,341760831.0
113,2026-06,2026-06-30,-1.000082,35.0,2664.183854,480278073.0
114,2026-07,2026-07-17,1.536021,35.0,2824.670764,261040578.0

In [48]:
## We will merge based on the month
fin_sector_merged = mde3.merge(
    fin_sec_monthly.drop(columns="date"),
    on="month",
    how="left"
)

In [49]:
fin_sector_merged

,consumer_price_index(CPI)_monthly,Crude Oil Price_monthly,Domestic Production_monthly,Crude Oil Export_monthly,Inflation_allItemsAverage_monthly,Money Supply(M2)_monthly,currency in circulation_monthly,bank reserves_monthly,netForeignAssets_monthly,netDomesticAssets_monthly,...,GDP at Current Market Prices_quarterly,FR_Date,foreign_reserve_Gross(USD)_monthly,foreign_reserve_Liquid(USD)_monthly,date,month,weighted_sector_returns,n_stocks_contributing,sector_index,sector_volume
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,2017-01-31,NaN,NaN,2017-01-31,2017-01,-0.996463,20.0,109.001843,87259637.0
1,198.041241,55.01,1.84,1.39,16.44,23096526.55,1994577.62,3311609.44,9473002.48,19005647.02,...,NaN,2017-02-28,2.817423e+10,2.745703e+10,2017-02-28,2017-02,0.649545,21.0,107.626307,169938472.0
2,201.001141,46.39,1.82,1.37,16.96,22210954.84,1978886.94,3234760.81,7977399.24,19746640.86,...,26228.85,2017-03-31,2.964668e+10,2.894094e+10,2017-03-31,2017-03,-0.017945,21.0,105.456849,141367620.0
3,204.456610,52.13,1.60,1.15,17.32,22304267.84,1983633.07,3309947.53,7628543.46,20342546.55,...,26228.85,2017-04-28,3.029795e+10,2.962647e+10,2017-04-30,2017-04,1.815887,20.0,115.418966,120760980.0
4,207.729678,52.94,1.79,1.34,17.59,21768241.12,1975812.32,3536407.29,7269852.64,20347360.25,...,26228.85,2017-05-31,3.086463e+10,3.017061e+10,2017-05-31,2017-05,-2.338342,21.0,138.127184,261656035.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,2026-07-16,5.145923e+10,5.081045e+10,2026-08-31,2026-08,NaN,NaN,NaN,NaN
116,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,5.191564e+10,5.129593e+10,2026-09-30,2026-09,NaN,NaN,NaN,NaN
117,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2026-10-31,2026-10,NaN,NaN,NaN,NaN
118,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2026-11-30,2026-11,NaN,NaN,NaN,NaN
119,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2026-12-31,2026-12,NaN,NaN,NaN,NaN

In [50]:
fin_sector_merged=fin_sector_merged.dropna()

In [51]:
fin_sector_merged

,consumer_price_index(CPI)_monthly,Crude Oil Price_monthly,Domestic Production_monthly,Crude Oil Export_monthly,Inflation_allItemsAverage_monthly,Money Supply(M2)_monthly,currency in circulation_monthly,bank reserves_monthly,netForeignAssets_monthly,netDomesticAssets_monthly,...,GDP at Current Market Prices_quarterly,FR_Date,foreign_reserve_Gross(USD)_monthly,foreign_reserve_Liquid(USD)_monthly,date,month,weighted_sector_returns,n_stocks_contributing,sector_index,sector_volume
2,201.001141,46.39,1.82,1.37,16.96,2.221095e+07,1978886.94,3234760.81,7977399.24,1.974664e+07,...,26228.850000,2017-03-31,2.964668e+10,2.894094e+10,2017-03-31,2017-03,-0.017945,21.0,105.456849,141367620.0
3,204.456610,52.13,1.60,1.15,17.32,2.230427e+07,1983633.07,3309947.53,7628543.46,2.034255e+07,...,26228.850000,2017-04-28,3.029795e+10,2.962647e+10,2017-04-30,2017-04,1.815887,20.0,115.418966,120760980.0
4,207.729678,52.94,1.79,1.34,17.59,2.176824e+07,1975812.32,3536407.29,7269852.64,2.034736e+07,...,26228.850000,2017-05-31,3.086463e+10,3.017061e+10,2017-05-31,2017-05,-2.338342,21.0,138.127184,261656035.0
5,211.637809,50.57,1.87,1.42,17.63,2.204777e+07,1897917.15,3254006.25,8540084.49,1.949923e+07,...,27266.390000,2017-06-30,3.032964e+10,2.961376e+10,2017-06-30,2017-06,-0.251046,21.0,162.591431,236727857.0
6,214.982456,47.42,1.95,1.50,17.58,2.198058e+07,1873544.00,3256863.20,8468080.62,1.985120e+07,...,27266.390000,2017-07-31,3.028841e+10,2.957675e+10,2017-07-31,2017-07,-3.410985,21.0,183.041162,130494807.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
108,917.368816,68.05,1.46,1.01,23.01,1.244002e+08,5732860.29,32035734.52,31505596.33,9.290425e+07,...,126032.267589,2025-12-31,4.466827e+10,4.411119e+10,2026-01-31,2026-01,-0.149558,35.0,1998.576704,254593845.0
109,890.956254,68.05,1.46,1.01,21.97,1.239393e+08,5731116.60,30254995.23,27085821.33,9.686314e+07,...,126032.267589,2026-01-30,4.550244e+10,4.493857e+10,2026-02-28,2026-02,0.000000,35.0,2364.419520,383962151.0
110,908.860705,72.33,1.31,0.86,21.03,1.231071e+08,5709846.43,32744055.08,25569115.78,9.754761e+07,...,113186.870120,2026-02-27,4.627990e+10,4.572994e+10,2026-03-31,2026-03,-1.878773,35.0,2347.696835,294022203.0
111,946.869623,106.09,1.38,0.93,20.05,1.249763e+08,5646391.19,34603460.67,24014048.35,1.009719e+08,...,113186.870120,2026-03-31,4.969398e+10,4.899603e+10,2026-04-30,2026-04,1.404651,35.0,2856.819058,809264585.0
112,967.050171,126.71,1.49,1.04,19.16,1.249763e+08,5646391.19,34603460.67,24014048.35,1.009719e+08,...,113186.870120,2026-04-30,4.923846e+10,4.849418e+10,2026-05-31,2026-05,-0.883768,35.0,2959.843133,341760831.0

In [53]:
## remove unuseful columns
fin_sector_merged_clean=fin_sector_merged.drop(columns=['date','month'])

In [54]:
fin_sector_merged_clean

,consumer_price_index(CPI)_monthly,Crude Oil Price_monthly,Domestic Production_monthly,Crude Oil Export_monthly,Inflation_allItemsAverage_monthly,Money Supply(M2)_monthly,currency in circulation_monthly,bank reserves_monthly,netForeignAssets_monthly,netDomesticAssets_monthly,...,GDP at Current Basic Prices_quarterly,Net Taxes on Products_quarterly,GDP at Current Market Prices_quarterly,FR_Date,foreign_reserve_Gross(USD)_monthly,foreign_reserve_Liquid(USD)_monthly,weighted_sector_returns,n_stocks_contributing,sector_index,sector_volume
2,201.001141,46.39,1.82,1.37,16.96,2.221095e+07,1978886.94,3234760.81,7977399.24,1.974664e+07,...,26028.360000,200.500000,26228.850000,2017-03-31,2.964668e+10,2.894094e+10,-0.017945,21.0,105.456849,141367620.0
3,204.456610,52.13,1.60,1.15,17.32,2.230427e+07,1983633.07,3309947.53,7628543.46,2.034255e+07,...,26028.360000,200.500000,26228.850000,2017-04-28,3.029795e+10,2.962647e+10,1.815887,20.0,115.418966,120760980.0
4,207.729678,52.94,1.79,1.34,17.59,2.176824e+07,1975812.32,3536407.29,7269852.64,2.034736e+07,...,26028.360000,200.500000,26228.850000,2017-05-31,3.086463e+10,3.017061e+10,-2.338342,21.0,138.127184,261656035.0
5,211.637809,50.57,1.87,1.42,17.63,2.204777e+07,1897917.15,3254006.25,8540084.49,1.949923e+07,...,27030.250000,236.140000,27266.390000,2017-06-30,3.032964e+10,2.961376e+10,-0.251046,21.0,162.591431,236727857.0
6,214.982456,47.42,1.95,1.50,17.58,2.198058e+07,1873544.00,3256863.20,8468080.62,1.985120e+07,...,27030.250000,236.140000,27266.390000,2017-07-31,3.028841e+10,2.957675e+10,-3.410985,21.0,183.041162,130494807.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
108,917.368816,68.05,1.46,1.01,23.01,1.244002e+08,5732860.29,32035734.52,31505596.33,9.290425e+07,...,122810.658960,3221.608629,126032.267589,2025-12-31,4.466827e+10,4.411119e+10,-0.149558,35.0,1998.576704,254593845.0
109,890.956254,68.05,1.46,1.01,21.97,1.239393e+08,5731116.60,30254995.23,27085821.33,9.686314e+07,...,122810.658960,3221.608629,126032.267589,2026-01-30,4.550244e+10,4.493857e+10,0.000000,35.0,2364.419520,383962151.0
110,908.860705,72.33,1.31,0.86,21.03,1.231071e+08,5709846.43,32744055.08,25569115.78,9.754761e+07,...,110786.347011,2400.523110,113186.870120,2026-02-27,4.627990e+10,4.572994e+10,-1.878773,35.0,2347.696835,294022203.0
111,946.869623,106.09,1.38,0.93,20.05,1.249763e+08,5646391.19,34603460.67,24014048.35,1.009719e+08,...,110786.347011,2400.523110,113186.870120,2026-03-31,4.969398e+10,4.899603e+10,1.404651,35.0,2856.819058,809264585.0
112,967.050171,126.71,1.49,1.04,19.16,1.249763e+08,5646391.19,34603460.67,24014048.35,1.009719e+08,...,110786.347011,2400.523110,113186.870120,2026-04-30,4.923846e+10,4.849418e+10,-0.883768,35.0,2959.843133,341760831.0

SOmething is wrong with the weighted sector returns. It has to be the monthly difference not the daily difference. WE HAVE WORK TO DO. We will use the sector_index to get these values. ((new-old)/old) * 100

In [55]:
fin_sector_merged_clean['new_monthly_returns']=fin_sector_merged_clean['sector_index'].pct_change()*100

In [56]:
fin_sector_merged_clean

,consumer_price_index(CPI)_monthly,Crude Oil Price_monthly,Domestic Production_monthly,Crude Oil Export_monthly,Inflation_allItemsAverage_monthly,Money Supply(M2)_monthly,currency in circulation_monthly,bank reserves_monthly,netForeignAssets_monthly,netDomesticAssets_monthly,...,Net Taxes on Products_quarterly,GDP at Current Market Prices_quarterly,FR_Date,foreign_reserve_Gross(USD)_monthly,foreign_reserve_Liquid(USD)_monthly,weighted_sector_returns,n_stocks_contributing,sector_index,sector_volume,new_monthly_returns
2,201.001141,46.39,1.82,1.37,16.96,2.221095e+07,1978886.94,3234760.81,7977399.24,1.974664e+07,...,200.500000,26228.850000,2017-03-31,2.964668e+10,2.894094e+10,-0.017945,21.0,105.456849,141367620.0,NaN
3,204.456610,52.13,1.60,1.15,17.32,2.230427e+07,1983633.07,3309947.53,7628543.46,2.034255e+07,...,200.500000,26228.850000,2017-04-28,3.029795e+10,2.962647e+10,1.815887,20.0,115.418966,120760980.0,9.446628
4,207.729678,52.94,1.79,1.34,17.59,2.176824e+07,1975812.32,3536407.29,7269852.64,2.034736e+07,...,200.500000,26228.850000,2017-05-31,3.086463e+10,3.017061e+10,-2.338342,21.0,138.127184,261656035.0,19.674598
5,211.637809,50.57,1.87,1.42,17.63,2.204777e+07,1897917.15,3254006.25,8540084.49,1.949923e+07,...,236.140000,27266.390000,2017-06-30,3.032964e+10,2.961376e+10,-0.251046,21.0,162.591431,236727857.0,17.711392
6,214.982456,47.42,1.95,1.50,17.58,2.198058e+07,1873544.00,3256863.20,8468080.62,1.985120e+07,...,236.140000,27266.390000,2017-07-31,3.028841e+10,2.957675e+10,-3.410985,21.0,183.041162,130494807.0,12.577373
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
108,917.368816,68.05,1.46,1.01,23.01,1.244002e+08,5732860.29,32035734.52,31505596.33,9.290425e+07,...,3221.608629,126032.267589,2025-12-31,4.466827e+10,4.411119e+10,-0.149558,35.0,1998.576704,254593845.0,10.900821
109,890.956254,68.05,1.46,1.01,21.97,1.239393e+08,5731116.60,30254995.23,27085821.33,9.686314e+07,...,3221.608629,126032.267589,2026-01-30,4.550244e+10,4.493857e+10,0.000000,35.0,2364.419520,383962151.0,18.305168
110,908.860705,72.33,1.31,0.86,21.03,1.231071e+08,5709846.43,32744055.08,25569115.78,9.754761e+07,...,2400.523110,113186.870120,2026-02-27,4.627990e+10,4.572994e+10,-1.878773,35.0,2347.696835,294022203.0,-0.707264
111,946.869623,106.09,1.38,0.93,20.05,1.249763e+08,5646391.19,34603460.67,24014048.35,1.009719e+08,...,2400.523110,113186.870120,2026-03-31,4.969398e+10,4.899603e+10,1.404651,35.0,2856.819058,809264585.0,21.686029
112,967.050171,126.71,1.49,1.04,19.16,1.249763e+08,5646391.19,34603460.67,24014048.35,1.009719e+08,...,2400.523110,113186.870120,2026-04-30,4.923846e+10,4.849418e+10,-0.883768,35.0,2959.843133,341760831.0,3.606251