## TRAINING AND TESTING

We will do all training and testing here.

In [39]:
import pandas as pd
import pandas_ta as ta
import numpy as np
import os
import datetime as dt

In [40]:
import pandas as pd

finance_sector_df=pd.read_csv('feature_engineering/stocks_sectors/financial_services/financial_services_sector')

In [41]:
finance_sector_df.head()

,date,sector,weighted_sector_returns,n_stocks_contributing,sector_index,sector_volume
0,2017-01-03,financial_services,0.000000,20.0,100.000000,48125518.0
1,2017-01-04,financial_services,0.353432,20.0,100.353432,26705191.0
2,2017-01-05,financial_services,-0.182223,20.0,100.170565,66991076.0
3,2017-01-06,financial_services,1.397196,20.0,101.570144,97521276.0
4,2017-01-09,financial_services,3.645896,20.0,105.273286,99013315.0

In [42]:
finance_sector_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2263 entries, 0 to 2262
Data columns (total 6 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   date                     2263 non-null   str
 1   sector                   2263 non-null   str
 2   weighted_sector_returns  2263 non-null   float64
 3   n_stocks_contributing    2263 non-null   float64
 4   sector_index             2263 non-null   float64
 5   sector_volume            2263 non-null   float64
dtypes: float64(4), str(2)
memory usage: 106.2 KB

In [43]:
finance_sector_df['date']=pd.to_datetime(finance_sector_df['date'], format='%Y-%m-%d', errors='coerce')

In [44]:
finance_sector_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2263 entries, 0 to 2262
Data columns (total 6 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   date                     2263 non-null   datetime64[us]
 1   sector                   2263 non-null   str
 2   weighted_sector_returns  2263 non-null   float64
 3   n_stocks_contributing    2263 non-null   float64
 4   sector_index             2263 non-null   float64
 5   sector_volume            2263 non-null   float64
dtypes: datetime64[us](1), float64(4), str(1)
memory usage: 106.2 KB

In [45]:
macro_eco_data=pd.read_csv('macroeconomic_data/populated_cleaned_macro_data')

In [46]:
macro_eco_data.head()

,Quarter,Month,Date,consumer_price_index(CPI)_monthly,Crude Oil Price_monthly,Domestic Production_monthly,Crude Oil Export_monthly,Inflation_allItemsAverage_monthly,Money Supply(M2)_monthly,currency in circulation_monthly,...,gdp_svc_Other Services_quarterly,GDP at Current Basic Prices_quarterly,Net Taxes on Products_quarterly,GDP at Current Market Prices_quarterly,foreign_reserve_Gross(USD)_monthly,foreign_reserve_Liquid(USD)_monthly,Year,Month_idx,foreign_reserve_gross(USD)_daily,foreign_reserve_liquid(USD)_daily
0,Q2,April,2017-04-03,204.45661,52.13,1.6,1.15,17.32,22304267.84,1983633.07,...,1237.68,26028.36,200.5,26228.85,3.029795e+10,2.962647e+10,2017,4,3.030715e+10,2.963927e+10
1,Q2,April,2017-04-04,204.45661,52.13,1.6,1.15,17.32,22304267.84,1983633.07,...,1237.68,26028.36,200.5,26228.85,3.029795e+10,2.962647e+10,2017,4,3.031831e+10,2.965163e+10
2,Q2,April,2017-04-05,204.45661,52.13,1.6,1.15,17.32,22304267.84,1983633.07,...,1237.68,26028.36,200.5,26228.85,3.029795e+10,2.962647e+10,2017,4,3.032576e+10,2.966022e+10
3,Q2,April,2017-04-06,204.45661,52.13,1.6,1.15,17.32,22304267.84,1983633.07,...,1237.68,26028.36,200.5,26228.85,3.029795e+10,2.962647e+10,2017,4,3.034555e+10,2.968121e+10
4,Q2,April,2017-04-07,204.45661,52.13,1.6,1.15,17.32,22304267.84,1983633.07,...,1237.68,26028.36,200.5,26228.85,3.029795e+10,2.962647e+10,2017,4,3.036654e+10,2.970295e+10

In [47]:
macro_eco_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 2257 entries, 0 to 2256
Data columns (total 84 columns):
 #   Column                                                                      Non-Null Count  Dtype
---  ------                                                                      --------------  -----
 0   Quarter                                                                     2257 non-null   str
 1   Month                                                                       2257 non-null   str
 2   Date                                                                        2257 non-null   str
 3   consumer_price_index(CPI)_monthly                                           2257 non-null   float64
 4   Crude Oil Price_monthly                                                     2257 non-null   float64
 5   Domestic Production_monthly                                                 2257 non-null   float64
 6   Crude Oil Export_monthly                                                    2257 non-null   float64
 7   Inflation_allItemsAverage_monthly                                           2257 non-null   float64
 8   Money Supply(M2)_monthly                                                    2257 non-null   float64
 9   currency in circulation_monthly                                             2257 non-null   float64
 10  bank reserves_monthly                                                       2257 non-null   float64
 11  netForeignAssets_monthly                                                    2257 non-null   float64
 12  netDomesticAssets_monthly                                                   2257 non-null   float64
 13  netDomesticCredit_monthly                                                   2257 non-null   float64
 14  creditToGovernment_monthly                                                  2257 non-null   float64
 15  creditToPrivateSector_monthly                                               2257 non-null   float64
 16  MonetaryPolicyRate_monthly                                                  2257 non-null   float64
 17  TreasuryBillRate_monthly                                                    2257 non-null   float64
 18  Lending_Rate_monthly                                                        2257 non-null   float64
 19  Exchange_Rate(USD-EOP)_monthly                                              2257 non-null   float64
 20  Premium_Motor_Spirit(PMS)_monthly                                           2257 non-null   float64
 21  A. GDP_AGRICULTURE(agric)_quarterly                                         2257 non-null   float64
 22  gdp_agric_Crop Production_quarterly                                         2257 non-null   float64
 23  gdp_agric_Livestock_quarterly                                               2257 non-null   float64
 24  gdp_agric_Forestry_quarterly                                                2257 non-null   float64
 25   gdp_Fishing_quarterly                                                      2257 non-null   float64
 26  GDP_INDUSTRY(ind)_quarterly                                                 2257 non-null   float64
 27  gdp_ind_Mining and Quarrying(MQ)_quarterly                                  2257 non-null   float64
 28  gdp_ind_MQ_Crude Petroleum and Natural Gas_quarterly                        2257 non-null   float64
 29  gdp_ind_MQ_Coal Mining_quarterly                                            2257 non-null   float64
 30  gdp_ind_MQ_Metal Ores_quarterly                                             2257 non-null   float64
 31  gdp_ind_MQ_Quarrying and Other Minerals_quarterly                           2257 non-null   float64
 32  gdp_ind_Manufacturing(mfg)_quarterly                                        2257 non-null   float64
 33   gdp_ind_mfg_Oil Refining_quarterly                                         2257 non-null   float64
 34  gdp_ind_mfg_Cement_quarterly                                                2257 non-null   float64
 35  gdp_ind_mfg_Food, Beverage and Tobacco_quarterly                            2257 non-null   float64
 36  gdp_ind_mfg_Textile, Apparel and Footwear_quarterly                         2257 non-null   float64
 37  gdp_ind_mfg_Wood and Wood Products_quarterly                                2257 non-null   float64
 38  gdp_ind_mfg_Pulp, Paper and Paper Products_quarterly                        2257 non-null   float64
 39  gdp_ind_mfg_Chemical and Pharmaceutical Products_quarterly                  2257 non-null   float64
 40  gdp_ind_mfg_Non-Metallic Products_quarterly                                 2257 non-null   float64
 41  gdp_ind_mfg_Plastic and Rubber Products_quarterly                           2257 non-null   float64
 42  gdp_ind_mfg_Electrical and Electronics_quarterly                            2257 non-null   float64
 43  gdp_ind_mfg_Basic Metal, Iron and Steel_quarterly                           2257 non-null   float64
 44  gdp_ind_mfg_Motor Vehicles and Assembly_quarterly                           2257 non-null   float64
 45  gdp_ind_mfg_Other Manufacturing_quarterly                                   2257 non-null   float64
 46  gdp_ind_Electricity, Gas, Steam & Air conditioner_quarterly                 2257 non-null   float64
 47  gdp_ind_Water supply, Sewage, Waste Management_quarterly                    2257 non-null   float64
 48  gdp_ind_Construction_quarterly                                              2257 non-null   float64
 49  GDP_SERVICES(svc)_quarterly                                                 2257 non-null   float64
 50  gdp_svc_Trade_quarterly                                                     2257 non-null   float64
 51  gdp_svc_Accommodation and Food Services_quarterly                           2257 non-null   float64
 52  gdp_svc_Transportation and Storage(TS)_quarterly                            2257 non-null   float64
 53  gdp_svc_TS_RoadTransport_quarterly                                          2257 non-null   float64
 54  gdp_svc_TS_Rail Transport & Pipelines_quarterly                             2257 non-null   float64
 55  gdp_svc_TS_Water Transport_quarterly                                        2257 non-null   float64
 56  gdp_svc_TS_Air Transport_quarterly                                          2257 non-null   float64
 57  gdp_svc_TS_Transport Services_quarterly                                     2257 non-null   float64
 58  gdp_svc_TS_Post and Courier Services_quarterly                              2257 non-null   float64
 59  gdp_svc_Information and Communication(IC)_quarterly                         2257 non-null   float64
 60  gdp_svc_IC_Telecommunications and Information Services_quarterly            2257 non-null   float64
 61  gdp_svc_IC_Publishing_quarterly                                             2257 non-null   float64
 62  gdp_svc_IC_Motion Pictures, Sound Recording and Music Production_quarterly  2257 non-null   float64
 63  gdp_svc_IC_Broadcasting_quarterly                                           2257 non-null   float64
 64  gdp_svc_Arts, Entertainment & Recreation_quarterly                          2257 non-null   float64
 65  gdp_svc_Financial and Insurance(FI)_quarterly                               2257 non-null   float64
 66  gdp_svc_FI_Financial Institutions_quarterly                                 2257 non-null   float64
 67  gdp_svc_FI_Insurance_quarterly                                              2257 non-null   float64
 68  gdp_svc_Real Estate_quarterly                                               2257 non-null   float64
 69  gdp_svc_Professional, Scientific & Technical Services_quarterly             2257 non-null   float64
 70  gdp_svc_Administrative and Support Services_quarterly                       2257 non-null   float64
 71  gdp_svc_Public Administration_quarterly                                     2257 non-null   float64
 72  gdp_svc_Education_quarterly                                                 2257 non-null   float64
 73  gdp_svc_Human Health & Social Services_quarterly                            2257 non-null   float64
 74  gdp_svc_Other Services_quarterly                                            2257 non-null   float64
 75  GDP at Current Basic Prices_quarterly                                       2257 non-null   float64
 76  Net Taxes on Products_quarterly                                             2257 non-null   float64
 77  GDP at Current Market Prices_quarterly                                      2257 non-null   float64
 78  foreign_reserve_Gross(USD)_monthly                                          2257 non-null   float64
 79  foreign_reserve_Liquid(USD)_monthly                                         2257 non-null   float64
 80  Year                                                                        2257 non-null   int64
 81  Month_idx                                                                   2257 non-null   int64
 82  foreign_reserve_gross(USD)_daily                                            2257 non-null   float64
 83  foreign_reserve_liquid(USD)_daily                                           2257 non-null   float64
dtypes: float64(79), int64(2), str(3)
memory usage: 1.4 MB

In [48]:
macro_eco_data['Date']=pd.to_datetime(macro_eco_data['Date'], format='%Y-%m-%d', errors="coerce")

In [49]:
macro_eco_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 2257 entries, 0 to 2256
Data columns (total 84 columns):
 #   Column                                                                      Non-Null Count  Dtype
---  ------                                                                      --------------  -----
 0   Quarter                                                                     2257 non-null   str
 1   Month                                                                       2257 non-null   str
 2   Date                                                                        2257 non-null   datetime64[us]
 3   consumer_price_index(CPI)_monthly                                           2257 non-null   float64
 4   Crude Oil Price_monthly                                                     2257 non-null   float64
 5   Domestic Production_monthly                                                 2257 non-null   float64
 6   Crude Oil Export_monthly                                                    2257 non-null   float64
 7   Inflation_allItemsAverage_monthly                                           2257 non-null   float64
 8   Money Supply(M2)_monthly                                                    2257 non-null   float64
 9   currency in circulation_monthly                                             2257 non-null   float64
 10  bank reserves_monthly                                                       2257 non-null   float64
 11  netForeignAssets_monthly                                                    2257 non-null   float64
 12  netDomesticAssets_monthly                                                   2257 non-null   float64
 13  netDomesticCredit_monthly                                                   2257 non-null   float64
 14  creditToGovernment_monthly                                                  2257 non-null   float64
 15  creditToPrivateSector_monthly                                               2257 non-null   float64
 16  MonetaryPolicyRate_monthly                                                  2257 non-null   float64
 17  TreasuryBillRate_monthly                                                    2257 non-null   float64
 18  Lending_Rate_monthly                                                        2257 non-null   float64
 19  Exchange_Rate(USD-EOP)_monthly                                              2257 non-null   float64
 20  Premium_Motor_Spirit(PMS)_monthly                                           2257 non-null   float64
 21  A. GDP_AGRICULTURE(agric)_quarterly                                         2257 non-null   float64
 22  gdp_agric_Crop Production_quarterly                                         2257 non-null   float64
 23  gdp_agric_Livestock_quarterly                                               2257 non-null   float64
 24  gdp_agric_Forestry_quarterly                                                2257 non-null   float64
 25   gdp_Fishing_quarterly                                                      2257 non-null   float64
 26  GDP_INDUSTRY(ind)_quarterly                                                 2257 non-null   float64
 27  gdp_ind_Mining and Quarrying(MQ)_quarterly                                  2257 non-null   float64
 28  gdp_ind_MQ_Crude Petroleum and Natural Gas_quarterly                        2257 non-null   float64
 29  gdp_ind_MQ_Coal Mining_quarterly                                            2257 non-null   float64
 30  gdp_ind_MQ_Metal Ores_quarterly                                             2257 non-null   float64
 31  gdp_ind_MQ_Quarrying and Other Minerals_quarterly                           2257 non-null   float64
 32  gdp_ind_Manufacturing(mfg)_quarterly                                        2257 non-null   float64
 33   gdp_ind_mfg_Oil Refining_quarterly                                         2257 non-null   float64
 34  gdp_ind_mfg_Cement_quarterly                                                2257 non-null   float64
 35  gdp_ind_mfg_Food, Beverage and Tobacco_quarterly                            2257 non-null   float64
 36  gdp_ind_mfg_Textile, Apparel and Footwear_quarterly                         2257 non-null   float64
 37  gdp_ind_mfg_Wood and Wood Products_quarterly                                2257 non-null   float64
 38  gdp_ind_mfg_Pulp, Paper and Paper Products_quarterly                        2257 non-null   float64
 39  gdp_ind_mfg_Chemical and Pharmaceutical Products_quarterly                  2257 non-null   float64
 40  gdp_ind_mfg_Non-Metallic Products_quarterly                                 2257 non-null   float64
 41  gdp_ind_mfg_Plastic and Rubber Products_quarterly                           2257 non-null   float64
 42  gdp_ind_mfg_Electrical and Electronics_quarterly                            2257 non-null   float64
 43  gdp_ind_mfg_Basic Metal, Iron and Steel_quarterly                           2257 non-null   float64
 44  gdp_ind_mfg_Motor Vehicles and Assembly_quarterly                           2257 non-null   float64
 45  gdp_ind_mfg_Other Manufacturing_quarterly                                   2257 non-null   float64
 46  gdp_ind_Electricity, Gas, Steam & Air conditioner_quarterly                 2257 non-null   float64
 47  gdp_ind_Water supply, Sewage, Waste Management_quarterly                    2257 non-null   float64
 48  gdp_ind_Construction_quarterly                                              2257 non-null   float64
 49  GDP_SERVICES(svc)_quarterly                                                 2257 non-null   float64
 50  gdp_svc_Trade_quarterly                                                     2257 non-null   float64
 51  gdp_svc_Accommodation and Food Services_quarterly                           2257 non-null   float64
 52  gdp_svc_Transportation and Storage(TS)_quarterly                            2257 non-null   float64
 53  gdp_svc_TS_RoadTransport_quarterly                                          2257 non-null   float64
 54  gdp_svc_TS_Rail Transport & Pipelines_quarterly                             2257 non-null   float64
 55  gdp_svc_TS_Water Transport_quarterly                                        2257 non-null   float64
 56  gdp_svc_TS_Air Transport_quarterly                                          2257 non-null   float64
 57  gdp_svc_TS_Transport Services_quarterly                                     2257 non-null   float64
 58  gdp_svc_TS_Post and Courier Services_quarterly                              2257 non-null   float64
 59  gdp_svc_Information and Communication(IC)_quarterly                         2257 non-null   float64
 60  gdp_svc_IC_Telecommunications and Information Services_quarterly            2257 non-null   float64
 61  gdp_svc_IC_Publishing_quarterly                                             2257 non-null   float64
 62  gdp_svc_IC_Motion Pictures, Sound Recording and Music Production_quarterly  2257 non-null   float64
 63  gdp_svc_IC_Broadcasting_quarterly                                           2257 non-null   float64
 64  gdp_svc_Arts, Entertainment & Recreation_quarterly                          2257 non-null   float64
 65  gdp_svc_Financial and Insurance(FI)_quarterly                               2257 non-null   float64
 66  gdp_svc_FI_Financial Institutions_quarterly                                 2257 non-null   float64
 67  gdp_svc_FI_Insurance_quarterly                                              2257 non-null   float64
 68  gdp_svc_Real Estate_quarterly                                               2257 non-null   float64
 69  gdp_svc_Professional, Scientific & Technical Services_quarterly             2257 non-null   float64
 70  gdp_svc_Administrative and Support Services_quarterly                       2257 non-null   float64
 71  gdp_svc_Public Administration_quarterly                                     2257 non-null   float64
 72  gdp_svc_Education_quarterly                                                 2257 non-null   float64
 73  gdp_svc_Human Health & Social Services_quarterly                            2257 non-null   float64
 74  gdp_svc_Other Services_quarterly                                            2257 non-null   float64
 75  GDP at Current Basic Prices_quarterly                                       2257 non-null   float64
 76  Net Taxes on Products_quarterly                                             2257 non-null   float64
 77  GDP at Current Market Prices_quarterly                                      2257 non-null   float64
 78  foreign_reserve_Gross(USD)_monthly                                          2257 non-null   float64
 79  foreign_reserve_Liquid(USD)_monthly                                         2257 non-null   float64
 80  Year                                                                        2257 non-null   int64
 81  Month_idx                                                                   2257 non-null   int64
 82  foreign_reserve_gross(USD)_daily                                            2257 non-null   float64
 83  foreign_reserve_liquid(USD)_daily                                           2257 non-null   float64
dtypes: datetime64[us](1), float64(79), int64(2), str(2)
memory usage: 1.4 MB

In [50]:
macro_eco_data = macro_eco_data.rename(columns={"Date": "date"})

In [51]:
macro_eco_data.head()

,Quarter,Month,date,consumer_price_index(CPI)_monthly,Crude Oil Price_monthly,Domestic Production_monthly,Crude Oil Export_monthly,Inflation_allItemsAverage_monthly,Money Supply(M2)_monthly,currency in circulation_monthly,...,gdp_svc_Other Services_quarterly,GDP at Current Basic Prices_quarterly,Net Taxes on Products_quarterly,GDP at Current Market Prices_quarterly,foreign_reserve_Gross(USD)_monthly,foreign_reserve_Liquid(USD)_monthly,Year,Month_idx,foreign_reserve_gross(USD)_daily,foreign_reserve_liquid(USD)_daily
0,Q2,April,2017-04-03,204.45661,52.13,1.6,1.15,17.32,22304267.84,1983633.07,...,1237.68,26028.36,200.5,26228.85,3.029795e+10,2.962647e+10,2017,4,3.030715e+10,2.963927e+10
1,Q2,April,2017-04-04,204.45661,52.13,1.6,1.15,17.32,22304267.84,1983633.07,...,1237.68,26028.36,200.5,26228.85,3.029795e+10,2.962647e+10,2017,4,3.031831e+10,2.965163e+10
2,Q2,April,2017-04-05,204.45661,52.13,1.6,1.15,17.32,22304267.84,1983633.07,...,1237.68,26028.36,200.5,26228.85,3.029795e+10,2.962647e+10,2017,4,3.032576e+10,2.966022e+10
3,Q2,April,2017-04-06,204.45661,52.13,1.6,1.15,17.32,22304267.84,1983633.07,...,1237.68,26028.36,200.5,26228.85,3.029795e+10,2.962647e+10,2017,4,3.034555e+10,2.968121e+10
4,Q2,April,2017-04-07,204.45661,52.13,1.6,1.15,17.32,22304267.84,1983633.07,...,1237.68,26028.36,200.5,26228.85,3.029795e+10,2.962647e+10,2017,4,3.036654e+10,2.970295e+10

LET US WORK WITHOUT ANY LAGGING AT FIRST

In [52]:
## Lets merge the data 

finance_sector_ME_df = finance_sector_df.merge(
    macro_eco_data,
    on="date",
    how="left"
)

In [53]:
finance_sector_ME_df

,date,sector,weighted_sector_returns,n_stocks_contributing,sector_index,sector_volume,Quarter,Month,consumer_price_index(CPI)_monthly,Crude Oil Price_monthly,...,gdp_svc_Other Services_quarterly,GDP at Current Basic Prices_quarterly,Net Taxes on Products_quarterly,GDP at Current Market Prices_quarterly,foreign_reserve_Gross(USD)_monthly,foreign_reserve_Liquid(USD)_monthly,Year,Month_idx,foreign_reserve_gross(USD)_daily,foreign_reserve_liquid(USD)_daily
0,2017-01-03,financial_services,0.000000,20.0,100.000000,48125518.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2017-01-04,financial_services,0.353432,20.0,100.353432,26705191.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2017-01-05,financial_services,-0.182223,20.0,100.170565,66991076.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2017-01-06,financial_services,1.397196,20.0,101.570144,97521276.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2017-01-09,financial_services,3.645896,20.0,105.273286,99013315.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2286,2026-07-13,financial_services,-0.746327,35.0,2695.019313,290562049.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2287,2026-07-14,financial_services,0.906947,35.0,2719.461701,163509442.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2288,2026-07-15,financial_services,0.779799,35.0,2740.668037,258362267.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2289,2026-07-16,financial_services,1.505893,35.0,2781.939574,261040578.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2290,2026-07-17,financial_services,1.536021,35.0,2824.670764,295044834.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [54]:
finance_sector_ME_df.dropna(inplace=True)

In [55]:
finance_sector_ME_df.head()

,date,sector,weighted_sector_returns,n_stocks_contributing,sector_index,sector_volume,Quarter,Month,consumer_price_index(CPI)_monthly,Crude Oil Price_monthly,...,gdp_svc_Other Services_quarterly,GDP at Current Basic Prices_quarterly,Net Taxes on Products_quarterly,GDP at Current Market Prices_quarterly,foreign_reserve_Gross(USD)_monthly,foreign_reserve_Liquid(USD)_monthly,Year,Month_idx,foreign_reserve_gross(USD)_daily,foreign_reserve_liquid(USD)_daily
64,2017-04-03,financial_services,-0.403579,21.0,105.031248,51906903.0,Q2,April,204.45661,52.13,...,1237.68,26028.36,200.5,26228.85,3.029795e+10,2.962647e+10,2017.0,4.0,3.030715e+10,2.963927e+10
65,2017-04-04,financial_services,-0.295235,21.0,104.721159,45091739.0,Q2,April,204.45661,52.13,...,1237.68,26028.36,200.5,26228.85,3.029795e+10,2.962647e+10,2017.0,4.0,3.031831e+10,2.965163e+10
66,2017-04-05,financial_services,0.584640,21.0,105.333401,96410309.0,Q2,April,204.45661,52.13,...,1237.68,26028.36,200.5,26228.85,3.029795e+10,2.962647e+10,2017.0,4.0,3.032576e+10,2.966022e+10
67,2017-04-06,financial_services,-0.282732,21.0,105.035590,101585127.0,Q2,April,204.45661,52.13,...,1237.68,26028.36,200.5,26228.85,3.029795e+10,2.962647e+10,2017.0,4.0,3.034555e+10,2.968121e+10
68,2017-04-07,financial_services,0.624710,21.0,105.691757,51494340.0,Q2,April,204.45661,52.13,...,1237.68,26028.36,200.5,26228.85,3.029795e+10,2.962647e+10,2017.0,4.0,3.036654e+10,2.970295e+10

In [56]:
finance_sector_ME_df.columns

Index(['date', 'sector', 'weighted_sector_returns', 'n_stocks_contributing',
       'sector_index', 'sector_volume', 'Quarter', 'Month',
       'consumer_price_index(CPI)_monthly', 'Crude Oil Price_monthly',
       'Domestic Production_monthly', 'Crude Oil Export_monthly',
       'Inflation_allItemsAverage_monthly', 'Money Supply(M2)_monthly',
       'currency in circulation_monthly', 'bank reserves_monthly',
       'netForeignAssets_monthly', 'netDomesticAssets_monthly',
       'netDomesticCredit_monthly', 'creditToGovernment_monthly',
       'creditToPrivateSector_monthly', 'MonetaryPolicyRate_monthly',
       'TreasuryBillRate_monthly', 'Lending_Rate_monthly',
       'Exchange_Rate(USD-EOP)_monthly', 'Premium_Motor_Spirit(PMS)_monthly',
       'A. GDP_AGRICULTURE(agric)_quarterly',
       'gdp_agric_Crop Production_quarterly', 'gdp_agric_Livestock_quarterly',
       'gdp_agric_Forestry_quarterly', ' gdp_Fishing_quarterly',
       'GDP_INDUSTRY(ind)_quarterly',
       'gdp_ind_Mining and Quarrying(MQ)_quarterly',
       'gdp_ind_MQ_Crude Petroleum and Natural Gas_quarterly',
       'gdp_ind_MQ_Coal Mining_quarterly', 'gdp_ind_MQ_Metal Ores_quarterly',
       'gdp_ind_MQ_Quarrying and Other Minerals_quarterly',
       'gdp_ind_Manufacturing(mfg)_quarterly',
       ' gdp_ind_mfg_Oil Refining_quarterly', 'gdp_ind_mfg_Cement_quarterly',
       'gdp_ind_mfg_Food, Beverage and Tobacco_quarterly',
       'gdp_ind_mfg_Textile, Apparel and Footwear_quarterly',
       'gdp_ind_mfg_Wood and Wood Products_quarterly',
       'gdp_ind_mfg_Pulp, Paper and Paper Products_quarterly',
       'gdp_ind_mfg_Chemical and Pharmaceutical Products_quarterly',
       'gdp_ind_mfg_Non-Metallic Products_quarterly',
       'gdp_ind_mfg_Plastic and Rubber Products_quarterly',
       'gdp_ind_mfg_Electrical and Electronics_quarterly',
       'gdp_ind_mfg_Basic Metal, Iron and Steel_quarterly',
       'gdp_ind_mfg_Motor Vehicles and Assembly_quarterly',
       'gdp_ind_mfg_Other Manufacturing_quarterly',
       'gdp_ind_Electricity, Gas, Steam & Air conditioner_quarterly',
       'gdp_ind_Water supply, Sewage, Waste Management_quarterly',
       'gdp_ind_Construction_quarterly', 'GDP_SERVICES(svc)_quarterly',
       'gdp_svc_Trade_quarterly',
       'gdp_svc_Accommodation and Food Services_quarterly',
       'gdp_svc_Transportation and Storage(TS)_quarterly',
       'gdp_svc_TS_RoadTransport_quarterly',
       'gdp_svc_TS_Rail Transport & Pipelines_quarterly',
       'gdp_svc_TS_Water Transport_quarterly',
       'gdp_svc_TS_Air Transport_quarterly',
       'gdp_svc_TS_Transport Services_quarterly',
       'gdp_svc_TS_Post and Courier Services_quarterly',
       'gdp_svc_Information and Communication(IC)_quarterly',
       'gdp_svc_IC_Telecommunications and Information Services_quarterly',
       'gdp_svc_IC_Publishing_quarterly',
       'gdp_svc_IC_Motion Pictures, Sound Recording and Music Production_quarterly',
       'gdp_svc_IC_Broadcasting_quarterly',
       'gdp_svc_Arts, Entertainment & Recreation_quarterly',
       'gdp_svc_Financial and Insurance(FI)_quarterly',
       'gdp_svc_FI_Financial Institutions_quarterly',
       'gdp_svc_FI_Insurance_quarterly', 'gdp_svc_Real Estate_quarterly',
       'gdp_svc_Professional, Scientific & Technical Services_quarterly',
       'gdp_svc_Administrative and Support Services_quarterly',
       'gdp_svc_Public Administration_quarterly',
       'gdp_svc_Education_quarterly',
       'gdp_svc_Human Health & Social Services_quarterly',
       'gdp_svc_Other Services_quarterly',
       'GDP at Current Basic Prices_quarterly',
       'Net Taxes on Products_quarterly',
       'GDP at Current Market Prices_quarterly',
       'foreign_reserve_Gross(USD)_monthly',
       'foreign_reserve_Liquid(USD)_monthly', 'Year', 'Month_idx',
       'foreign_reserve_gross(USD)_daily',
       'foreign_reserve_liquid(USD)_daily'],
      dtype='str')

In [57]:
finance_sector_ME_df.rename(columns={'A. GDP_AGRICULTURE(agric)_quarterly':'GDP_AGRICULTURE(agric)_quarterly', ' gdp_ind_mfg_Oil Refining_quarterly':'gdp_ind_mfg_Oil Refining_quarterly'}, inplace=True)

In [58]:
finance_sec_num_df = finance_sector_ME_df.select_dtypes(include="number")

In [59]:
finance_sec_num_df.columns

Index(['weighted_sector_returns', 'n_stocks_contributing', 'sector_index',
       'sector_volume', 'consumer_price_index(CPI)_monthly',
       'Crude Oil Price_monthly', 'Domestic Production_monthly',
       'Crude Oil Export_monthly', 'Inflation_allItemsAverage_monthly',
       'Money Supply(M2)_monthly', 'currency in circulation_monthly',
       'bank reserves_monthly', 'netForeignAssets_monthly',
       'netDomesticAssets_monthly', 'netDomesticCredit_monthly',
       'creditToGovernment_monthly', 'creditToPrivateSector_monthly',
       'MonetaryPolicyRate_monthly', 'TreasuryBillRate_monthly',
       'Lending_Rate_monthly', 'Exchange_Rate(USD-EOP)_monthly',
       'Premium_Motor_Spirit(PMS)_monthly', 'GDP_AGRICULTURE(agric)_quarterly',
       'gdp_agric_Crop Production_quarterly', 'gdp_agric_Livestock_quarterly',
       'gdp_agric_Forestry_quarterly', ' gdp_Fishing_quarterly',
       'GDP_INDUSTRY(ind)_quarterly',
       'gdp_ind_Mining and Quarrying(MQ)_quarterly',
       'gdp_ind_MQ_Crude Petroleum and Natural Gas_quarterly',
       'gdp_ind_MQ_Coal Mining_quarterly', 'gdp_ind_MQ_Metal Ores_quarterly',
       'gdp_ind_MQ_Quarrying and Other Minerals_quarterly',
       'gdp_ind_Manufacturing(mfg)_quarterly',
       'gdp_ind_mfg_Oil Refining_quarterly', 'gdp_ind_mfg_Cement_quarterly',
       'gdp_ind_mfg_Food, Beverage and Tobacco_quarterly',
       'gdp_ind_mfg_Textile, Apparel and Footwear_quarterly',
       'gdp_ind_mfg_Wood and Wood Products_quarterly',
       'gdp_ind_mfg_Pulp, Paper and Paper Products_quarterly',
       'gdp_ind_mfg_Chemical and Pharmaceutical Products_quarterly',
       'gdp_ind_mfg_Non-Metallic Products_quarterly',
       'gdp_ind_mfg_Plastic and Rubber Products_quarterly',
       'gdp_ind_mfg_Electrical and Electronics_quarterly',
       'gdp_ind_mfg_Basic Metal, Iron and Steel_quarterly',
       'gdp_ind_mfg_Motor Vehicles and Assembly_quarterly',
       'gdp_ind_mfg_Other Manufacturing_quarterly',
       'gdp_ind_Electricity, Gas, Steam & Air conditioner_quarterly',
       'gdp_ind_Water supply, Sewage, Waste Management_quarterly',
       'gdp_ind_Construction_quarterly', 'GDP_SERVICES(svc)_quarterly',
       'gdp_svc_Trade_quarterly',
       'gdp_svc_Accommodation and Food Services_quarterly',
       'gdp_svc_Transportation and Storage(TS)_quarterly',
       'gdp_svc_TS_RoadTransport_quarterly',
       'gdp_svc_TS_Rail Transport & Pipelines_quarterly',
       'gdp_svc_TS_Water Transport_quarterly',
       'gdp_svc_TS_Air Transport_quarterly',
       'gdp_svc_TS_Transport Services_quarterly',
       'gdp_svc_TS_Post and Courier Services_quarterly',
       'gdp_svc_Information and Communication(IC)_quarterly',
       'gdp_svc_IC_Telecommunications and Information Services_quarterly',
       'gdp_svc_IC_Publishing_quarterly',
       'gdp_svc_IC_Motion Pictures, Sound Recording and Music Production_quarterly',
       'gdp_svc_IC_Broadcasting_quarterly',
       'gdp_svc_Arts, Entertainment & Recreation_quarterly',
       'gdp_svc_Financial and Insurance(FI)_quarterly',
       'gdp_svc_FI_Financial Institutions_quarterly',
       'gdp_svc_FI_Insurance_quarterly', 'gdp_svc_Real Estate_quarterly',
       'gdp_svc_Professional, Scientific & Technical Services_quarterly',
       'gdp_svc_Administrative and Support Services_quarterly',
       'gdp_svc_Public Administration_quarterly',
       'gdp_svc_Education_quarterly',
       'gdp_svc_Human Health & Social Services_quarterly',
       'gdp_svc_Other Services_quarterly',
       'GDP at Current Basic Prices_quarterly',
       'Net Taxes on Products_quarterly',
       'GDP at Current Market Prices_quarterly',
       'foreign_reserve_Gross(USD)_monthly',
       'foreign_reserve_Liquid(USD)_monthly', 'Year', 'Month_idx',
       'foreign_reserve_gross(USD)_daily',
       'foreign_reserve_liquid(USD)_daily'],
      dtype='str')

In [60]:
fin_sec_corr=finance_sec_num_df.corr()

In [61]:
fin_sec_corr

,weighted_sector_returns,n_stocks_contributing,sector_index,sector_volume,consumer_price_index(CPI)_monthly,Crude Oil Price_monthly,Domestic Production_monthly,Crude Oil Export_monthly,Inflation_allItemsAverage_monthly,Money Supply(M2)_monthly,...,gdp_svc_Other Services_quarterly,GDP at Current Basic Prices_quarterly,Net Taxes on Products_quarterly,GDP at Current Market Prices_quarterly,foreign_reserve_Gross(USD)_monthly,foreign_reserve_Liquid(USD)_monthly,Year,Month_idx,foreign_reserve_gross(USD)_daily,foreign_reserve_liquid(USD)_daily
weighted_sector_returns,1.000000,0.013134,0.036320,0.078945,0.036956,-0.040798,-0.030343,-0.030343,0.057628,0.037051,...,0.019696,0.033253,0.026542,0.033293,-0.062380,-0.063666,0.029180,0.007373,-0.059885,-0.061164
n_stocks_contributing,0.013134,1.000000,0.574562,0.232719,0.775609,0.480108,-0.693658,-0.693658,0.521398,0.758349,...,0.385504,0.705498,0.167179,0.705564,0.040983,0.040849,0.909361,-0.001014,0.057298,0.056909
sector_index,0.036320,0.574562,1.000000,0.399895,0.921058,0.298052,-0.292877,-0.292877,0.516747,0.901570,...,0.606790,0.949877,0.088525,0.949411,0.327477,0.322421,0.794263,-0.076155,0.406158,0.402043
sector_volume,0.078945,0.232719,0.399895,1.000000,0.389579,0.061151,-0.109461,-0.109461,0.264222,0.384258,...,0.244019,0.397899,0.062896,0.397814,0.062106,0.058561,0.326554,-0.011213,0.112582,0.110399
consumer_price_index(CPI)_monthly,0.036956,0.775609,0.921058,0.389579,1.000000,0.376336,-0.512520,-0.512520,0.709324,0.993408,...,0.574753,0.960515,0.126560,0.961487,0.142102,0.134870,0.939833,-0.028351,0.215572,0.209259
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
foreign_reserve_Liquid(USD)_monthly,-0.063666,0.040849,0.322421,0.058561,0.134870,0.255068,0.235269,0.235269,-0.258691,0.104791,...,0.289085,0.251707,-0.164784,0.250469,0.998800,1.000000,0.059941,-0.096226,0.969719,0.971192
Year,0.029180,0.909361,0.794263,0.326554,0.939833,0.463800,-0.690198,-0.690198,0.665742,0.925565,...,0.574229,0.885934,0.173804,0.886334,0.061955,0.059941,1.000000,-0.131171,0.111809,0.109941
Month_idx,0.007373,-0.001014,-0.076155,-0.011213,-0.028351,-0.001027,-0.050502,-0.050502,0.065195,-0.040498,...,-0.621855,-0.075549,-0.198451,-0.075114,-0.098474,-0.096226,-0.131171,1.000000,-0.074016,-0.071864
foreign_reserve_gross(USD)_daily,-0.059885,0.057298,0.406158,0.112582,0.215572,0.235058,0.221834,0.221834,-0.149984,0.190632,...,0.350613,0.331794,-0.146956,0.330780,0.971457,0.969719,0.111809,-0.074016,1.000000,0.998873
foreign_reserve_liquid(USD)_daily,-0.061164,0.056909,0.402043,0.110399,0.209259,0.233212,0.213639,0.213639,-0.163145,0.183294,...,0.349043,0.328711,-0.151083,0.327616,0.970683,0.971192,0.109941,-0.071864,0.998873,1.000000

In [62]:
sector_corr = fin_sec_corr['weighted_sector_returns']
# strong_corr = sector_corr[sector_corr.abs() >= 0.5]

sector_corr

weighted_sector_returns                1.000000
n_stocks_contributing                  0.013134
sector_index                           0.036320
sector_volume                          0.078945
consumer_price_index(CPI)_monthly      0.036956
                                         ...
foreign_reserve_Liquid(USD)_monthly   -0.063666
Year                                   0.029180
Month_idx                              0.007373
foreign_reserve_gross(USD)_daily      -0.059885
foreign_reserve_liquid(USD)_daily     -0.061164
Name: weighted_sector_returns, Length: 85, dtype: float64

In [63]:
finance_sector_ME_df.columns

Index(['date', 'sector', 'weighted_sector_returns', 'n_stocks_contributing',
       'sector_index', 'sector_volume', 'Quarter', 'Month',
       'consumer_price_index(CPI)_monthly', 'Crude Oil Price_monthly',
       'Domestic Production_monthly', 'Crude Oil Export_monthly',
       'Inflation_allItemsAverage_monthly', 'Money Supply(M2)_monthly',
       'currency in circulation_monthly', 'bank reserves_monthly',
       'netForeignAssets_monthly', 'netDomesticAssets_monthly',
       'netDomesticCredit_monthly', 'creditToGovernment_monthly',
       'creditToPrivateSector_monthly', 'MonetaryPolicyRate_monthly',
       'TreasuryBillRate_monthly', 'Lending_Rate_monthly',
       'Exchange_Rate(USD-EOP)_monthly', 'Premium_Motor_Spirit(PMS)_monthly',
       'GDP_AGRICULTURE(agric)_quarterly',
       'gdp_agric_Crop Production_quarterly', 'gdp_agric_Livestock_quarterly',
       'gdp_agric_Forestry_quarterly', ' gdp_Fishing_quarterly',
       'GDP_INDUSTRY(ind)_quarterly',
       'gdp_ind_Mining and Quarrying(MQ)_quarterly',
       'gdp_ind_MQ_Crude Petroleum and Natural Gas_quarterly',
       'gdp_ind_MQ_Coal Mining_quarterly', 'gdp_ind_MQ_Metal Ores_quarterly',
       'gdp_ind_MQ_Quarrying and Other Minerals_quarterly',
       'gdp_ind_Manufacturing(mfg)_quarterly',
       'gdp_ind_mfg_Oil Refining_quarterly', 'gdp_ind_mfg_Cement_quarterly',
       'gdp_ind_mfg_Food, Beverage and Tobacco_quarterly',
       'gdp_ind_mfg_Textile, Apparel and Footwear_quarterly',
       'gdp_ind_mfg_Wood and Wood Products_quarterly',
       'gdp_ind_mfg_Pulp, Paper and Paper Products_quarterly',
       'gdp_ind_mfg_Chemical and Pharmaceutical Products_quarterly',
       'gdp_ind_mfg_Non-Metallic Products_quarterly',
       'gdp_ind_mfg_Plastic and Rubber Products_quarterly',
       'gdp_ind_mfg_Electrical and Electronics_quarterly',
       'gdp_ind_mfg_Basic Metal, Iron and Steel_quarterly',
       'gdp_ind_mfg_Motor Vehicles and Assembly_quarterly',
       'gdp_ind_mfg_Other Manufacturing_quarterly',
       'gdp_ind_Electricity, Gas, Steam & Air conditioner_quarterly',
       'gdp_ind_Water supply, Sewage, Waste Management_quarterly',
       'gdp_ind_Construction_quarterly', 'GDP_SERVICES(svc)_quarterly',
       'gdp_svc_Trade_quarterly',
       'gdp_svc_Accommodation and Food Services_quarterly',
       'gdp_svc_Transportation and Storage(TS)_quarterly',
       'gdp_svc_TS_RoadTransport_quarterly',
       'gdp_svc_TS_Rail Transport & Pipelines_quarterly',
       'gdp_svc_TS_Water Transport_quarterly',
       'gdp_svc_TS_Air Transport_quarterly',
       'gdp_svc_TS_Transport Services_quarterly',
       'gdp_svc_TS_Post and Courier Services_quarterly',
       'gdp_svc_Information and Communication(IC)_quarterly',
       'gdp_svc_IC_Telecommunications and Information Services_quarterly',
       'gdp_svc_IC_Publishing_quarterly',
       'gdp_svc_IC_Motion Pictures, Sound Recording and Music Production_quarterly',
       'gdp_svc_IC_Broadcasting_quarterly',
       'gdp_svc_Arts, Entertainment & Recreation_quarterly',
       'gdp_svc_Financial and Insurance(FI)_quarterly',
       'gdp_svc_FI_Financial Institutions_quarterly',
       'gdp_svc_FI_Insurance_quarterly', 'gdp_svc_Real Estate_quarterly',
       'gdp_svc_Professional, Scientific & Technical Services_quarterly',
       'gdp_svc_Administrative and Support Services_quarterly',
       'gdp_svc_Public Administration_quarterly',
       'gdp_svc_Education_quarterly',
       'gdp_svc_Human Health & Social Services_quarterly',
       'gdp_svc_Other Services_quarterly',
       'GDP at Current Basic Prices_quarterly',
       'Net Taxes on Products_quarterly',
       'GDP at Current Market Prices_quarterly',
       'foreign_reserve_Gross(USD)_monthly',
       'foreign_reserve_Liquid(USD)_monthly', 'Year', 'Month_idx',
       'foreign_reserve_gross(USD)_daily',
       'foreign_reserve_liquid(USD)_daily'],
      dtype='str')

In [64]:
finance_sector_ME_df.info()

<class 'pandas.DataFrame'>
Index: 2152 entries, 64 to 2277
Data columns (total 89 columns):
 #   Column                                                                      Non-Null Count  Dtype
---  ------                                                                      --------------  -----
 0   date                                                                        2152 non-null   datetime64[us]
 1   sector                                                                      2152 non-null   str
 2   weighted_sector_returns                                                     2152 non-null   float64
 3   n_stocks_contributing                                                       2152 non-null   float64
 4   sector_index                                                                2152 non-null   float64
 5   sector_volume                                                               2152 non-null   float64
 6   Quarter                                                                     2152 non-null   str
 7   Month                                                                       2152 non-null   str
 8   consumer_price_index(CPI)_monthly                                           2152 non-null   float64
 9   Crude Oil Price_monthly                                                     2152 non-null   float64
 10  Domestic Production_monthly                                                 2152 non-null   float64
 11  Crude Oil Export_monthly                                                    2152 non-null   float64
 12  Inflation_allItemsAverage_monthly                                           2152 non-null   float64
 13  Money Supply(M2)_monthly                                                    2152 non-null   float64
 14  currency in circulation_monthly                                             2152 non-null   float64
 15  bank reserves_monthly                                                       2152 non-null   float64
 16  netForeignAssets_monthly                                                    2152 non-null   float64
 17  netDomesticAssets_monthly                                                   2152 non-null   float64
 18  netDomesticCredit_monthly                                                   2152 non-null   float64
 19  creditToGovernment_monthly                                                  2152 non-null   float64
 20  creditToPrivateSector_monthly                                               2152 non-null   float64
 21  MonetaryPolicyRate_monthly                                                  2152 non-null   float64
 22  TreasuryBillRate_monthly                                                    2152 non-null   float64
 23  Lending_Rate_monthly                                                        2152 non-null   float64
 24  Exchange_Rate(USD-EOP)_monthly                                              2152 non-null   float64
 25  Premium_Motor_Spirit(PMS)_monthly                                           2152 non-null   float64
 26  GDP_AGRICULTURE(agric)_quarterly                                            2152 non-null   float64
 27  gdp_agric_Crop Production_quarterly                                         2152 non-null   float64
 28  gdp_agric_Livestock_quarterly                                               2152 non-null   float64
 29  gdp_agric_Forestry_quarterly                                                2152 non-null   float64
 30   gdp_Fishing_quarterly                                                      2152 non-null   float64
 31  GDP_INDUSTRY(ind)_quarterly                                                 2152 non-null   float64
 32  gdp_ind_Mining and Quarrying(MQ)_quarterly                                  2152 non-null   float64
 33  gdp_ind_MQ_Crude Petroleum and Natural Gas_quarterly                        2152 non-null   float64
 34  gdp_ind_MQ_Coal Mining_quarterly                                            2152 non-null   float64
 35  gdp_ind_MQ_Metal Ores_quarterly                                             2152 non-null   float64
 36  gdp_ind_MQ_Quarrying and Other Minerals_quarterly                           2152 non-null   float64
 37  gdp_ind_Manufacturing(mfg)_quarterly                                        2152 non-null   float64
 38  gdp_ind_mfg_Oil Refining_quarterly                                          2152 non-null   float64
 39  gdp_ind_mfg_Cement_quarterly                                                2152 non-null   float64
 40  gdp_ind_mfg_Food, Beverage and Tobacco_quarterly                            2152 non-null   float64
 41  gdp_ind_mfg_Textile, Apparel and Footwear_quarterly                         2152 non-null   float64
 42  gdp_ind_mfg_Wood and Wood Products_quarterly                                2152 non-null   float64
 43  gdp_ind_mfg_Pulp, Paper and Paper Products_quarterly                        2152 non-null   float64
 44  gdp_ind_mfg_Chemical and Pharmaceutical Products_quarterly                  2152 non-null   float64
 45  gdp_ind_mfg_Non-Metallic Products_quarterly                                 2152 non-null   float64
 46  gdp_ind_mfg_Plastic and Rubber Products_quarterly                           2152 non-null   float64
 47  gdp_ind_mfg_Electrical and Electronics_quarterly                            2152 non-null   float64
 48  gdp_ind_mfg_Basic Metal, Iron and Steel_quarterly                           2152 non-null   float64
 49  gdp_ind_mfg_Motor Vehicles and Assembly_quarterly                           2152 non-null   float64
 50  gdp_ind_mfg_Other Manufacturing_quarterly                                   2152 non-null   float64
 51  gdp_ind_Electricity, Gas, Steam & Air conditioner_quarterly                 2152 non-null   float64
 52  gdp_ind_Water supply, Sewage, Waste Management_quarterly                    2152 non-null   float64
 53  gdp_ind_Construction_quarterly                                              2152 non-null   float64
 54  GDP_SERVICES(svc)_quarterly                                                 2152 non-null   float64
 55  gdp_svc_Trade_quarterly                                                     2152 non-null   float64
 56  gdp_svc_Accommodation and Food Services_quarterly                           2152 non-null   float64
 57  gdp_svc_Transportation and Storage(TS)_quarterly                            2152 non-null   float64
 58  gdp_svc_TS_RoadTransport_quarterly                                          2152 non-null   float64
 59  gdp_svc_TS_Rail Transport & Pipelines_quarterly                             2152 non-null   float64
 60  gdp_svc_TS_Water Transport_quarterly                                        2152 non-null   float64
 61  gdp_svc_TS_Air Transport_quarterly                                          2152 non-null   float64
 62  gdp_svc_TS_Transport Services_quarterly                                     2152 non-null   float64
 63  gdp_svc_TS_Post and Courier Services_quarterly                              2152 non-null   float64
 64  gdp_svc_Information and Communication(IC)_quarterly                         2152 non-null   float64
 65  gdp_svc_IC_Telecommunications and Information Services_quarterly            2152 non-null   float64
 66  gdp_svc_IC_Publishing_quarterly                                             2152 non-null   float64
 67  gdp_svc_IC_Motion Pictures, Sound Recording and Music Production_quarterly  2152 non-null   float64
 68  gdp_svc_IC_Broadcasting_quarterly                                           2152 non-null   float64
 69  gdp_svc_Arts, Entertainment & Recreation_quarterly                          2152 non-null   float64
 70  gdp_svc_Financial and Insurance(FI)_quarterly                               2152 non-null   float64
 71  gdp_svc_FI_Financial Institutions_quarterly                                 2152 non-null   float64
 72  gdp_svc_FI_Insurance_quarterly                                              2152 non-null   float64
 73  gdp_svc_Real Estate_quarterly                                               2152 non-null   float64
 74  gdp_svc_Professional, Scientific & Technical Services_quarterly             2152 non-null   float64
 75  gdp_svc_Administrative and Support Services_quarterly                       2152 non-null   float64
 76  gdp_svc_Public Administration_quarterly                                     2152 non-null   float64
 77  gdp_svc_Education_quarterly                                                 2152 non-null   float64
 78  gdp_svc_Human Health & Social Services_quarterly                            2152 non-null   float64
 79  gdp_svc_Other Services_quarterly                                            2152 non-null   float64
 80  GDP at Current Basic Prices_quarterly                                       2152 non-null   float64
 81  Net Taxes on Products_quarterly                                             2152 non-null   float64
 82  GDP at Current Market Prices_quarterly                                      2152 non-null   float64
 83  foreign_reserve_Gross(USD)_monthly                                          2152 non-null   float64
 84  foreign_reserve_Liquid(USD)_monthly                                         2152 non-null   float64
 85  Year                                                                        2152 non-null   float64
 86  Month_idx                                                                   2152 non-null   float64
 87  foreign_reserve_gross(USD)_daily                                            2152 non-null   float64
 88  foreign_reserve_liquid(USD)_daily                                           2152 non-null   float64
dtypes: datetime64[us](1), float64(85), str(3)
memory usage: 1.5 MB

In [65]:
## LET US DROP COLUMNS THAT WONT HAVE ANY EFFECT AT ALL (eg date, index etc)

In [66]:
finance_sector_ME_df2=finance_sector_ME_df.drop(columns=['foreign_reserve_Gross(USD)_monthly','foreign_reserve_Liquid(USD)_monthly', 'Year', 'Month_idx','date', 'sector','Quarter', 'Month'])

In [67]:
finance_sector_ME_df2.shape

(2152, 81)

In [68]:
## We will need to lag the sector_volume by 1 day to avoid leakage
finance_sector_ME_df['sector_volume']=finance_sector_ME_df['sector_volume'].shift(1)
finance_sector_ME_df['sector_volume'].head()

64            NaN
65     51906903.0
66     45091739.0
67     96410309.0
68    101585127.0
Name: sector_volume, dtype: float64

In [70]:
finance_sector_ME_df=finance_sector_ME_df.dropna()

We will perform a quick training to see the performance. We will apply xgboost because it is tree based.

NOTE: WHen doing the splitting we use time series method instead of a random split because this data is a time series data

In [126]:
from sklearn.model_selection import TimeSeriesSplit
from sklearn.linear_model import Ridge
from xgboost import XGBRegressor
from sklearn.metrics import r2_score,mean_squared_error,mean_absolute_error
import numpy as np

In [127]:
## The needed features for this training (Check Cloud AI for explanation)
X_y_finance_features = [
    #target feature
    'weighted_sector_returns',

    'sector_volume',  # consider lagging — see caveat below

    # Prices / inflation
    'consumer_price_index(CPI)_monthly',
    'Inflation_allItemsAverage_monthly',
    'Premium_Motor_Spirit(PMS)_monthly',

    # Oil
    'Crude Oil Price_monthly',
    'Domestic Production_monthly',
    'Crude Oil Export_monthly',

    # Money supply / banking system
    'Money Supply(M2)_monthly',
    'currency in circulation_monthly',
    'bank reserves_monthly',
    'netForeignAssets_monthly',
    'netDomesticAssets_monthly',
    'netDomesticCredit_monthly',
    'creditToGovernment_monthly',
    'creditToPrivateSector_monthly',

    # Interest rates
    'MonetaryPolicyRate_monthly',
    'TreasuryBillRate_monthly',
    'Lending_Rate_monthly',

    # Exchange rate
    'Exchange_Rate(USD-EOP)_monthly',

    # Broad economy GDP
    'GDP_AGRICULTURE(agric)_quarterly',
    'GDP_INDUSTRY(ind)_quarterly',
    'GDP at Current Market Prices_quarterly',

    # Financial sector-specific GDP
    'gdp_svc_FI_Financial Institutions_quarterly',

    # Foreign reserves (pick one frequency — daily shown here)
    'foreign_reserve_gross(USD)_daily',
    'foreign_reserve_liquid(USD)_daily',
]

In [128]:
len(X_y_finance_features)

26

In [129]:
financial_sec_feat=finance_sector_ME_df[X_y_finance_features]

In [130]:
## We will inspect the correlations to remove redundant features ie avoidng collinearity
financial_sec_feat.corr()

,weighted_sector_returns,sector_volume,consumer_price_index(CPI)_monthly,Inflation_allItemsAverage_monthly,Premium_Motor_Spirit(PMS)_monthly,Crude Oil Price_monthly,Domestic Production_monthly,Crude Oil Export_monthly,Money Supply(M2)_monthly,currency in circulation_monthly,...,MonetaryPolicyRate_monthly,TreasuryBillRate_monthly,Lending_Rate_monthly,Exchange_Rate(USD-EOP)_monthly,GDP_AGRICULTURE(agric)_quarterly,GDP_INDUSTRY(ind)_quarterly,GDP at Current Market Prices_quarterly,gdp_svc_FI_Financial Institutions_quarterly,foreign_reserve_gross(USD)_daily,foreign_reserve_liquid(USD)_daily
weighted_sector_returns,1.000000,0.034559,0.036788,0.057614,0.037428,-0.040990,-0.030321,-0.030321,0.036900,0.033725,...,0.044230,0.027193,0.027322,0.038416,0.033296,0.033946,0.033132,0.034103,-0.060217,-0.061498
sector_volume,0.034559,1.000000,0.390069,0.264882,0.385354,0.061151,-0.108977,-0.108977,0.384723,0.358076,...,0.379395,0.258623,0.260255,0.368635,0.372103,0.262271,0.397952,0.368102,0.114115,0.111998
consumer_price_index(CPI)_monthly,0.036788,0.390069,1.000000,0.709470,0.938913,0.375995,-0.512593,-0.512593,0.993408,0.936904,...,0.926271,0.555632,0.418807,0.942293,0.878492,0.870827,0.961467,0.942385,0.214907,0.208585
Inflation_allItemsAverage_monthly,0.057614,0.264882,0.709470,1.000000,0.642471,0.360213,-0.540425,-0.540425,0.746231,0.609236,...,0.764461,0.528143,0.296194,0.796574,0.507435,0.717676,0.561274,0.737271,-0.150168,-0.163339
Premium_Motor_Spirit(PMS)_monthly,0.037428,0.385354,0.938913,0.642471,1.000000,0.270276,-0.300621,-0.300621,0.940199,0.894628,...,0.926396,0.663997,0.585364,0.921414,0.792128,0.781481,0.899733,0.906764,0.262585,0.254381
Crude Oil Price_monthly,-0.040990,0.061151,0.375995,0.360213,0.270276,1.000000,-0.585350,-0.585350,0.349511,0.347724,...,0.251566,0.072344,-0.122648,0.259164,0.215951,0.525015,0.297553,0.354519,0.234410,0.232559
Domestic Production_monthly,-0.030321,-0.108977,-0.512593,-0.540425,-0.300621,-0.585350,1.000000,1.000000,-0.489953,-0.482229,...,-0.293811,0.156622,0.413686,-0.391947,-0.419765,-0.701822,-0.420385,-0.438209,0.222102,0.213903
Crude Oil Export_monthly,-0.030321,-0.108977,-0.512593,-0.540425,-0.300621,-0.585350,1.000000,1.000000,-0.489953,-0.482229,...,-0.293811,0.156622,0.413686,-0.391947,-0.419765,-0.701822,-0.420385,-0.438209,0.222102,0.213903
Money Supply(M2)_monthly,0.036900,0.384723,0.993408,0.746231,0.940199,0.349511,-0.489953,-0.489953,1.000000,0.938204,...,0.945928,0.600021,0.440887,0.971839,0.851138,0.863730,0.939999,0.953609,0.190025,0.182679
currency in circulation_monthly,0.033725,0.358076,0.936904,0.609236,0.894628,0.347724,-0.482229,-0.482229,0.938204,1.000000,...,0.831393,0.524282,0.367484,0.889486,0.844631,0.800373,0.918321,0.889172,0.274077,0.276003
bank reserves_monthly,0.040210,0.390276,0.988509,0.664852,0.929906,0.298465,-0.505720,-0.505720,0.979204,0.928672,...,0.896805,0.498941,0.387619,0.923213,0.884735,0.858798,0.958844,0.923530,0.188460,0.184589
netForeignAssets_monthly,0.004136,0.336442,0.716061,0.428372,0.767662,0.076944,0.014666,0.014666,0.747475,0.684555,...,0.804407,0.755005,0.679620,0.794225,0.612610,0.442028,0.711096,0.693288,0.356417,0.345407
netDomesticAssets_monthly,0.044282,0.361334,0.966531,0.763039,0.898956,0.382128,-0.559377,-0.559377,0.966082,0.923767,...,0.890024,0.516941,0.348740,0.922592,0.824813,0.886815,0.903544,0.929415,0.122612,0.116971
netDomesticCredit_monthly,0.046168,0.352500,0.970244,0.781944,0.897996,0.416194,-0.585572,-0.585572,0.971304,0.893359,...,0.903870,0.508609,0.336295,0.928572,0.826460,0.924557,0.902376,0.926252,0.120639,0.111808
creditToGovernment_monthly,0.051951,0.295017,0.870374,0.706519,0.780633,0.466343,-0.646486,-0.646486,0.849772,0.776542,...,0.763032,0.330152,0.183788,0.768550,0.751895,0.902174,0.808922,0.812385,0.108339,0.100386
creditToPrivateSector_monthly,0.041317,0.364151,0.974360,0.782836,0.913749,0.373415,-0.530002,-0.530002,0.985749,0.909059,...,0.930603,0.571176,0.394195,0.963382,0.824934,0.893613,0.906478,0.939056,0.121094,0.112240
MonetaryPolicyRate_monthly,0.044230,0.379395,0.926271,0.764461,0.926396,0.251566,-0.293811,-0.293811,0.945928,0.831393,...,1.000000,0.766699,0.647788,0.963006,0.753599,0.747973,0.858277,0.927812,0.193404,0.174915
TreasuryBillRate_monthly,0.027193,0.258623,0.555632,0.528143,0.663997,0.072344,0.156622,0.156622,0.600021,0.524282,...,0.766699,1.000000,0.836225,0.691095,0.396332,0.295594,0.511819,0.605502,0.270337,0.249381
Lending_Rate_monthly,0.027322,0.260255,0.418807,0.296194,0.585364,-0.122648,0.413686,0.413686,0.440887,0.367484,...,0.647788,0.836225,1.000000,0.504463,0.361078,0.069977,0.450472,0.461116,0.388745,0.365644
Exchange_Rate(USD-EOP)_monthly,0.038416,0.368635,0.942293,0.796574,0.921414,0.259164,-0.391947,-0.391947,0.971839,0.889486,...,0.963006,0.691095,0.504463,1.000000,0.761735,0.802733,0.857824,0.937651,0.126597,0.116147
GDP_AGRICULTURE(agric)_quarterly,0.033296,0.372103,0.878492,0.507435,0.792128,0.215951,-0.419765,-0.419765,0.851138,0.844631,...,0.753599,0.396332,0.361078,0.761735,1.000000,0.724056,0.955608,0.736153,0.307253,0.306467
GDP_INDUSTRY(ind)_quarterly,0.033946,0.262271,0.870827,0.717676,0.781481,0.525015,-0.701822,-0.701822,0.863730,0.800373,...,0.747973,0.295594,0.069977,0.802733,0.724056,1.000000,0.780284,0.820247,0.039713,0.035875
GDP at Current Market Prices_quarterly,0.033132,0.397952,0.961467,0.561274,0.899733,0.297553,-0.420385,-0.420385,0.939999,0.918321,...,0.858277,0.511819,0.450472,0.857824,0.955608,0.780284,1.000000,0.858160,0.330260,0.327091
gdp_svc_FI_Financial Institutions_quarterly,0.034103,0.368102,0.942385,0.737271,0.906764,0.354519,-0.438209,-0.438209,0.953609,0.889172,...,0.927812,0.605502,0.461116,0.937651,0.736153,0.820247,0.858160,1.000000,0.167125,0.157994
foreign_reserve_gross(USD)_daily,-0.060217,0.114115,0.214907,-0.150168,0.262585,0.234410,0.222102,0.222102,0.190025,0.274077,...,0.193404,0.270337,0.388745,0.126597,0.307253,0.039713,0.330260,0.167125,1.000000,0.998872
foreign_reserve_liquid(USD)_daily,-0.061498,0.111998,0.208585,-0.163339,0.254381,0.232559,0.213903,0.213903,0.182679,0.276003,...,0.174915,0.249381,0.365644,0.116147,0.306467,0.035875,0.327091,0.157994,0.998872,1.000000

In [131]:
## We will set a threshold for this exercise eg 0.85
## Note: this threshold is determined by the DOMAIN EXPERT
## For now we will use 0.90
## Let us improve the below

def correlation(dataset, threshold):
    col_corr = set()
    col_pair = set()
    
    corr_matrix = dataset.corr()

    for i in range(len(corr_matrix.columns)):
        for j in range(i):
            if abs(corr_matrix.iloc[i, j]) > threshold:
                colname1 = corr_matrix.columns[i]
                colname2 = corr_matrix.columns[j]

                col_pair.add((colname1, colname2, corr_matrix.iloc[i, j]))
                col_corr.add(colname1)

    return col_corr, col_pair

In [132]:
## We will use the correlation() function we created.
## This will identify features that are highly correlated to each other
correlated_features,column_pairs =correlation(financial_sec_feat,0.85)
correlated_features

## The column pairing is good for investigative purposes

{'Crude Oil Export_monthly',
 'Exchange_Rate(USD-EOP)_monthly',
 'GDP at Current Market Prices_quarterly',
 'GDP_AGRICULTURE(agric)_quarterly',
 'GDP_INDUSTRY(ind)_quarterly',
 'MonetaryPolicyRate_monthly',
 'Money Supply(M2)_monthly',
 'Premium_Motor_Spirit(PMS)_monthly',
 'bank reserves_monthly',
 'creditToGovernment_monthly',
 'creditToPrivateSector_monthly',
 'currency in circulation_monthly',
 'foreign_reserve_liquid(USD)_daily',
 'gdp_svc_FI_Financial Institutions_quarterly',
 'netDomesticAssets_monthly',
 'netDomesticCredit_monthly'}

In [133]:
column_pairs

{('Crude Oil Export_monthly',
  'Domestic Production_monthly',
  np.float64(0.9999999999999998)),
 ('Exchange_Rate(USD-EOP)_monthly',
  'MonetaryPolicyRate_monthly',
  np.float64(0.963005924212574)),
 ('Exchange_Rate(USD-EOP)_monthly',
  'Money Supply(M2)_monthly',
  np.float64(0.9718386491774184)),
 ('Exchange_Rate(USD-EOP)_monthly',
  'Premium_Motor_Spirit(PMS)_monthly',
  np.float64(0.9214136482702564)),
 ('Exchange_Rate(USD-EOP)_monthly',
  'bank reserves_monthly',
  np.float64(0.9232133674542858)),
 ('Exchange_Rate(USD-EOP)_monthly',
  'consumer_price_index(CPI)_monthly',
  np.float64(0.9422931038722505)),
 ('Exchange_Rate(USD-EOP)_monthly',
  'creditToPrivateSector_monthly',
  np.float64(0.9633817411889825)),
 ('Exchange_Rate(USD-EOP)_monthly',
  'currency in circulation_monthly',
  np.float64(0.889486406658956)),
 ('Exchange_Rate(USD-EOP)_monthly',
  'netDomesticAssets_monthly',
  np.float64(0.9225921107107503)),
 ('Exchange_Rate(USD-EOP)_monthly',
  'netDomesticCredit_monthly',
  np.float64(0.9285721834559336)),
 ('GDP at Current Market Prices_quarterly',
  'Exchange_Rate(USD-EOP)_monthly',
  np.float64(0.8578244745522008)),
 ('GDP at Current Market Prices_quarterly',
  'GDP_AGRICULTURE(agric)_quarterly',
  np.float64(0.9556080902764711)),
 ('GDP at Current Market Prices_quarterly',
  'MonetaryPolicyRate_monthly',
  np.float64(0.85827718514173)),
 ('GDP at Current Market Prices_quarterly',
  'Money Supply(M2)_monthly',
  np.float64(0.9399986181791238)),
 ('GDP at Current Market Prices_quarterly',
  'Premium_Motor_Spirit(PMS)_monthly',
  np.float64(0.8997331271060133)),
 ('GDP at Current Market Prices_quarterly',
  'bank reserves_monthly',
  np.float64(0.9588442523066327)),
 ('GDP at Current Market Prices_quarterly',
  'consumer_price_index(CPI)_monthly',
  np.float64(0.9614674208652414)),
 ('GDP at Current Market Prices_quarterly',
  'creditToPrivateSector_monthly',
  np.float64(0.9064777379108854)),
 ('GDP at Current Market Prices_quarterly',
  'currency in circulation_monthly',
  np.float64(0.9183205383154911)),
 ('GDP at Current Market Prices_quarterly',
  'netDomesticAssets_monthly',
  np.float64(0.9035436896450181)),
 ('GDP at Current Market Prices_quarterly',
  'netDomesticCredit_monthly',
  np.float64(0.9023760072585345)),
 ('GDP_AGRICULTURE(agric)_quarterly',
  'Money Supply(M2)_monthly',
  np.float64(0.8511381817858177)),
 ('GDP_AGRICULTURE(agric)_quarterly',
  'bank reserves_monthly',
  np.float64(0.88473461935549)),
 ('GDP_AGRICULTURE(agric)_quarterly',
  'consumer_price_index(CPI)_monthly',
  np.float64(0.8784921761357524)),
 ('GDP_INDUSTRY(ind)_quarterly',
  'Money Supply(M2)_monthly',
  np.float64(0.8637301203661936)),
 ('GDP_INDUSTRY(ind)_quarterly',
  'bank reserves_monthly',
  np.float64(0.858797623138937)),
 ('GDP_INDUSTRY(ind)_quarterly',
  'consumer_price_index(CPI)_monthly',
  np.float64(0.8708273810284519)),
 ('GDP_INDUSTRY(ind)_quarterly',
  'creditToGovernment_monthly',
  np.float64(0.9021740645387394)),
 ('GDP_INDUSTRY(ind)_quarterly',
  'creditToPrivateSector_monthly',
  np.float64(0.8936128145595746)),
 ('GDP_INDUSTRY(ind)_quarterly',
  'netDomesticAssets_monthly',
  np.float64(0.886815292793497)),
 ('GDP_INDUSTRY(ind)_quarterly',
  'netDomesticCredit_monthly',
  np.float64(0.9245566422374517)),
 ('MonetaryPolicyRate_monthly',
  'Money Supply(M2)_monthly',
  np.float64(0.9459280575199603)),
 ('MonetaryPolicyRate_monthly',
  'Premium_Motor_Spirit(PMS)_monthly',
  np.float64(0.9263961244934045)),
 ('MonetaryPolicyRate_monthly',
  'bank reserves_monthly',
  np.float64(0.8968052851246248)),
 ('MonetaryPolicyRate_monthly',
  'consumer_price_index(CPI)_monthly',
  np.float64(0.9262710610712299)),
 ('MonetaryPolicyRate_monthly',
  'creditToPrivateSector_monthly',
  np.float64(0.9306027803464241)),
 ('MonetaryPolicyRate_monthly',
  'netDomesticAssets_monthly',
  np.float64(0.8900237638731597)),
 ('MonetaryPolicyRate_monthly',
  'netDomesticCredit_monthly',
  np.float64(0.9038699693636645)),
 ('Money Supply(M2)_monthly',
  'Premium_Motor_Spirit(PMS)_monthly',
  np.float64(0.9401993902050456)),
 ('Money Supply(M2)_monthly',
  'consumer_price_index(CPI)_monthly',
  np.float64(0.9934077341104154)),
 ('Premium_Motor_Spirit(PMS)_monthly',
  'consumer_price_index(CPI)_monthly',
  np.float64(0.9389129356271994)),
 ('bank reserves_monthly',
  'Money Supply(M2)_monthly',
  np.float64(0.9792044057772457)),
 ('bank reserves_monthly',
  'Premium_Motor_Spirit(PMS)_monthly',
  np.float64(0.9299063044577892)),
 ('bank reserves_monthly',
  'consumer_price_index(CPI)_monthly',
  np.float64(0.9885088832100655)),
 ('bank reserves_monthly',
  'currency in circulation_monthly',
  np.float64(0.9286719427841106)),
 ('creditToGovernment_monthly',
  'bank reserves_monthly',
  np.float64(0.8558213577037572)),
 ('creditToGovernment_monthly',
  'consumer_price_index(CPI)_monthly',
  np.float64(0.8703740458801453)),
 ('creditToGovernment_monthly',
  'netDomesticAssets_monthly',
  np.float64(0.9133193511890015)),
 ('creditToGovernment_monthly',
  'netDomesticCredit_monthly',
  np.float64(0.9358730144906805)),
 ('creditToPrivateSector_monthly',
  'Money Supply(M2)_monthly',
  np.float64(0.9857491662081507)),
 ('creditToPrivateSector_monthly',
  'Premium_Motor_Spirit(PMS)_monthly',
  np.float64(0.9137488369092426)),
 ('creditToPrivateSector_monthly',
  'bank reserves_monthly',
  np.float64(0.9562911481952058)),
 ('creditToPrivateSector_monthly',
  'consumer_price_index(CPI)_monthly',
  np.float64(0.9743604957049907)),
 ('creditToPrivateSector_monthly',
  'creditToGovernment_monthly',
  np.float64(0.8629779954332866)),
 ('creditToPrivateSector_monthly',
  'currency in circulation_monthly',
  np.float64(0.9090588750480685)),
 ('creditToPrivateSector_monthly',
  'netDomesticAssets_monthly',
  np.float64(0.9648100509663785)),
 ('creditToPrivateSector_monthly',
  'netDomesticCredit_monthly',
  np.float64(0.9856533377158321)),
 ('currency in circulation_monthly',
  'Money Supply(M2)_monthly',
  np.float64(0.9382037405323014)),
 ('currency in circulation_monthly',
  'Premium_Motor_Spirit(PMS)_monthly',
  np.float64(0.8946279556310451)),
 ('currency in circulation_monthly',
  'consumer_price_index(CPI)_monthly',
  np.float64(0.9369040327260718)),
 ('foreign_reserve_liquid(USD)_daily',
  'foreign_reserve_gross(USD)_daily',
  np.float64(0.9988717860285592)),
 ('gdp_svc_FI_Financial Institutions_quarterly',
  'Exchange_Rate(USD-EOP)_monthly',
  np.float64(0.9376509079044997)),
 ('gdp_svc_FI_Financial Institutions_quarterly',
  'GDP at Current Market Prices_quarterly',
  np.float64(0.8581604995114338)),
 ('gdp_svc_FI_Financial Institutions_quarterly',
  'MonetaryPolicyRate_monthly',
  np.float64(0.9278124053334997)),
 ('gdp_svc_FI_Financial Institutions_quarterly',
  'Money Supply(M2)_monthly',
  np.float64(0.9536094010182748)),
 ('gdp_svc_FI_Financial Institutions_quarterly',
  'Premium_Motor_Spirit(PMS)_monthly',
  np.float64(0.906763608997728)),
 ('gdp_svc_FI_Financial Institutions_quarterly',
  'bank reserves_monthly',
  np.float64(0.9235301824099758)),
 ('gdp_svc_FI_Financial Institutions_quarterly',
  'consumer_price_index(CPI)_monthly',
  np.float64(0.9423852000216606)),
 ('gdp_svc_FI_Financial Institutions_quarterly',
  'creditToPrivateSector_monthly',
  np.float64(0.9390563481243084)),
 ('gdp_svc_FI_Financial Institutions_quarterly',
  'currency in circulation_monthly',
  np.float64(0.889172451750516)),
 ('gdp_svc_FI_Financial Institutions_quarterly',
  'netDomesticAssets_monthly',
  np.float64(0.9294151929900526)),
 ('gdp_svc_FI_Financial Institutions_quarterly',
  'netDomesticCredit_monthly',
  np.float64(0.9262522181233819)),
 ('netDomesticAssets_monthly',
  'Money Supply(M2)_monthly',
  np.float64(0.9660820747994185)),
 ('netDomesticAssets_monthly',
  'Premium_Motor_Spirit(PMS)_monthly',
  np.float64(0.8989563044463242)),
 ('netDomesticAssets_monthly',
  'bank reserves_monthly',
  np.float64(0.9520154061886821)),
 ('netDomesticAssets_monthly',
  'consumer_price_index(CPI)_monthly',
  np.float64(0.9665310861018933)),
 ('netDomesticAssets_monthly',
  'currency in circulation_monthly',
  np.float64(0.9237672136371382)),
 ('netDomesticCredit_monthly',
  'Money Supply(M2)_monthly',
  np.float64(0.9713036895111336)),
 ('netDomesticCredit_monthly',
  'Premium_Motor_Spirit(PMS)_monthly',
  np.float64(0.8979963662240095)),
 ('netDomesticCredit_monthly',
  'bank reserves_monthly',
  np.float64(0.952781570373185)),
 ('netDomesticCredit_monthly',
  'consumer_price_index(CPI)_monthly',
  np.float64(0.9702440034739734)),
 ('netDomesticCredit_monthly',
  'currency in circulation_monthly',
  np.float64(0.8933590825148879)),
 ('netDomesticCredit_monthly',
  'netDomesticAssets_monthly',
  np.float64(0.9779302919522995))}

There are too many features that are highly correlated. This should be because a lot of these macro economic variables increase over that. The correlation might not necessarily be due to actual economic relationship but rather of common driver direction.

(Check Claude AI pinned chat for more)

We will carryout the following steps to get actual reasonable relatonship:
1. Drop the near-duplicate (Crude Oil Export or Domestic Production — pick one).
2. Convert all remaining trending macro levels to % change / differenced versions.
3. Re-run correlation on the differenced set — expect it to shrink substantially.
4. For whatever real correlation remains (likely the money-supply/credit cluster), use VIF to prune, or lean on Lasso/ElasticNet to handle it automatically rather than manually picking.

In [134]:
## Before we drop 'Crude Oil Export_monthly' lets carry out 2 to 4 and see the perfromance
collinear_features=[
    'Crude Oil Export_monthly',
    'Exchange_Rate(USD-EOP)_monthly',
    'GDP at Current Market Prices_quarterly',
    'GDP_AGRICULTURE(agric)_quarterly',
    'GDP_INDUSTRY(ind)_quarterly',
    'MonetaryPolicyRate_monthly',
    'Money Supply(M2)_monthly',
    'Premium_Motor_Spirit(PMS)_monthly',
    'bank reserves_monthly',
    'creditToGovernment_monthly',
    'creditToPrivateSector_monthly',
    'currency in circulation_monthly',
    'foreign_reserve_liquid(USD)_daily',
    'gdp_svc_FI_Financial Institutions_quarterly',
    'netDomesticAssets_monthly',
    'netDomesticCredit_monthly'
]

In [135]:
## We will perform the percent change for the collinear_features
financial_sec_feat[collinear_features]=financial_sec_feat[collinear_features].pct_change()

In [136]:
financial_sec_feat=financial_sec_feat.dropna()

In [137]:
financial_sec_feat.head()

,weighted_sector_returns,sector_volume,consumer_price_index(CPI)_monthly,Inflation_allItemsAverage_monthly,Premium_Motor_Spirit(PMS)_monthly,Crude Oil Price_monthly,Domestic Production_monthly,Crude Oil Export_monthly,Money Supply(M2)_monthly,currency in circulation_monthly,...,MonetaryPolicyRate_monthly,TreasuryBillRate_monthly,Lending_Rate_monthly,Exchange_Rate(USD-EOP)_monthly,GDP_AGRICULTURE(agric)_quarterly,GDP_INDUSTRY(ind)_quarterly,GDP at Current Market Prices_quarterly,gdp_svc_FI_Financial Institutions_quarterly,foreign_reserve_gross(USD)_daily,foreign_reserve_liquid(USD)_daily
66,0.584640,45091739.0,204.45661,17.32,0.0,52.13,1.6,0.0,0.0,0.0,...,0.0,13.6,17.43,0.0,0.0,0.0,0.0,0.0,3.032576e+10,0.000290
67,-0.282732,96410309.0,204.45661,17.32,0.0,52.13,1.6,0.0,0.0,0.0,...,0.0,13.6,17.43,0.0,0.0,0.0,0.0,0.0,3.034555e+10,0.000708
68,0.624710,101585127.0,204.45661,17.32,0.0,52.13,1.6,0.0,0.0,0.0,...,0.0,13.6,17.43,0.0,0.0,0.0,0.0,0.0,3.036654e+10,0.000732
69,-0.184162,51494340.0,204.45661,17.32,0.0,52.13,1.6,0.0,0.0,0.0,...,0.0,13.6,17.43,0.0,0.0,0.0,0.0,0.0,3.039389e+10,0.000964
70,-0.462029,24515324.0,204.45661,17.32,0.0,52.13,1.6,0.0,0.0,0.0,...,0.0,13.6,17.43,0.0,0.0,0.0,0.0,0.0,3.039392e+10,0.000002

In [138]:
financial_sec_feat.columns

Index(['weighted_sector_returns', 'sector_volume',
       'consumer_price_index(CPI)_monthly',
       'Inflation_allItemsAverage_monthly',
       'Premium_Motor_Spirit(PMS)_monthly', 'Crude Oil Price_monthly',
       'Domestic Production_monthly', 'Crude Oil Export_monthly',
       'Money Supply(M2)_monthly', 'currency in circulation_monthly',
       'bank reserves_monthly', 'netForeignAssets_monthly',
       'netDomesticAssets_monthly', 'netDomesticCredit_monthly',
       'creditToGovernment_monthly', 'creditToPrivateSector_monthly',
       'MonetaryPolicyRate_monthly', 'TreasuryBillRate_monthly',
       'Lending_Rate_monthly', 'Exchange_Rate(USD-EOP)_monthly',
       'GDP_AGRICULTURE(agric)_quarterly', 'GDP_INDUSTRY(ind)_quarterly',
       'GDP at Current Market Prices_quarterly',
       'gdp_svc_FI_Financial Institutions_quarterly',
       'foreign_reserve_gross(USD)_daily',
       'foreign_reserve_liquid(USD)_daily'],
      dtype='str')

In [139]:
## Now let us run the correlations again
correlated_features,column_pairs =correlation(financial_sec_feat,0.85)
correlated_features

set()

In [140]:
column_pairs

set()

In [141]:
financial_sec_feat.corr()

,weighted_sector_returns,sector_volume,consumer_price_index(CPI)_monthly,Inflation_allItemsAverage_monthly,Premium_Motor_Spirit(PMS)_monthly,Crude Oil Price_monthly,Domestic Production_monthly,Crude Oil Export_monthly,Money Supply(M2)_monthly,currency in circulation_monthly,...,MonetaryPolicyRate_monthly,TreasuryBillRate_monthly,Lending_Rate_monthly,Exchange_Rate(USD-EOP)_monthly,GDP_AGRICULTURE(agric)_quarterly,GDP_INDUSTRY(ind)_quarterly,GDP at Current Market Prices_quarterly,gdp_svc_FI_Financial Institutions_quarterly,foreign_reserve_gross(USD)_daily,foreign_reserve_liquid(USD)_daily
weighted_sector_returns,1.000000,0.034492,0.036653,0.057603,0.003415,-0.041147,-0.030304,0.028092,0.007552,-0.012657,...,0.013220,0.027303,0.027442,0.045452,-0.035434,-0.002806,-0.012243,0.021613,-0.060494,0.042313
sector_volume,0.034492,1.000000,0.389935,0.264876,0.033217,0.060906,-0.108951,0.013147,0.038449,0.011591,...,0.014136,0.258872,0.260524,0.021206,-0.001449,-0.000178,0.010839,-0.000091,0.113776,0.089309
consumer_price_index(CPI)_monthly,0.036653,0.389935,1.000000,0.709617,0.019704,0.375653,-0.512666,0.012869,0.013772,0.011407,...,0.023133,0.556264,0.419420,0.006356,0.000651,-0.009626,0.018593,0.016886,0.214241,0.076734
Inflation_allItemsAverage_monthly,0.057603,0.264876,0.709617,1.000000,0.031571,0.360264,-0.540422,0.025883,0.034992,0.027223,...,0.056620,0.528257,0.296282,0.028604,0.011589,0.005814,0.024600,0.028755,-0.150351,0.132869
Premium_Motor_Spirit(PMS)_monthly,0.003415,0.033217,0.019704,0.031571,1.000000,0.014436,-0.031047,0.323752,0.025574,0.035051,...,0.093459,-0.013433,-0.001615,0.022557,0.054497,0.085926,0.055555,-0.012748,-0.009238,-0.015755
Crude Oil Price_monthly,-0.041147,0.060906,0.375653,0.360264,0.014436,1.000000,-0.585444,0.023483,0.011084,-0.003144,...,0.080696,0.072776,-0.122272,0.005025,-0.012390,-0.007936,-0.012738,0.006976,0.233760,-0.059462
Domestic Production_monthly,-0.030304,-0.108951,-0.512666,-0.540422,-0.031047,-0.585444,1.000000,0.020443,-0.026183,-0.021195,...,-0.070467,0.156595,0.413703,-0.023251,-0.003585,0.000383,-0.016440,-0.010130,0.222371,0.019817
Crude Oil Export_monthly,0.028092,0.013147,0.012869,0.025883,0.323752,0.023483,0.020443,1.000000,0.099519,-0.158560,...,-0.079577,0.016074,0.020171,0.077740,0.031618,-0.012352,0.034383,0.082607,-0.005196,-0.012409
Money Supply(M2)_monthly,0.007552,0.038449,0.013772,0.034992,0.025574,0.011084,-0.026183,0.099519,1.000000,0.181880,...,0.044556,-0.047953,-0.032984,0.669239,0.028576,0.019237,0.175865,0.145521,-0.038235,-0.011807
currency in circulation_monthly,-0.012657,0.011591,0.011407,0.027223,0.035051,-0.003144,-0.021195,-0.158560,0.181880,1.000000,...,-0.019247,-0.005673,-0.003574,0.038894,-0.125308,0.103426,-0.017993,0.197330,-0.015252,0.015722
bank reserves_monthly,-0.018342,-0.015902,-0.004323,0.000322,0.016562,-0.016758,0.018195,0.039866,0.207747,-0.059934,...,-0.014667,-0.017886,0.009155,-0.036388,0.018737,0.060859,0.072784,0.096139,-0.013255,-0.001342
netForeignAssets_monthly,0.004033,0.336322,0.715968,0.428398,-0.022542,0.076587,0.014717,-0.000357,0.010496,-0.002169,...,0.004099,0.755503,0.680132,0.001571,0.005203,-0.029024,0.022107,-0.008187,0.356095,0.076900
netDomesticAssets_monthly,-0.002095,-0.007420,0.002553,0.007476,-0.007763,0.013209,-0.016314,0.021233,-0.004924,-0.203402,...,-0.012167,-0.021499,-0.014652,-0.001474,0.006511,0.005696,0.005742,0.017943,-0.008721,-0.004760
netDomesticCredit_monthly,-0.003249,0.009699,0.005476,0.007564,0.035854,0.002431,-0.019488,0.004301,0.251478,0.053074,...,0.078122,-0.024966,-0.028692,0.296164,0.235206,0.138512,0.202170,-0.047269,-0.004470,0.018123
creditToGovernment_monthly,-0.008230,-0.000279,0.005209,0.007716,0.016103,0.005475,-0.007683,-0.046637,-0.063066,0.037315,...,0.005298,-0.001599,-0.008610,0.026521,0.126629,0.097320,0.119424,-0.003599,0.000620,-0.016709
creditToPrivateSector_monthly,0.000996,0.016966,0.004756,0.018814,0.016694,-0.000139,-0.017387,0.073244,0.594437,0.103597,...,0.087129,-0.036135,-0.026776,0.583946,0.154439,-0.010948,0.113516,-0.044908,-0.024239,0.017480
MonetaryPolicyRate_monthly,0.013220,0.014136,0.023133,0.056620,0.093459,0.080696,-0.070467,-0.079577,0.044556,-0.019247,...,1.000000,0.015492,-0.025327,0.099781,-0.003968,0.007397,-0.002078,0.067407,-0.033253,-0.042540
TreasuryBillRate_monthly,0.027303,0.258872,0.556264,0.528257,-0.013433,0.072776,0.156595,0.016074,-0.047953,-0.005673,...,0.015492,1.000000,0.836174,-0.031395,0.012178,-0.003520,0.009360,-0.003202,0.271209,0.132124
Lending_Rate_monthly,0.027442,0.260524,0.419420,0.296282,-0.001615,-0.122272,0.413703,0.020171,-0.032984,-0.003574,...,-0.025327,0.836174,1.000000,-0.029856,0.002839,-0.010455,0.004592,0.000499,0.389773,0.146091
Exchange_Rate(USD-EOP)_monthly,0.045452,0.021206,0.006356,0.028604,0.022557,0.005025,-0.023251,0.077740,0.669239,0.038894,...,0.099781,-0.031395,-0.029856,1.000000,0.043343,-0.008754,0.006221,-0.070331,-0.046861,-0.042075
GDP_AGRICULTURE(agric)_quarterly,-0.035434,-0.001449,0.000651,0.011589,0.054497,-0.012390,-0.003585,0.031618,0.028576,-0.125308,...,-0.003968,0.012178,0.002839,0.043343,1.000000,0.363874,0.816518,-0.347082,-0.013307,0.043229
GDP_INDUSTRY(ind)_quarterly,-0.002806,-0.000178,-0.009626,0.005814,0.085926,-0.007936,0.000383,-0.012352,0.019237,0.103426,...,0.007397,-0.003520,-0.010455,-0.008754,0.363874,1.000000,0.361502,-0.222106,0.025980,0.088020
GDP at Current Market Prices_quarterly,-0.012243,0.010839,0.018593,0.024600,0.055555,-0.012738,-0.016440,0.034383,0.175865,-0.017993,...,-0.002078,0.009360,0.004592,0.006221,0.816518,0.361502,1.000000,-0.068956,-0.007059,0.055286
gdp_svc_FI_Financial Institutions_quarterly,0.021613,-0.000091,0.016886,0.028755,-0.012748,0.006976,-0.010130,0.082607,0.145521,0.197330,...,0.067407,-0.003202,0.000499,-0.070331,-0.347082,-0.222106,-0.068956,1.000000,-0.007969,0.009691
foreign_reserve_gross(USD)_daily,-0.060494,0.113776,0.214241,-0.150351,-0.009238,0.233760,0.222371,-0.005196,-0.038235,-0.015252,...,-0.033253,0.271209,0.389773,-0.046861,-0.013307,0.025980,-0.007059,-0.007969,1.000000,0.032382
foreign_reserve_liquid(USD)_daily,0.042313,0.089309,0.076734,0.132869,-0.015755,-0.059462,0.019817,-0.012409,-0.011807,0.015722,...,-0.042540,0.132124,0.146091,-0.042075,0.043229,0.088020,0.055286,0.009691,0.032382,1.000000

### FANTASTIC!!! 

We have handled the issue of multicollinearity. Percent change has a better economic meaning than the actual values.

In [143]:
## Independent features
X=financial_sec_feat.drop(columns=['weighted_sector_returns'])

In [144]:
## dependent features
y=financial_sec_feat['weighted_sector_returns']

In [145]:
## Apply standard scaler
from sklearn.preprocessing import StandardScaler

# Initialize the scaler
scaler = StandardScaler()

In [147]:
# X: independent features, y: sector returns
# CRITICAL: X and y must already be sorted by date, ascending
# X = X.sort_values('date')  # or however df is indexed. Our df is 
# y = y.loc[X.index]

tscv = TimeSeriesSplit(n_splits=5)  # 5 sequential folds

rmse_scores = []
r2scores = []
for fold, (train_idx, test_idx) in enumerate(tscv.split(X)):
    X_train, X_test = X.iloc[train_idx], X.iloc[test_idx] ## This area uses the index to pick the data from X and y
    y_train, y_test = y.iloc[train_idx], y.iloc[test_idx]

    ## Apply standardscaler to standardize the data
    # Fit to the training data (calculates mean and std)
    scaler.fit(X_train)

    # Transform the training and testing data
    X_train_scaled = scaler.transform(X_train)
    X_test_scaled = scaler.transform(X_test)


    model = Ridge(alpha=1.0)
    model.fit(X_train_scaled, y_train)
    preds = model.predict(X_test_scaled)

    rmse = np.sqrt(mean_squared_error(y_test, preds))
    rmse_scores.append(rmse)

    r2_=r2_score(y_true=y_test,y_pred=preds)
    r2scores.append(r2_)

    print(f"Fold {fold}: train={len(X_train)} rows ({X_train.index.min()} to {X_train.index.max()}), "
          f"test={len(X_test)} rows ({X_test.index.min()} to {X_test.index.max()}), RMSE={rmse:.4f}, r2score={r2_:.4f}")
    
print(f"\nMean RMSE across folds: {np.mean(rmse_scores):.4f}")
print(f"\nMean R2_score across folds: {np.mean(r2scores):.4f}")

Fold 0: train=360 rows (66 to 426), test=358 rows (427 to 787), RMSE=7.9962, r2score=-16.1008
Fold 1: train=718 rows (66 to 787), test=358 rows (788 to 1158), RMSE=2.8566, r2score=-2.4645
Fold 2: train=1076 rows (66 to 1158), test=358 rows (1159 to 1527), RMSE=1.3649, r2score=-1.1822
Fold 3: train=1434 rows (66 to 1527), test=358 rows (1529 to 1912), RMSE=2.1874, r2score=-0.1836
Fold 4: train=1792 rows (66 to 1912), test=358 rows (1913 to 2277), RMSE=1.5165, r2score=-0.0187

Mean RMSE across folds: 3.1843

Mean R2_score across folds: -3.9899

## VERY, VERY BAD! Please revisit.