## Monthly Data Training

We will sort the daily data to fit monthly

In [4]:
import pandas as pd
from datetime import datetime as dt

# 1. Generate the date range from January 1, 2017, up to today
date_series = pd.date_range(start='2017-01-01', end=dt.now(), freq='ME')

# 2. Create the DataFrame and format the dates as %Y-%m-%d
df = pd.DataFrame()
df['date'] = date_series.strftime('%Y-%m-%d')

In [5]:
df

           date
0    2017-01-31
1    2017-02-28
2    2017-03-31
3    2017-04-30
4    2017-05-31
..          ...
110  2026-03-31
111  2026-04-30
112  2026-05-31
113  2026-06-30
114  2026-07-31

[115 rows x 1 columns]

In [6]:
md=pd.read_csv('macroeconomic_data/macro_data(csv)')
md

,year,month,month_idx,consumer_price_index(CPI)_monthly,Crude Oil Price_monthly,Domestic Production_monthly,Crude Oil Export_monthly,Inflation_allItemsAverage_monthly,Money Supply(M2)_monthly,currency in circulation_monthly,...,gdp_svc_Public Administration_quarterly,gdp_svc_Education_quarterly,gdp_svc_Human Health & Social Services_quarterly,gdp_svc_Other Services_quarterly,GDP at Current Basic Prices_quarterly,Net Taxes on Products_quarterly,GDP at Current Market Prices_quarterly,FR_Date,foreign_reserve_Gross(USD)_monthly,foreign_reserve_Liquid(USD)_monthly
0,2017.0,january,1,198.041241,55.01,1.84,1.39,16.44,23096526.55,1994577.62,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01/31/2017,2.817423e+10,2.745703e+10
1,NaN,february,2,201.001141,46.39,1.82,1.37,16.96,22210954.84,1978886.94,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,02/28/2017,2.964668e+10,2.894094e+10
2,NaN,march,3,204.456610,52.13,1.60,1.15,17.32,22304267.84,1983633.07,...,680.04,587.79,186.24,1237.68,26028.36,200.5,26228.85,03/31/2017,3.029795e+10,2.962647e+10
3,NaN,april,4,207.729678,52.94,1.79,1.34,17.59,21768241.12,1975812.32,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,04/28/2017,3.086463e+10,3.017061e+10
4,NaN,may,5,211.637809,50.57,1.87,1.42,17.63,22047770.68,1897917.15,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,05/31/2017,3.032964e+10,2.961376e+10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,NaN,august,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,07/16/2026,5.191564e+10,5.129593e+10
116,NaN,september,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
117,NaN,october,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
118,NaN,november,11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
119,NaN,december,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
mde=pd.read_excel('macroeconomic_data/NGX_Macro_project_data(complete).xlsx')
mde

,year,month,month_idx,consumer_price_index(CPI)_monthly,Crude Oil Price_monthly,Domestic Production_monthly,Crude Oil Export_monthly,Inflation_allItemsAverage_monthly,Money Supply(M2)_monthly,currency in circulation_monthly,...,gdp_svc_Public Administration_quarterly,gdp_svc_Education_quarterly,gdp_svc_Human Health & Social Services_quarterly,gdp_svc_Other Services_quarterly,GDP at Current Basic Prices_quarterly,Net Taxes on Products_quarterly,GDP at Current Market Prices_quarterly,FR_Date,foreign_reserve_Gross(USD)_monthly,foreign_reserve_Liquid(USD)_monthly
0,2017.0,january,1,198.041241,55.01,1.84,1.39,16.44,23096526.55,1994577.62,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01/31/2017,2.817423e+10,2.745703e+10
1,NaN,february,2,201.001141,46.39,1.82,1.37,16.96,22210954.84,1978886.94,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,02/28/2017,2.964668e+10,2.894094e+10
2,NaN,march,3,204.456610,52.13,1.60,1.15,17.32,22304267.84,1983633.07,...,680.04,587.79,186.24,1237.68,26028.36,200.5,26228.85,03/31/2017,3.029795e+10,2.962647e+10
3,NaN,april,4,207.729678,52.94,1.79,1.34,17.59,21768241.12,1975812.32,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,04/28/2017,3.086463e+10,3.017061e+10
4,NaN,may,5,211.637809,50.57,1.87,1.42,17.63,22047770.68,1897917.15,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,05/31/2017,3.032964e+10,2.961376e+10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,NaN,august,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,07/16/2026,5.191564e+10,5.129593e+10
116,NaN,september,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
117,NaN,october,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
118,NaN,november,11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
119,NaN,december,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
mde2=pd.read_excel('macroeconomic_data/NGX_Macro_project_data(complete22).xlsx')
mde2

,year,month,month_idx,consumer_price_index(CPI)_monthly,Crude Oil Price_monthly,Domestic Production_monthly,Crude Oil Export_monthly,Inflation_allItemsAverage_monthly,Money Supply(M2)_monthly,currency in circulation_monthly,...,gdp_svc_Public Administration_quarterly,gdp_svc_Education_quarterly,gdp_svc_Human Health & Social Services_quarterly,gdp_svc_Other Services_quarterly,GDP at Current Basic Prices_quarterly,Net Taxes on Products_quarterly,GDP at Current Market Prices_quarterly,FR_Date,foreign_reserve_Gross(USD)_monthly,foreign_reserve_Liquid(USD)_monthly
0,2017.0,january,1,198.041241,55.01,1.84,1.39,16.44,23096526.55,1994577.62,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01/31/2017,2.817423e+10,2.745703e+10
1,NaN,february,2,201.001141,46.39,1.82,1.37,16.96,22210954.84,1978886.94,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,02/28/2017,2.964668e+10,2.894094e+10
2,NaN,march,3,204.456610,52.13,1.60,1.15,17.32,22304267.84,1983633.07,...,680.04,587.79,186.24,1237.68,26028.36,200.5,26228.85,03/31/2017,3.029795e+10,2.962647e+10
3,NaN,april,4,207.729678,52.94,1.79,1.34,17.59,21768241.12,1975812.32,...,680.04,587.79,186.24,1237.68,26028.36,200.5,26228.85,04/28/2017,3.086463e+10,3.017061e+10
4,NaN,may,5,211.637809,50.57,1.87,1.42,17.63,22047770.68,1897917.15,...,680.04,587.79,186.24,1237.68,26028.36,200.5,26228.85,05/31/2017,3.032964e+10,2.961376e+10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,NaN,august,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,07/16/2026,5.191564e+10,5.129593e+10
116,NaN,september,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
117,NaN,october,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
118,NaN,november,11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
119,NaN,december,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
mde2['FR_Date'] = pd.to_datetime(mde2['FR_Date']).dt.strftime('%Y-%m-%d')