## Monthly Data Training

We will sort the daily data to fit monthly

In [1]:
import pandas as pd
from datetime import datetime as dt

# 1. Generate the date range from January 1, 2017, up to today
date_series = pd.date_range(start='2017-01-01', end=dt.now(), freq='ME')

# 2. Create the DataFrame and format the dates as %Y-%m-%d
df = pd.DataFrame()
df['date'] = date_series.strftime('%Y-%m-%d')

In [2]:
df

           date
0    2017-01-31
1    2017-02-28
2    2017-03-31
3    2017-04-30
4    2017-05-31
..          ...
110  2026-03-31
111  2026-04-30
112  2026-05-31
113  2026-06-30
114  2026-07-31

[115 rows x 1 columns]

In [3]:
md=pd.read_csv('macroeconomic_data/macro_data(csv)')
md

,year,month,month_idx,consumer_price_index(CPI)_monthly,Crude Oil Price_monthly,Domestic Production_monthly,Crude Oil Export_monthly,Inflation_allItemsAverage_monthly,Money Supply(M2)_monthly,currency in circulation_monthly,...,gdp_svc_Public Administration_quarterly,gdp_svc_Education_quarterly,gdp_svc_Human Health & Social Services_quarterly,gdp_svc_Other Services_quarterly,GDP at Current Basic Prices_quarterly,Net Taxes on Products_quarterly,GDP at Current Market Prices_quarterly,FR_Date,foreign_reserve_Gross(USD)_monthly,foreign_reserve_Liquid(USD)_monthly
0,2017.0,january,1,198.041241,55.01,1.84,1.39,16.44,23096526.55,1994577.62,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01/31/2017,2.817423e+10,2.745703e+10
1,NaN,february,2,201.001141,46.39,1.82,1.37,16.96,22210954.84,1978886.94,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,02/28/2017,2.964668e+10,2.894094e+10
2,NaN,march,3,204.456610,52.13,1.60,1.15,17.32,22304267.84,1983633.07,...,680.04,587.79,186.24,1237.68,26028.36,200.5,26228.85,03/31/2017,3.029795e+10,2.962647e+10
3,NaN,april,4,207.729678,52.94,1.79,1.34,17.59,21768241.12,1975812.32,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,04/28/2017,3.086463e+10,3.017061e+10
4,NaN,may,5,211.637809,50.57,1.87,1.42,17.63,22047770.68,1897917.15,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,05/31/2017,3.032964e+10,2.961376e+10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,NaN,august,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,07/16/2026,5.191564e+10,5.129593e+10
116,NaN,september,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
117,NaN,october,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
118,NaN,november,11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
119,NaN,december,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
mde=pd.read_excel('macroeconomic_data/NGX_Macro_project_data(complete).xlsx')
mde

,year,month,month_idx,consumer_price_index(CPI)_monthly,Crude Oil Price_monthly,Domestic Production_monthly,Crude Oil Export_monthly,Inflation_allItemsAverage_monthly,Money Supply(M2)_monthly,currency in circulation_monthly,...,gdp_svc_Public Administration_quarterly,gdp_svc_Education_quarterly,gdp_svc_Human Health & Social Services_quarterly,gdp_svc_Other Services_quarterly,GDP at Current Basic Prices_quarterly,Net Taxes on Products_quarterly,GDP at Current Market Prices_quarterly,FR_Date,foreign_reserve_Gross(USD)_monthly,foreign_reserve_Liquid(USD)_monthly
0,2017.0,january,1,198.041241,55.01,1.84,1.39,16.44,23096526.55,1994577.62,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01/31/2017,2.817423e+10,2.745703e+10
1,NaN,february,2,201.001141,46.39,1.82,1.37,16.96,22210954.84,1978886.94,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,02/28/2017,2.964668e+10,2.894094e+10
2,NaN,march,3,204.456610,52.13,1.60,1.15,17.32,22304267.84,1983633.07,...,680.04,587.79,186.24,1237.68,26028.36,200.5,26228.85,03/31/2017,3.029795e+10,2.962647e+10
3,NaN,april,4,207.729678,52.94,1.79,1.34,17.59,21768241.12,1975812.32,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,04/28/2017,3.086463e+10,3.017061e+10
4,NaN,may,5,211.637809,50.57,1.87,1.42,17.63,22047770.68,1897917.15,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,05/31/2017,3.032964e+10,2.961376e+10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,NaN,august,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,07/16/2026,5.191564e+10,5.129593e+10
116,NaN,september,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
117,NaN,october,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
118,NaN,november,11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
119,NaN,december,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
mde2=pd.read_excel('macroeconomic_data/NGX_Macro_project_data(complete22).xlsx')
mde2

,year,month,month_idx,consumer_price_index(CPI)_monthly,Crude Oil Price_monthly,Domestic Production_monthly,Crude Oil Export_monthly,Inflation_allItemsAverage_monthly,Money Supply(M2)_monthly,currency in circulation_monthly,...,gdp_svc_Public Administration_quarterly,gdp_svc_Education_quarterly,gdp_svc_Human Health & Social Services_quarterly,gdp_svc_Other Services_quarterly,GDP at Current Basic Prices_quarterly,Net Taxes on Products_quarterly,GDP at Current Market Prices_quarterly,FR_Date,foreign_reserve_Gross(USD)_monthly,foreign_reserve_Liquid(USD)_monthly
0,2017.0,january,1,198.041241,55.01,1.84,1.39,16.44,23096526.55,1994577.62,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01/31/2017,2.817423e+10,2.745703e+10
1,NaN,february,2,201.001141,46.39,1.82,1.37,16.96,22210954.84,1978886.94,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,02/28/2017,2.964668e+10,2.894094e+10
2,NaN,march,3,204.456610,52.13,1.60,1.15,17.32,22304267.84,1983633.07,...,680.04,587.79,186.24,1237.68,26028.36,200.5,26228.85,03/31/2017,3.029795e+10,2.962647e+10
3,NaN,april,4,207.729678,52.94,1.79,1.34,17.59,21768241.12,1975812.32,...,680.04,587.79,186.24,1237.68,26028.36,200.5,26228.85,04/28/2017,3.086463e+10,3.017061e+10
4,NaN,may,5,211.637809,50.57,1.87,1.42,17.63,22047770.68,1897917.15,...,680.04,587.79,186.24,1237.68,26028.36,200.5,26228.85,05/31/2017,3.032964e+10,2.961376e+10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,NaN,august,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,07/16/2026,5.191564e+10,5.129593e+10
116,NaN,september,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
117,NaN,october,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
118,NaN,november,11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
119,NaN,december,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
mde2['FR_Date'] = pd.to_datetime(mde2['FR_Date']).dt.strftime('%Y-%m-%d')

In [8]:
mde2["date"] = pd.date_range(
    start="2017-01-31",
    periods=len(mde2),
    freq="ME"
)

In [9]:
mde2

,year,month,month_idx,consumer_price_index(CPI)_monthly,Crude Oil Price_monthly,Domestic Production_monthly,Crude Oil Export_monthly,Inflation_allItemsAverage_monthly,Money Supply(M2)_monthly,currency in circulation_monthly,...,gdp_svc_Education_quarterly,gdp_svc_Human Health & Social Services_quarterly,gdp_svc_Other Services_quarterly,GDP at Current Basic Prices_quarterly,Net Taxes on Products_quarterly,GDP at Current Market Prices_quarterly,FR_Date,foreign_reserve_Gross(USD)_monthly,foreign_reserve_Liquid(USD)_monthly,date
0,2017.0,january,1,198.041241,55.01,1.84,1.39,16.44,23096526.55,1994577.62,...,NaN,NaN,NaN,NaN,NaN,NaN,2017-01-31,2.817423e+10,2.745703e+10,2017-01-31
1,NaN,february,2,201.001141,46.39,1.82,1.37,16.96,22210954.84,1978886.94,...,NaN,NaN,NaN,NaN,NaN,NaN,2017-02-28,2.964668e+10,2.894094e+10,2017-02-28
2,NaN,march,3,204.456610,52.13,1.60,1.15,17.32,22304267.84,1983633.07,...,587.79,186.24,1237.68,26028.36,200.5,26228.85,2017-03-31,3.029795e+10,2.962647e+10,2017-03-31
3,NaN,april,4,207.729678,52.94,1.79,1.34,17.59,21768241.12,1975812.32,...,587.79,186.24,1237.68,26028.36,200.5,26228.85,2017-04-28,3.086463e+10,3.017061e+10,2017-04-30
4,NaN,may,5,211.637809,50.57,1.87,1.42,17.63,22047770.68,1897917.15,...,587.79,186.24,1237.68,26028.36,200.5,26228.85,2017-05-31,3.032964e+10,2.961376e+10,2017-05-31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,NaN,august,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2026-07-16,5.191564e+10,5.129593e+10,2026-08-31
116,NaN,september,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-09-30
117,NaN,october,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-10-31
118,NaN,november,11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-11-30
119,NaN,december,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-12-31

shift the foreign reserve data to avoid look ahead bias we will shift the monthly data by 1 month. So the information is used to predict the next months returns.

In [12]:
mde2[['foreign_reserve_Gross(USD)_monthly','foreign_reserve_Liquid(USD)_monthly']]=mde2[['foreign_reserve_Gross(USD)_monthly','foreign_reserve_Liquid(USD)_monthly']].shift(1)

In [13]:
mde2

,year,month,month_idx,consumer_price_index(CPI)_monthly,Crude Oil Price_monthly,Domestic Production_monthly,Crude Oil Export_monthly,Inflation_allItemsAverage_monthly,Money Supply(M2)_monthly,currency in circulation_monthly,...,gdp_svc_Education_quarterly,gdp_svc_Human Health & Social Services_quarterly,gdp_svc_Other Services_quarterly,GDP at Current Basic Prices_quarterly,Net Taxes on Products_quarterly,GDP at Current Market Prices_quarterly,FR_Date,foreign_reserve_Gross(USD)_monthly,foreign_reserve_Liquid(USD)_monthly,date
0,2017.0,january,1,198.041241,55.01,1.84,1.39,16.44,23096526.55,1994577.62,...,NaN,NaN,NaN,NaN,NaN,NaN,2017-01-31,NaN,NaN,2017-01-31
1,NaN,february,2,201.001141,46.39,1.82,1.37,16.96,22210954.84,1978886.94,...,NaN,NaN,NaN,NaN,NaN,NaN,2017-02-28,2.817423e+10,2.745703e+10,2017-02-28
2,NaN,march,3,204.456610,52.13,1.60,1.15,17.32,22304267.84,1983633.07,...,587.79,186.24,1237.68,26028.36,200.5,26228.85,2017-03-31,2.964668e+10,2.894094e+10,2017-03-31
3,NaN,april,4,207.729678,52.94,1.79,1.34,17.59,21768241.12,1975812.32,...,587.79,186.24,1237.68,26028.36,200.5,26228.85,2017-04-28,3.029795e+10,2.962647e+10,2017-04-30
4,NaN,may,5,211.637809,50.57,1.87,1.42,17.63,22047770.68,1897917.15,...,587.79,186.24,1237.68,26028.36,200.5,26228.85,2017-05-31,3.086463e+10,3.017061e+10,2017-05-31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,NaN,august,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2026-07-16,5.145923e+10,5.081045e+10,2026-08-31
116,NaN,september,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.191564e+10,5.129593e+10,2026-09-30
117,NaN,october,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-10-31
118,NaN,november,11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-11-30
119,NaN,december,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-12-31

In [14]:
mde3=mde2.drop(columns=['year','month','month_idx'])

In [15]:
mde3

,consumer_price_index(CPI)_monthly,Crude Oil Price_monthly,Domestic Production_monthly,Crude Oil Export_monthly,Inflation_allItemsAverage_monthly,Money Supply(M2)_monthly,currency in circulation_monthly,bank reserves_monthly,netForeignAssets_monthly,netDomesticAssets_monthly,...,gdp_svc_Education_quarterly,gdp_svc_Human Health & Social Services_quarterly,gdp_svc_Other Services_quarterly,GDP at Current Basic Prices_quarterly,Net Taxes on Products_quarterly,GDP at Current Market Prices_quarterly,FR_Date,foreign_reserve_Gross(USD)_monthly,foreign_reserve_Liquid(USD)_monthly,date
0,198.041241,55.01,1.84,1.39,16.44,23096526.55,1994577.62,3311609.44,9473002.48,19005647.02,...,NaN,NaN,NaN,NaN,NaN,NaN,2017-01-31,NaN,NaN,2017-01-31
1,201.001141,46.39,1.82,1.37,16.96,22210954.84,1978886.94,3234760.81,7977399.24,19746640.86,...,NaN,NaN,NaN,NaN,NaN,NaN,2017-02-28,2.817423e+10,2.745703e+10,2017-02-28
2,204.456610,52.13,1.60,1.15,17.32,22304267.84,1983633.07,3309947.53,7628543.46,20342546.55,...,587.79,186.24,1237.68,26028.36,200.5,26228.85,2017-03-31,2.964668e+10,2.894094e+10,2017-03-31
3,207.729678,52.94,1.79,1.34,17.59,21768241.12,1975812.32,3536407.29,7269852.64,20347360.25,...,587.79,186.24,1237.68,26028.36,200.5,26228.85,2017-04-28,3.029795e+10,2.962647e+10,2017-04-30
4,211.637809,50.57,1.87,1.42,17.63,22047770.68,1897917.15,3254006.25,8540084.49,19499233.11,...,587.79,186.24,1237.68,26028.36,200.5,26228.85,2017-05-31,3.086463e+10,3.017061e+10,2017-05-31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2026-07-16,5.145923e+10,5.081045e+10,2026-08-31
116,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.191564e+10,5.129593e+10,2026-09-30
117,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-10-31
118,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-11-30
119,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-12-31

In [18]:
for column in mde3.columns:
    if column.endswith('_monthly'):
        mde3[column]=mde3[column].shift(1)

In [19]:
## We performed the shift in mde2
mde3

,consumer_price_index(CPI)_monthly,Crude Oil Price_monthly,Domestic Production_monthly,Crude Oil Export_monthly,Inflation_allItemsAverage_monthly,Money Supply(M2)_monthly,currency in circulation_monthly,bank reserves_monthly,netForeignAssets_monthly,netDomesticAssets_monthly,...,gdp_svc_Education_quarterly,gdp_svc_Human Health & Social Services_quarterly,gdp_svc_Other Services_quarterly,GDP at Current Basic Prices_quarterly,Net Taxes on Products_quarterly,GDP at Current Market Prices_quarterly,FR_Date,foreign_reserve_Gross(USD)_monthly,foreign_reserve_Liquid(USD)_monthly,date
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2017-01-31,NaN,NaN,2017-01-31
1,198.041241,55.01,1.84,1.39,16.44,23096526.55,1994577.62,3311609.44,9473002.48,19005647.02,...,NaN,NaN,NaN,NaN,NaN,NaN,2017-02-28,NaN,NaN,2017-02-28
2,201.001141,46.39,1.82,1.37,16.96,22210954.84,1978886.94,3234760.81,7977399.24,19746640.86,...,587.79,186.24,1237.68,26028.36,200.5,26228.85,2017-03-31,2.817423e+10,2.745703e+10,2017-03-31
3,204.456610,52.13,1.60,1.15,17.32,22304267.84,1983633.07,3309947.53,7628543.46,20342546.55,...,587.79,186.24,1237.68,26028.36,200.5,26228.85,2017-04-28,2.964668e+10,2.894094e+10,2017-04-30
4,207.729678,52.94,1.79,1.34,17.59,21768241.12,1975812.32,3536407.29,7269852.64,20347360.25,...,587.79,186.24,1237.68,26028.36,200.5,26228.85,2017-05-31,3.029795e+10,2.962647e+10,2017-05-31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2026-07-16,4.958097e+10,4.889970e+10,2026-08-31
116,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.145923e+10,5.081045e+10,2026-09-30
117,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.191564e+10,5.129593e+10,2026-10-31
118,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-11-30
119,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-12-31

In [20]:
mde3[['foreign_reserve_Gross(USD)_monthly','foreign_reserve_Liquid(USD)_monthly']]=mde3[['foreign_reserve_Gross(USD)_monthly','foreign_reserve_Liquid(USD)_monthly']].shift(-1)

In [21]:
mde3

,consumer_price_index(CPI)_monthly,Crude Oil Price_monthly,Domestic Production_monthly,Crude Oil Export_monthly,Inflation_allItemsAverage_monthly,Money Supply(M2)_monthly,currency in circulation_monthly,bank reserves_monthly,netForeignAssets_monthly,netDomesticAssets_monthly,...,gdp_svc_Education_quarterly,gdp_svc_Human Health & Social Services_quarterly,gdp_svc_Other Services_quarterly,GDP at Current Basic Prices_quarterly,Net Taxes on Products_quarterly,GDP at Current Market Prices_quarterly,FR_Date,foreign_reserve_Gross(USD)_monthly,foreign_reserve_Liquid(USD)_monthly,date
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2017-01-31,NaN,NaN,2017-01-31
1,198.041241,55.01,1.84,1.39,16.44,23096526.55,1994577.62,3311609.44,9473002.48,19005647.02,...,NaN,NaN,NaN,NaN,NaN,NaN,2017-02-28,2.817423e+10,2.745703e+10,2017-02-28
2,201.001141,46.39,1.82,1.37,16.96,22210954.84,1978886.94,3234760.81,7977399.24,19746640.86,...,587.79,186.24,1237.68,26028.36,200.5,26228.85,2017-03-31,2.964668e+10,2.894094e+10,2017-03-31
3,204.456610,52.13,1.60,1.15,17.32,22304267.84,1983633.07,3309947.53,7628543.46,20342546.55,...,587.79,186.24,1237.68,26028.36,200.5,26228.85,2017-04-28,3.029795e+10,2.962647e+10,2017-04-30
4,207.729678,52.94,1.79,1.34,17.59,21768241.12,1975812.32,3536407.29,7269852.64,20347360.25,...,587.79,186.24,1237.68,26028.36,200.5,26228.85,2017-05-31,3.086463e+10,3.017061e+10,2017-05-31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2026-07-16,5.145923e+10,5.081045e+10,2026-08-31
116,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.191564e+10,5.129593e+10,2026-09-30
117,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-10-31
118,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-11-30
119,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-12-31

We are now done with the macroeconomic variables. We will head over to the stock_data. We will start with the finance sector stock data.

In [22]:
fin_sec_data=pd.read_csv('feature_engineering/stocks_sectors/financial_services/financial_services_sector')

In [23]:
fin_sec_data

,date,sector,weighted_sector_returns,n_stocks_contributing,sector_index,sector_volume
0,2017-01-03,financial_services,0.000000,20.0,100.000000,48125518.0
1,2017-01-04,financial_services,0.353432,20.0,100.353432,26705191.0
2,2017-01-05,financial_services,-0.182223,20.0,100.170565,66991076.0
3,2017-01-06,financial_services,1.397196,20.0,101.570144,97521276.0
4,2017-01-09,financial_services,3.645896,20.0,105.273286,99013315.0
...,...,...,...,...,...,...
2258,2026-07-13,financial_services,-0.746327,35.0,2695.019313,290562049.0
2259,2026-07-14,financial_services,0.906947,35.0,2719.461701,163509442.0
2260,2026-07-15,financial_services,0.779799,35.0,2740.668037,258362267.0
2261,2026-07-16,financial_services,1.505893,35.0,2781.939574,261040578.0
2262,2026-07-17,financial_services,1.536021,35.0,2824.670764,295044834.0

In [24]:
fin_sec_data_clean=fin_sec_data.copy()

In [25]:
fin_sec_data_clean['sector_volume']=fin_sec_data_clean['sector_volume'].shift(1)

In [27]:
fin_sec_data_clean=fin_sec_data_clean.drop('sector',axis=1)

In [28]:
fin_sec_data_clean

,date,weighted_sector_returns,n_stocks_contributing,sector_index,sector_volume
0,2017-01-03,0.000000,20.0,100.000000,NaN
1,2017-01-04,0.353432,20.0,100.353432,48125518.0
2,2017-01-05,-0.182223,20.0,100.170565,26705191.0
3,2017-01-06,1.397196,20.0,101.570144,66991076.0
4,2017-01-09,3.645896,20.0,105.273286,97521276.0
...,...,...,...,...,...
2258,2026-07-13,-0.746327,35.0,2695.019313,242350071.0
2259,2026-07-14,0.906947,35.0,2719.461701,290562049.0
2260,2026-07-15,0.779799,35.0,2740.668037,163509442.0
2261,2026-07-16,1.505893,35.0,2781.939574,258362267.0
2262,2026-07-17,1.536021,35.0,2824.670764,261040578.0

In [29]:
fin_sec_data_clean=fin_sec_data_clean.dropna()

In [31]:
fin_sec_data_clean['date']=pd.to_datetime(fin_sec_data_clean['date'])

In [33]:
print(fin_sec_data_clean['date'].dtypes)

datetime64[us]

In [43]:
mde3["month"] = mde3["date"].dt.to_period("M")
fin_sec_data_clean["month"] = fin_sec_data_clean["date"].dt.to_period("M")

In [44]:
mde3

,consumer_price_index(CPI)_monthly,Crude Oil Price_monthly,Domestic Production_monthly,Crude Oil Export_monthly,Inflation_allItemsAverage_monthly,Money Supply(M2)_monthly,currency in circulation_monthly,bank reserves_monthly,netForeignAssets_monthly,netDomesticAssets_monthly,...,gdp_svc_Human Health & Social Services_quarterly,gdp_svc_Other Services_quarterly,GDP at Current Basic Prices_quarterly,Net Taxes on Products_quarterly,GDP at Current Market Prices_quarterly,FR_Date,foreign_reserve_Gross(USD)_monthly,foreign_reserve_Liquid(USD)_monthly,date,month
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,2017-01-31,NaN,NaN,2017-01-31,2017-01
1,198.041241,55.01,1.84,1.39,16.44,23096526.55,1994577.62,3311609.44,9473002.48,19005647.02,...,NaN,NaN,NaN,NaN,NaN,2017-02-28,2.817423e+10,2.745703e+10,2017-02-28,2017-02
2,201.001141,46.39,1.82,1.37,16.96,22210954.84,1978886.94,3234760.81,7977399.24,19746640.86,...,186.24,1237.68,26028.36,200.5,26228.85,2017-03-31,2.964668e+10,2.894094e+10,2017-03-31,2017-03
3,204.456610,52.13,1.60,1.15,17.32,22304267.84,1983633.07,3309947.53,7628543.46,20342546.55,...,186.24,1237.68,26028.36,200.5,26228.85,2017-04-28,3.029795e+10,2.962647e+10,2017-04-30,2017-04
4,207.729678,52.94,1.79,1.34,17.59,21768241.12,1975812.32,3536407.29,7269852.64,20347360.25,...,186.24,1237.68,26028.36,200.5,26228.85,2017-05-31,3.086463e+10,3.017061e+10,2017-05-31,2017-05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,2026-07-16,5.145923e+10,5.081045e+10,2026-08-31,2026-08
116,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,5.191564e+10,5.129593e+10,2026-09-30,2026-09
117,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-10-31,2026-10
118,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-11-30,2026-11
119,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-12-31,2026-12

In [45]:
fin_sec_data_clean

,date,weighted_sector_returns,n_stocks_contributing,sector_index,sector_volume,month
1,2017-01-04,0.353432,20.0,100.353432,48125518.0,2017-01
2,2017-01-05,-0.182223,20.0,100.170565,26705191.0,2017-01
3,2017-01-06,1.397196,20.0,101.570144,66991076.0,2017-01
4,2017-01-09,3.645896,20.0,105.273286,97521276.0,2017-01
5,2017-01-10,-1.454119,20.0,103.742486,99013315.0,2017-01
...,...,...,...,...,...,...
2258,2026-07-13,-0.746327,35.0,2695.019313,242350071.0,2026-07
2259,2026-07-14,0.906947,35.0,2719.461701,290562049.0,2026-07
2260,2026-07-15,0.779799,35.0,2740.668037,163509442.0,2026-07
2261,2026-07-16,1.505893,35.0,2781.939574,258362267.0,2026-07
2262,2026-07-17,1.536021,35.0,2824.670764,261040578.0,2026-07

In [46]:
## Get last day of the month
fin_sec_monthly = (
    fin_sec_data_clean
    .sort_values("date")
    .groupby("month")
    .last()
    .reset_index()
)

In [47]:
fin_sec_monthly

,month,date,weighted_sector_returns,n_stocks_contributing,sector_index,sector_volume
0,2017-01,2017-01-31,-0.996463,20.0,109.001843,87259637.0
1,2017-02,2017-02-28,0.649545,21.0,107.626307,169938472.0
2,2017-03,2017-03-31,-0.017945,21.0,105.456849,141367620.0
3,2017-04,2017-04-28,1.815887,20.0,115.418966,120760980.0
4,2017-05,2017-05-31,-2.338342,21.0,138.127184,261656035.0
...,...,...,...,...,...,...
110,2026-03,2026-03-31,-1.878773,35.0,2347.696835,294022203.0
111,2026-04,2026-04-30,1.404651,35.0,2856.819058,809264585.0
112,2026-05,2026-05-29,-0.883768,35.0,2959.843133,341760831.0
113,2026-06,2026-06-30,-1.000082,35.0,2664.183854,480278073.0
114,2026-07,2026-07-17,1.536021,35.0,2824.670764,261040578.0

In [48]:
## We will merge based on the month
fin_sector_merged = mde3.merge(
    fin_sec_monthly.drop(columns="date"),
    on="month",
    how="left"
)

In [49]:
fin_sector_merged

,consumer_price_index(CPI)_monthly,Crude Oil Price_monthly,Domestic Production_monthly,Crude Oil Export_monthly,Inflation_allItemsAverage_monthly,Money Supply(M2)_monthly,currency in circulation_monthly,bank reserves_monthly,netForeignAssets_monthly,netDomesticAssets_monthly,...,GDP at Current Market Prices_quarterly,FR_Date,foreign_reserve_Gross(USD)_monthly,foreign_reserve_Liquid(USD)_monthly,date,month,weighted_sector_returns,n_stocks_contributing,sector_index,sector_volume
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,2017-01-31,NaN,NaN,2017-01-31,2017-01,-0.996463,20.0,109.001843,87259637.0
1,198.041241,55.01,1.84,1.39,16.44,23096526.55,1994577.62,3311609.44,9473002.48,19005647.02,...,NaN,2017-02-28,2.817423e+10,2.745703e+10,2017-02-28,2017-02,0.649545,21.0,107.626307,169938472.0
2,201.001141,46.39,1.82,1.37,16.96,22210954.84,1978886.94,3234760.81,7977399.24,19746640.86,...,26228.85,2017-03-31,2.964668e+10,2.894094e+10,2017-03-31,2017-03,-0.017945,21.0,105.456849,141367620.0
3,204.456610,52.13,1.60,1.15,17.32,22304267.84,1983633.07,3309947.53,7628543.46,20342546.55,...,26228.85,2017-04-28,3.029795e+10,2.962647e+10,2017-04-30,2017-04,1.815887,20.0,115.418966,120760980.0
4,207.729678,52.94,1.79,1.34,17.59,21768241.12,1975812.32,3536407.29,7269852.64,20347360.25,...,26228.85,2017-05-31,3.086463e+10,3.017061e+10,2017-05-31,2017-05,-2.338342,21.0,138.127184,261656035.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,2026-07-16,5.145923e+10,5.081045e+10,2026-08-31,2026-08,NaN,NaN,NaN,NaN
116,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,5.191564e+10,5.129593e+10,2026-09-30,2026-09,NaN,NaN,NaN,NaN
117,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2026-10-31,2026-10,NaN,NaN,NaN,NaN
118,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2026-11-30,2026-11,NaN,NaN,NaN,NaN
119,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2026-12-31,2026-12,NaN,NaN,NaN,NaN

In [50]:
fin_sector_merged=fin_sector_merged.dropna()

In [51]:
fin_sector_merged

,consumer_price_index(CPI)_monthly,Crude Oil Price_monthly,Domestic Production_monthly,Crude Oil Export_monthly,Inflation_allItemsAverage_monthly,Money Supply(M2)_monthly,currency in circulation_monthly,bank reserves_monthly,netForeignAssets_monthly,netDomesticAssets_monthly,...,GDP at Current Market Prices_quarterly,FR_Date,foreign_reserve_Gross(USD)_monthly,foreign_reserve_Liquid(USD)_monthly,date,month,weighted_sector_returns,n_stocks_contributing,sector_index,sector_volume
2,201.001141,46.39,1.82,1.37,16.96,2.221095e+07,1978886.94,3234760.81,7977399.24,1.974664e+07,...,26228.850000,2017-03-31,2.964668e+10,2.894094e+10,2017-03-31,2017-03,-0.017945,21.0,105.456849,141367620.0
3,204.456610,52.13,1.60,1.15,17.32,2.230427e+07,1983633.07,3309947.53,7628543.46,2.034255e+07,...,26228.850000,2017-04-28,3.029795e+10,2.962647e+10,2017-04-30,2017-04,1.815887,20.0,115.418966,120760980.0
4,207.729678,52.94,1.79,1.34,17.59,2.176824e+07,1975812.32,3536407.29,7269852.64,2.034736e+07,...,26228.850000,2017-05-31,3.086463e+10,3.017061e+10,2017-05-31,2017-05,-2.338342,21.0,138.127184,261656035.0
5,211.637809,50.57,1.87,1.42,17.63,2.204777e+07,1897917.15,3254006.25,8540084.49,1.949923e+07,...,27266.390000,2017-06-30,3.032964e+10,2.961376e+10,2017-06-30,2017-06,-0.251046,21.0,162.591431,236727857.0
6,214.982456,47.42,1.95,1.50,17.58,2.198058e+07,1873544.00,3256863.20,8468080.62,1.985120e+07,...,27266.390000,2017-07-31,3.028841e+10,2.957675e+10,2017-07-31,2017-07,-3.410985,21.0,183.041162,130494807.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
108,917.368816,68.05,1.46,1.01,23.01,1.244002e+08,5732860.29,32035734.52,31505596.33,9.290425e+07,...,126032.267589,2025-12-31,4.466827e+10,4.411119e+10,2026-01-31,2026-01,-0.149558,35.0,1998.576704,254593845.0
109,890.956254,68.05,1.46,1.01,21.97,1.239393e+08,5731116.60,30254995.23,27085821.33,9.686314e+07,...,126032.267589,2026-01-30,4.550244e+10,4.493857e+10,2026-02-28,2026-02,0.000000,35.0,2364.419520,383962151.0
110,908.860705,72.33,1.31,0.86,21.03,1.231071e+08,5709846.43,32744055.08,25569115.78,9.754761e+07,...,113186.870120,2026-02-27,4.627990e+10,4.572994e+10,2026-03-31,2026-03,-1.878773,35.0,2347.696835,294022203.0
111,946.869623,106.09,1.38,0.93,20.05,1.249763e+08,5646391.19,34603460.67,24014048.35,1.009719e+08,...,113186.870120,2026-03-31,4.969398e+10,4.899603e+10,2026-04-30,2026-04,1.404651,35.0,2856.819058,809264585.0
112,967.050171,126.71,1.49,1.04,19.16,1.249763e+08,5646391.19,34603460.67,24014048.35,1.009719e+08,...,113186.870120,2026-04-30,4.923846e+10,4.849418e+10,2026-05-31,2026-05,-0.883768,35.0,2959.843133,341760831.0

In [53]:
## remove unuseful columns
fin_sector_merged_clean=fin_sector_merged.drop(columns=['date','month'])

In [54]:
fin_sector_merged_clean

,consumer_price_index(CPI)_monthly,Crude Oil Price_monthly,Domestic Production_monthly,Crude Oil Export_monthly,Inflation_allItemsAverage_monthly,Money Supply(M2)_monthly,currency in circulation_monthly,bank reserves_monthly,netForeignAssets_monthly,netDomesticAssets_monthly,...,GDP at Current Basic Prices_quarterly,Net Taxes on Products_quarterly,GDP at Current Market Prices_quarterly,FR_Date,foreign_reserve_Gross(USD)_monthly,foreign_reserve_Liquid(USD)_monthly,weighted_sector_returns,n_stocks_contributing,sector_index,sector_volume
2,201.001141,46.39,1.82,1.37,16.96,2.221095e+07,1978886.94,3234760.81,7977399.24,1.974664e+07,...,26028.360000,200.500000,26228.850000,2017-03-31,2.964668e+10,2.894094e+10,-0.017945,21.0,105.456849,141367620.0
3,204.456610,52.13,1.60,1.15,17.32,2.230427e+07,1983633.07,3309947.53,7628543.46,2.034255e+07,...,26028.360000,200.500000,26228.850000,2017-04-28,3.029795e+10,2.962647e+10,1.815887,20.0,115.418966,120760980.0
4,207.729678,52.94,1.79,1.34,17.59,2.176824e+07,1975812.32,3536407.29,7269852.64,2.034736e+07,...,26028.360000,200.500000,26228.850000,2017-05-31,3.086463e+10,3.017061e+10,-2.338342,21.0,138.127184,261656035.0
5,211.637809,50.57,1.87,1.42,17.63,2.204777e+07,1897917.15,3254006.25,8540084.49,1.949923e+07,...,27030.250000,236.140000,27266.390000,2017-06-30,3.032964e+10,2.961376e+10,-0.251046,21.0,162.591431,236727857.0
6,214.982456,47.42,1.95,1.50,17.58,2.198058e+07,1873544.00,3256863.20,8468080.62,1.985120e+07,...,27030.250000,236.140000,27266.390000,2017-07-31,3.028841e+10,2.957675e+10,-3.410985,21.0,183.041162,130494807.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
108,917.368816,68.05,1.46,1.01,23.01,1.244002e+08,5732860.29,32035734.52,31505596.33,9.290425e+07,...,122810.658960,3221.608629,126032.267589,2025-12-31,4.466827e+10,4.411119e+10,-0.149558,35.0,1998.576704,254593845.0
109,890.956254,68.05,1.46,1.01,21.97,1.239393e+08,5731116.60,30254995.23,27085821.33,9.686314e+07,...,122810.658960,3221.608629,126032.267589,2026-01-30,4.550244e+10,4.493857e+10,0.000000,35.0,2364.419520,383962151.0
110,908.860705,72.33,1.31,0.86,21.03,1.231071e+08,5709846.43,32744055.08,25569115.78,9.754761e+07,...,110786.347011,2400.523110,113186.870120,2026-02-27,4.627990e+10,4.572994e+10,-1.878773,35.0,2347.696835,294022203.0
111,946.869623,106.09,1.38,0.93,20.05,1.249763e+08,5646391.19,34603460.67,24014048.35,1.009719e+08,...,110786.347011,2400.523110,113186.870120,2026-03-31,4.969398e+10,4.899603e+10,1.404651,35.0,2856.819058,809264585.0
112,967.050171,126.71,1.49,1.04,19.16,1.249763e+08,5646391.19,34603460.67,24014048.35,1.009719e+08,...,110786.347011,2400.523110,113186.870120,2026-04-30,4.923846e+10,4.849418e+10,-0.883768,35.0,2959.843133,341760831.0

SOmething is wrong with the weighted sector returns. It has to be the monthly difference not the daily difference. WE HAVE WORK TO DO. We will use the sector_index to get these values. ((new-old)/old) * 100

In [55]:
fin_sector_merged_clean['new_monthly_returns']=fin_sector_merged_clean['sector_index'].pct_change()*100

In [56]:
fin_sector_merged_clean

,consumer_price_index(CPI)_monthly,Crude Oil Price_monthly,Domestic Production_monthly,Crude Oil Export_monthly,Inflation_allItemsAverage_monthly,Money Supply(M2)_monthly,currency in circulation_monthly,bank reserves_monthly,netForeignAssets_monthly,netDomesticAssets_monthly,...,Net Taxes on Products_quarterly,GDP at Current Market Prices_quarterly,FR_Date,foreign_reserve_Gross(USD)_monthly,foreign_reserve_Liquid(USD)_monthly,weighted_sector_returns,n_stocks_contributing,sector_index,sector_volume,new_monthly_returns
2,201.001141,46.39,1.82,1.37,16.96,2.221095e+07,1978886.94,3234760.81,7977399.24,1.974664e+07,...,200.500000,26228.850000,2017-03-31,2.964668e+10,2.894094e+10,-0.017945,21.0,105.456849,141367620.0,NaN
3,204.456610,52.13,1.60,1.15,17.32,2.230427e+07,1983633.07,3309947.53,7628543.46,2.034255e+07,...,200.500000,26228.850000,2017-04-28,3.029795e+10,2.962647e+10,1.815887,20.0,115.418966,120760980.0,9.446628
4,207.729678,52.94,1.79,1.34,17.59,2.176824e+07,1975812.32,3536407.29,7269852.64,2.034736e+07,...,200.500000,26228.850000,2017-05-31,3.086463e+10,3.017061e+10,-2.338342,21.0,138.127184,261656035.0,19.674598
5,211.637809,50.57,1.87,1.42,17.63,2.204777e+07,1897917.15,3254006.25,8540084.49,1.949923e+07,...,236.140000,27266.390000,2017-06-30,3.032964e+10,2.961376e+10,-0.251046,21.0,162.591431,236727857.0,17.711392
6,214.982456,47.42,1.95,1.50,17.58,2.198058e+07,1873544.00,3256863.20,8468080.62,1.985120e+07,...,236.140000,27266.390000,2017-07-31,3.028841e+10,2.957675e+10,-3.410985,21.0,183.041162,130494807.0,12.577373
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
108,917.368816,68.05,1.46,1.01,23.01,1.244002e+08,5732860.29,32035734.52,31505596.33,9.290425e+07,...,3221.608629,126032.267589,2025-12-31,4.466827e+10,4.411119e+10,-0.149558,35.0,1998.576704,254593845.0,10.900821
109,890.956254,68.05,1.46,1.01,21.97,1.239393e+08,5731116.60,30254995.23,27085821.33,9.686314e+07,...,3221.608629,126032.267589,2026-01-30,4.550244e+10,4.493857e+10,0.000000,35.0,2364.419520,383962151.0,18.305168
110,908.860705,72.33,1.31,0.86,21.03,1.231071e+08,5709846.43,32744055.08,25569115.78,9.754761e+07,...,2400.523110,113186.870120,2026-02-27,4.627990e+10,4.572994e+10,-1.878773,35.0,2347.696835,294022203.0,-0.707264
111,946.869623,106.09,1.38,0.93,20.05,1.249763e+08,5646391.19,34603460.67,24014048.35,1.009719e+08,...,2400.523110,113186.870120,2026-03-31,4.969398e+10,4.899603e+10,1.404651,35.0,2856.819058,809264585.0,21.686029
112,967.050171,126.71,1.49,1.04,19.16,1.249763e+08,5646391.19,34603460.67,24014048.35,1.009719e+08,...,2400.523110,113186.870120,2026-04-30,4.923846e+10,4.849418e+10,-0.883768,35.0,2959.843133,341760831.0,3.606251

We have to drop the daily sector returns

In [57]:
fin_sector_merged_clean=fin_sector_merged_clean.drop('weighted_sector_returns', axis=1)

In [58]:
fin_sector_merged_clean

,consumer_price_index(CPI)_monthly,Crude Oil Price_monthly,Domestic Production_monthly,Crude Oil Export_monthly,Inflation_allItemsAverage_monthly,Money Supply(M2)_monthly,currency in circulation_monthly,bank reserves_monthly,netForeignAssets_monthly,netDomesticAssets_monthly,...,GDP at Current Basic Prices_quarterly,Net Taxes on Products_quarterly,GDP at Current Market Prices_quarterly,FR_Date,foreign_reserve_Gross(USD)_monthly,foreign_reserve_Liquid(USD)_monthly,n_stocks_contributing,sector_index,sector_volume,new_monthly_returns
2,201.001141,46.39,1.82,1.37,16.96,2.221095e+07,1978886.94,3234760.81,7977399.24,1.974664e+07,...,26028.360000,200.500000,26228.850000,2017-03-31,2.964668e+10,2.894094e+10,21.0,105.456849,141367620.0,NaN
3,204.456610,52.13,1.60,1.15,17.32,2.230427e+07,1983633.07,3309947.53,7628543.46,2.034255e+07,...,26028.360000,200.500000,26228.850000,2017-04-28,3.029795e+10,2.962647e+10,20.0,115.418966,120760980.0,9.446628
4,207.729678,52.94,1.79,1.34,17.59,2.176824e+07,1975812.32,3536407.29,7269852.64,2.034736e+07,...,26028.360000,200.500000,26228.850000,2017-05-31,3.086463e+10,3.017061e+10,21.0,138.127184,261656035.0,19.674598
5,211.637809,50.57,1.87,1.42,17.63,2.204777e+07,1897917.15,3254006.25,8540084.49,1.949923e+07,...,27030.250000,236.140000,27266.390000,2017-06-30,3.032964e+10,2.961376e+10,21.0,162.591431,236727857.0,17.711392
6,214.982456,47.42,1.95,1.50,17.58,2.198058e+07,1873544.00,3256863.20,8468080.62,1.985120e+07,...,27030.250000,236.140000,27266.390000,2017-07-31,3.028841e+10,2.957675e+10,21.0,183.041162,130494807.0,12.577373
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
108,917.368816,68.05,1.46,1.01,23.01,1.244002e+08,5732860.29,32035734.52,31505596.33,9.290425e+07,...,122810.658960,3221.608629,126032.267589,2025-12-31,4.466827e+10,4.411119e+10,35.0,1998.576704,254593845.0,10.900821
109,890.956254,68.05,1.46,1.01,21.97,1.239393e+08,5731116.60,30254995.23,27085821.33,9.686314e+07,...,122810.658960,3221.608629,126032.267589,2026-01-30,4.550244e+10,4.493857e+10,35.0,2364.419520,383962151.0,18.305168
110,908.860705,72.33,1.31,0.86,21.03,1.231071e+08,5709846.43,32744055.08,25569115.78,9.754761e+07,...,110786.347011,2400.523110,113186.870120,2026-02-27,4.627990e+10,4.572994e+10,35.0,2347.696835,294022203.0,-0.707264
111,946.869623,106.09,1.38,0.93,20.05,1.249763e+08,5646391.19,34603460.67,24014048.35,1.009719e+08,...,110786.347011,2400.523110,113186.870120,2026-03-31,4.969398e+10,4.899603e+10,35.0,2856.819058,809264585.0,21.686029
112,967.050171,126.71,1.49,1.04,19.16,1.249763e+08,5646391.19,34603460.67,24014048.35,1.009719e+08,...,110786.347011,2400.523110,113186.870120,2026-04-30,4.923846e+10,4.849418e+10,35.0,2959.843133,341760831.0,3.606251

I think its ok when we think of it.

In [59]:
fin_sector_merged_clean1=fin_sector_merged_clean.dropna()

In [61]:
fin_sector_merged_clean1=fin_sector_merged_clean1.drop('FR_Date',axis=1)

In [65]:
fin_sector_merged_clean1.rename(columns={'A. GDP_AGRICULTURE(agric)_quarterly':'GDP_AGRICULTURE(agric)_quarterly', ' gdp_ind_mfg_Oil Refining_quarterly':'gdp_ind_mfg_Oil Refining_quarterly'}, inplace=True)

In [66]:
fin_sector_merged_clean1.columns

Index(['consumer_price_index(CPI)_monthly', 'Crude Oil Price_monthly',
       'Domestic Production_monthly', 'Crude Oil Export_monthly',
       'Inflation_allItemsAverage_monthly', 'Money Supply(M2)_monthly',
       'currency in circulation_monthly', 'bank reserves_monthly',
       'netForeignAssets_monthly', 'netDomesticAssets_monthly',
       'netDomesticCredit_monthly', 'creditToGovernment_monthly',
       'creditToPrivateSector_monthly', 'MonetaryPolicyRate_monthly',
       'TreasuryBillRate_monthly', 'Lending_Rate_monthly',
       'Exchange_Rate(USD-EOP)_monthly', 'Premium_Motor_Spirit(PMS)_monthly',
       'GDP_AGRICULTURE(agric)_quarterly',
       'gdp_agric_Crop Production_quarterly', 'gdp_agric_Livestock_quarterly',
       'gdp_agric_Forestry_quarterly', ' gdp_Fishing_quarterly',
       'GDP_INDUSTRY(ind)_quarterly',
       'gdp_ind_Mining and Quarrying(MQ)_quarterly',
       'gdp_ind_MQ_Crude Petroleum and Natural Gas_quarterly',
       'gdp_ind_MQ_Coal Mining_quarterly', 'gdp_ind_MQ_Metal Ores_quarterly',
       'gdp_ind_MQ_Quarrying and Other Minerals_quarterly',
       'gdp_ind_Manufacturing(mfg)_quarterly',
       'gdp_ind_mfg_Oil Refining_quarterly', 'gdp_ind_mfg_Cement_quarterly',
       'gdp_ind_mfg_Food, Beverage and Tobacco_quarterly',
       'gdp_ind_mfg_Textile, Apparel and Footwear_quarterly',
       'gdp_ind_mfg_Wood and Wood Products_quarterly',
       'gdp_ind_mfg_Pulp, Paper and Paper Products_quarterly',
       'gdp_ind_mfg_Chemical and Pharmaceutical Products_quarterly',
       'gdp_ind_mfg_Non-Metallic Products_quarterly',
       'gdp_ind_mfg_Plastic and Rubber Products_quarterly',
       'gdp_ind_mfg_Electrical and Electronics_quarterly',
       'gdp_ind_mfg_Basic Metal, Iron and Steel_quarterly',
       'gdp_ind_mfg_Motor Vehicles and Assembly_quarterly',
       'gdp_ind_mfg_Other Manufacturing_quarterly',
       'gdp_ind_Electricity, Gas, Steam & Air conditioner_quarterly',
       'gdp_ind_Water supply, Sewage, Waste Management_quarterly',
       'gdp_ind_Construction_quarterly', 'GDP_SERVICES(svc)_quarterly',
       'gdp_svc_Trade_quarterly',
       'gdp_svc_Accommodation and Food Services_quarterly',
       'gdp_svc_Transportation and Storage(TS)_quarterly',
       'gdp_svc_TS_RoadTransport_quarterly',
       'gdp_svc_TS_Rail Transport & Pipelines_quarterly',
       'gdp_svc_TS_Water Transport_quarterly',
       'gdp_svc_TS_Air Transport_quarterly',
       'gdp_svc_TS_Transport Services_quarterly',
       'gdp_svc_TS_Post and Courier Services_quarterly',
       'gdp_svc_Information and Communication(IC)_quarterly',
       'gdp_svc_IC_Telecommunications and Information Services_quarterly',
       'gdp_svc_IC_Publishing_quarterly',
       'gdp_svc_IC_Motion Pictures, Sound Recording and Music Production_quarterly',
       'gdp_svc_IC_Broadcasting_quarterly',
       'gdp_svc_Arts, Entertainment & Recreation_quarterly',
       'gdp_svc_Financial and Insurance(FI)_quarterly',
       'gdp_svc_FI_Financial Institutions_quarterly',
       'gdp_svc_FI_Insurance_quarterly', 'gdp_svc_Real Estate_quarterly',
       'gdp_svc_Professional, Scientific & Technical Services_quarterly',
       'gdp_svc_Administrative and Support Services_quarterly',
       'gdp_svc_Public Administration_quarterly',
       'gdp_svc_Education_quarterly',
       'gdp_svc_Human Health & Social Services_quarterly',
       'gdp_svc_Other Services_quarterly',
       'GDP at Current Basic Prices_quarterly',
       'Net Taxes on Products_quarterly',
       'GDP at Current Market Prices_quarterly',
       'foreign_reserve_Gross(USD)_monthly',
       'foreign_reserve_Liquid(USD)_monthly', 'n_stocks_contributing',
       'sector_index', 'sector_volume', 'new_monthly_returns'],
      dtype='str')

In [71]:
## The needed features for this training (Check Cloud AI for explanation)
X_y_finance_features = [
    #target feature
    'new_monthly_returns',

    'sector_volume',  # consider lagging — see caveat below

    # Prices / inflation
    'consumer_price_index(CPI)_monthly',
    'Inflation_allItemsAverage_monthly',
    'Premium_Motor_Spirit(PMS)_monthly',

    # Oil
    'Crude Oil Price_monthly',
    'Domestic Production_monthly',
    'Crude Oil Export_monthly',

    # Money supply / banking system
    'Money Supply(M2)_monthly',
    'currency in circulation_monthly',
    'bank reserves_monthly',
    'netForeignAssets_monthly',
    'netDomesticAssets_monthly',
    'netDomesticCredit_monthly',
    'creditToGovernment_monthly',
    'creditToPrivateSector_monthly',

    # Interest rates
    'MonetaryPolicyRate_monthly',
    'TreasuryBillRate_monthly',
    'Lending_Rate_monthly',

    # Exchange rate
    'Exchange_Rate(USD-EOP)_monthly',

    # Broad economy GDP
    'GDP_AGRICULTURE(agric)_quarterly',
    'GDP_INDUSTRY(ind)_quarterly',
    'GDP at Current Market Prices_quarterly',

    # Financial sector-specific GDP
    'gdp_svc_FI_Financial Institutions_quarterly',

    # Foreign reserves (pick one frequency — daily shown here)
    'foreign_reserve_Gross(USD)_monthly',
    'foreign_reserve_Liquid(USD)_monthly',

    # Misc
    'n_stocks_contributing'
]

In [72]:
fin_data_tr=fin_sector_merged_clean1[X_y_finance_features]

In [73]:
fin_data_tr.corr()

,new_monthly_returns,sector_volume,consumer_price_index(CPI)_monthly,Inflation_allItemsAverage_monthly,Premium_Motor_Spirit(PMS)_monthly,Crude Oil Price_monthly,Domestic Production_monthly,Crude Oil Export_monthly,Money Supply(M2)_monthly,currency in circulation_monthly,...,TreasuryBillRate_monthly,Lending_Rate_monthly,Exchange_Rate(USD-EOP)_monthly,GDP_AGRICULTURE(agric)_quarterly,GDP_INDUSTRY(ind)_quarterly,GDP at Current Market Prices_quarterly,gdp_svc_FI_Financial Institutions_quarterly,foreign_reserve_Gross(USD)_monthly,foreign_reserve_Liquid(USD)_monthly,n_stocks_contributing
new_monthly_returns,1.000000,0.092346,0.171637,0.210366,0.183537,-0.129958,-0.109576,-0.109576,0.168990,0.156345,...,0.103557,0.120148,0.165206,0.164420,0.129529,0.173275,0.205102,-0.205736,-0.209249,0.044736
sector_volume,0.092346,1.000000,0.325806,0.176236,0.288739,0.055435,-0.100588,-0.100588,0.307632,0.271050,...,0.194994,0.220726,0.260912,0.365352,0.224870,0.375271,0.282773,0.118515,0.112915,0.212434
consumer_price_index(CPI)_monthly,0.171637,0.325806,1.000000,0.724667,0.936667,0.356898,-0.528580,-0.528580,0.992826,0.929905,...,0.539539,0.393682,0.941353,0.881655,0.865589,0.964087,0.941951,0.091090,0.083398,0.775110
Inflation_allItemsAverage_monthly,0.210366,0.176236,0.724667,1.000000,0.666089,0.374906,-0.550428,-0.550428,0.758753,0.613613,...,0.513605,0.283431,0.801148,0.525731,0.746046,0.580866,0.777581,-0.264406,-0.278871,0.529628
Premium_Motor_Spirit(PMS)_monthly,0.183537,0.288739,0.936667,0.666089,1.000000,0.241875,-0.317778,-0.317778,0.939749,0.889637,...,0.655104,0.565611,0.926690,0.794912,0.761874,0.901900,0.898998,0.145498,0.134887,0.611132
Crude Oil Price_monthly,-0.129958,0.055435,0.356898,0.374906,0.241875,1.000000,-0.586880,-0.586880,0.332297,0.320598,...,0.059268,-0.145855,0.248405,0.208411,0.517094,0.276090,0.334272,0.217137,0.217957,0.475219
Domestic Production_monthly,-0.109576,-0.100588,-0.528580,-0.550428,-0.317778,-0.586880,1.000000,1.000000,-0.502132,-0.482465,...,0.157513,0.417685,-0.397901,-0.435900,-0.727369,-0.439512,-0.461398,0.269427,0.258960,-0.701794
Crude Oil Export_monthly,-0.109576,-0.100588,-0.528580,-0.550428,-0.317778,-0.586880,1.000000,1.000000,-0.502132,-0.482465,...,0.157513,0.417685,-0.397901,-0.435900,-0.727369,-0.439512,-0.461398,0.269427,0.258960,-0.701794
Money Supply(M2)_monthly,0.168990,0.307632,0.992826,0.758753,0.939749,0.332297,-0.502132,-0.502132,1.000000,0.932494,...,0.584151,0.416599,0.972108,0.851879,0.855237,0.941845,0.953595,0.064076,0.055411,0.755554
currency in circulation_monthly,0.156345,0.271050,0.929905,0.613613,0.889637,0.320598,-0.482465,-0.482465,0.932494,1.000000,...,0.516764,0.348031,0.886734,0.839732,0.774980,0.917275,0.883587,0.165270,0.167388,0.704714
bank reserves_monthly,0.182571,0.310483,0.988114,0.677221,0.927521,0.279004,-0.521251,-0.521251,0.977884,0.921768,...,0.479981,0.361018,0.920577,0.884466,0.851388,0.960309,0.922555,0.069119,0.063555,0.769875
netForeignAssets_monthly,0.036765,0.276380,0.707653,0.419665,0.767847,0.071759,0.014706,0.014706,0.741359,0.681820,...,0.743369,0.664011,0.788011,0.621807,0.408741,0.711880,0.665687,0.281107,0.268203,0.368071
netDomesticAssets_monthly,0.191517,0.286375,0.961965,0.778206,0.893248,0.358438,-0.571574,-0.571574,0.962107,0.917232,...,0.500356,0.321643,0.920623,0.814219,0.882524,0.898078,0.934691,-0.010910,-0.017149,0.768849
netDomesticCredit_monthly,0.195194,0.261586,0.968294,0.797853,0.894846,0.400243,-0.600252,-0.600252,0.969471,0.880954,...,0.485984,0.307125,0.926710,0.807273,0.924795,0.895819,0.936169,-0.007001,-0.016648,0.807300
creditToGovernment_monthly,0.213374,0.231554,0.860484,0.724645,0.763557,0.442367,-0.665566,-0.665566,0.838256,0.750788,...,0.300680,0.149401,0.756976,0.723220,0.906438,0.792081,0.823547,-0.009765,-0.018721,0.793416
creditToPrivateSector_monthly,0.177087,0.263206,0.972690,0.794040,0.913973,0.360809,-0.540095,-0.540095,0.984947,0.900218,...,0.550620,0.367302,0.962587,0.808164,0.888731,0.901788,0.944411,-0.005346,-0.014855,0.774799
MonetaryPolicyRate_monthly,0.184905,0.301306,0.925462,0.768819,0.930049,0.238384,-0.305103,-0.305103,0.943508,0.824065,...,0.756705,0.633589,0.957649,0.755785,0.732342,0.862889,0.925554,0.080722,0.059846,0.592758
TreasuryBillRate_monthly,0.103557,0.194994,0.539539,0.513605,0.655104,0.059268,0.157513,0.157513,0.584151,0.516764,...,1.000000,0.833241,0.676436,0.386818,0.254495,0.504962,0.595301,0.198106,0.175511,0.076177
Lending_Rate_monthly,0.120148,0.220726,0.393682,0.283431,0.565611,-0.145855,0.417685,0.417685,0.416599,0.348031,...,0.833241,1.000000,0.483645,0.337051,0.029064,0.429947,0.429936,0.315263,0.289397,-0.156960
Exchange_Rate(USD-EOP)_monthly,0.165206,0.260912,0.941353,0.801148,0.926690,0.248405,-0.397901,-0.397901,0.972108,0.886734,...,0.676436,0.483645,1.000000,0.765514,0.788731,0.863155,0.940068,0.005382,-0.006575,0.671475
GDP_AGRICULTURE(agric)_quarterly,0.164420,0.365352,0.881655,0.525731,0.794912,0.208411,-0.435900,-0.435900,0.851879,0.839732,...,0.386818,0.337051,0.765514,1.000000,0.719479,0.953601,0.734729,0.168206,0.166255,0.678638
GDP_INDUSTRY(ind)_quarterly,0.129529,0.224870,0.865589,0.746046,0.761874,0.517094,-0.727369,-0.727369,0.855237,0.774980,...,0.254495,0.029064,0.788731,0.719479,1.000000,0.776374,0.818373,-0.031781,-0.036621,0.886331
GDP at Current Market Prices_quarterly,0.173275,0.375271,0.964087,0.580866,0.901900,0.276090,-0.439512,-0.439512,0.941845,0.917275,...,0.504962,0.429947,0.863155,0.953601,0.776374,1.000000,0.858622,0.202157,0.197706,0.706333
gdp_svc_FI_Financial Institutions_quarterly,0.205102,0.282773,0.941951,0.777581,0.898998,0.334272,-0.461398,-0.461398,0.953595,0.883587,...,0.595301,0.429936,0.940068,0.734729,0.818373,0.858622,1.000000,0.046945,0.035528,0.706647
foreign_reserve_Gross(USD)_monthly,-0.205736,0.118515,0.091090,-0.264406,0.145498,0.217137,0.269427,0.269427,0.064076,0.165270,...,0.198106,0.315263,0.005382,0.168206,-0.031781,0.202157,0.046945,1.000000,0.998745,0.005240
foreign_reserve_Liquid(USD)_monthly,-0.209249,0.112915,0.083398,-0.278871,0.134887,0.217957,0.258960,0.258960,0.055411,0.167388,...,0.175511,0.289397,-0.006575,0.166255,-0.036621,0.197706,0.035528,0.998745,1.000000,0.004872
n_stocks_contributing,0.044736,0.212434,0.775110,0.529628,0.611132,0.475219,-0.701794,-0.701794,0.755554,0.704714,...,0.076177,-0.156960,0.671475,0.678638,0.886331,0.706333,0.706647,0.005240,0.004872,1.000000

In [74]:
## We will set a threshold for this exercise eg 0.85
## Note: this threshold is determined by the DOMAIN EXPERT
## For now we will use 0.90
## Let us improve the below

def correlation(dataset, threshold):
    col_corr = set()
    col_pair = set()
    
    corr_matrix = dataset.corr()

    for i in range(len(corr_matrix.columns)):
        for j in range(i):
            if abs(corr_matrix.iloc[i, j]) > threshold:
                colname1 = corr_matrix.columns[i]
                colname2 = corr_matrix.columns[j]

                col_pair.add((colname1, colname2, corr_matrix.iloc[i, j]))
                col_corr.add(colname1)

    return col_corr, col_pair

In [75]:
correlation## We will use the correlation() function we created.
## This will identify features that are highly correlated to each other
correlated_features,column_pairs =correlation(fin_data_tr,0.85)
correlated_features

## The column pairing is good for investigative purposes

{'Crude Oil Export_monthly',
 'Exchange_Rate(USD-EOP)_monthly',
 'GDP at Current Market Prices_quarterly',
 'GDP_AGRICULTURE(agric)_quarterly',
 'GDP_INDUSTRY(ind)_quarterly',
 'MonetaryPolicyRate_monthly',
 'Money Supply(M2)_monthly',
 'Premium_Motor_Spirit(PMS)_monthly',
 'bank reserves_monthly',
 'creditToGovernment_monthly',
 'creditToPrivateSector_monthly',
 'currency in circulation_monthly',
 'foreign_reserve_Liquid(USD)_monthly',
 'gdp_svc_FI_Financial Institutions_quarterly',
 'n_stocks_contributing',
 'netDomesticAssets_monthly',
 'netDomesticCredit_monthly'}

In [76]:
column_pairs

{('Crude Oil Export_monthly', 'Domestic Production_monthly', np.float64(1.0)),
 ('Exchange_Rate(USD-EOP)_monthly',
  'MonetaryPolicyRate_monthly',
  np.float64(0.9576491793461572)),
 ('Exchange_Rate(USD-EOP)_monthly',
  'Money Supply(M2)_monthly',
  np.float64(0.9721081529567054)),
 ('Exchange_Rate(USD-EOP)_monthly',
  'Premium_Motor_Spirit(PMS)_monthly',
  np.float64(0.9266900693743361)),
 ('Exchange_Rate(USD-EOP)_monthly',
  'bank reserves_monthly',
  np.float64(0.9205768260425549)),
 ('Exchange_Rate(USD-EOP)_monthly',
  'consumer_price_index(CPI)_monthly',
  np.float64(0.9413529536776452)),
 ('Exchange_Rate(USD-EOP)_monthly',
  'creditToPrivateSector_monthly',
  np.float64(0.9625870435705848)),
 ('Exchange_Rate(USD-EOP)_monthly',
  'currency in circulation_monthly',
  np.float64(0.8867339550418918)),
 ('Exchange_Rate(USD-EOP)_monthly',
  'netDomesticAssets_monthly',
  np.float64(0.9206229532496679)),
 ('Exchange_Rate(USD-EOP)_monthly',
  'netDomesticCredit_monthly',
  np.float64(0.9267099457704021)),
 ('GDP at Current Market Prices_quarterly',
  'Exchange_Rate(USD-EOP)_monthly',
  np.float64(0.8631553170952908)),
 ('GDP at Current Market Prices_quarterly',
  'GDP_AGRICULTURE(agric)_quarterly',
  np.float64(0.9536011477597361)),
 ('GDP at Current Market Prices_quarterly',
  'MonetaryPolicyRate_monthly',
  np.float64(0.8628887116409812)),
 ('GDP at Current Market Prices_quarterly',
  'Money Supply(M2)_monthly',
  np.float64(0.9418446847301504)),
 ('GDP at Current Market Prices_quarterly',
  'Premium_Motor_Spirit(PMS)_monthly',
  np.float64(0.9019004447221723)),
 ('GDP at Current Market Prices_quarterly',
  'bank reserves_monthly',
  np.float64(0.9603089423495125)),
 ('GDP at Current Market Prices_quarterly',
  'consumer_price_index(CPI)_monthly',
  np.float64(0.9640865550430474)),
 ('GDP at Current Market Prices_quarterly',
  'creditToPrivateSector_monthly',
  np.float64(0.9017878429187735)),
 ('GDP at Current Market Prices_quarterly',
  'currency in circulation_monthly',
  np.float64(0.9172749553852114)),
 ('GDP at Current Market Prices_quarterly',
  'netDomesticAssets_monthly',
  np.float64(0.898078144073525)),
 ('GDP at Current Market Prices_quarterly',
  'netDomesticCredit_monthly',
  np.float64(0.895818964683559)),
 ('GDP_AGRICULTURE(agric)_quarterly',
  'Money Supply(M2)_monthly',
  np.float64(0.8518792649889612)),
 ('GDP_AGRICULTURE(agric)_quarterly',
  'bank reserves_monthly',
  np.float64(0.8844662278195261)),
 ('GDP_AGRICULTURE(agric)_quarterly',
  'consumer_price_index(CPI)_monthly',
  np.float64(0.8816547990553996)),
 ('GDP_INDUSTRY(ind)_quarterly',
  'Money Supply(M2)_monthly',
  np.float64(0.8552365429993705)),
 ('GDP_INDUSTRY(ind)_quarterly',
  'bank reserves_monthly',
  np.float64(0.8513877222138815)),
 ('GDP_INDUSTRY(ind)_quarterly',
  'consumer_price_index(CPI)_monthly',
  np.float64(0.8655887072959361)),
 ('GDP_INDUSTRY(ind)_quarterly',
  'creditToGovernment_monthly',
  np.float64(0.9064384995153834)),
 ('GDP_INDUSTRY(ind)_quarterly',
  'creditToPrivateSector_monthly',
  np.float64(0.8887306053490396)),
 ('GDP_INDUSTRY(ind)_quarterly',
  'netDomesticAssets_monthly',
  np.float64(0.8825243458166253)),
 ('GDP_INDUSTRY(ind)_quarterly',
  'netDomesticCredit_monthly',
  np.float64(0.9247949111921324)),
 ('MonetaryPolicyRate_monthly',
  'Money Supply(M2)_monthly',
  np.float64(0.9435081253885989)),
 ('MonetaryPolicyRate_monthly',
  'Premium_Motor_Spirit(PMS)_monthly',
  np.float64(0.9300491835263016)),
 ('MonetaryPolicyRate_monthly',
  'bank reserves_monthly',
  np.float64(0.893858270355348)),
 ('MonetaryPolicyRate_monthly',
  'consumer_price_index(CPI)_monthly',
  np.float64(0.925461680023216)),
 ('MonetaryPolicyRate_monthly',
  'creditToPrivateSector_monthly',
  np.float64(0.9249459593383624)),
 ('MonetaryPolicyRate_monthly',
  'netDomesticAssets_monthly',
  np.float64(0.8851106039042548)),
 ('MonetaryPolicyRate_monthly',
  'netDomesticCredit_monthly',
  np.float64(0.8998253896506823)),
 ('Money Supply(M2)_monthly',
  'Premium_Motor_Spirit(PMS)_monthly',
  np.float64(0.9397488001408807)),
 ('Money Supply(M2)_monthly',
  'consumer_price_index(CPI)_monthly',
  np.float64(0.9928261629021097)),
 ('Premium_Motor_Spirit(PMS)_monthly',
  'consumer_price_index(CPI)_monthly',
  np.float64(0.9366668127810687)),
 ('bank reserves_monthly',
  'Money Supply(M2)_monthly',
  np.float64(0.9778835747628404)),
 ('bank reserves_monthly',
  'Premium_Motor_Spirit(PMS)_monthly',
  np.float64(0.927520506698207)),
 ('bank reserves_monthly',
  'consumer_price_index(CPI)_monthly',
  np.float64(0.9881135683110814)),
 ('bank reserves_monthly',
  'currency in circulation_monthly',
  np.float64(0.9217680300333764)),
 ('creditToGovernment_monthly',
  'consumer_price_index(CPI)_monthly',
  np.float64(0.8604838598362654)),
 ('creditToGovernment_monthly',
  'netDomesticAssets_monthly',
  np.float64(0.9012370085064538)),
 ('creditToGovernment_monthly',
  'netDomesticCredit_monthly',
  np.float64(0.9304093189872013)),
 ('creditToPrivateSector_monthly',
  'Money Supply(M2)_monthly',
  np.float64(0.9849466948460442)),
 ('creditToPrivateSector_monthly',
  'Premium_Motor_Spirit(PMS)_monthly',
  np.float64(0.9139725616846737)),
 ('creditToPrivateSector_monthly',
  'bank reserves_monthly',
  np.float64(0.9535642659855396)),
 ('creditToPrivateSector_monthly',
  'consumer_price_index(CPI)_monthly',
  np.float64(0.9726903104714547)),
 ('creditToPrivateSector_monthly',
  'creditToGovernment_monthly',
  np.float64(0.8522228135181539)),
 ('creditToPrivateSector_monthly',
  'currency in circulation_monthly',
  np.float64(0.9002182203353526)),
 ('creditToPrivateSector_monthly',
  'netDomesticAssets_monthly',
  np.float64(0.9608319993794384)),
 ('creditToPrivateSector_monthly',
  'netDomesticCredit_monthly',
  np.float64(0.9846727520607641)),
 ('currency in circulation_monthly',
  'Money Supply(M2)_monthly',
  np.float64(0.9324943521873212)),
 ('currency in circulation_monthly',
  'Premium_Motor_Spirit(PMS)_monthly',
  np.float64(0.8896369404788191)),
 ('currency in circulation_monthly',
  'consumer_price_index(CPI)_monthly',
  np.float64(0.9299053433257637)),
 ('foreign_reserve_Liquid(USD)_monthly',
  'foreign_reserve_Gross(USD)_monthly',
  np.float64(0.9987450669890262)),
 ('gdp_svc_FI_Financial Institutions_quarterly',
  'Exchange_Rate(USD-EOP)_monthly',
  np.float64(0.9400681810491938)),
 ('gdp_svc_FI_Financial Institutions_quarterly',
  'GDP at Current Market Prices_quarterly',
  np.float64(0.8586215748387847)),
 ('gdp_svc_FI_Financial Institutions_quarterly',
  'MonetaryPolicyRate_monthly',
  np.float64(0.9255539791558516)),
 ('gdp_svc_FI_Financial Institutions_quarterly',
  'Money Supply(M2)_monthly',
  np.float64(0.953594940847639)),
 ('gdp_svc_FI_Financial Institutions_quarterly',
  'Premium_Motor_Spirit(PMS)_monthly',
  np.float64(0.8989984378152897)),
 ('gdp_svc_FI_Financial Institutions_quarterly',
  'bank reserves_monthly',
  np.float64(0.9225551655520214)),
 ('gdp_svc_FI_Financial Institutions_quarterly',
  'consumer_price_index(CPI)_monthly',
  np.float64(0.9419508717572236)),
 ('gdp_svc_FI_Financial Institutions_quarterly',
  'creditToPrivateSector_monthly',
  np.float64(0.9444105358130831)),
 ('gdp_svc_FI_Financial Institutions_quarterly',
  'currency in circulation_monthly',
  np.float64(0.8835871119669909)),
 ('gdp_svc_FI_Financial Institutions_quarterly',
  'netDomesticAssets_monthly',
  np.float64(0.9346907490869097)),
 ('gdp_svc_FI_Financial Institutions_quarterly',
  'netDomesticCredit_monthly',
  np.float64(0.9361688386262328)),
 ('n_stocks_contributing',
  'GDP_INDUSTRY(ind)_quarterly',
  np.float64(0.8863312952347339)),
 ('netDomesticAssets_monthly',
  'Money Supply(M2)_monthly',
  np.float64(0.9621069868987964)),
 ('netDomesticAssets_monthly',
  'Premium_Motor_Spirit(PMS)_monthly',
  np.float64(0.8932481205028497)),
 ('netDomesticAssets_monthly',
  'bank reserves_monthly',
  np.float64(0.9470482364565334)),
 ('netDomesticAssets_monthly',
  'consumer_price_index(CPI)_monthly',
  np.float64(0.9619650054120634)),
 ('netDomesticAssets_monthly',
  'currency in circulation_monthly',
  np.float64(0.9172318595338825)),
 ('netDomesticCredit_monthly',
  'Money Supply(M2)_monthly',
  np.float64(0.9694707096259647)),
 ('netDomesticCredit_monthly',
  'Premium_Motor_Spirit(PMS)_monthly',
  np.float64(0.8948461830271802)),
 ('netDomesticCredit_monthly',
  'bank reserves_monthly',
  np.float64(0.9502666272613957)),
 ('netDomesticCredit_monthly',
  'consumer_price_index(CPI)_monthly',
  np.float64(0.9682944566326122)),
 ('netDomesticCredit_monthly',
  'currency in circulation_monthly',
  np.float64(0.8809537134589494)),
 ('netDomesticCredit_monthly',
  'netDomesticAssets_monthly',
  np.float64(0.9735727786322169))}

In [86]:
from xgboost import XGBRegressor, XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score,accuracy_score,classification_report,confusion_matrix
import numpy as np

In [80]:
X=fin_data_tr.drop(columns=['new_monthly_returns'])
y=fin_data_tr['new_monthly_returns']


X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,shuffle=False)



## getting baseline
pred_base = np.full_like(y_test, y_train.mean(), dtype=float)
baseline_rmse=np.sqrt(mean_squared_error(y_test, pred_base))

## Apply standardscaler to standardize the data
# Fit to the training data (calculates mean and std)
scaler=StandardScaler()
scaler.fit(X_train)

# Transform the training and testing data
X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)


model = XGBRegressor(
    max_depth=2,           # very shallow — start conservative
    n_estimators=300,
    learning_rate=0.01,
    subsample=0.6,
    colsample_bytree=0.6,
    reg_alpha=2.0,
    reg_lambda=10.0,
    min_child_weight=20,
    random_state=42
)


model.fit(X_train_scaled, y_train)
preds_test = model.predict(X_test_scaled)
preds_train = model.predict(X_train_scaled)

rmse = np.sqrt(mean_squared_error(y_test, preds_test))

r2_test=r2_score(y_true=y_test,y_pred=preds_test)
r2_train=r2_score(y_true=y_train,y_pred=preds_train)

    
print(f"\nRMSE: {rmse:.4f}")
print(f"\nR2_score_test: {r2_test:.4f}")
print(f"\nMean R2_score_train across folds: {r2_train:.4f}")
print('baseline information: ', baseline_rmse)

RMSE: 8.8887

R2_score_test: -0.2469

Mean R2_score_train across folds: 0.2270
baseline information:  8.775099710172928

Let us apply classification. Regression will be very poor because of how small the data size is.

In [83]:
## include a target column for classification

fin_data_tr['returns_movement']=[1 if num >= 0 else 0 for num in fin_data_tr['new_monthly_returns']]

In [84]:
fin_data_tr['returns_movement']

3      1
4      1
5      1
6      1
7      1
      ..
108    1
109    1
110    0
111    1
112    1
Name: returns_movement, Length: 110, dtype: int64

In [85]:
fin_data_tr['returns_movement'].value_counts()

returns_movement
1    69
0    41
Name: count, dtype: int64

In [89]:
X=fin_data_tr.drop(columns=['new_monthly_returns','returns_movement'])
y=fin_data_tr['returns_movement']


X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.4,shuffle=False)



## getting baseline
pred_base = np.full_like(y_test, y_train.mean(), dtype=float)
baseline_rmse=np.sqrt(mean_squared_error(y_test, pred_base))

## Apply standardscaler to standardize the data
# Fit to the training data (calculates mean and std)
scaler=StandardScaler()
scaler.fit(X_train)

# Transform the training and testing data
X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)


model_obj=XGBClassifier(
    max_depth=2,
    n_estimators=300,
    learning_rate=0.01,
    subsample=0.6,
    colsample_bytree=0.6,
    reg_alpha=2.0,
    reg_lambda=10.0,
    min_child_weight=20,
    random_state=42
)


model_obj.fit(X_train_scaled, y_train)
preds_train=model_obj.predict(X_train_scaled)
preds_test = model_obj.predict(X_test_scaled)


train_accuracy_score1=accuracy_score(y_true=y_train,y_pred=preds_train)
test_accuracy_score1=accuracy_score(y_true=y_test,y_pred=preds_test)

print(f"training accuracy_score={train_accuracy_score1}")
print(f"test accuracy_score ={test_accuracy_score1:.4f}")
print(f'{classification_report(y_true=y_test,y_pred=preds_test)}')
print(f'{confusion_matrix(y_true=y_test,y_pred=preds_test)}')

training accuracy_score=0.5909090909090909
test accuracy_score =0.6818
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        14
           1       0.68      1.00      0.81        30

    accuracy                           0.68        44
   macro avg       0.34      0.50      0.41        44
weighted avg       0.46      0.68      0.55        44

[[ 0 14]
 [ 0 30]]

c:\Users\pc\Downloads\Python_NGX_Project\venv\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\pc\Downloads\Python_NGX_Project\venv\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\pc\Downloads\Python_NGX_Project\venv\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

### I DON TIRE!!!